### ISSUE TITLE
Startup crash on recent reslease

### ISSUE THREAD

**Issue by polski-g** [CoFH/Feedback#1006]
```
java.lang.NullPointerException: Null string not allowed
	at java.util.Objects.requireNonNull(Unknown Source)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137)
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:108)
	at cofh.api.util.ThermalExpansionHelper.addTransposerFill(ThermalExpansionHelper.java:421)
	at cofh.thermaldynamics.util.TDCrafting.addTransposerFill(TDCrafting.java:175)
	at cofh.thermaldynamics.util.TDCrafting.loadRecipes(TDCrafting.java:60)
	at cofh.thermaldynamics.init.TDItems.registerRecipes(TDItems.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1060_TDItems_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:718)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

CoFHCore-1.12.2-4.3.11.6-universal.jar
ThermalDynamics-1.12.2-2.3.11.5-universal.jar
ThermalExpansion-1.12.2-5.3.11.13-universal.jar
ThermalFoundation-1.12.2-2.3.11.7-universal.jar

**Comment by xAlicatt** [comment]
Came here to report the same crash. Mod versions are the same as listed in the OP.

https://gist.github.com/xAlicatt/7bb48bddc7494119d6abf83d9f5dd750

**Comment by KingLemming** [comment]
Literally doesn't happen for me. I have absolutely no idea what to tell you here.

**Comment by KingLemming** [comment]
I believe I know what's happening here. It's caused by EnderIO but is fundamentally a Forge problem. Will see what I can do.

**Comment by polski-g** [comment]
Yeah its something else outside of COFH stuff.
Does not fail with only these mods:

```
2018-04-03  09:01 PM           658,041 CodeChickenLib-1.12.2-3.1.6.339-universal.jar
2018-04-07  01:39 AM           773,509 CoFHCore-1.12.2-4.3.11.6-universal.jar
2018-04-03  09:01 PM           399,333 CoFHWorld-1.12.2-1.1.1.12-universal.jar
2018-04-03  09:01 PM            33,436 RedstoneFlux-1.12-2.0.1.2-universal.jar
2018-04-07  01:45 AM           719,019 ThermalDynamics-1.12.2-2.3.11.5-universal.jar
2018-04-07  01:37 AM         2,189,440 ThermalExpansion-1.12.2-5.3.11.13-universal.jar
2018-04-07  01:39 AM         2,046,285 ThermalFoundation-1.12.2-2.3.11.7-universal.jar
```

**Comment by xAlicatt** [comment]
Which version of Forge are you using in your dev environment? I'm using 2634 cause it's the highest version required by the mods in my pack. I don't update Forge until either A) there is a new recommended version or B) one of my mods requires a newer version than whatever I'm currently using.

**Comment by KingLemming** [comment]
2611 in dev. The problem seems to be conflicting FluidStack behavior caused by EnderIO.

I'm going to see what's up with it.

**Comment by xAlicatt** [comment]
@polski-g , tbh, that doesn't matter because nobody only runs these mods. They are 98% of the time used in packs. And if I can start up my pack with the older releases of these mods, then my only conclusion is to decide that the "cause" is from these mods....even if it's not actually caused specifically by these mods....if that makes any sense.

**Comment by KingLemming** [comment]
The cause isn't actually these mods. The cause is that you installed EnderIO. :) That's the difference, and it has something to do with load order and all sorts of fluid stupidity.

I'm working on a fix.

**Comment by xAlicatt** [comment]
@KingLemming Thank you for your work and your time.

**Comment by KingLemming** [comment]
There are new hotfix versions of Thermal Foundation and Thermal Dynamics up. Please go download both. That fixed it in my testing.

**Comment by xAlicatt** [comment]
@KingLemming On Curse? (i'm assuming not since the time of day it is things aren't generally getting approved for many hours) 

And as far as the EIO thing goes, is it something you can report to them...or will that not matter? xD

**Comment by KingLemming** [comment]
Yeah, it's on Curse now.

**Comment by xAlicatt** [comment]
Definitely not crashing anymore. I haven't had the time to test it on the server yet, but will report back if there are any more issues. Thanks for the prompt fix!

**Comment by KingLemming** [comment]
Cool, thanks!
