### ISSUE TITLE
Corrupt world after update CoFHCore, ThermalFoundation, ThermalExpansion

### ISSUE THREAD

**Issue by dimitriy0810** [CoFH/Feedback#1015]
When I try to open a previosly generated world, I get the following message: Forge Mod Loader detected that the backup level.dat is being used.
This may happen due to a bug or corruption, continuing can damage
your world beyond repair or lose data / progress. (lines 1203-1208 in log file)
It's recommended to create a world backup before continuing. I have two options: yes (/fml confirm) and no (/fml cancel). If I click yes I get crash, if I click no I get nothing (the server is closed). Log: http://paste.ubuntu.com/14678093/ Crash-report: http://paste.ubuntu.com/14678110/
Versions: Forge 10.13.4..1614, ThermalExpansion: 4.1.1-237, ThermalFoundation: 1.2.0-102, CoFHCore: 3.1.0-323

**Comment by skyboy** [comment]
```
[10:28:11] [Server thread/INFO] [FML/]: Injecting new block and item data into this server instance.
[10:28:11] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.RuntimeException: Invalid id 10151 - maximum id range exceeded.
[10:28:11] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:379)
[10:28:11] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:894)
[10:28:11] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.registry.GameData.injectWorldIDMap(GameData.java:564)
[10:28:11] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLContainer.readData(FMLContainer.java:277)
[10:28:11] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:403)
[10:28:11] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:124)
[10:28:11] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:201)
[10:28:11] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258)
[10:28:11] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[10:28:11] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[10:28:11] [Server thread/WARN] [FML/]: Forge Mod Loader detected that the backup level.dat is being used.
```

You have too many mods adding content, this is not an error with our mods.

**Comment by dimitriy0810** [comment]
How this repair?

**Comment by XFactHD** [comment]
This is unfixable from your side.

**Comment by dimitriy0810** [comment]
Why? And what I should do? I want to open world with new version mods.

**Comment by XFactHD** [comment]
The amount if possible item IDs is capped (Forge does already make it higher). The problem in this case is that Forge blocks item IDs if the mod they were used for is removed. This is a security measure.

**Comment by dimitriy0810** [comment]
If I understand correctly the solution to this problem is the re-creation of the world with new versions of mods

**Comment by XFactHD** [comment]
Yes. In a completely new world this should work.

**Comment by dimitriy0810** [comment]
How I can transfer the buildings from the old world to the new?

**Comment by XFactHD** [comment]
That's impossible because the item IDs are different between worlds as said before.
