### ISSUE TITLE
TE devices crash when placed with some blocks from FurnitureMod

### ISSUE THREAD

**Issue by vadimyer** [CoFH/Feedback#1020]
I'm having a crash with devices from TE and a washing machine/dishwasher/microwave oven from MrCrayfish's Furniture Mod. Other blocks from that mod work good. I even upgraded CoFH, TE&TF to the latest versions, and still it does persist. I reproduced this crash now on latest versions.

```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 1/29/16 12:15 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at cofh.thermalexpansion.util.Utils.isAccessibleOutput(Utils.java:161)
	at cofh.thermalexpansion.block.TileInventory.transferItem(TileInventory.java:177)
	at cofh.thermalexpansion.block.machine.TilePulverizer.transferOutput(TilePulverizer.java:197)
	at cofh.thermalexpansion.block.machine.TileMachineBase.func_145845_h(TileMachineBase.java:124)
	at net.minecraft.world.World.func_72939_s(World.java:2513)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cofh.thermalexpansion.util.Utils.isAccessibleOutput(Utils.java:161)
	at cofh.thermalexpansion.block.TileInventory.transferItem(TileInventory.java:177)
	at cofh.thermalexpansion.block.machine.TilePulverizer.transferOutput(TilePulverizer.java:197)
	at cofh.thermalexpansion.block.machine.TileMachineBase.func_145845_h(TileMachineBase.java:124)

-- Block entity being ticked --
Details:
	Name: thermalexpansion.Pulverizer // cofh.thermalexpansion.block.machine.TilePulverizer
	Block type: ID #861 (tile.thermalexpansion.machine // cofh.thermalexpansion.block.machine.BlockMachine)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-13,64,-4), Chunk: (at 3,4,12 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #861 (tile.thermalexpansion.machine // cofh.thermalexpansion.block.machine.BlockMachine)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2513)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
```

**Comment by skyboy** [comment]
MrCrayfish's mod is erroneously returning null where it should be returning an array (in this case, of length 0).
