### ISSUE TITLE
fresh mc download crash

### ISSUE THREAD

**Issue by resengen** [CoFH/Feedback#1024]
with a fresh mc download in 1.7.10 with forge mc crashes mid forge start up on CoFHCore everytime.

[12:12:01] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[12:12:01] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[12:12:01] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[12:12:01] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[12:12:01] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_71, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_71
[12:12:02] [main/INFO] [FML]: [AppEng] Core Init
[12:12:02] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:12:02] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:12:02] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[12:12:02] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:12:02] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:12:02] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:12:07] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[12:12:07] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[12:12:07] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:12:07] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:12:08] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[12:12:08] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:12:09] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[12:12:09] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[12:12:09] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[12:12:10] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Transformed
[12:12:10] [main/INFO] [AE2-CORE]: func_146977_a_original(Lnet/minecraft/inventory/Slot;)V - New Method
[12:12:10] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Invoke Virtual
[12:12:12] [main/INFO]: Setting user: lazarusdraigon
[12:12:16] [Client thread/INFO]: LWJGL Version: 2.9.1
[12:12:19] [Client thread/INFO] [FML]: Could not load splash.properties, will create a default one
[12:12:19] [Client thread/INFO] [STDOUT]: [cpw.mods.fml.client.SplashProgress:start:188]: ---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 1/29/16 12:12 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 115333800 bytes (109 MB) / 193196032 bytes (184 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2869' Renderer: 'Intel(R) G45/G43 Express Chipset'
[12:12:20] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[12:12:20] [Client thread/INFO] [FML]: MinecraftForge v10.13.4.1614 Initialized
[12:12:20] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[12:12:20] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[12:12:20] [Client thread/INFO] [FML]: [AppEng] Core Init
[12:12:20] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[12:12:20] [Client thread/INFO] [FML]: Searching C:\Users\Lazarus Draigon\AppData\Roaming\.minecraft\mods for mods
[12:12:35] [Client thread/INFO] [FML]: Forge Mod Loader has identified 7 mods to load
[12:12:37] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, appliedenergistics2-core, <CoFH ASM>, appliedenergistics2, CoFHCore] at CLIENT
[12:12:37] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, appliedenergistics2-core, <CoFH ASM>, appliedenergistics2, CoFHCore] at SERVER
[12:12:40] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:CoFH Core
[12:12:40] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[12:12:40] [Client thread/INFO] [FML]: Found 337 ObjectHolder annotations
[12:12:40] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[12:12:40] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[12:12:41] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[12:12:41] [Client thread/INFO] [AE2:C]: Pre Initialization ( started )
[12:12:43] [Client thread/INFO] [AE2-CORE]: func_145839_a(Lnet/minecraft/nbt/NBTTagCompound;)V - Transformed
[12:12:43] [Client thread/INFO] [AE2-CORE]: func_145841_b(Lnet/minecraft/nbt/NBTTagCompound;)V - Transformed
[12:12:44] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.energy.tile.IEnergySink from appeng/tile/powersink/IC2 because IC2 integration is disabled.
[12:12:44] [Client thread/INFO] [AE2-CORE]: Updated appeng/tile/powersink/IC2
[12:12:44] [Client thread/INFO] [AE2-CORE]: Removing Interface Reika.RotaryCraft.API.Power.AdvancedShaftPowerReceiver from appeng/tile/powersink/RotaryCraft because RotaryCraft integration is disabled.
[12:12:44] [Client thread/INFO] [AE2-CORE]: Removing Interface Reika.RotaryCraft.API.Interfaces.Transducerable from appeng/tile/powersink/RotaryCraft because RotaryCraft integration is disabled.
[12:12:44] [Client thread/INFO] [AE2-CORE]: Removing Method Tick_RotaryCraft from appeng/tile/powersink/RotaryCraft because RotaryCraft integration is disabled.
[12:12:44] [Client thread/INFO] [AE2-CORE]: Updated appeng/tile/powersink/RotaryCraft
[12:12:44] [Client thread/INFO] [AE2-CORE]: Allowing Interface cofh.api.energy.IEnergyReceiver from appeng/tile/powersink/RedstoneFlux because RF integration is enabled.
[12:12:44] [Client thread/INFO] [AE2-CORE]: Removing Interface mekanism.api.energy.IStrictEnergyAcceptor from appeng/tile/powersink/MekJoules because Mekanism integration is disabled.
[12:12:44] [Client thread/INFO] [AE2-CORE]: Updated appeng/tile/powersink/MekJoules
[12:12:44] [Client thread/INFO] [AE2-CORE]: Removing Interface powercrystals.minefactoryreloaded.api.rednet.connectivity.IRedNetConnection from appeng/block/networking/BlockCableBus because MFR integration is disabled.
[12:12:44] [Client thread/INFO] [AE2-CORE]: Removing Method getConnectionType from appeng/block/networking/BlockCableBus because MFR integration is disabled.
[12:12:44] [Client thread/INFO] [AE2-CORE]: Updated appeng/block/networking/BlockCableBus
[12:12:45] [Client thread/INFO] [AE2-CORE]: Removing Interface buildcraft.api.tools.IToolWrench from appeng/items/tools/quartz/ToolQuartzWrench because BC integration is disabled.
[12:12:45] [Client thread/INFO] [AE2-CORE]: Updated appeng/items/tools/quartz/ToolQuartzWrench
[12:12:45] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.item.ISpecialElectricItem from appeng/items/tools/powered/powersink/IC2 because IC2 integration is disabled.
[12:12:45] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.item.IElectricItemManager from appeng/items/tools/powered/powersink/IC2 because IC2 integration is disabled.
[12:12:45] [Client thread/INFO] [AE2-CORE]: Removing Method getManager from appeng/items/tools/powered/powersink/IC2 because IC2 integration is disabled.
[12:12:45] [Client thread/INFO] [AE2-CORE]: Updated appeng/items/tools/powered/powersink/IC2
[12:12:45] [Client thread/INFO] [AE2-CORE]: Allowing Interface cofh.api.energy.IEnergyContainerItem from appeng/items/tools/powered/powersink/RedstoneFlux because RFItem integration is enabled.
[12:12:45] [Client thread/INFO] [AE2-CORE]: Removing Interface buildcraft.api.tools.IToolWrench from appeng/items/tools/ToolNetworkTool because BC integration is disabled.
[12:12:45] [Client thread/INFO] [AE2-CORE]: Updated appeng/items/tools/ToolNetworkTool
[12:12:45] [Client thread/INFO] [AE2-CORE]: Removing Interface buildcraft.api.transport.IPipeConnection from appeng/parts/misc/PartStorageBus because BC integration is disabled.
[12:12:45] [Client thread/INFO] [AE2-CORE]: Removing Method overridePipeConnection from appeng/parts/misc/PartStorageBus because BC integration is disabled.
[12:12:45] [Client thread/INFO] [AE2-CORE]: Updated appeng/parts/misc/PartStorageBus
[12:12:45] [Client thread/INFO] [AE2-CORE]: Removing Interface buildcraft.api.transport.IPipeConnection from appeng/parts/p2p/PartP2PItems because BC integration is disabled.
[12:12:45] [Client thread/INFO] [AE2-CORE]: Removing Method overridePipeConnection from appeng/parts/p2p/PartP2PItems because BC integration is disabled.
[12:12:45] [Client thread/INFO] [AE2-CORE]: Updated appeng/parts/p2p/PartP2PItems
[12:12:45] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.energy.tile.IEnergySink from appeng/parts/p2p/PartP2PIC2Power because IC2 integration is disabled.
[12:12:45] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.energy.tile.IEnergySource from appeng/parts/p2p/PartP2PIC2Power because IC2 integration is disabled.
[12:12:45] [Client thread/INFO] [AE2-CORE]: Updated appeng/parts/p2p/PartP2PIC2Power
[12:12:45] [Client thread/INFO] [AE2-CORE]: Allowing Interface cofh.api.energy.IEnergyReceiver from appeng/parts/p2p/PartP2PRFPower because RF integration is enabled.
[12:12:46] [Client thread/INFO] [AE2:C]: Starting AE2 VersionChecker
[12:12:46] [Client thread/INFO] [AE2:C]: Pre Initialization ( ended after 5656ms )
Exception in thread "AE2 VersionChecker" [12:12:47] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.IllegalArgumentException: Raw channel stable did not contain any of the pre-programmed types.
[12:12:47] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at appeng.services.version.VersionParser.parseChannel(VersionParser.java:117)
[12:12:47] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at appeng.services.version.VersionParser.parseVersion(VersionParser.java:72)
[12:12:47] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at appeng.services.version.VersionParser.parse(VersionParser.java:34)
[12:12:47] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at appeng.services.version.ModVersionFetcher.get(ModVersionFetcher.java:34)
[12:12:47] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at appeng.services.VersionChecker.processInterval(VersionChecker.java:106)
[12:12:47] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at appeng.services.VersionChecker.run(VersionChecker.java:86)
[12:12:47] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Thread.run(Unknown Source)

**Comment by skyboy** [comment]
There is no crash with CoFHCore in your log.

**Comment by XFactHD** [comment]
This crash is a known problem with the AE2  version checker. You can disable it in the config file. Do not report it to the AE2 devs, they are aware of this!

**Comment by resengen** [comment]
how do i do that?

**Comment by XFactHD** [comment]
In your config folder there is a folder called appliedenergistics2. Go into there and open the aeversionchecker.cfg.

**Comment by resengen** [comment]
Yes however the file is blank... Do I simply delete the file or should I enter some script? If a script the what should it say

-----Original Message-----

**Comment by XFactHD** [comment]
Oh right, now I recall, the problem was that the file was empty. You could try deleting this file. Also, I think this bug is fixed in one of the latest versions of AE2.
