### ISSUE TITLE
[1.12.2] Redstone Arsenal/Thermal Innovation viewing item crash

### ISSUE THREAD

**Issue by TheLordofMelons** [CoFH/Feedback#1027]
Redstone Arsenal crashes the game when viewing it's creative tab.  This also happens with Thermal Innovation when viewing the crafting recipe for it's items via JEI.

Redstone Arsenal:
`---- Minecraft Crash Report ----
// You're mean.

Time: 4/12/18 11:58 AM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at cofh.redstoneflux.util.EnergyContainerItemWrapper.getCapability(EnergyContainerItemWrapper.java:95)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108)
	at net.minecraft.item.ItemStack.getCapability(ItemStack.java:1169)
	at net.minecraftforge.client.model.animation.AnimationItemOverrideList.handleItemState(AnimationItemOverrideList.java:68)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:243)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:342)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cofh.redstoneflux.util.EnergyContainerItemWrapper.getCapability(EnergyContainerItemWrapper.java:95)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108)
	at net.minecraft.item.ItemStack.getCapability(ItemStack.java:1169)
	at net.minecraftforge.client.model.animation.AnimationItemOverrideList.handleItemState(AnimationItemOverrideList.java:68)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:243)

-- Item being rendered --
Details:
	Item Type: cofh.redstonearsenal.item.tool.ItemShieldFlux@381db99e
	Item Aux: 0
	Item NBT: {Energy:0}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:342)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (134, 35). Absolute: (403, 614)
	Screen size: Scaled: (427, 240). Absolute: (1280, 720). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheLordofMelons'/0, l='MpServer', x=141.50, y=56.00, z=176.50]]
	Chunk stats: MultiplayerChunkCache: 544, 544
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (143,4,179), Chunk: (at 15,0,3 in 8,11; contains blocks 128,0,176 to 143,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 107 game time, 107 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['TheLordofMelons'/0, l='MpServer', x=141.50, y=56.00, z=176.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 316007064 bytes (301 MB) / 1238892544 bytes (1181 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2657 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID              | Version      | Source                                        | Signature                                |
	|:--------- |:--------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft       | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp             | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML             | 8.0.99.99    | forge-1.12.2-14.23.3.2657.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge           | 14.23.3.2657 | forge-1.12.2-14.23.3.2657.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | redstoneflux    | 2.0.1        | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | cofhcore        | 4.3.11       | CoFHCore-1.12.2-4.3.11.6-universal.jar        | None                                     |
	| UCHIJAAAA | redstonearsenal | 2.3.11       | RedstoneArsenal-1.12.2-2.3.11.5-universal.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: forge-14.23.3.2657
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz`

Thermal Innovation:
`---- Minecraft Crash Report ----
// Don't do that.

Time: 4/12/18 12:04 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at cofh.redstoneflux.util.EnergyContainerItemWrapper.getCapability(EnergyContainerItemWrapper.java:95)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108)
	at net.minecraft.item.ItemStack.getCapability(ItemStack.java:1169)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackListFactory$FluidSubtypeInterpreter.apply(ItemStackListFactory.java:147)
	at mezz.jei.api.ISubtypeRegistry$ISubtypeInterpreter.getSubtypeInfo(ISubtypeRegistry.java:87)
	at mezz.jei.runtime.SubtypeRegistry.getSubtypeInfo(SubtypeRegistry.java:50)
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:383)
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:360)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.getUniqueId(ItemStackHelper.java:42)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.getUniqueId(ItemStackHelper.java:16)
	at mezz.jei.ingredients.IngredientInformation.getUniqueIdsWithWildcard(IngredientInformation.java:61)
	at mezz.jei.recipes.RecipeMap.getRecipeCategories(RecipeMap.java:38)
	at mezz.jei.recipes.InternalRecipeRegistryPlugin.getRecipeCategoryUids(InternalRecipeRegistryPlugin.java:50)
	at mezz.jei.recipes.RecipeRegistry.getRecipeCategories(RecipeRegistry.java:552)
	at mezz.jei.gui.recipes.RecipeGuiLogic.setFocus(RecipeGuiLogic.java:40)
	at mezz.jei.gui.recipes.RecipesGui.show(RecipesGui.java:362)
	at mezz.jei.input.InputHandler.handleFocusKeybinds(InputHandler.java:242)
	at mezz.jei.input.InputHandler.handleKeyDown(InputHandler.java:200)
	at mezz.jei.input.InputHandler.handleKeyEvent(InputHandler.java:182)
	at mezz.jei.gui.GuiEventHandler.onGuiKeyboardEvent(GuiEventHandler.java:150)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_63_GuiEventHandler_onGuiKeyboardEvent_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:513)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cofh.redstoneflux.util.EnergyContainerItemWrapper.getCapability(EnergyContainerItemWrapper.java:95)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108)
	at net.minecraft.item.ItemStack.getCapability(ItemStack.java:1169)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackListFactory$FluidSubtypeInterpreter.apply(ItemStackListFactory.java:147)
	at mezz.jei.api.ISubtypeRegistry$ISubtypeInterpreter.getSubtypeInfo(ISubtypeRegistry.java:87)
	at mezz.jei.runtime.SubtypeRegistry.getSubtypeInfo(SubtypeRegistry.java:50)
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:383)
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:360)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.getUniqueId(ItemStackHelper.java:42)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.getUniqueId(ItemStackHelper.java:16)
	at mezz.jei.ingredients.IngredientInformation.getUniqueIdsWithWildcard(IngredientInformation.java:61)
	at mezz.jei.recipes.RecipeMap.getRecipeCategories(RecipeMap.java:38)
	at mezz.jei.recipes.InternalRecipeRegistryPlugin.getRecipeCategoryUids(InternalRecipeRegistryPlugin.java:50)
	at mezz.jei.recipes.RecipeRegistry.getRecipeCategories(RecipeRegistry.java:552)
	at mezz.jei.gui.recipes.RecipeGuiLogic.setFocus(RecipeGuiLogic.java:40)
	at mezz.jei.gui.recipes.RecipesGui.show(RecipesGui.java:362)
	at mezz.jei.input.InputHandler.handleFocusKeybinds(InputHandler.java:242)
	at mezz.jei.input.InputHandler.handleKeyDown(InputHandler.java:200)
	at mezz.jei.input.InputHandler.handleKeyEvent(InputHandler.java:182)
	at mezz.jei.gui.GuiEventHandler.onGuiKeyboardEvent(GuiEventHandler.java:150)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_63_GuiEventHandler_onGuiKeyboardEvent_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:513)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheLordofMelons'/0, l='MpServer', x=141.50, y=56.00, z=176.50]]
	Chunk stats: MultiplayerChunkCache: 544, 544
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (143,4,179), Chunk: (at 15,0,3 in 8,11; contains blocks 128,0,176 to 143,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 273 game time, 273 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['TheLordofMelons'/0, l='MpServer', x=141.50, y=56.00, z=176.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 399110072 bytes (380 MB) / 1311768576 bytes (1251 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2657 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version      | Source                                          | Signature                                |
	|:--------- |:----------------- |:------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2       | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp               | 9.42         | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99    | forge-1.12.2-14.23.3.2657.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.3.2657 | forge-1.12.2-14.23.3.2657.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | redstoneflux      | 2.0.1        | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | cofhcore          | 4.3.11       | CoFHCore-1.12.2-4.3.11.6-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld         | 1.1.1        | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCHIJAAAA | jei               | 4.8.5.159    | jei_1.12.2-4.8.5.159.jar                        | None                                     |
	| UCHIJAAAA | redstonearsenal   | 2.3.11       | RedstoneArsenal-1.12.2-2.3.11.5-universal.jar   | None                                     |
	| UCHIJAAAA | thermalfoundation | 2.3.11       | ThermalFoundation-1.12.2-2.3.11.8-universal.jar | None                                     |
	| UCHIJAAAA | thermalinnovation | 0.1.0        | ThermalInnovation-1.12.2-0.1.0.3-universal.jar  | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: forge-14.23.3.2657
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz`

Side note: This seems to be happening with unrelated mods as well such as Matter Overdrive.  I suspect this may be a Forge issue.

**Comment by KingLemming** [comment]
It is a Forge issue. Downgrade Forge.

**Comment by covers1624** [comment]
Forge has fixed the issue, either downgrade or use the latest.
