### ISSUE TITLE
[Thermal Expansion] Bug with Tesseracts

### ISSUE THREAD

**Issue by Esctogrillo** [CoFH/Feedback#1046]
When a player lock a tesseract the console starts to flood with this message:

[02:21:37] [CoFH User Loader/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@3c353b29[id=6048d6bd-1806-3fdb-b514-1f98081e2bde,name=#PLAYERNAME#,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[server-1.7.10.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [server-1.7.10.jar:?]
	at cofh.lib.util.helpers.SecurityHelper.getProfile(SecurityHelper.java:216) [SecurityHelper.class:?]
	at cofh.thermalexpansion.block.TileInventory$1.run(TileInventory.java:483) [TileInventory$1.class:?]

Server starts to lag and players get timed out.

Using the latest version of CoFH Core, Thermal Expansion and Thermal Fundation with Thermos (KCauldron).
Modpack info and mods: [Jordann Pack] (https://github.com/TheKingdomServer/JordannPack)

This is not a new version bug. Using older versions of CoFH mods I got the same issue.

**Comment by KingLemming** [comment]
Can you make it happen with only CoFH mods?

Can you make it happen without KCauldron?

I'm betting it's KCauldron.

**Comment by skyboy** [comment]
This is just rate limiting on mojang's servers. It's abnormal that you have enough unique users to actually hit the limit (profiles are cached by the server for up to 30 days), and we have no way to really gracefully handle hitting that limit.

**Comment by ArcasCZ** [comment]
I'm getting same error (for two offline players -_-)

**Comment by Esctogrillo** [comment]
@ArcasCZ You can do what I did, use the Dimensional Transceiver from Ender IO.

**Comment by ArcasCZ** [comment]
It's not about me, it's about lot of players...

**Comment by evernife** [comment]
Any way to deactivate this ?

I think this only occuers on offline servers :D

**Comment by Eufranio** [comment]
Happens in a world with only CoFH mods, and pure forge 1614.
