### ISSUE TITLE
[Crash] After open up game Thermal Dynamics Update

### ISSUE THREAD

**Issue by SugarDaddii** [CoFH/Feedback#1052]
[13:33:59] [Client thread/INFO] [FML/ThermalDynamics]: Java has been asked to exit (code 1) by cpw.mods.fml.common.FMLCommonHandler.exitJava(FMLCommonHandler.java:613).
[13:33:59] [Client thread/INFO] [FML/ThermalDynamics]: This is an abortive exit and could cause world corruption or other things
[13:33:59] [Client thread/INFO] [FML/ThermalDynamics]: If this was an unexpected exit, use -Dfml.debugExit=true as a JVM argument to find out where it was called

That what my LOG says!Pls help

**Comment by skyboy** [comment]
First: this is an alpha. If you don't like having worlds break, don't use it.
Second: post more of the log.

**Comment by Tsyklop** [comment]
same.

my full log http://pastebin.com/zSCWvcrd

**Comment by skyboy** [comment]
```
[21:16:50] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.UnsupportedOperationException: This LP version isn't compatible with the installed TD version.
[21:16:50] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at logisticspipes.asm.td.ClassTileMultiBlockHandler.handleTileMultiBlockClass(ClassTileMultiBlockHandler.java:33)
[21:16:50] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at logisticspipes.asm.LogisticsClassTransformer.applyLPTransforms(LogisticsClassTransformer.java:107)
```

It's logistics pipes.
