### ISSUE TITLE
there have a crash

### ISSUE THREAD

**Issue by KnightBlood** [CoFH/Feedback#1059]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.8.9.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9-1.12.2-anarchy.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CorePlugin (UnicodeFontExtension-1.12.2-2.7.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.7.0.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 4/29/18 10:24 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Dynamics (thermaldynamics)
Caused by: java.lang.NullPointerException
	at cofh.thermaldynamics.duct.attachments.cover.CoverHelper.getCoverStack(CoverHelper.java:187)
	at cofh.thermaldynamics.duct.attachments.cover.CoverHelper.getCoverStack(CoverHelper.java:174)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at cofh.thermaldynamics.item.ItemCover.getCoverList(ItemCover.java:105)
	at cofh.thermaldynamics.init.TDItems.preInit(TDItems.java:39)
	at cofh.thermaldynamics.ThermalDynamics.preInit(ThermalDynamics.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:280)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:149)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:637)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2994753912 bytes (2856 MB) / 3997171712 bytes (3812 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2674 115 mods loaded, 115 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version                      | Source                                           | Signature                                |
	|:----- |:-------------------------- |:---------------------------- |:------------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft                  | 1.12.2                       | minecraft.jar                                    | None                                     |
	| UCH   | mcp                        | 9.42                         | minecraft.jar                                    | None                                     |
	| UCH   | FML                        | 8.0.99.99                    | forge-1.12.2-14.23.3.2674.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                      | 14.23.3.2674                 | forge-1.12.2-14.23.3.2674.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | unicodefontextensioncore   | 1.12.2-2.6                   | minecraft.jar                                    | None                                     |
	| UCH   | foamfixcore                | 7.7.4                        | minecraft.jar                                    | None                                     |
	| UCH   | unicodefontextension       | 1.12.2-2.7                   | UnicodeFontExtension-1.12.2-2.7.jar              | None                                     |
	| UCH   | jei                        | 4.9.1.172                    | jei_1.12.2-4.9.1.172.jar                         | None                                     |
	| UCH   | abyssalcraft               | 1.9.4.8                      | AbyssalCraft-1.12.2-1.9.4.8.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCH   | appliedenergistics2        | rv5-stable-11                | appliedenergistics2-rv5-stable-11_2.jar          | None                                     |
	| UCH   | bdlib                      | 1.14.3.12                    | bdlib-1.14.3.12-mc1.12.2.jar                     | None                                     |
	| UCH   | ae2stuff                   | 0.7.0.4                      | ae2stuff-0.7.0.4-mc1.12.2.jar                    | None                                     |
	| UCH   | orbis_api                  | 1.12.2-1.0.0                 | OrbisAPI-1.12.2-1.0.0.jar                        | None                                     |
	| UCH   | aether                     | 1.12.2-1.0.0                 | AetherII-1.12.2-1.0.0.jar                        | None                                     |
	| UCH   | baubles                    | 1.5.2                        | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCH   | astralsorcery              | 1.8.9                        | astralsorcery-1.12.2-1.8.9.jar                   | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCH   | betterbedrockgen           | 6.0.2                        | BetterBedrockGenerator-1.12-6.1.1.jar            | None                                     |
	| UCH   | ic2                        | 2.8.73-ex112                 | industrialcraft-2-2.8.73-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | reborncore                 | 3.8.0.264                    | RebornCore-1.12.2-3.8.0.264-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCH   | techreborn                 | 2.15.4.624                   | TechReborn-1.12.2-2.15.4.624-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCH   | forestry                   | 5.8.0.277                    | forestry_1.12.2-5.8.0.277.jar                    | None                                     |
	| UCH   | binniecore                 | 2.5.0.164                    | binnie-mods-1.12.2-2.5.0.164.jar                 | None                                     |
	| UCH   | binniedesign               | 2.5.0.164                    | binnie-mods-1.12.2-2.5.0.164.jar                 | None                                     |
	| UCH   | genetics                   | 2.5.0.164                    | binnie-mods-1.12.2-2.5.0.164.jar                 | None                                     |
	| UCH   | botany                     | 2.5.0.164                    | binnie-mods-1.12.2-2.5.0.164.jar                 | None                                     |
	| UCH   | extrabees                  | 2.5.0.164                    | binnie-mods-1.12.2-2.5.0.164.jar                 | None                                     |
	| UCH   | extratrees                 | 2.5.0.164                    | binnie-mods-1.12.2-2.5.0.164.jar                 | None                                     |
	| UCH   | guideapi                   | 1.12-2.1.5-60                | Guide-API-1.12-2.1.5-60.jar                      | None                                     |
	| UCH   | bloodmagic                 | 1.12.2-2.2.11-96             | BloodMagic-1.12.2-2.2.11-96.jar                  | None                                     |
	| UCH   | thaumcraft                 | 6.1.BETA11                   | Thaumcraft-1.12.2-6.1.BETA11.jar                 | None                                     |
	| UCH   | botania                    | r1.10-354                    | Botania r1.10-354.jar                            | None                                     |
	| UCH   | codechickenlib             | 3.1.7.340                    | CodeChickenLib-1.12.2-3.1.7.340-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux               | 2.0.1                        | RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | brandonscore               | 2.4.2                        | BrandonsCore-1.12-2.4.2.157-universal.jar        | None                                     |
	| UCH   | candymod                   | 0.4.2                        | candyworld-0.4.2.jar                             | None                                     |
	| UCH   | chineseworkshop            | 1.1.0.0                      | ChineseWorkshop_1.12.2-1.1.0.0.jar               | None                                     |
	| UCH   | chinjufumod                | 3.1.4.1                      | ChinjufuMod[1.12.2]3.1.4.1.jar                   | None                                     |
	| UCH   | clib                       | 1.0.2.31                     | CLib-1.0.2.31-universal.jar                      | None                                     |
	| UCH   | cofhcore                   | 4.4.1                        | CoFHCore-1.12.2-4.4.1.12-universal.jar           | None                                     |
	| UCH   | cofhworld                  | 1.1.1                        | CoFHWorld-1.12.2-1.1.1.12-universal.jar          | None                                     |
	| UCH   | compactsolars              | 1.12.2-5.0.17.340            | CompactSolars-1.12.2-5.0.17.340-universal.jar    | None                                     |
	| UCH   | cucumber                   | 1.1.0                        | cucumber-1.12-1.1.0.jar                          | None                                     |
	| UCH   | cyclopscore                | 0.11.5                       | CyclopsCore-1.12.2-0.11.5.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | thermalfoundation          | 2.4.1                        | ThermalFoundation-1.12.2-2.4.1.15-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | draconicevolution          | 2.3.11                       | Draconic-Evolution-1.12-2.3.11.290-universal.jar | None                                     |
	| UCH   | endercore                  | 1.12.2-0.5.22                | EnderCore-1.12.2-0.5.22.jar                      | None                                     |
	| UCH   | thermalexpansion           | 5.4.2                        | ThermalExpansion-1.12.2-5.4.2.25-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | enderio                    | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                        | None                                     |
	| UCH   | enderiointegrationtic      | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                        | None                                     |
	| UCH   | enderiobase                | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                        | None                                     |
	| UCH   | enderioconduits            | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                        | None                                     |
	| UCH   | enderiointegrationforestry | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                        | None                                     |
	| UCH   | mantle                     | 1.12-1.3.1.21                | Mantle-1.12-1.3.1.21.jar                         | None                                     |
	| UCH   | tconstruct                 | 1.12.2-2.9.1.65              | TConstruct-1.12.2-2.9.1.65.jar                   | None                                     |
	| UCH   | enderiointegrationticlate  | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                        | None                                     |
	| UCH   | enderiomachines            | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                        | None                                     |
	| UCH   | enderiopowertools          | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                        | None                                     |
	| UCH   | valkyrielib                | 1.12.2-2.0.9b                | valkyrielib-1.12.2-2.0.9b.jar                    | None                                     |
	| UCH   | environmentalmaterials     | @EM_VERSION@                 | environmentalmaterials-1.12.2-1.0.9a.jar         | None                                     |
	| UCH   | environmentaltech          | 1.12.2-2.0.9c                | environmentaltech-1.12.2-2.0.9c.jar              | None                                     |
	| UCH   | etlunar                    | 1.12.2-2.0.9a                | etlunar-1.12.2-2.0.9a.jar                        | None                                     |
	| UCH   | evilcraft                  | 0.10.55                      | EvilCraft-1.12.2-0.10.55.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | evilcraftcompat            | 1.0.0                        | EvilCraft-1.12.2-0.10.55.jar                     | None                                     |
	| UCH   | waila                      | 1.8.25                       | Hwyla-1.8.25-B40_1.12.jar                        | None                                     |
	| UCH   | extracells                 | 2.5.13                       | ExtraCells-1.12.2-2.5.13a56.jar                  | None                                     |
	| UCH   | fastleafdecay              | v14                          | FastLeafDecay-v14.jar                            | None                                     |
	| UCH   | foamfix                    | 0.9.9-1.12.2                 | foamfix-0.9.9-1.12.2-anarchy.jar                 | None                                     |
	| UCH   | gendustry                  | 1.6.5.8                      | gendustry-1.6.5.8-mc1.12.2.jar                   | None                                     |
	| UCH   | hammercore                 | 1.9.7.0                      | HammerCore-1.12.2-1.9.7.0.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCH   | inventorytweaks            | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                     | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | mysticalagriculture        | 1.6.9                        | mysticalagriculture-1.12-1.6.9.jar               | None                                     |
	| UCH   | jaopcaagriculture          | 1.12.2-1.2.1.10              | JAOPCAAgriculture-1.12.2-1.2.1.10.jar            | None                                     |
	| UCH   | jaopca                     | 1.12.2-2.2.6.83              | JAOPCA-1.12.2-2.2.6.83.jar                       | None                                     |
	| UCH   | oredictinit                | 1.12.2-2.2.1.67              | JAOPCA-1.12.2-2.2.6.83.jar                       | None                                     |
	| UCH   | jeibees                    | 0.9.0.5                      | jeibees-0.9.0.5-mc1.12.2.jar                     | None                                     |
	| UCH   | journeymap                 | 1.12.2-5.5.2                 | journeymap-1.12.2-5.5.2_2.jar                    | None                                     |
	| UCH   | jeresources                | 0.8.7.41                     | JustEnoughResources-1.12.2-0.8.7.41.jar          | None                                     |
	| UCH   | magicbees                  | 1.0                          | MagicBees-1.12.2-3.1.9.jar                       | None                                     |
	| UCH   | matteroverdrive            | 0.6.0.148                    | MatterOverdrive-1.12.2-0.6.0.148-universal.jar   | None                                     |
	| UCH   | mcjtylib_ng                | 2.6.7                        | mcjtylib-1.12-2.6.7.jar                          | None                                     |
	| UCH   | mekanism                   | 1.12.2-9.4.6.341             | Mekanism-1.12.2-9.4.6.341.jar                    | None                                     |
	| UCH   | mekanismgenerators         | 9.4.4                        | MekanismGenerators-1.12.2-9.4.6.341.jar          | None                                     |
	| UCH   | mekanismtools              | 9.4.4                        | MekanismTools-1.12.2-9.4.6.341.jar               | None                                     |
	| UCH   | mousetweaks                | 2.8                          | MouseTweaks-2.8-mc1.12.1_2.jar                   | None                                     |
	| UCH   | neid                       | 1.5.4.2                      | NotEnoughIDs-1.5.4.2.jar                         | None                                     |
	| UCH   | quickleafdecay             | 1.2.4                        | QuickLeafDecay-MC1.12.1-1.2.4.jar                | None                                     |
	| UCH   | refinedstorage             | 1.5.32                       | refinedstorage-1.5.32.jar                        | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCH   | rebornstorage              | 1.0.0                        | RebornStorage-1.12.2-3.0.5.41.jar                | None                                     |
	| UCH   | redstonearsenal            | 2.4.2                        | RedstoneArsenal-1.12.2-2.4.2.8-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | refinedstorageaddons       | 0.2                          | refinedstorageaddons-0.2.jar                     | None                                     |
	| UCH   | resourceloader             | 1.5.3                        | ResourceLoader-MC1.12.1-1.5.3.jar                | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCH   | rftools                    | 7.33                         | rftools-1.12-7.33.jar                            | None                                     |
	| UCH   | rftoolscontrol             | 1.8.1                        | rftoolsctrl-1.12-1.8.1.jar                       | None                                     |
	| UCH   | corerm                     | 1.3.1                        | RikMuldsCore_1.3.1.jar                           | None                                     |
	| UCH   | simplegenerators           | 1.12.2-2.0.9a                | simplegenerators-1.12.2-2.0.9a.jar               | None                                     |
	| UCH   | solarfluxreborn            | 3.50r                        | SolarFluxReborn_1.12.2-3.50r.jar                 | None                                     |
	| UCH   | tcinventoryscan            | 2.0.8                        | ThaumicInventoryScanning_1.12.2-2.0.8.jar        | None                                     |
	| UCH   | thaumicjei                 | 1.2.1                        | ThaumicJEI-1.12.2-1.2.2-5.jar                    | None                                     |
	| UCH   | camping                    | 2.4.1                        | TheCampingMod_2.4.1.jar                          | None                                     |
	| UCH   | thermalcultivation         | 0.2.0                        | ThermalCultivation-1.12.2-0.2.0.6-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCE   | thermaldynamics            | 2.4.1                        | ThermalDynamics-1.12.2-2.4.1.9-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | thermalinnovation          | 0.2.1                        | ThermalInnovation-1.12.2-0.2.1.6-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | tinker_io                  | release 2.6.1                | tinker_io-1.12.2-release 2.6.1.jar               | None                                     |
	| UCH   | tinkersaddons              | 1.0.7                        | Tinkers' Addons-1.12.1-1.0.7.jar                 | None                                     |
	| UCH   | tcomplement                | ${version}                   | TinkersComplement-1.12.2-0.2.3b.jar              | None                                     |
	| UCH   | tinkertoolleveling         | 1.12-1.0.3.DEV.56fac4f       | TinkerToolLeveling-1.12-1.0.3.jar                | None                                     |
	| UCH   | twilightforest             | 3.6.398                      | twilightforest-1.12.2-3.6.398-universal.jar      | None                                     |
	| UCH   | universalmodifiers         | 1.12.2-1.0.9a                | valkyrielib-1.12.2-2.0.9b.jar                    | None                                     |
	| UCH   | veinminer                  | 0.38.2                       | VeinMiner-1.12-0.38.2.647+b31535a.jar            | None                                     |
	| UCH   | veinminermodsupport        | 0.38.2                       | VeinMiner-1.12-0.38.2.647+b31535a.jar            | None                                     |
	| UCH   | wailaharvestability        | 1.1.12                       | WailaHarvestability-mc1.12-1.1.12.jar            | None                                     |
	| UCH   | wanionlib                  | 1.12.2-1.5                   | WanionLib-1.12.2-1.5.jar                         | None                                     |
	| UCH   | wawla                      | 2.5.255                      | Wawla-1.12.2-2.5.255.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | unidict                    | 1.12.2-2.4c                  | UniDict-1.12.2-2.4c.jar                          | None                                     |
	| UCH   | wrapup                     | 1.12-1.1.3                   | WrapUp-1.12-1.1.3.jar                            | None                                     |

	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.8.9.jar)
  
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
CorePlugin (UnicodeFontExtension-1.12.2-2.7.jar)
  bre.ufex.asm.Transformer
Plugin (NotEnoughIDs-1.5.4.2.jar)
  ru.fewizz.neid.asm.Transformer
HammerCoreCore (HammerCore-1.12.2-1.9.7.0.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4549' Renderer: 'Intel(R) HD Graphics 4600'
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)

	List of loaded APIs: 
		* AbyssalCraftAPI (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Biome (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Block (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Caps (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Condition (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Disruption (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Energy (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Entity (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Event (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Integration (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Internal (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Item (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Necronomicon (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Recipe (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Ritual (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* AbyssalCraftAPI|Spell (1.14.0) from AbyssalCraft-1.12.2-1.9.4.8.jar
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-11_2.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* bloodmagic-api (2.0.0) from BloodMagic-1.12.2-2.2.11-96.jar
		* BotaniaAPI (89) from Botania r1.10-354.jar
		* cofhapi (2.4.1) from CoFHCore-1.12.2-4.4.1.12-universal.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12-2.3.11.290-universal.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.0.277.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.0.277.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.8-mc1.12.2.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.5-60.jar
		* jeresources|API (0.8.7.41) from JustEnoughResources-1.12.2-0.8.7.41.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2_2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2_2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2_2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2_2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2_2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.9.1.172.jar
		* MatterOverdrive|API (0.4.1) from MatterOverdrive-1.12.2-0.6.0.148-universal.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.6.341.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.6.341.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.6.341.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.6.341.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.6.341.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.6.341.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.6.341.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1_2.jar
		* reborncoreAPI (3.8.0.264) from RebornCore-1.12.2-3.8.0.264-universal.jar
		* reborncoreAPI|Power (3.8.0.264) from RebornCore-1.12.2-3.8.0.264-universal.jar
		* reborncoreAPI|Recipe (3.8.0.264) from RebornCore-1.12.2-3.8.0.264-universal.jar
		* reborncoreAPI|Tile (3.8.0.264) from RebornCore-1.12.2-3.8.0.264-universal.jar
		* techrebornAPI (2.15.4.624) from TechReborn-1.12.2-2.15.4.624-universal.jar
		* Thaumcraft|API (6.0.2) from Thaumcraft-1.12.2-6.1.BETA11.jar
		* valkyrielib.api (1.12-2.0.1a) from valkyrielib-1.12.2-2.0.9b.jar
		* veinminerApi (0.3) from VeinMiner-1.12-0.38.2.647+b31535a.jar
		* WailaAPI (1.3) from Hwyla-1.8.25-B40_1.12.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.8.0.264
		Runtime Debofucsation 1
		RenderEngine: 0

**Comment by KingLemming** [comment]
You have a mod apparently registering a null block, which shouldn't be possible. Only advice I have for you is to remove mods til you find the culprit.

**Comment by KingLemming** [comment]
Simple enough mitigation on our end, but I'd like to know who is causing this in the first place.

**Comment by KnightBlood** [comment]
it seems like ChineseWorkshop

link:https://minecraft.curseforge.com/projects/chineseworkshop?gameCategorySlug=mc-mods&projectID=291142
