### ISSUE TITLE
FileNotFound Exception on startup

### ISSUE THREAD

**Issue by kmccmk9** [CoFH/Feedback#1063]
Hello using 
* `ThermalFoundation-1.12.2 2.4.1.15` 
* `Forge: v14.23.3.2655`
 * `Sponge Forge: 1.12.2-2655-7.1.0-BETA-3064`

I am receiving the following stack trace error output in my console.

`[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: java.io.IOException: No such file or directory
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at java.io.File.createNewFile(File.java:1012)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at cofh.thermalfoundation.init.TFProps.addWorldGeneration(TFProps.java:387)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at cofh.thermalfoundation.init.TFProps.preInit(TFProps.java:36)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at cofh.thermalfoundation.ThermalFoundation.preInit(ThermalFoundation.java:80)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:390]: 	at java.lang.Thread.run(Thread.java:748)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: java.io.IOException: No such file or directory
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at java.io.File.createNewFile(File.java:1012)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at cofh.thermalfoundation.init.TFProps.addWorldGeneration(TFProps.java:397)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at cofh.thermalfoundation.init.TFProps.preInit(TFProps.java:36)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at cofh.thermalfoundation.ThermalFoundation.preInit(ThermalFoundation.java:80)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:400]: 	at java.lang.Thread.run(Thread.java:748)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: java.io.IOException: No such file or directory
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at java.io.File.createNewFile(File.java:1012)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at cofh.thermalfoundation.init.TFProps.addWorldGeneration(TFProps.java:407)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at cofh.thermalfoundation.init.TFProps.preInit(TFProps.java:36)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at cofh.thermalfoundation.ThermalFoundation.preInit(ThermalFoundation.java:80)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[14:17:34] [Server thread/INFO] [STDERR]: [cofh.thermalfoundation.init.TFProps:addWorldGeneration:410]: 	at java.lang.Thread.run(Thread.java:748)`

**Comment by KingLemming** [comment]
Do you have CoFHWorld installed?

**Comment by KingLemming** [comment]
Honestly, this just sounds like your config folder is write protected or some such. That's going to be some configuration on your end to figure out.

**Comment by kmccmk9** [comment]
Hi @KingLemming I have checked the permissons on the folder and they are as such:

`drwxr-xr-x 23 root  root`

So read, write, execute for owner/group root. And I have confirmed that I am trying to start my minecraft server as root. Permissions on the folder shouldn't be an issue. Especially if you consider that I have 60 other mods that don't seem to be complaining about reading configuration files.

Also to answer your previous question I do not have CoFHWorld installed.

**Comment by KingLemming** [comment]
Fair enough. Do you have your world generation otherwise sorted?

If you do not, then Thermal Foundation Ores will not generate. If you want things to proceed normally, please go download CoFHWorld.

**Comment by kmccmk9** [comment]
That was it, that seems to have fixed my issue
