### ISSUE TITLE
Forge Lexicon Rockwool Crash

### ISSUE THREAD

**Issue by DietmarKracht** [CoFH/Feedback#1074]
The following crashreport comes with all version of TE 4.0+
When you have a Forge Lexicon in your inventory and then pick up some dropped rockwool it will be dyed black by default. This block is unnamed and leads to this crash.
you can check the conversions of rockwool in the forge lexicon.

`java.lang.ArrayIndexOutOfBoundsException: -32752
	at cofh.thermalexpansion.block.simple.ItemBlockRockwool.func_77667_c(ItemBlockRockwool.java:32) ~[ItemBlockRockwool.class:?]
	at cofh.thermalexpansion.block.simple.ItemBlockRockwool.func_77653_i(ItemBlockRockwool.java:26) ~[ItemBlockRockwool.class:?]
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
	at net.minecraftforge.client.GuiIngameForge.renderToolHightlight(GuiIngameForge.java:583) ~[GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:154) ~[GuiIngameForge.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[17:59:48] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----`

**Comment by KingLemming** [comment]
First of all, you went out of your way to enable this conversion...so that's bad.

Secondly, this is actually a corner case Lexicon issue that only happens because of the above. The default whitelist/blacklist options exist for a reason. You really should be using them.
