### ISSUE TITLE
[1.12.2] [Fixed issue] Thermal Expansion & CoFH core crash

### ISSUE THREAD

**Issue by David1261** [CoFH/Feedback#1090]
Hi,
English isn't my native language, but I'll try to do my best.
I play with some mods, I wanted to add Thermal Expansion so I installed all the dependencies.
But CoFH core seems to crash...
How I can fix it ? 
Thank you very much <3
```
Time: 5/13/18 6:37 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)
Caused by: java.lang.NoClassDefFoundError: cofh/thermalexpansion/plugins/top/PluginTOP
	at cofh.thermalexpansion.init.TEPlugins.preInit(TEPlugins.java:18)
	at cofh.thermalexpansion.ThermalExpansion.preInit(ThermalExpansion.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cofh.thermalexpansion.plugins.top.PluginTOP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NoClassDefFoundError: cofh/core/util/ModPlugin
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 44 more
Caused by: java.lang.ClassNotFoundException: cofh.core.util.ModPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3376785576 bytes (3220 MB) / 3875536896 bytes (3696 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 Optifine OptiFine_1.12.2_HD_U_D2 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                  | Source                                           | Signature                                |
	|:----- |:--------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft             | 1.12.2                   | minecraft.jar                                    | None                                     |
	| UCH   | mcp                   | 9.42                     | minecraft.jar                                    | None                                     |
	| UCH   | FML                   | 8.0.99.99                | forge-1.12.2-14.23.3.2655.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                 | 14.23.3.2655             | forge-1.12.2-14.23.3.2655.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | buildcraftlib         | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                        | None                                     |
	| UCH   | buildcraftcore        | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                        | None                                     |
	| UCH   | buildcraftbuilders    | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                        | None                                     |
	| UCH   | buildcraftenergy      | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                        | None                                     |
	| UCH   | buildcraftfactory     | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                        | None                                     |
	| UCH   | buildcraftrobotics    | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                        | None                                     |
	| UCH   | buildcraftsilicon     | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                        | None                                     |
	| UCH   | buildcrafttransport   | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                        | None                                     |
	| UCH   | codechickenlib        | 3.1.8.341                | CodeChickenLib-1.12.2-3.1.8.341-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | chickenchunks         | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux          | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | cofhcore              | 4.3.11                   | CoFHCore-1.12.2-4.3.11.6-universal.jar           | None                                     |
	| UCH   | cofhworld             | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar          | None                                     |
	| UCH   | customspawner         | 3.11.3                   | Custom-Mob-Spawner-Mod-1.12.2.jar                | None                                     |
	| UCH   | enderstorage          | 2.4.0.122                | Ender-Storage-Mod-1.12.jar                       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | forgelin              | 1.6.0                    | Forgelin-1.6.0.jar                               | None                                     |
	| UCH   | waila                 | 1.8.20                   | Hwyla-Mod-1.12.1.jar                             | None                                     |
	| UCH   | ic2                   | 2.8.73-ex112             | Industrialcraft-1.12.jar                         | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | ism                   | 2.0.0 MC-1.12.2          | Instant-Structures-Mod-1.12.2.jar                | None                                     |
	| UCH   | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironchest             | 1.12.2-7.0.40.824        | Iron-Chests-Mod-1.12.2.jar                       | None                                     |
	| UCH   | ironbackpacks         | 1.12.2-3.0.7-10          | IronBackpacks-1.12.2.jar                         | None                                     |
	| UCH   | jei                   | 4.9.1.170                | jei_1.12.2-4.9.1.170.jar                         | None                                     |
	| UCH   | modelloader           | 1.0.5                    | modelloader-1.0.5.jar                            | None                                     |
	| UCH   | magneticraft          | 2.3.0                    | Magneticraft-1.12.2.jar                          | None                                     |
	| UCH   | mocreatures           | 12.0.3                   | Mo-Creatures-Mod-1.12.2.jar                      | None                                     |
	| UCH   | mrnobody_morecommands | 6.0                      | More-Commands-Mod-1.12.2.jar                     | None                                     |
	| UCH   | nei                   | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.233-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | rftools               | 6.13                     | RFTools-1.12.jar                                 | None                                     |
	| UCH   | thermalfoundation     | 2.3.11                   | ThermalFoundation-1.12.2-2.3.12.10-universal.jar | None                                     |
	| UCE   | thermalexpansion      | 5.3.10                   | Thermal-Expansion-Mod-1.12.2.jar                 | None                                     |
	| UCH   | worldedit             | 6.1.8                    | WorldEdit-1.12.jar                               | None                                     |
	| UCH   | xaerominimap          | 1.13.9                   | Xaeros-Minimap-Fair-Play-1.12.jar                | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
MoreCommandsLoadingPlugin (More-Commands-Mod-1.12.2.jar)
  com.mrnobody.morecommands.asm.transform.TransformBlockRailBase
  com.mrnobody.morecommands.asm.transform.TransformForgeHooks
  com.mrnobody.morecommands.asm.transform.TransformItemStack
  com.mrnobody.morecommands.asm.transform.TransformStyle
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.64' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_D2
	OptiFine Build: 20180430-132249
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-v11.0.zip
	OpenGlVersion: 4.6.0 NVIDIA 397.64
	OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by David1261** [comment]
Edit : **Fixed issue**

I've updated **Thermal Expansion**, CoFHCore, Thermal Foundation, 
_(CoFHCore-1.12.2-4.4.1.12-universal) (ThermalFoundation-1.12.2-2.4.1.15-universal) (ThermalFoundation-1.12.2-2.4.1.15-universal)_

**Comment by KingLemming** [comment]
Yes. The only issue here was that you had not actually updated your mods.
