### ISSUE TITLE
cofh takes down my server

### ISSUE THREAD

**Issue by wackoamd1** [CoFH/Feedback#1105]
i recently updated all my mods. and it crashes randomly after awhile . the only mention is cofhcore .

[10:10:07] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
at net.minecraft.util.AxisAlignedBB.func_72330_a(SourceFile:9) ~[azt.class:?]
at net.minecraft.util.AxisAlignedBB.func_72314_b(SourceFile:59) ~[azt.class:?]
at net.minecraft.world.World.func_72945_a(World.java:1444) ~[ahb.class:?]
at cofh.asmhooks.HooksCore.getEntityCollisionBoxes(HooksCore.java:118) ~[HooksCore.class:?]
at net.minecraft.entity.Entity.func_70091_d(Entity.java:596) ~[sa.class:?]
at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1490) ~[sv.class:?]
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814) ~[sv.class:?]
at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367) ~[sw.class:?]
at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25) ~[yg.class:?]
at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217) ~[yq.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) ~[sv.class:?]
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) ~[sw.class:?]
at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30) ~[yg.class:?]
at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303) ~[yq.class:?]
at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) ~[mt.class:?]
at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]

cofh somehow causes a ticking entity.
so above this are a whole bunch of lines with "can't keep up is the server overloaded" ( and by a bunch i mean allot )
and below this is just the shutdown of the server

im not a coder so i have no idea how to fix this.
i really dont wanna downgrade all my updated teamcofh mods. and i got them all except tabula

mc 1.7.10
cofhcore 3.1.2
all the latest versions of the mods

**Comment by XFactHD** [comment]
"Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded" Give your server more RAM. If you don't know how, ask Google.

**Comment by skyboy** [comment]
As mentioned, this is just your server running out of memory.
