### ISSUE TITLE
cofh.tweak.asmhooks.HooksCore.getBlockCollisionBoxes

### ISSUE THREAD

**Issue by dpsman917** [CoFH/Feedback#1130]
I seem to be getting a crash on server side no matter what i do i even set "EntityCollisions=false".

-- Head --
Stacktrace:
	at cofh.tweak.asmhooks.HooksCore.getBlockCollisionBoxes(HooksCore.java:482)
	at cofh.tweak.asmhooks.HooksCore.getEntityCollisionBoxes(HooksCore.java:502)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:596)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1490)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)

More info in the crash reports it seems to only be modded entities... so far atleast.

Versions:
CoFHTweaks-[1.7.10]1.1.3B2-91

CoFHLib-[1.7.10]1.1.1-181*Edit* Removed CofhLib(Still crashing without) Derped and forgot its built into cofh core.

CoFHCore-[1.7.10]3.1.2-325

Forge 1.7.10-1566
Multimc 5 v0.4.11-751

This crash started after i installed cofh tweaks (I uninstall Optifine and fastcraft first)
Server boots we play arround for about ~5m then get a crash that has to do with EntityCollisions now this has happened with thaumcraft firebats, TIC slimes, thaumcraft wisps, and BoP nether wasps, im assuming its cofh tweaks + somthing else not playing along but i am at a loss as to what.
[crash-2016-04-03_22.30.13-server.txt](https://github.com/CoFH/Feedback/files/201772/crash-2016-04-03_22.30.13-server.txt)
[crash-2016-04-03_23.26.59-server.txt](https://github.com/CoFH/Feedback/files/201773/crash-2016-04-03_23.26.59-server.txt)
[crash-2016-04-04_00.23.13-server.txt](https://github.com/CoFH/Feedback/files/201774/crash-2016-04-04_00.23.13-server.txt)

Let me know if there is any other info you need, going to bed for now. Thanks in advance.

**Comment by skyboy** [comment]
I failed to commit the fix for this several months ago, a new build will go live in a few hours.

**Comment by dpsman917** [comment]
Oh awesome you guys are the best!!!!!~~~

**Comment by dpsman917** [comment]
Great work i updated it this morning my friend played on the server all day while i was at work so its fixed :D
