### ISSUE TITLE
ThermalFoundation-[1.7.10] 1.2.4-114 crash with AutoPackager mod.

### ISSUE THREAD

**Issue by MindCaged** [CoFH/Feedback#1159]
After quite a bit of debugging, I discovered that a Ticking Entity crash was being caused by this version of ThermalFoundation with AutoPackager, when I downgraded to the previous version it fixed it. Not sure if the problem is on this end or AutoPackager's end. Not sure what it could be, also not sure if any other mod is involved.

It only seems to happen if you have an AutoPackager actually in-world functioning and trying to craft.

Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.item.crafting.ShapelessRecipes.func_77569_a(SourceFile:36)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:323)
	at org.mcupdater.autopackager.TilePackager.tryCraft(TilePackager.java:132)
	at org.mcupdater.autopackager.TilePackager.func_145845_h(TilePackager.java:81)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

[crash-2016-05-20_19.19.50-server.txt](https://github.com/CoFH/Feedback/files/275595/crash-2016-05-20_19.19.50-server.txt)

**Comment by skyboy** [comment]
Anything attempting to craft would trigger this error, and given that no one else has reported this issue and that it is not present in dev, then the error is being introduced by another mod that's utilizing ThermalFoundation materials.
