### ISSUE TITLE
Update check for CoFH Core failed.

### ISSUE THREAD

**Issue by HelpMi** [CoFH/Feedback#1175]
I installed mods from the CoFH team onto my already modded minecraft and I had no problems until I added the mods from the CoFH team and when I launch minecraft I get the following error:
**Update check for CoFH Core failed.
java.io.FileNotFoundException: https://raw.githubusercontent.com/CoFH/VERSION/master/CoFHCore
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1834)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1429)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1428)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1038)
	at cofh.mod.updater.UpdateCheckThread.run(UpdateCheckThread.java:55)**

Is there anyway to fix it and have other people experienced this error?

**Comment by KingLemming** [comment]
1.7.10 is unsupported and this error is non-fatal. There's no issue.

**Comment by MCRakaan** [comment]
YES! I am digging this up! Supported or not, how hard is it to just remove the updater from the start and upload it?!There is no need for any server to have these kind of errors! Just because your to lazy?!
