### ISSUE TITLE
Thermal Foundation crashing MC while rendering an item in the creative menu

### ISSUE THREAD

**Issue by steamkore** [CoFH/Feedback#1183]
modpack is crashing while in the creative menu from trying to render cofh.thermalfoundation.block.ItemBlockGlassAlloy@341ad3a6

`Time: 6/30/18 8:24 PM
Description: Rendering item

java.lang.ClassCastException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap cannot be cast to gnu.trove.map.hash.TIntObjectHashMap
	at team.chisel.ctm.client.model.ModelUtil.lambda$getMesh$0(ModelUtil.java:51)
	at team.chisel.ctm.client.model.ModelUtil$$Lambda$5556/746472429.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at team.chisel.ctm.client.model.ModelUtil.getMesh(ModelUtil.java:51)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel$Overrides.handleItemState(AbstractCTMBakedModel.java:84)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.call(Reflector.java:960)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:399)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:258)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:210)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:653)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at team.chisel.ctm.client.model.ModelUtil.lambda$getMesh$0(ModelUtil.java:51)
	at team.chisel.ctm.client.model.ModelUtil$$Lambda$5556/746472429.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at team.chisel.ctm.client.model.ModelUtil.getMesh(ModelUtil.java:51)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel$Overrides.handleItemState(AbstractCTMBakedModel.java:84)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.call(Reflector.java:960)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:399)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:258)

-- Item being rendered --
Details:
	Item Type: cofh.thermalfoundation.block.ItemBlockGlassAlloy@341ad3a6
	Item Aux: 2
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:210)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:653)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (565, 191). Absolute: (1131, 697)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2`

**Comment by PanSzelescik** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63
