### ISSUE TITLE
ClassCastException Rendering thermalfoundation.block.ItemBlockGlass

### ISSUE THREAD

**Issue by Gibil** [CoFH/Feedback#1188]
I've tried this on server and single player, in creative menu and in inventory menu.  Client only crash is the same in all cases, and consistent when doing a search for glass and hitting this item on the screen. CoFH Core and Thermal Foundation are latest release.

full:
https://pastebin.com/cRDZRUyJ

excerpt:
Description: Rendering item

java.lang.ClassCastException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:222)

-- Item being rendered --
Details:
	Item Type: cofh.thermalfoundation.block.ItemBlockGlass@60bc530c
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:222)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

etc...

**Comment by KingLemming** [comment]
Can't replicate at all. I notice you have CTM. Is it up to date and does this crash happen with it removed?

There was an issue at one point with it and Forge.

**Comment by Gibil** [comment]
Confirmed it's CTM. Thank you very much.  Tested with two different instances. Will either update or remove.

**Comment by KingLemming** [comment]
Cool.
