### ISSUE TITLE
NullPointerException: Batching chunks

### ISSUE THREAD

**Issue by codydbgt** [CoFH/Feedback#1204]
https://cdn.discordapp.com/attachments/463980171775442944/468476983987404800/5gNnwCbb.txt
Description: Batching chunks
java.lang.NullPointerException: Batching chunks
	at mrtjp.projectred.relocation.MovementManager$.getWorldStructs(movement.scala:38)
	at mrtjp.projectred.relocation.WrappedTileMap.get(renders.scala:345)
	at mrtjp.projectred.relocation.WrappedTileMap.get(renders.scala:325)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147546_a(TileEntityRendererDispatcher.java:92)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147547_b(TileEntityRendererDispatcher.java:107)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:261)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)

**Comment by KingLemming** [comment]
Cool, but that's not us at all.

**Comment by codydbgt** [comment]
who is it?
if we dont find out no one will use your mod lol

**Comment by codydbgt** [comment]
i see 3 other issues like this u refuse to fix it just say u dont care .. oh wait u did

**Comment by Drullkus** [comment]
Don’t harass him, he’s a hard-working man and has enough on his plate, and I see Project Red on the top of the stacktrace.

**Comment by KingLemming** [comment]
Dude. This one is Project Red. The other ones were Harvestcraft, which I even mentioned at the time.

If you don't want to use the mod because you apparently refuse to read a crash log, that's fine. Don't.
