### ISSUE TITLE
compatibility issue? CoFHcore and Helpful Villagers

### ISSUE THREAD

**Issue by InuYasha86000** [CoFH/Feedback#1211]
I have been testing out mods for my modpack and have come across some strange errors about: a mod sorting cycle, and the errors seem to be around CoFHcore and CoFHAPI:1.0.

now these only happen when I add Helpful Villagers but the odd part is I had Helpful Villagers working with everything, even playable, I restarted the game and found the same error came up. here are screenshots of both errors:
![2016-07-14_19 39 43](https://cloud.githubusercontent.com/assets/15805183/16863371/ad5262ba-4a06-11e6-864d-be6843126cce.png)
![2016-07-14_21 03 21](https://cloud.githubusercontent.com/assets/15805183/16863375/b086cd0e-4a06-11e6-8e37-33741da0ce6e.png)

I'm not sure which end the full issue is on,

THIS error get's thrown in the log:
[20:59:11] [Client thread/TRACE] [FML/]: Sorting mods into an ordered list
[20:59:11] [Client thread/ERROR] [FML/]: Mod Sorting failed.
[20:59:11] [Client thread/ERROR] [FML/]: Visting node APIContainer{CoFHAPI:1.0}
[20:59:11] [Client thread/ERROR] [FML/]: Current sorted list : [Dummy Container (BeforeAll) @1589807065, Wrapped{mcp}, Wrapped{FML}, Wrapped{Forge}, Wrapped{da3dsoulASMFix}, Wrapped{CodeChickenCore}, Wrapped{CustomLanPort}, Wrapped{NotEnoughItems}, Wrapped{<CoFH ASM>}, Wrapped{cuchaz.ships.core}, Wrapped{FastCraft}, Dummy Container (Before) @707983020, FMLMod:LookingGlass{0.2.0.00}, FMLMod:securitycraft{v1.8.1}, FMLMod:FLabsBF{4.3}]
[20:59:11] [Client thread/ERROR] [FML/]: Visited set for this node : [FMLMod:Additional-Buildcraft-Objects{MC1.7.10-BC7.1release4.0.9}, Wrapped{<CoFH ASM>}, FMLMod:FLabsBF{4.3}, FMLMod:BuildCraft|Silicon{7.1.17}, Dummy Container (After) @52514663, Wrapped{cuchaz.ships.core}, FMLMod:BuildCraft|Core{7.1.17}, Wrapped{NotEnoughItems}, FMLMod:securitycraft{v1.8.1}, Wrapped{da3dsoulASMFix}, FMLMod:LookingGlass{0.2.0.00}, Wrapped{CodeChickenCore}, Wrapped{FML}, Dummy Container (BeforeAll) @1589807065, Wrapped{CustomLanPort}, Wrapped{FastCraft}, Wrapped{Forge}, Dummy Container (AfterAll) @1319167580, Wrapped{mcp}, FMLMod:CoFHCore{1.7.10R3.1.2}, Dummy Container (Before) @707983020, APIContainer{CoFHAPI:1.0}]
[20:59:11] [Client thread/ERROR] [FML/]: Explored node set : [Wrapped{<CoFH ASM>}, FMLMod:FLabsBF{4.3}, Wrapped{cuchaz.ships.core}, Wrapped{NotEnoughItems}, FMLMod:securitycraft{v1.8.1}, Wrapped{da3dsoulASMFix}, FMLMod:LookingGlass{0.2.0.00}, Wrapped{CodeChickenCore}, Wrapped{FML}, Dummy Container (BeforeAll) @1589807065, Wrapped{CustomLanPort}, Wrapped{FastCraft}, Wrapped{Forge}, Wrapped{mcp}, Dummy Container (Before) @707983020]
[20:59:11] [Client thread/ERROR] [FML/]: Likely cycle is in : [FMLMod:Additional-Buildcraft-Objects{MC1.7.10-BC7.1release4.0.9}, FMLMod:BuildCraft|Silicon{7.1.17}, Dummy Container (After) @52514663, FMLMod:BuildCraft|Core{7.1.17}, Dummy Container (AfterAll) @1319167580, FMLMod:CoFHCore{1.7.10R3.1.2}, APIContainer{CoFHAPI:1.0}]
[20:59:11] [Client thread/ERROR] [FML/]: A dependency cycle was detected in the input mod set so an ordering cannot be determined
[20:59:11] [Client thread/ERROR] [FML/]: The first mod in the cycle is APIContainer{CoFHAPI:1.0}
[20:59:11] [Client thread/ERROR] [FML/]: The mod cycle involves
[20:59:11] [Client thread/ERROR] [FML/]: FMLMod:Additional-Buildcraft-Objects{MC1.7.10-BC7.1release4.0.9} : before: [], after: [Forge@[10.13.2.1208,), BuildCraft|Transport, BuildCraft|Energy, BuildCraft|Silicon, BuildCraft|Factory, BuildCraft|Builders, LiquidXP, GeoStrata, CoFHCore, ThermalFoundation, ThermalExpansion]
[20:59:11] [Client thread/ERROR] [FML/]: FMLMod:BuildCraft|Silicon{7.1.17} : before: [], after: [BuildCraft|Core@7.1.17]
[20:59:11] [Client thread/ERROR] [FML/]: Dummy Container (After) @52514663 : before: [], after: []
[20:59:11] [Client thread/ERROR] [FML/]: FMLMod:BuildCraft|Core{7.1.17} : before: [], after: [Forge@[10.13.2.1236,)]
[20:59:11] [Client thread/ERROR] [FML/]: Dummy Container (AfterAll) @1319167580 : before: [], after: []
[20:59:11] [Client thread/ERROR] [FML/]: FMLMod:CoFHCore{1.7.10R3.1.2} : before: [], after: [Forge@[10.13.4.1448,10.14)]
[20:59:11] [Client thread/ERROR] [FML/]: APIContainer{CoFHAPI:1.0} : before: [redgear_core, bcadditions, Railcraft, networksmanager, CoFHCore, ExtraUtilities, BuildCraft|Compat, rfwindmill, FloodLights, Forestry, BuildCraft|Silicon, BuildCraft|Transport, BuildCraft|Builders, BuildCraft|Energy, BuildCraft|Robotics, BuildCraft|Factory, BuildCraft|Core, flansmod, ImmersiveEngineering], after: [CoFHCore]
[20:59:11] [Client thread/ERROR] [FML/]: The full error
cpw.mods.fml.common.toposort.ModSortingException: There was a cycle detected in the input graph, sorting is not possible
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:190) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.topologicalSort(TopologicalSort.java:145) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.ModSorter.sort(ModSorter.java:133) ~[ModSorter.class:?]
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:272) [Loader.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:493) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by KingLemming** [comment]
Sorry, but this isn't solvable nor is it really an issue, it's just how the mods you have interact.

It's exactly as stated - there's a dependency sorting error. Somebody is doing something they shouldn't be. It's not us, as Core isn't supposed to load after *anything.* Try removing duplicate code from your mod jars/zips, but that's the best I got for ya.

**Comment by InuYasha86000** [comment]
I want to thank you for looking at my issue. I found out after some deep log looking that it was an issue with Fastcraft. Thank you again for checking my error before.

**Comment by skyboy** [comment]
You should be able to use CoFHTweaks to get much of the same performance gain, just without the other weird side effects.
