### ISSUE TITLE
Possible Thermal Expansion Bug with Storage Drawers?

### ISSUE THREAD

**Issue by InuYasha86000** [CoFH/Feedback#1216]
I'm not sure which mod is causing this bug/error in the log but I wanted to post it to both just in case:

[12:43:31] [Server thread/WARN] [StorageDrawers/StorageDrawersForestry]: Error registering pack block in module: com.jaquadro.minecraft.storagedrawers.integration.ThermalExpansion
java.lang.NullPointerException
	at com.jaquadro.minecraft.storagedrawers.packs.forestry.core.DataResolver.getBlock(DataResolver.java:46) ~[DataResolver.class:?]
	at com.jaquadro.minecraft.storagedrawers.integration.ThermalExpansion.registerPackBlock(ThermalExpansion.java:117) [ThermalExpansion.class:?]
	at com.jaquadro.minecraft.storagedrawers.core.Api.registerStandardPackRecipes(Api.java:54) [Api.class:?]
	at com.jaquadro.minecraft.storagedrawers.packs.forestry.StorageDrawersPack.postInit(StorageDrawersPack.java:53) [StorageDrawersPack.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:1.7.10-1614.57]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:1.7.10-1614.57]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:1.7.10-1614.57]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-1614.57]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:1.7.10-1614.57]
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:1.7.10-1614.57]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324) [FMLCommonHandler.class:1.7.10-1614.57]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:288) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[12:43:31] [Server thread/WARN] [StorageDrawers/StorageDrawersForestry]: Error registering pack block in module: com.jaquadro.minecraft.storagedrawers.integration.ThermalExpansion
java.lang.NullPointerException
	at com.jaquadro.minecraft.storagedrawers.packs.forestry.core.DataResolver.getBlock(DataResolver.java:46) ~[DataResolver.class:?]
	at com.jaquadro.minecraft.storagedrawers.integration.ThermalExpansion.registerPackBlock(ThermalExpansion.java:117) [ThermalExpansion.class:?]
	at com.jaquadro.minecraft.storagedrawers.core.Api.registerStandardPackRecipes(Api.java:54) [Api.class:?]
	at com.jaquadro.minecraft.storagedrawers.packs.forestry.StorageDrawersPack.postInit(StorageDrawersPack.java:53) [StorageDrawersPack.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:1.7.10-1614.57]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:1.7.10-1614.57]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:1.7.10-1614.57]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-1614.57]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:1.7.10-1614.57]
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:1.7.10-1614.57]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324) [FMLCommonHandler.class:1.7.10-1614.57]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:288) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

It always happens in the same spot, the server still boots, i'm not sure about client side as I don't see the boot up window like the server does but I would presume it is there as well.

**Comment by KingLemming** [comment]
There is nothing in that log that points to us in any way. None of those files belong to us.
