### ISSUE TITLE
COFH World Crash

### ISSUE THREAD

**Issue by Coconatra** [CoFH/Feedback#1224]
To run thermal expansion I need COFH World 1.2.0 (or above) and under 2.0.0. I used the latest version (1.2.0.5) because the one under that is the 1.1.1.12 version (that I can't use because it's under 1.2.0) but i got a crash report.
I'm running this mods: (With forge 1.12.2 - 14.23.4.2739)
appliedenergistics2-rv5-stable-11
backpacks+1.12.2+-+3.5.2
Baubles-Mod-1.12.2
Botania r1.10-354
CodeChickenLib-1.12.2-3.2.0.345-universal
CoFHCore-1.12.2-4.5.1.17-universal
CoFHWorld-1.12.2-1.2.0.5-universal 
Dense-Metals-Mod-1.12.2
extrautils2-1.12-1.8.1
Forgelin-1.5.1
GiacomosExperienceSeedling-1.12.2-1.2.2
industrialcraft-2-2.8.73-ex112
Industrial-Foregoing-Mod-1.12.2
InventoryTweaks-1.64-dev
Iron-Chests-Mod-1.12.2
jei_1.12.2-4.11.0.202
Mantle-Mod-1.12.2
OpenBlocks-Mod-1.12.2
OpenModsLib-1.12.2
RedstoneFlux-1.12-2.0.2.3-universal
SimplyEnchanting-1.12-1.0.3
TConstruct-1.12.2-2.10.1.87
Tech+Ores+1.1+[1.12.2]
Tesla-Core-Lib-1.12.2
ThermalExpansion-1.12.2-5.5.0.29-universal (1)
ThermalFoundation-1.12.2-2.5.0.18-universal
TreeCapitator-Mod-1.12 (1)
twilightforest-1.12.2-3.7.424-universal
Xaeros_Minimap_1.15.2_Forge_1.12

And this is the crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.5.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2.jar)
  BCModPlugin (backpacks+1.12.2+-+3.5.2.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 7/25/18 7:18 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Foundation (thermalfoundation)
Caused by: java.lang.NoClassDefFoundError: cofh/core/fluid/BlockFluidCore
	at cofh.thermalfoundation.block.BlockOreFluid.<clinit>(BlockOreFluid.java:429)
	at cofh.thermalfoundation.init.TFBlocks.preInit(TFBlocks.java:23)
	at cofh.thermalfoundation.ThermalFoundation.preInit(ThermalFoundation.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:246)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cofh.core.fluid.BlockFluidCore
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: java.lang.VerifyError: class cofh.core.fluid.BlockFluidCore overrides final method getDensity.()I
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 507834896 bytes (484 MB) / 1344606208 bytes (1282 MB) up to 5263851520 bytes (5020 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1000M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2739 Optifine OptiFine_1.12.2_HD_U_E1 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version                      | Source                                             | Signature                                |
	|:----- |:----------------------- |:---------------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft               | 1.12.2                       | minecraft.jar                                      | None                                     |
	| UCH   | mcp                     | 9.42                         | minecraft.jar                                      | None                                     |
	| UCH   | FML                     | 8.0.99.99                    | forge-1.12.2-14.23.4.2739.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                   | 14.23.4.2739                 | forge-1.12.2-14.23.4.2739.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | openmodscore            | 0.11.3                       | minecraft.jar                                      | None                                     |
	| UCH   | appliedenergistics2     | rv5-stable-11                | appliedenergistics2-rv5-stable-11.jar              | None                                     |
	| UCH   | backpacks16840          | 3.5.2                        | backpacks+1.12.2+-+3.5.2.jar                       | None                                     |
	| UCH   | baubles                 | 1.5.2                        | Baubles-Mod-1.12.2.jar                             | None                                     |
	| UCH   | botania                 | r1.10-354                    | Botania r1.10-354.jar                              | None                                     |
	| UCH   | codechickenlib          | 3.2.0.345                    | CodeChickenLib-1.12.2-3.2.0.345-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux            | 2.0.2                        | RedstoneFlux-1.12-2.0.2.3-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | cofhcore                | 4.5.1                        | CoFHCore-1.12.2-4.5.1.17-universal.jar             | None                                     |
	| UCH   | cofhworld               | 1.2.0                        | CoFHWorld-1.12.2-1.2.0.5-universal (4).jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | densemetals             | 1.0.1                        | Dense-Metals-Mod-1.12.2.jar                        | None                                     |
	| UCH   | jei                     | 4.11.0.202                   | jei_1.12.2-4.11.0.202.jar                          | None                                     |
	| UCH   | mantle                  | 1.12-1.3.2.24                | Mantle-Mod-1.12.2.jar                              | None                                     |
	| UCH   | tconstruct              | 1.12.2-2.10.1.87             | TConstruct-1.12.2-2.10.1.87.jar                    | None                                     |
	| UCH   | extrautils2             | 1.0                          | extrautils2-1.12-1.8.1.jar                         | None                                     |
	| UCH   | forgelin                | 1.5.1                        | Forgelin-1.5.1.jar                                 | None                                     |
	| UCH   | giacomos_exp            | 1.2.2                        | GiacomosExperienceSeedling-1.12.2-1.2.2.jar        | None                                     |
	| UCH   | teslacorelib            | 1.0.10                       | Tesla-Core-Lib-1.12.2.jar                          | None                                     |
	| UCH   | industrialforegoing     | 1.12.2-1.12.1                | Industrial-Foregoing-Mod-1.12.2.jar                | None                                     |
	| UCH   | ic2                     | 2.8.73-ex112                 | industrialcraft-2-2.8.73-ex112.jar                 | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | inventorytweaks         | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironchest               | 1.12.2-7.0.40.824            | Iron-Chests-Mod-1.12.2.jar                         | None                                     |
	| UCH   | openmods                | 0.11.3                       | OpenModsLib-1.12.2.jar                             | None                                     |
	| UCH   | openblocks              | 1.7.3                        | OpenBlocks-Mod-1.12.2.jar                          | None                                     |
	| UCH   | simplyenchanting        | 1.0.3                        | SimplyEnchanting-1.12-1.0.3.jar                    | None                                     |
	| UCH   | techores                | 1.1                          | Tech+Ores+1.1+[1.12.2].jar                         | None                                     |
	| UCEE  | thermalfoundation       | 2.5.0                        | ThermalFoundation-1.12.2-2.5.0.18-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thermalexpansion        | 5.5.0                        | ThermalExpansion-1.12.2-5.5.0.29-universal (1).jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | bspkrscore              | at_0.9                       | TreeCapitator-Mod-1.12 (1).jar                     | None                                     |
	| UC    | treecapitator           | at_0.9                       | TreeCapitator-Mod-1.12 (1).jar                     | None                                     |
	| UC    | twilightforest          | 3.7.424                      | twilightforest-1.12.2-3.7.424-universal.jar        | None                                     |
	| UC    | xaerominimap            | 1.15.2                       | Xaeros_Minimap_1.15.2_Forge_1.12.jar               | None                                     |
	| UC    | teslacorelib_registries | 1.0.10                       | Tesla-Core-Lib-1.12.2.jar                          | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.5.1.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2.jar)
  openmods.core.OpenModsClassTransformer
BCModPlugin (backpacks+1.12.2+-+3.5.2.jar)
  brad16840.core.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

Any help? What can I do?
Thanks.

**Comment by KingLemming** [comment]
You can update CoFHCore because I literally put out a patch for this. ;)
