### ISSUE TITLE
NPE in BlockCache

### ISSUE THREAD

**Issue by Ghostlyr** [CoFH/Feedback#1227]
I have a crash with last version of TE, when left-clicking on empty cache. 

```
java.lang.NullPointerException: Ticking memory connection
	at cofh.thermalexpansion.block.cache.BlockCache.func_149699_a(BlockCache.java:174)
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:165)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cofh.thermalexpansion.block.cache.BlockCache.func_149699_a(BlockCache.java:174)
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:165)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@4c3e4318
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

MC 1.7.10 Forge 1614
CoFHCore 3.1.3-327
ThermalFoundation 1.2.5-115
ThermalExpansion 4.1.3-246

**Comment by mcdodge34** [comment]
Quick question, should I update to the dev to fix this issue or wait for an official release, so far its the only bug I've found that is a little annoying but maybe there's more bugs that I'm not aware like memory leaks that would need me to update to the latest dev to fix a few issues.
