### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LemonNick** [CoFH/Feedback#1228]
Crash on server
Time: 7/31/16 4:56 AM
Description: Exception in server tick loop

java.lang.ClassCastException: cofh.thermaldynamics.duct.fluid.FluidGrid cannot be cast to cofh.thermaldynamics.duct.fluid.FluidGridSuper
	at cofh.thermaldynamics.duct.fluid.TileFluidDuctSuper.setGrid(TileFluidDuctSuper.java:18)
	at cofh.thermaldynamics.multiblock.MultiBlockFormer.checkMultiBlock(MultiBlockFormer.java:45)
	at cofh.thermaldynamics.multiblock.MultiBlockFormer.formGrid(MultiBlockFormer.java:22)
	at cofh.thermaldynamics.block.TileTDBase.formGrid(TileTDBase.java:629)
	at cofh.thermaldynamics.block.TileTDBase.tickMultiBlock(TileTDBase.java:617)
	at cofh.thermaldynamics.core.WorldGridList.tickEnd(WorldGridList.java:89)
	at cofh.thermaldynamics.core.TickHandler.tick(TickHandler.java:91)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_174_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1006)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Silver-Wulf** [comment]
Um, this still exists in the latest version and is terrorizing my server at seemingly random intervals.
