### ISSUE TITLE
[Thermal Expansion] Morbs in strongbox crashes game

### ISSUE THREAD

**Issue by pascal-aman** [CoFH/Feedback#1229]
It seems like the NBT data of morbs is quite large. I have a natural spawn darkroom with creature captures set up sending captures mobs into a buffer strongbox before processing. Seems like there was some backup, and i had a few morbs in the strongbox, about 1/3 of the max enchanted strongbox was full. Then the game started crashing. Sometimes with an "Illegal argument exception, payload may not exceed 32kb", sometimes the game will just hang. Only some interactions crash, like opening the GUI, wrenching the strongbox and then placing it again etc. It seems like TD pipes can still interact with it, like piping out items with a servo is working.

I'm not fully sure, but i don't think the backlog was larger than a vanilla double chest. I know Minecraft itself has a silly NBT size limit, but i don't think just 30-40 filled morbs should exceed this limit, esp. if the mobs inside them are naturally spawned mobs. I play with basically only the TE series of mods, so the only non-vanilla mobs i have are the blizzes etc.

Forge: 1.12.2-14.23.4.2739
CoFH core: 1.12.2-4.5.3.20
Thermal Foundation: 1.12.2-2.5.0.19
Thermal Expansion: 1.12.2-5.5.0.29

Here is a crash trying to open the strongbox. Not much help it seems, since the crash is in Minecraft:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 7/28/18 12:45 AM
Description: Updating screen events

java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at net.minecraft.network.NetworkSystem$1.func_179280_b(NetworkSystem.java:52)
	at net.minecraft.network.NetworkSystem$1.func_179280_b(NetworkSystem.java:49)
	at net.minecraft.util.LazyLoadBase.func_179281_c(SourceFile:10)
	at net.minecraft.network.NetworkSystem.func_151270_a(NetworkSystem.java:140)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2412)
	at net.minecraftforge.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:728)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186777_e(GuiListWorldSelectionEntry.java:249)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186774_a(GuiListWorldSelectionEntry.java:199)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_148278_a(GuiListWorldSelectionEntry.java:163)
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41)
	at net.minecraft.client.gui.GuiWorldSelection.func_73864_a(SourceFile:117)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiWorldSelection.func_146274_d(SourceFile:49)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:157)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 30 more
Caused by: java.io.IOException: Unable to establish loopback connection
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:101)
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:68)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:170)
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50)
	at java.nio.channels.Pipe.open(Pipe.java:155)
	at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:127)
	at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:155)
	... 34 more
Caused by: java.net.SocketException: Permission denied: connect
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
	at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:130)
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:83)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at net.minecraft.network.NetworkSystem$1.func_179280_b(NetworkSystem.java:52)
	at net.minecraft.network.NetworkSystem$1.func_179280_b(NetworkSystem.java:49)
	at net.minecraft.util.LazyLoadBase.func_179281_c(SourceFile:10)
	at net.minecraft.network.NetworkSystem.func_151270_a(NetworkSystem.java:140)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2412)
	at net.minecraftforge.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:728)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186777_e(GuiListWorldSelectionEntry.java:249)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186774_a(GuiListWorldSelectionEntry.java:199)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_148278_a(GuiListWorldSelectionEntry.java:163)
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41)
	at net.minecraft.client.gui.GuiWorldSelection.func_73864_a(SourceFile:117)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiWorldSelection.func_146274_d(SourceFile:49)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiScreenWorking
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1624003008 bytes (1548 MB) / 4281597952 bytes (4083 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.4.2739 Optifine OptiFine_1.12.2_HD_U_E1 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                 | Version                  | Source                                          | Signature                                |
	|:--------- |:------------------ |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft          | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                | 8.0.99.99                | forge-1.12.2-14.23.4.2739.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge              | 14.23.4.2739             | forge-1.12.2-14.23.4.2739.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | baubles            | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJAAAA | biomesoplenty      | 7.0.1.2384               | BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar   | None                                     |
	| UCHIJAAAA | codechickenlib     | 3.2.0.345                | CodeChickenLib-1.12.2-3.2.0.345-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux       | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | cofhcore           | 4.5.3                    | CoFHCore-1.12.2-4.5.3.20-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld          | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | jei                | 4.11.0.202               | jei_1.12.2-4.11.0.202.jar                       | None                                     |
	| UCHIJAAAA | ftblib             | 5.2.0.25                 | FTBLib-5.2.0.25.jar                             | None                                     |
	| UCHIJAAAA | journeymap         | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAA | ftbutilities       | 5.2.0.30                 | FTBUtilities-5.2.0.30.jar                       | None                                     |
	| UCHIJAAAA | inventorytweaks    | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | thermalfoundation  | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalexpansion   | 5.5.0                    | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | redstonearsenal    | 2.5.1                    | RedstoneArsenal-1.12.2-2.5.1.13-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermaldynamics    | 2.5.1                    | ThermalDynamics-1.12.2-2.5.1.14-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | simplyjetpacks     | 2.2.7.45                 | SimplyJetpacks2-1.12.2-2.2.7.45.jar             | None                                     |
	| UCHIJAAAA | theoneprobe        | 1.4.23                   | theoneprobe-1.12-1.4.23.jar                     | None                                     |
	| UCHIJAAAA | thermalcultivation | 0.3.0                    | ThermalCultivation-1.12.2-0.3.0.7-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalinnovation  | 0.3.0                    | ThermalInnovation-1.12.2-0.3.0.7-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.58' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2739
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.58, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft 128x MC112.zip, PureBDcraft Damaged Items MC111.zip, PureBDcraft More 3D Blocks MC111.zip, Sphax Baubles 128x 1.11.2-1.4.4.zip, Sphax128x_BOP_Ver7.0.1.2334.zip, Sphax_CoFHCore_512x-64x.zip, Sphax_JustEnoughItems_512x-64x.zip, Sphax_RedstoneArsenal_128x.zip (incompatible), Sphax_SimplyJetpacks_128x.zip, Sphax_ThermalCultivation_128x.zip, Sphax_ThermalDynamics_128x.zip, Sphax_ThermalExpansion_128x.zip, Sphax_ThermalFoundation_128x.zip, Sphax_ThermalInnovation_128x.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7 CPU 920 @ 2.67GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 398.58
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by KingLemming** [comment]
So, we had a report of this a while back with Forestry bees.

And ultimately, we found out that our mod actually had nothing to do with it. Couldn't replicate this at all even if we had megabytes of data on the bees. And I can't seem to make it happen with Morbs either.

There's probably something else going on here. There's no TE code at all in that trace.

**Comment by covers1624** [comment]
Client -> Server packets have a hard limit of 32K, where as Server -> Client packets /technecally/ don't have a limit. Whilst the NBT data may be large, the only way this can occur is if the tag is sent from the client -> server. i can't think of many cases where this happens atm.

**Comment by pascal-aman** [comment]
Seems like the exception itself was not in the crash report but in the logs, looks like this:

[20:22:13] [Netty Local Client IO #0/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:534) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [DefaultEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]


I get this error in the log with a server shutdown consistently if i fill an enderium strongbox with holding iV to about 1/3 with morbs caught in a normal darkroom and then try to open the strongbox. As long as i don't open the strongbox, no error happens, TD works fine with it, so does detailed info of theoneprobe (it shows a large list of colorful morbs if i sneak-look at the strongbox). The error is specific to opening the GUI.
I can wrench the strongbox and collect it no problem, but if i then place it in the world again, i get the same exception in the log:

[20:29:44] [Netty Local Client IO #1/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:534) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [DefaultEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

Still, no TE code in the stack. Is this a bug in forge caused by the morbs?

**Comment by KingLemming** [comment]
This isn't in Forge. It's possibly in another mod you have which tries to "sync" inventory contents to the server.

Which...it shouldn't be doing that.

**Comment by pascal-aman** [comment]
After removing the few other mods i have one by one i found that The One Probe causes the bug. Seems like Refined Storage and Draconium Chests cause the same issue. They track the bug at https://github.com/McJtyMods/TheOneProbe/issues/215

Sorry to have wasted your time.

**Comment by KingLemming** [comment]
No worries! Glad it's sorted. :)
