### ISSUE TITLE
Redstone arsenal - crash

### ISSUE THREAD

**Issue by KasperFranz** [CoFH/Feedback#124]
Time: 2/18/15 5:21 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: redstonearsenal.item.tool.ItemShovelRF.harvestBlock(Lnet/minecraft/world/World;IIILnet/minecraft/entity/player/EntityPlayer;)V
	at redstonearsenal.item.tool.ItemShovelRF.func_150894_a(ItemShovelRF.java:110)
	at net.minecraft.item.ItemStack.func_150999_a(ItemStack.java:368)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:350)
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:242)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:749)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:744)

running on 1.0.1 Infinity pack using RedstoneArsenal{1.7.10R1.1.0RC1}

It happens with all of the weapons there destroys blocks, when you have empowered it.

**Comment by KingLemming** [comment]
Report it to the Infinity pack. They screwed up and included an alpha.

**Comment by KasperFranz** [comment]
Oh wow didn't even see it was a alpha build.

That means that the bug is fixed in the latest build 
 :)?

**Comment by KingLemming** [comment]
No, it means they should be using the actual release builds and not alphas. The alphas are for as-of-yet unreleased builds.

That only happens when you mix release builds and alphas, which they've done.
