### ISSUE TITLE
problem with TE and Bitcoin mod

### ISSUE THREAD

**Issue by MadRatSRP** [CoFH/Feedback#1245]
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class cofh.core.inventory.ComparableItemStack id= 252525823 hashCode= -469978147 toString= cofh.core.inventory.ComparableItemStack@252525823{m:70, i:cofh.thermalfoundation.item.ItemCoin@1534025102, v:5160}; object #2 =class cofh.core.inventory.ComparableItemStack id= 252525823 hashCode= -469978147 toString= cofh.core.inventory.ComparableItemStack@252525823{m:70, i:cofh.thermalfoundation.item.ItemCoin@1534025102, v:5160}

    at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
    at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:426)
    at gnu.trove.map.hash.TObjectIntHashMap.rehash(TObjectIntHashMap.java:191)
    at gnu.trove.impl.hash.THash.compact(THash.java:201)
    at gnu.trove.impl.hash.THash.removeAt(THash.java:272)
    at gnu.trove.impl.hash.TObjectHash.removeAt(TObjectHash.java:104)
    at gnu.trove.map.hash.TObjectIntHashMap.removeAt(TObjectIntHashMap.java:292)
    at gnu.trove.map.hash.TObjectIntHashMap.remove(TObjectIntHashMap.java:277)
    at cofh.thermalexpansion.util.managers.dynamo.NumismaticManager.removeFuel(NumismaticManager.java:86)
    at boni.bitcoin.ThermalExpansion.removeBitcoinRecipe(ThermalExpansion.java:22)
    at boni.bitcoin.ThermalExpansion.updateBitcoinRecipe(ThermalExpansion.java:26)
    at boni.bitcoin.stockexchange.BullAndBear.setCurrentValue(BullAndBear.java:90)
    at boni.bitcoin.stockexchange.BullAndBear.updateCurrentValue(BullAndBear.java:138)
    at boni.bitcoin.stockexchange.BullAndBear.modifyValue(BullAndBear.java:99)
    at boni.bitcoin.stockexchange.BullAndBear.onWorldTick(BullAndBear.java:80)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2737_BullAndBear_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:776)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

**Comment by Tora-B** [comment]
I think CoFH switched from Trove to FastUtils after Forge did. I don't know if that's actually the cause of the problem here, but it looks pretty likely that the bitcoin mod is at fault. Probably an API change they need to adapt to.

**Comment by KingLemming** [comment]
We did indeed change. Please update your mods.
