### ISSUE TITLE
The client has sent too many requests within a certain amount of time

### ISSUE THREAD

**Issue by Eufranio** [CoFH/Feedback#1248]
Seems CoFH is asking too many requests to mojang when looking for a uuid/skin in a Tesseract or private machine.

Log:
```
[13:40:12 WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@57d1827[id=b11912c9-6816-3c18-8ba9-bef06cc3d94b,name=yFox,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[server-1.7.10.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [server-1.7.10.jar:?]
        at cofh.lib.util.helpers.SecurityHelper.getProfile(SecurityHelper.java:216) [SecurityHelper.class:?]
        at cofh.thermalexpansion.block.TileInventory$1.run(TileInventory.java:485) [TileInventory$1.class:?]
```

**Comment by HeyZeer0** [comment]
nothing?

**Comment by evernife** [comment]
Old related/ignored https://github.com/CoFH/Feedback/issues/1046
