### ISSUE TITLE
[SF3] heavy lag after updating to 3/25 versions

### ISSUE THREAD

**Issue by SigurdCole** [CoFH/Feedback#126]
Hello!

I've added the TE suite (Redstone Arsenal, Thermal Foundation, Thermal Expansion and CodeChickenLib) to Skyfactory 3, and it's been running pretty well to date.

Updating to the most recent version has reduced my FPS from 50+ to roughly 1.

I've tried loading a clean world - since it's a skyblock, there isn't much to load - but the problem persists.

My MultiMC log is showing substantial repeated errors, here's an excerpt of a non-repeating section.

[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: java.io.IOException: Server returned HTTP response code: 403 for URL: http://eladkay.pw/scanner/ScannerCallback.php?username=<PROFILE NAME>&timestamp=SatMar2507:48:35AKDT2017&version=1.4
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.GeneratedConstructorAccessor197.newInstance(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at java.security.AccessController.doPrivileged(Native Method)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at java.security.AccessController.doPrivileged(Native Method)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at eladkay.scanner.proxy.ClientProxy.sendGet(ClientProxy.java:71)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at eladkay.scanner.proxy.ClientProxy.onClientTick(ClientProxy.java:57)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_704_ClientProxy_onClientTick_ClientTickEvent.invoke(.dynamic)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
[07:48:35] [Client thread/INFO] [STDERR]: [eladkay.scanner.proxy.ClientProxy:onClientTick:61]: 	at org.multimc.EntryPoint.main(EntryPoint.java:53)

**Comment by KingLemming** [comment]
That's not us. That's eladkay.scanner, whatever mod that is.
