### ISSUE TITLE
IndexOutOfBoundsException crash in GUI

### ISSUE THREAD

**Issue by purpleposeidon** [CoFH/Feedback#1260]
I managed to press ctrl-tab-escape, click, and switch workspaces all at the same time, or something ridiculous like that, and got this crash. Uh, good luck reproducing it I guess.

```
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1770) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 65, Size: 46
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_171]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_171]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:356) ~[afr.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566) ~[bsa.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638) ~[bmg.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146983_a(GuiContainer.java:671) ~[bmg.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java:648) ~[bmg.class:?]
	at cofh.core.gui.GuiContainerCore.func_73869_a(GuiContainerCore.java:203) ~[GuiContainerCore.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558) ~[blk.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512) ~[blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757) ~[bib.class:?]
```

Rest of crash report:
https://gist.githubusercontent.com/purpleposeidon/dfa9b99232d59917e165e1e6723e855f/raw/dd5a06ae5b59f018d687743f59e84c03e23d3cf0/gistfile1.txt

**Comment by Tora-B** [comment]
And you're reporting this to the CoFH team because...? I don't see anything in that crash log that points to a CoFH mod as being responsible. Or any mod in particular as being responsible. It's probably just a vanilla Minecraft bug, but I wouldn't recommend reporting it to Mojang either unless you can reproduce it in a vanilla environment, without any mods.

**Comment by KingLemming** [comment]
Yeah this seems to be some memory that got out of whack, not our issue.
