### ISSUE TITLE
World startup error

### ISSUE THREAD

**Issue by firelizzard18** [CoFH/Feedback#1277]
Crashed my client while playing locally.

```Java
java.lang.IllegalAccessError: tried to access class cofh.api.transport.IEnderAttuned from class cofh.lib.transport.EnderRegistry
	at cofh.lib.transport.EnderRegistry.addHandler(EnderRegistry.java:265) ~[EnderRegistry.class:?]
	at cofh.lib.transport.EnderRegistry.addItemHandler(EnderRegistry.java:281) ~[EnderRegistry.class:?]
	at cofh.lib.transport.EnderRegistry.add(EnderRegistry.java:380) ~[EnderRegistry.class:?]
	at cofh.thermalexpansion.block.ender.TileTesseract.addToRegistry(TileTesseract.java:247) ~[TileTesseract.class:?]
	at cofh.thermalexpansion.block.ender.TileTesseract.validate(TileTesseract.java:152) ~[TileTesseract.class:?]
	at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:969) ~[Chunk.class:?]
	at net.minecraft.world.chunk.Chunk.addTileEntity(Chunk.java:945) ~[Chunk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:529) ~[AnvilChunkLoader.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:144) ~[ChunkProviderServer.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:119) ~[ChunkProviderServer.class:?]
	at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:305) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:79) ~[IntegratedServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.startServer(IntegratedServer.java:96) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:445) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
```

**Comment by firelizzard18** [comment]
It looks like it's a problem with buildcraft-compat's definition of `cofh.api.transport.IEnderAttuned` masking CoFHCore's. This may be restricted to development environments. Any ideas on how I can fix this without manually deleting buildcraft-compat's class file?

**Comment by KingLemming** [comment]
Nope. Delete BC's file. It's apparently wrong.
