### ISSUE TITLE
[Lib] BlockHelper NullPointerException

### ISSUE THREAD

**Issue by firelizzard18** [CoFH/Feedback#1289]
I have my own mod (FireCraft). I only use it on my server. My mod calls `BlockHelper.breakBlock`. Sometimes this throws a NullPointerException. The error is in [`createStackedBlock`](https://github.com/CoFH/CoFHLib/blob/49cdbedc56dbb1fafbcff0e8f4aafc228f910fb4/src/main/java/cofh/lib/util/helpers/BlockHelper.java#L565).

Scenarios in which I've seen this happen:

  * Calling `BlockHelper.breakBlock` normally on a Logistics pipe: [call](https://github.com/firelizzard18/FireCraft/blob/9830e23be2ab3f74b7cb95d21e50a5b39dc5c147/src/main/java/com/firelizzard/firecraft/item/DestroyerTool.java#L259)
  * Calling `BlockHelper.breakBlock` with silk touch on random blocks: [call](https://github.com/firelizzard18/FireCraft/blob/9830e23be2ab3f74b7cb95d21e50a5b39dc5c147/src/main/java/com/firelizzard/firecraft/item/DestroyerTool.java#L452)

The following is a stack trace from using it to silk touch a redstone ore block:

	---- Minecraft Crash Report ----
	// Oops.

	Time: 1/2/17 11:41 PM
	Description: Unexpected error

	java.lang.NullPointerException: Unexpected error
		at cofh.lib.util.helpers.BlockHelper.createStackedBlock(BlockHelper.java:565)
		at cofh.lib.util.helpers.BlockHelper.breakBlock(BlockHelper.java:540)
		at com.firelizzard.firecraft.item.DestroyerTool.func_77648_a(DestroyerTool.java:492)
		at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
		at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
		at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
		at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
		at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
		at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
		at net.minecraft.client.main.Main.main(SourceFile:148)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:483)
		at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
		at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

	A detailed walkthrough of the error, its code path and all known details is as follows:
	---------------------------------------------------------------------------------------

	-- Head --
	Stacktrace:
		at cofh.lib.util.helpers.BlockHelper.createStackedBlock(BlockHelper.java:565)
		at cofh.lib.util.helpers.BlockHelper.breakBlock(BlockHelper.java:540)
		at com.firelizzard.firecraft.item.DestroyerTool.func_77648_a(DestroyerTool.java:492)
		at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
		at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
		at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)

	-- Affected level --
	Details:
		Level name: MpServer
		All players: 1 total; [EntityClientPlayerMP['firelizzard'/17698740, l='MpServer', x=561.92, y=38.62, z=1013.92]]
		Chunk stats: MultiplayerChunkCache: 441, 441
		Level seed: 0
		Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
		Level generator options: 
		Level spawn location: World: (267,70,1065), Chunk: (at 11,4,9 in 16,66; contains blocks 256,0,1056 to 271,255,1071), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
		Level time: 224107478 game time, 3360545 day time
		Level dimension: 0
		Level storage version: 0x00000 - Unknown?
		Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
		Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
		Forced entities: 72 total; [EntityBat['Bat'/19022624, l='MpServer', x=585.75, y=24.10, z=1014.25], EntityPig['Pig'/20298800, l='MpServer', x=580.76, y=36.00, z=1035.23], EntityItem['item.tile.sapling.oak'/20280381, l='MpServer', x=576.81, y=47.13, z=1034.78], EntityBat['Bat'/19335995, l='MpServer', x=538.75, y=35.10, z=1011.75], EntityCreeper['Creeper'/20300331, l='MpServer', x=513.31, y=71.00, z=966.44], EntityChicken['Chicken'/20308244, l='MpServer', x=580.25, y=36.00, z=1036.63], EntityBat['Bat'/19367429, l='MpServer', x=577.25, y=24.10, z=1018.53], EntityPig['Pig'/20222738, l='MpServer', x=581.69, y=36.00, z=1035.89], EntityBat['Bat'/19750405, l='MpServer', x=585.75, y=24.10, z=1017.47], EntityBat['Bat'/19750406, l='MpServer', x=577.25, y=24.10, z=1015.50], EntityBat['Bat'/19025168, l='MpServer', x=558.22, y=24.10, z=1010.56], EntityBat['Bat'/20309518, l='MpServer', x=605.00, y=55.14, z=1023.31], EntityCow['Cow'/20293896, l='MpServer', x=580.88, y=36.00, z=1036.57], EntityBat['Bat'/20309515, l='MpServer', x=616.34, y=60.60, z=1015.25], EntityBat['Bat'/20309514, l='MpServer', x=613.69, y=60.20, z=1029.78], EntityBat['Bat'/19371895, l='MpServer', x=540.75, y=36.10, z=1007.25], EntityPig['Pig'/20270951, l='MpServer', x=580.86, y=36.00, z=1035.94], EntityChicken['Chicken'/20231279, l='MpServer', x=580.21, y=36.00, z=1035.08], EntityChicken['Chicken'/17698156, l='MpServer', x=621.63, y=89.00, z=1069.63], EntityChicken['Chicken'/17698157, l='MpServer', x=623.28, y=90.00, z=1067.78], EntityChicken['Chicken'/17698155, l='MpServer', x=623.94, y=90.00, z=1067.16], EntityVillager['Bob the Builder'/103, l='MpServer', x=561.94, y=36.00, z=1031.94], EntityVillager['Villager'/104, l='MpServer', x=560.25, y=36.00, z=1045.34], EntityChicken['Chicken'/105, l='MpServer', x=574.19, y=36.00, z=1036.13], EntityChicken['Chicken'/106, l='MpServer', x=574.16, y=36.00, z=1035.16], EntityCow['Cow'/107, l='MpServer', x=576.25, y=36.00, z=1035.97], EntityVillager['Bob the Builder'/108, l='MpServer', x=565.50, y=36.00, z=1036.69], EntityPig['Pig'/109, l='MpServer', x=577.91, y=36.00, z=1036.06], EntityBat['Bat'/19336010, l='MpServer', x=581.50, y=24.10, z=1014.25], EntityPig['Pig'/110, l='MpServer', x=575.16, y=36.00, z=1035.47], EntityCow['Cow'/111, l='MpServer', x=575.47, y=36.00, z=1037.41], EntitySheep['Sheep'/124, l='MpServer', x=585.38, y=37.00, z=1019.47], EntitySheep['Sheep'/125, l='MpServer', x=586.53, y=37.00, z=1020.34], EntityCow['Cow'/126, l='MpServer', x=584.47, y=37.00, z=1020.72], EntityOcelot['Cat'/127, l='MpServer', x=585.84, y=96.00, z=1019.25], EntityVillager['Villager'/128, l='MpServer', x=557.38, y=36.00, z=1032.72], EntityVillager['Villager'/129, l='MpServer', x=554.31, y=36.00, z=1037.97], EntityVillager['Villager'/130, l='MpServer', x=555.59, y=36.00, z=1045.38], EntityVillager['Villager'/131, l='MpServer', x=563.72, y=36.00, z=1044.50], EntityVillager['Villager'/132, l='MpServer', x=566.94, y=36.00, z=1045.50], EntityVillager['Villager'/133, l='MpServer', x=566.34, y=36.00, z=1036.44], EntityVillager['Villager'/134, l='MpServer', x=562.50, y=36.00, z=1039.22], EntityVillager['Villager'/135, l='MpServer', x=562.41, y=36.00, z=1045.38], EntityVillager['Villager'/136, l='MpServer', x=567.97, y=36.00, z=1045.41], EntityVillager['Villager'/137, l='MpServer', x=564.50, y=36.19, z=1038.50], EntityVillager['Villager'/138, l='MpServer', x=555.22, y=36.00, z=1034.13], EntityVillager['Villager'/139, l='MpServer', x=554.31, y=36.00, z=1035.00], EntityVillager['Villager'/140, l='MpServer', x=559.22, y=36.00, z=1040.31], EntityPig['Pig'/20136383, l='MpServer', x=580.25, y=36.00, z=1037.19], EntityVillager['Villager'/141, l='MpServer', x=554.63, y=36.00, z=1044.28], EntityIronGolem['Iron Golem'/142, l='MpServer', x=543.03, y=6.00, z=997.66], EntityBat['Bat'/19821728, l='MpServer', x=537.53, y=35.10, z=1011.75], EntityBat['Bat'/19336628, l='MpServer', x=577.31, y=24.10, z=1022.56], EntityBat['Bat'/19341746, l='MpServer', x=577.25, y=24.10, z=1018.50], EntityBat['Bat'/19403710, l='MpServer', x=566.44, y=14.10, z=1015.50], EntityChicken['Chicken'/20148644, l='MpServer', x=580.12, y=36.00, z=1035.44], EntityBlaze['Blaze'/3913634, l='MpServer', x=19.50, y=-17.62, z=22.98], EntityBat['Bat'/19341754, l='MpServer', x=578.72, y=24.10, z=1017.00], EntityBat['Bat'/18985607, l='MpServer', x=585.69, y=24.10, z=1014.25], EntityHorse['Horse'/6525892, l='MpServer', x=622.34, y=80.00, z=1030.28], EntityZombie['Zombie'/17698750, l='MpServer', x=530.13, y=71.11, z=988.50], EntityZombie['Zombie'/17698756, l='MpServer', x=597.30, y=32.00, z=1092.70], EntityZombie['Zombie'/17698754, l='MpServer', x=609.31, y=60.17, z=1086.15], EntityZombie['Zombie'/17698752, l='MpServer', x=608.31, y=61.20, z=1087.31], EntityZombie['Zombie'/17698753, l='MpServer', x=609.70, y=60.00, z=1085.30], EntityBat['Bat'/19750399, l='MpServer', x=577.25, y=24.10, z=1015.66], EntityCow['Cow'/20121569, l='MpServer', x=581.00, y=36.00, z=1037.75], EntityChicken['Chicken'/20274407, l='MpServer', x=580.09, y=36.00, z=1035.09], EntityClientPlayerMP['firelizzard'/17698740, l='MpServer', x=561.92, y=38.62, z=1013.92], EntityCow['Cow'/20265940, l='MpServer', x=580.22, y=36.00, z=1035.78], EntityZombie['Zombie'/17698285, l='MpServer', x=529.34, y=71.00, z=994.09], EntityCow['Cow'/20210910, l='MpServer', x=581.50, y=36.00, z=1035.22]]
		Retry entities: 0 total; []
		Server brand: fml,forge
		Server type: Non-integrated multiplayer server
	Stacktrace:
		at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
		at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
		at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
		at net.minecraft.client.main.Main.main(SourceFile:148)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:483)
		at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
		at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

	-- System Details --
	Details:
		Minecraft Version: 1.7.10
		Operating System: Windows 10 (amd64) version 10.0
		Java Version: 1.8.0_25, Oracle Corporation
		Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
		Memory: 2204850320 bytes (2102 MB) / 5587243008 bytes (5328 MB) up to 8576565248 bytes (8179 MB)
		JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:+UnlockCommercialFeatures -XX:+FlightRecorder
		AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
		IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
		FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 84 mods loaded, 73 mods active
		States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
		UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
		UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
		UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
		UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
		UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
		UCHIJA	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar) 
		UCHIJA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
		UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
		UCHIJA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
		UCHIJA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
		UCHIJA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
		UCHIJA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
		UCHIJA	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
		UCHIJA	ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.5-115.jar) 
		UCHIJA	ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.4-247.jar) 
		UCHIJA	BigReactors{0.4.5B} [Big Reactors] (BigReactors-0.4.5B.jar) 
		UCHIJA	BuildCraft|Core{7.1.18} [BuildCraft] (buildcraft-7.1.18.jar) 
		UCHIJA	BuildCraft|Transport{7.1.18} [BC Transport] (buildcraft-7.1.18.jar) 
		UCHIJA	BuildCraft|Silicon{7.1.18} [BC Silicon] (buildcraft-7.1.18.jar) 
		UCHIJA	BuildCraft|Energy{7.1.18} [BC Energy] (buildcraft-7.1.18.jar) 
		UCHIJA	BuildCraft|Factory{7.1.18} [BC Factory] (buildcraft-7.1.18.jar) 
		UCHIJA	BuildCraft|Builders{7.1.18} [BC Builders] (buildcraft-7.1.18.jar) 
		UCHIJA	BuildCraft|Robotics{7.1.18} [BC Robotics] (buildcraft-7.1.18.jar) 
		UCHIJA	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
		UCHIJA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
		UCHIJA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
		UCHIJA	Dynmap{2.3-163} [Dynmap] (Dynmap-2.3-forge-1.7.10.jar) 
		UCHIJA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
		UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
		UCHIJA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
		UCHIJA	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
		UCHIJA	ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar) 
		UCHIJA	firecraft{1.3} [FireCraft] (firecraft-0.4.jar) 
		UCHIJA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
		UCHIJA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
		UCHIJA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
		UCHIJA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
		UCHIJA	LogisticsPipes{0.9.3.local} [Logistics Pipes] (logisticspipes-0.9.3.local.jar) 
		UCHIJA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
		UCHIJA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
		UCHIJA	modtweaker2{0.9.5} [Mod Tweaker 2] (ModTweaker2-0.9.5.jar) 
		UCHIJA	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
		UCHIJA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
		UCHIJA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
		UCHIJA	powersuits{0.11.0.301} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.301.jar) 
		UCHIJA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
		UCHIJA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
		UCHIJA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
		UCHIJA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
		UCHIJA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
		UCHIJA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
		UCHIJA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
		UCHIJA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
		UCHIJA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
		UCHIJA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
		UCHIJA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
		UCHIJA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
		UCHIJA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
		UCHIJA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
		UCHIJA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
		UCHIJA	TabulaRasa{1.7.10R1.0.1} [Tabula Rasa] (TabulaRasa-[1.7.10]1.0.1-3.jar) 
		UCHIJA	ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.0-171.jar) 
		UCHIJA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
		UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
		UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
		UD	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.91' Renderer: 'GeForce GTX 970/PCIe/SSE2'
		Mantle Environment: Environment healthy.
		CoFHCore: -[1.7.10]3.1.3-327
		ThermalFoundation: -[1.7.10]1.2.5-115
		ThermalExpansion: -[1.7.10]4.1.4-247
		MineFactoryReloaded: -[1.7.10]2.8.1-174
		TConstruct Environment: Environment healthy.
		firecraft: Lacking version information.
		NetherOres: -[1.7.10]2.3.1-22
		ThermalDynamics: -[1.7.10]1.2.0-171
		Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
		LWJGL: 2.9.1
		OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.91, NVIDIA Corporation
		GL Caps: Using GL 1.3 multitexturing.
	Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
	Anisotropic filtering is supported and maximum anisotropy is 16.
	Shaders are available because OpenGL 2.1 is supported.

		Is Modded: Definitely; Client brand changed to 'fml,forge'
		Type: Client (map_client.txt)
		Resource Packs: []
		Current Language: English (US)
		Profiler Position: N/A (disabled)
		Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
		Anisotropic Filtering: Off (1)

**Comment by firelizzard18** [comment]
There are some blocks this consistently fails with, including (vanilla) redstone ore.

**Comment by KingLemming** [comment]
Try this with TE's block breaker. If it crashes, then okay, there's an issue here.

If not, then the problem is with your mod and when you're calling this.

**Comment by firelizzard18** [comment]
As in a copper pick axe enchanted with silk touch? I don't see tools other
than TF's alternate metal versions of vanilla tools, and nothing that says
it does silk touch without an enchantment.

I assumed `BlockHelper.breakBlock` was designed to handle any block. It's
not like the method parameters are complicated.

**Comment by bookerthegeek** [comment]
> I assumed `BlockHelper.breakBlock` was designed to handle any block. It's
not like the method parameters are complicated.

Complicated enough for you to ask for help on how to use it correctly

**Comment by KingLemming** [comment]
I still don't have any evidence that you aren't calling it on the client side or something crazy like that. It is a pretty straightforward function, yes, but that doesn't mean it won't blow up if you effectively hand it a null.

**Comment by firelizzard18** [comment]
For the case where I attempt to silk touch the block, it seems likely that the issue is me calling `breakBlock` on the client. I'm still not sure in the other case, as that one definitely doesn't get called on the client.

Also, I can't find any call to `BlockHelper.breakBlock` with `silkTouch: true` in Lib, Core, TF, TE, or TD. The only call I did find was in TE's `cofh.thermalexpansion.item.tool.ItemMiner` which doesn't show up in TE's creative tab (so I assume it's not done).

**Comment by firelizzard18** [comment]
I take that back. The issue is that the block is `Blocks.lit_redstone_ore`, which does not have an item.
