### ISSUE TITLE
CoFHUpdater "Update check for Thermal Expansion Failed"

### ISSUE THREAD

**Issue by rbuckton** [CoFH/Feedback#129]
Found in `fml-client-latest.log`:

```
[19:43:35] [CoFHUpdater:ThermalExpansion/WARN] [ThermalExpansion/ThermalExpansion]: Update check for Thermal Expansion failed.
java.io.FileNotFoundException: https://raw.githubusercontent.com/CoFH/ThermalExpansion/master/VERSION
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1834) ~[?:1.8.0_25]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_25]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431) ~[?:1.8.0_25]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1429) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_25]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1428) ~[?:1.8.0_25]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_25]
	at java.net.URL.openStream(URL.java:1038) ~[?:1.8.0_25]
	at cofh.mod.updater.UpdateCheckThread.run(UpdateCheckThread.java:44) [UpdateCheckThread.class:?]
```

CoFH Related Mods:
* CoFHCore-[1.7.10]3.0.0B9-40
* CoFHLib-[1.7.10]1.0.0B8-34
* ThermalFoundation-[1.7.10]1.0.0RC1-13
* ThermalExpansion-[1.7.10]4.0.0B8-23

**Comment by crunkazcanbe** [comment]
What DEV build would we have to use to remove this error from the console ?

**Comment by crunkazcanbe** [comment]
Damn I guess its hard to speak a few words. Considering no change logs we may never no . Even skyboy probably doesn't know what dev build it was fixed in.
