### ISSUE TITLE
flood and lag in console!

### ISSUE THREAD

**Issue by felipeleite5w** [CoFH/Feedback#1292]
this error flood my console everyday

 [CoFH User Loader/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@5d8478e1[id=111f0c77-a4cd-38e3-809c-0cc72445a4eb,name=vitor_ggames,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[server-1.7.10.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [server-1.7.10.jar:?]
        at cofh.lib.util.helpers.SecurityHelper.getProfile(SecurityHelper.java:216) [SecurityHelper.class:?]
        at cofh.thermalexpansion.block.TileInventory$1.run(TileInventory.java:485) [TileInventory$1.class:?]
[00:00:07] [CoFH User Loader/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@67cec49f[id=111f0c77-a4cd-38e3-809c-0cc72445a4eb,name=vitor_ggames,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[server-1.7.10.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [server-1.7.10.jar:?]
        at cofh.lib.util.helpers.SecurityHelper.getProfile(SecurityHelper.java:216) [SecurityHelper.class:?]
        at cofh.thermalexpansion.block.TileInventory$1.run(TileInventory.java:485) [TileInventory$1.class:?]
[00:00:07] [CoFH User Loader/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@483b553c[id=111f0c77-a4cd-38e3-809c-0cc72445a4eb,name=vitor_ggames,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[server-1.7.10.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [server-1.7.10.jar:?]
        at cofh.lib.util.helpers.SecurityHelper.getProfile(SecurityHelper.java:216) [SecurityHelper.class:?]
        at cofh.thermalexpansion.block.TileInventory$1.run(TileInventory.java:485) [TileInventory$1.class:?]
[00:00:07] [CoFH User Loader/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@7f3b76[id=111f0c77-a4cd-38e3-809c-0cc72445a4eb,name=vitor_ggames,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[server-1.7.10.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [server-1.7.10.jar:?]
        at cofh.lib.util.helpers.SecurityHelper.getProfile(SecurityHelper.java:216) [SecurityHelper.class:?]
        at cofh.thermalexpansion.block.TileInventory$1.run(TileInventory.java:485) [TileInventory$1.class:?]
[00:00:07] [CoFH User Loader/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@caf6300[id=111f0c77-a4cd-38e3-809c-0cc72445a4eb,name=vitor_ggames,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[server-1.7.10.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [server-1.7.10.jar:?]
        at cofh.lib.util.helpers.SecurityHelper.getProfile(SecurityHelper.java:216) [SecurityHelper.class:?]
        at cofh.thermalexpansion.block.TileInventory$1.run(TileInventory.java:485) [TileInventory$1.class:?]

**Comment by KingLemming** [comment]
This is on your end and 1.7.10 is unsupported.

**Comment by felipeleite5w** [comment]
ok, but there is a way to hide this menssage?

**Comment by felipeleite5w** [comment]
or fix it?

**Comment by covers1624** [comment]
1.7.10 is un upported there is absolutely nothing we can sou about this.

**Comment by felipeleite5w** [comment]
make a supported version!!!

**Comment by covers1624** [comment]
This is your one and only warning, demanding is not tolerated here. 1.7.10 has had its day, we will not be spending any more of OUR time on it, time that we take out of OUR day for a HOBBY.

**Comment by KingLemming** [comment]
We do make a supported version. It's called 1.12.2. It is supported. Go play 1.12.2.

**Comment by felipeleite5w** [comment]
i know, but there is no good mods in 1.12.2
