### ISSUE TITLE
IFEatureGenerator Error

### ISSUE THREAD

**Issue by Nekks** [CoFH/Feedback#1303]
Hours of attempting to make this work i have thrown up my hands on where to go to report this issue so try not to stone me to hard if i have posted in the wrong thread, board, forum, ect. Many hopes and wishes i can get an answer to my problem ^-^.

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2/17/17 1:58 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cofh/api/world/IFeatureGenerator
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: cofh/api/world/IFeatureGenerator
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: cofh.api.world.IFeatureGenerator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 135543008 bytes (129 MB) / 278257664 bytes (265 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UC	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) 
	UC	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UC	BiblioCraft{1.8.2} [BiblioCraft] (_BiblioCraft-Mod-1.7.10.jar) 
	UC	CoFHCore{1.7.10R3.0.0B1} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B1-19.jar) 
	UC	UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} [Universal Electricity] (universal-electricity-4.0.0.9-core.jar) 
	UC	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UC	Mekanism{8.1.9} [Mekanism] (Mekanism-1.7.10-8.1.9.265.jar) 
	UC	MekanismGenerators{8.1.9} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.9.265.jar) 
	UC	MekanismTools{8.1.9} [MekanismTools] (MekanismTools-1.7.10-8.1.9.265.jar) 
	UC	ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} [Resonant Engine] (resonant-engine-2.0.0.32-core.jar) 
	UC	MFFS{@MAJOR@.@MINOR@.@REVIS@} [Modular Force Field System] (mffs-4.0.0.18-core.jar) 
	UE	MineFactoryReloaded{1.7.10R2.8.0RC1} [MineFactory Reloaded] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC1} [MFR Compat: Applied Energistics] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0B4} [MFR Compat: Atum] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC1} [MFR Compat: BackTools] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC1} [MFR Compat: BuildCraft] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0B4} [MFR Compat: Chococraft] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0B4} [MFR Compat: ExtraBiomes] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC1} [MFR Compat: Forestry] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC1} [MFR Compat: ForgeMicroblock] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC1} [MFR Compat: IC2] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0B4} [MFR Compat: Mystcraft] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatPams{1.7.10R2.8.0B4} [MFR Compat: Pam's Mods] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0B4} [MFR Compat ProjectRed] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC1} [MFR Compat: Railcraft] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0B4} [MFR Compat: RP2] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0B4} [MFR Compat: Sufficient Biomes] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC1} [MFR Compat: Thaumcraft] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC1} [MFR Compat: Thermal Expansion] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC1} [MFR Compat: TwilightForest] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UE	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC1} [MFR Compat: Vanilla] (MineFactory-Reloaded-Mod-1.7.10.jar) 
	UC	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UC	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UC	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UC	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4549' Renderer: 'Intel(R) HD Graphics 5500'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe

**Comment by KingLemming** [comment]
Your mods are ridiculously outdated. That's really it.
