### ISSUE TITLE
[1.12] java.lang.UnsupportedOperationException when breaking Extra Utilities 2 generators

### ISSUE THREAD

**Issue by rrbrussell** [CoFH/Feedback#1306]
Description of issue: When picking up a magma generator from extra utilities 2 version 1.12-1.9.4 my game crashed. The magma generator was not dropped but the 4 speed upgrades inside of it were.

I tested with several other generators from extra utilities and the same crash occurred with all of them.

Cofh core version is 1.12.2-4.6.0.21

```
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException
    at com.google.common.collect.ImmutableList.replaceAll(ImmutableList.java:553)
    at cofh.core.proxy.EventHandler.handleHarvestDropsEvent(EventHandler.java:294)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_582_EventHandler_handleHarvestDropsEvent_HarvestDropsEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:320)
    at net.minecraft.block.Block.dropBlockAsItemWithChance(Block.java:572)
    at net.minecraft.block.Block.dropBlockAsItem(Block.java:564)
    at net.minecraft.block.Block.harvestBlock(Block.java:735)
    at com.rwtema.extrautils2.backend.XUBlock.harvestBlock(XUBlock.java:350)
    at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:327)
    at net.minecraft.server.management.PlayerInteractionManager.blockRemoving(PlayerInteractionManager.java:244)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:704)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:40)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more
```

A full crash report with mod list is [here](https://paste.dimdev.org/afipudafaz.mccrash).

**Comment by KingLemming** [comment]
Please let ExU2 know. He shouldn't be returning an immutable list there.

**Comment by rrbrussell** [comment]
[Link](https://github.com/rwtema/Extra-Utilities-2-Source/issues/) to bug on Extra Utilities 2 repo.
