### ISSUE TITLE
[Crash] At mine ExtraUtils 2 Crusher in cofh.core.proxy.EventHandler.handleHarvestDropsEvent

### ISSUE THREAD

**Issue by VladimirMangos** [CoFH/Feedback#1309]
https://paste.dimdev.org/gobewimodo.mccrash

java.lang.UnsupportedOperationException
    at com.google.common.collect.ImmutableList.replaceAll(ImmutableList.java:553)
    at cofh.core.proxy.EventHandler.handleHarvestDropsEvent(EventHandler.java:294)

At mine ExtraUtils 2 Crusher

**Comment by KingLemming** [comment]
Duplicate of #1306. Please check closed issues before posting if you would. :)
