### ISSUE TITLE
[1.12.2] Not support Forge 14.23.5.2768

### ISSUE THREAD

**Issue by Flactine** [CoFH/Feedback#1322]
When I update forge 14.23.5.2768, game crashed,
By Thermal Innovation-1.12.2-0.3.1.8.

**Comment by Flactine** [comment]
> Crashlog? Also do you update both forge and all CoFH mods together?

Oh I forgot that.

**Comment by Flactine** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  JechCore ([JEI系]JustEnoughCharacters-1.12.0-2.3.2.jar)
  CorePlugin (UnicodeFontExtension-1.12.2-2.7.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 10/12/18 7:39 PM
Description: Initializing game

java.lang.NoClassDefFoundError: cofh/thermalinnovation/item/ItemMagnet
	at cofh.thermalinnovation.ThermalInnovation.<clinit>(ThermalInnovation.java:51)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: cofh.thermalinnovation.item.ItemMagnet
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 47 more
Caused by: java.lang.NoClassDefFoundError: baubles/api/IBauble
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 49 more
Caused by: java.lang.ClassNotFoundException: baubles.api.IBauble
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 53 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cofh.thermalinnovation.ThermalInnovation.<clinit>(ThermalInnovation.java:51)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1591941552 bytes (1518 MB) / 2348810240 bytes (2240 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx6144m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_D3 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version           | Source                                               | Signature                                |
	|:----- |:------------------------ |:----------------- |:---------------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft                | 1.12.2            | minecraft.jar                                        | None                                     |
	| UC    | mcp                      | 9.42              | minecraft.jar                                        | None                                     |
	| UC    | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2768-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                    | 14.23.5.2768      | forge-1.12.2-14.23.5.2768-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | jecharacters             | 1.12.0-2.3.2      | [JEI系]JustEnoughCharacters-1.12.0-2.3.2.jar          | None                                     |
	| UC    | unicodefontextensioncore | 1.12.2-2.6        | minecraft.jar                                        | None                                     |
	| UC    | unicodefontextension     | 1.12.2-2.7        | UnicodeFontExtension-1.12.2-2.7.jar                  | None                                     |
	| UC    | appliedenergistics2      | rv5-stable-11     | [AE系]appliedenergistics2-rv5-stable-11.jar           | None                                     |
	| UC    | bdlib                    | 1.14.3.12         | [AE系]bdlib-1.14.3.12-mc1.12.2.jar                    | None                                     |
	| UC    | ae2stuff                 | 0.7.0.4           | [AE系]ae2stuff-0.7.0.4-mc1.12.2.jar                   | None                                     |
	| UC    | waila                    | 1.8.24            | [JEI系]Hwyla-1.8.24-B39_1.12.jar                      | None                                     |
	| UC    | extracells               | 2.5.13            | [AE系]ExtraCells-1.12.2-2.5.13a58.jar                 | None                                     |
	| UC    | codechickenlib           | 3.2.2.353         | [JEI系]CodeChickenLib-1.12.2-3.2.2.353-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | crafttweaker             | 4.1.8             | [MT系]CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| UC    | mtlib                    | 3.0.5             | [MT系]MTLib-3.0.5.jar                                 | None                                     |
	| UC    | modtweaker               | 4.0.13            | [MT系]modtweaker-4.0.14.jar                           | None                                     |
	| UC    | jei                      | 4.12.1.217        | [JEI系]jei_1.12.2-4.12.1.217.jar                      | None                                     |
	| UC    | jeiintegration           | 1.5.1.36          | [JEI系]jeiintegration_1.12.2-1.5.1.36.jar             | None                                     |
	| UC    | jeresources              | 0.8.5.27          | [JEI系]JustEnoughResources-1.12.2-0.8.5.27.jar        | None                                     |
	| UC    | nei                      | 2.4.2             | [JEI系]NotEnoughItems-1.12.2-2.4.2.240-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | mantle                   | 1.12-1.3.2.24     | [TIC系]Mantle-1.12-1.3.2.24.jar                       | None                                     |
	| UC    | tconstruct               | 1.12.2-2.10.1.87  | [TIC系]TConstruct-1.12.2-2.10.1.87.jar                | None                                     |
	| UC    | wailaharvestability      | 1.1.12            | [JEI系]WailaHarvestability-mc1.12-1.1.12.jar          | None                                     |
	| UC    | ctgui                    | 1.0.0             | [MT系]CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| UC    | crafttweakerjei          | 2.0.2             | [MT系]CraftTweaker2-1.12-4.1.8.jar                    | None                                     |
	| UC    | redstoneflux             | 2.1.0             | [TE系]RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | cofhcore                 | 4.6.1             | [TE系]CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| UC    | cofhworld                | 1.3.0             | [TE系]CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thermalfoundation        | 2.6.1             | [TE系]ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thermalexpansion         | 5.5.2             | [TE系]ThermalExpansion-1.12.2-5.5.2.39-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thermalcultivation       | 0.3.1             | [TE系]ThermalCultivation-1.12.2-0.3.1.8-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thermaldynamics          | 2.5.3             | [TE系]ThermalDynamics-1.12.2-2.5.3.16-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| U     | thermalinnovation        | 0.3.1             | [TE系]ThermalInnovation-1.12.2-0.3.1.8-universal.jar  | None                                     |
	| U     | baubles                  | 1.5.2             | [TIC系]Baubles-1.12-1.5.2.jar                         | None                                     |
	| U     | japaricraftmod           | 4.2.7             | [加帕里]JapariCraft-Mod-1.12.2.jar                      | None                                     |
	| U     | waystones                | 4.0.63            | [实用-传送石]Waystones_1.12.2-4.0.63.jar                  | None                                     |
	| U     | roguelike                | 1.8.0             | [实用-地牢]RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| U     | ironchest                | 1.12.2-7.0.40.824 | [实用-铁箱子]ironchest-1.12.2-7.0.40.824.jar              | None                                     |
	| U     | item_search              | 1.0.0             | [百科查询]ItemSearch_V1.0.0_MC1.12.2.jar                 | None                                     |
	| U     | journeymap               | 1.12.2-5.5.2      | [辅助-地图]journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| U     | realtimeclock            | 1.12.2-1.1        | [辅助-时间]jRealTimeClock-1.12.2-1.1.jar                 | None                                     |
	| U     | neat                     | 1.4-15            | [辅助-血量]Neat+1.4-15.jar                               | None                                     |
	| U     | mousetweaks              | 2.8               | [辅助-鼠标手势]MouseTweaks-2.8-mc1.12.1.jar                | None                                     |
	| U     | bibliocraft              | 2.4.4             | BiblioCraft[v2.4.4][MC1.12.2].jar                    | None                                     |
	| U     | botania                  | r1.10-354         | Botania+r1.10-354.jar                                | None                                     |
	| U     | chickenchunks            | 2.4.1.73          | ChickenChunks-1.12.2-2.4.1.73-universal.jar          | None                                     |
	| U     | elevatorid               | 1.3.6             | ElevatorMod-1.12.2-1.3.6.jar                         | None                                     |
	| U     | cfm                      | 5.9.1             | furniture-5.9.1-1.12.2.jar                           | None                                     |
	| U     | gokistats                | 1.2.5.1           | gokiStats-1.2.5.1.jar                                | None                                     |
	| U     | worldedit                | 6.1.8             | worldedit-forge-mc1.12-6.1.8-dist.jar                | None                                     |

	Loaded coremods (and transformers): 
JechCore ([JEI系]JustEnoughCharacters-1.12.0-2.3.2.jar)
  me.towdium.jecharacters.core.JechClassTransformer
CorePlugin (UnicodeFontExtension-1.12.2-2.7.jar)
  bre.ufex.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 399.07' Renderer: 'GeForce 920M/PCIe/SSE2'
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce 920M/PCIe/SSE2 GL version 4.6.0 NVIDIA 399.07, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 399.07
	OpenGlRenderer: GeForce 920M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by covers1624** [comment]
This is sort of a bug, apparently there is a hard dep on the Baubles API, for now just install Baubles.

**Comment by covers1624** [comment]
Oh wait, you have baubles.. Perhaps try updating Baubles, the jar could also be corrupt try re-downloading it. Failing that, another mod is probably repacking Baubles causing some classes to go missing.

**Comment by KingLemming** [comment]
There's not a hard dep on Baubles, no. We're correctly using @Optional.

**Comment by KingLemming** [comment]
I don't know what exactly this is, but I am very sure that it's not us. You're welcome to come by the Discord for tech support and maybe we can help you figure out which mod you have is causing it.

But it's nothing in our code.
