### ISSUE TITLE
java.lang.StackOverflowError: Exception while updating neighbours

### ISSUE THREAD

**Issue by edelwysse** [CoFH/Feedback#1349]
I have the Stoneblock (1.0.25) modpack installed on a 5GB server. [[These](https://i.gyazo.com/29dd7ed848af5d037d612a7303081b47.png)] are the CoFH mods I am using. 

After a player placed multiple cryo-stabilized fluxducts with a Builder's Wand, and the server restarted, it kept crashing. I'm not sure if this is the cause, but it seems like it was the last thing that was done on the server. I've pasted the the first bit of the latest crash report I had on file. The rest of the log is too long to paste, but I can send it to anyone who needs it (?)

If anyone has any idea of how to fix this or what's going on, I'd greatly appreciate it! Please let me know if any other information is needed of me. 

```
Time: 10/31/18 11:36 PM
Description: Exception while updating neighbours

java.lang.StackOverflowError: Exception while updating neighbours
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.ClassLoader.checkPackageAccess(Unknown Source)
	at net.minecraft.world.World.func_190524_a(World.java:557)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
	at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
```
and
```
-- Block being updated --
Details:
	Source block type: ID #1232 (tile.thermaldynamics.duct // cofh.thermaldynamics.block.BlockDuct // thermaldynamics:duct_0)
	Block: thermaldynamics:duct_0[meta=5]
	Block location: World: (-936,95,931), Chunk: (at 8,5,3 in -59,58; contains blocks -944,0,928 to -929,255,943), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)

-- Block being updated --
Details:
	Source block type: ID #1232 (tile.thermaldynamics.duct // cofh.thermaldynamics.block.BlockDuct // thermaldynamics:duct_0)
	Block: thermaldynamics:duct_0[meta=5]
	Block location: World: (-937,95,931), Chunk: (at 7,5,3 in -59,58; contains blocks -944,0,928 to -929,255,943), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)

-- Block being updated --
Details:
	Source block type: ID #1232 (tile.thermaldynamics.duct // cofh.thermaldynamics.block.BlockDuct // thermaldynamics:duct_0)
	Block: thermaldynamics:duct_0[meta=5]
	Block location: World: (-938,95,931), Chunk: (at 6,5,3 in -59,58; contains blocks -944,0,928 to -929,255,943), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)

-- Block being updated --
Details:
	Source block type: ID #1232 (tile.thermaldynamics.duct // cofh.thermaldynamics.block.BlockDuct // thermaldynamics:duct_0)
	Block: thermaldynamics:duct_0[meta=5]
	Block location: World: (-939,95,931), Chunk: (at 5,5,3 in -59,58; contains blocks -944,0,928 to -929,255,943), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)

-- Block being updated --
Details:
	Source block type: ID #1232 (tile.thermaldynamics.duct // cofh.thermaldynamics.block.BlockDuct // thermaldynamics:duct_0)
	Block: thermaldynamics:duct_0[meta=5]
	Block location: World: (-940,95,931), Chunk: (at 4,5,3 in -59,58; contains blocks -944,0,928 to -929,255,943), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)

-- Block being updated --
Details:
	Source block type: ID #1232 (tile.thermaldynamics.duct // cofh.thermaldynamics.block.BlockDuct // thermaldynamics:duct_0)
	Block: thermaldynamics:duct_0[meta=5]
	Block location: World: (-941,95,931), Chunk: (at 3,5,3 in -59,58; contains blocks -944,0,928 to -929,255,943), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)

-- Block being updated --
Details:
	Source block type: ID #1232 (tile.thermaldynamics.duct // cofh.thermaldynamics.block.BlockDuct // thermaldynamics:duct_0)
	Block: thermaldynamics:duct_0[meta=5]
	Block location: World: (-942,95,931), Chunk: (at 2,5,3 in -59,58; contains blocks -944,0,928 to -929,255,943), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)`
```

**Comment by KingLemming** [comment]
You're going to have to NBTEdit your world I'm afraid - the builder's wand doesn't necessarily correctly place complex blocks like ducts, and it's borked everything up.

Feel free to come by the Discord for tech support, but there's not really a code issue; just the builder's wand not correctly placing complex tiles.
