### ISSUE TITLE
KingLemmings is gonna laugh at this TF error

### ISSUE THREAD

**Issue by Wolfseverest93** [CoFH/Feedback#136]
Ok so this time since it's something that logs itself, I have not only a log but a screenshot of the incident, my girlfriend is trying to play minecraft with me using all the same mods, but thermal foundation keeps throwing an unexpected error when initializing, making minecraft assume it doesn't have that mod, and thus crashes minecraft.
screenshot:

![wtf computer](https://cloud.githubusercontent.com/assets/10728464/6316993/d419f892-ba09-11e4-99d4-5140d972cad4.png)

crash details:

[20:15:10] [Client thread/TRACE] [FML/]: Located mcmod.info file in file ThermalExpansion-[1.7.10]4.0.0B8-23.jar
[20:15:10] [Client thread/DEBUG] [FML/]: Identified a mod of type Lcpw/mods/fml/common/Mod; (thermalexpansion.ThermalExpansion) - loading
[20:15:10] [Client thread/TRACE] [ThermalExpansion/]: Parsed dependency info : [ThermalFoundation@[1.7.10R1.0.0RC1,)] [ThermalFoundation@[1.7.10R1.0.0RC1,)] []
[20:15:15] [Client thread/DEBUG] [FML/]: Examining file ThermalFoundation-[1.7.10]1.0.0RC1-13.jar for potential mods
[20:15:15] [Client thread/WARN] [FML/]: Zip file ThermalFoundation-[1.7.10]1.0.0RC1-13.jar failed to read properly, it will be ignored
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.6.0_20]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.6.0_20]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.6.0_20]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.6.0_20]
	at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:41) [JarDiscoverer.class:?]
	at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [ContainerType.class:?]
	at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [ModCandidate.class:?]
	at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:127) [ModDiscoverer.class:?]
	at cpw.mods.fml.common.Loader.identifyMods(Loader.java:347) [Loader.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:468) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.6.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.6.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.6.0_20]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.6.0_20]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.6.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.6.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.6.0_20]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.6.0_20]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[20:15:15] [Client thread/INFO] [FML/]: Forge Mod Loader has identified 4 mods to load
[20:15:15] [Client thread/TRACE] [FML/]: Received a system property request ''
[20:15:15] [Client thread/TRACE] [FML/]: System property request managing the state of 0 mods
[20:15:15] [Client thread/DEBUG] [FML/]: After merging, found state information for 0 mods

-- followed by typical injection of forge language --

ending with:

[1.7.10]4.0.0B8-23.jar at assets/thermalexpansion/lang/zh_CN.lang into language system
[20:15:16] [Client thread/TRACE] [FML/]: Verifying mod requirements are satisfied
[20:15:16] [Client thread/ERROR] [FML/]: The mod ThermalExpansion (Thermal Expansion) requires mods [ThermalFoundation] to be available
[20:15:16] [Client thread/DEBUG] [FML/]: Mod sorting data
[20:15:16] [Client thread/DEBUG] [FML/]: 	ThermalExpansion(Thermal Expansion:1.7.10R4.0.0B8): ThermalExpansion-[1.7.10]4.0.0B8-23.jar (required-after:ThermalFoundation@[1.7.10R1.0.0RC1,))
[20:15:16] [Client thread/DEBUG] [Forge Mod Loader/]: Mod Forge Mod Loader is missing a pack.mcmeta file, substituting a dummy one
[20:15:16] [Client thread/DEBUG] [Minecraft Forge/]: Mod Minecraft Forge is missing a pack.mcmeta file, substituting a dummy one
[20:15:16] [Client thread/DEBUG] [Thermal Expansion/]: Mod Thermal Expansion is missing a pack.mcmeta file, substituting a dummy one
[20:15:16] [Client thread/WARN] [FML/]: There were errors previously. Not beginning mod initialization phase

-- All in all, I partially want to say this happened because she didn't follow my instructions properly, seeing as she hasn't had this issue until recently, but this one seems rather new to me... >.>

**Comment by KingLemming** [comment]
Try updating to all the new versions just released please. :)

**Comment by Wolfseverest93** [comment]
Already told her to. It notified me while I was messing around in my world XD

**Comment by KingLemming** [comment]
Any updates with this? :)

**Comment by Wolfseverest93** [comment]
seems its working now, mustve been a bug in that last version i was lucky enough to avoid and she wasnt. XD
