### ISSUE TITLE
[Thermal Expansion] Disconnecting player when trying to take sth. from Satchel

### ISSUE THREAD

**Issue by bluefi** [CoFH/Feedback#14]
Hey,  i get an Internal Server Error everytime when i try to take something out of my resonant Satchel. This happens since a few days. I didn't change anything in the mod or config files.
I get disconnected with the message "Internal Server Error" and the Server stays on. 
In the Server log i get this message:

```
[23:49:28] [Server thread/WARN]: Failed to handle packet for /my_ip_address:54569
java.lang.IndexOutOfBoundsException: Index: 83, Size: 72
	at java.util.ArrayList.rangeCheck(ArrayList.java:638) ~[?:1.8.0]
	at java.util.ArrayList.get(ArrayList.java:414) ~[?:1.8.0]
	at cofh.lib.gui.container.ContainerInventoryItem.func_75144_a(ContainerInventoryItem.java:180) ~[ContainerInventoryItem.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883) ~[nh.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:49:28] [Server thread/INFO]: my_mc_name lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[23:49:28] [Server thread/INFO]: my_mc_name left the game
``´

**Comment by KingLemming** [comment]
Your Satchel has been corrupted somehow. Try with a different Satchel and you shouldn't have that problem.

**Comment by bochen415** [comment]
@KingLemming is the satchel contents saved in the world directory (or config) somewhere? I've seen the cofh friend config file corruption in the past and deleting the file was the fastest way to eliminate this.

**Comment by KingLemming** [comment]
This is NBT corruption; it's part of the save file, not a config.

There's unfortunately no great way to protect against this, as NBT is a shared structure and any mod that gets it wrong will ruin it for everyone else.

**Comment by bluefi** [comment]
Okay thanks! 

Is the satchel data saved in the player file itself or does it only link to somewhere else? @KingLemming

**Comment by bluefi** [comment]
I think you can close this issue. A lot of data in my world got corrupted after i updated chickenbones mods and let my hoster move all my files to a faster Server. I dont know which of those caused that Problem, but there are many corrupted Blocks/tileEntities, items and chunks appearing now. There are even Server crashs without any information in the log files. Probably the Server just crashed once while saving my player data. Not a Problem of cofh mods. Thanks for your support @KingLemming
