### ISSUE TITLE
Crashes with thermal foundation on load up

### ISSUE THREAD

**Issue by TheLostBuck** [CoFH/Feedback#1404]
-- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 1/17/19 11:57 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Foundation (thermalfoundation)
Caused by: java.lang.NoClassDefFoundError: cofh/core/fluid/BlockFluidCore
	at cofh.thermalfoundation.block.BlockOreFluid.<clinit>(BlockOreFluid.java:429)
	at cofh.thermalfoundation.init.TFBlocks.preInit(TFBlocks.java:23)
	at cofh.thermalfoundation.ThermalFoundation.preInit(ThermalFoundation.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cofh.core.fluid.BlockFluidCore
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.VerifyError: class cofh.core.fluid.BlockFluidCore overrides final method getDensity.()I
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1372580032 bytes (1308 MB) / 1845493760 bytes (1760 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2807 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version      | Source                                          | Signature                                |
	|:----- |:-------------------- |:------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2       | minecraft.jar                                   | None                                     |
	| LCH   | mcp                  | 9.42         | minecraft.jar                                   | None                                     |
	| LCH   | FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2807.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2807 | forge-1.12.2-14.23.5.2807.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | bibliocraft          | 2.4.4        | BiblioCraft[v2.4.4][MC1.12.2].jar               | None                                     |
	| LCH   | biomesoplenty        | 7.0.1.2391   | BiomesOPlenty-1.12.2-7.0.1.2391-universal.jar   | None                                     |
	| LCH   | codechickenlib       | 3.1.9.344    | CodeChickenLib-1.12.2-3.1.9.344-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux         | 2.0.2        | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore             | 4.5.2        | CoFHCore-1.12.2-4.5.2.19-universal.jar          | None                                     |
	| LCH   | cofhworld            | 1.2.0        | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cookingforblockheads | 6.4.40       | CookingForBlockheads_1.12.2-6.4.40.jar          | None                                     |
	| LCH   | jei                  | 4.10.0.199   | jei_1.12.2-4.10.0.199.jar                       | None                                     |
	| LCE   | thermalfoundation    | 2.5.0        | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion     | 5.5.0        | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalcultivation   | 0.3.0        | ThermalCultivation-1.12.2-0.3.0.7-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermaldynamics      | 2.5.1        | ThermalDynamics-1.12.2-2.5.1.14-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |

	Loaded coremods (and transformers):

**Comment by TheLostBuck** [comment]
okay thank you cos of the pack my girl built for me I wasn't able to go to the latest version but I did update Redstone flux and the CoFH mods as far as it would let me between the version numbers it gave me now its working perfectly ^~^
