### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ridwanazeez** [CoFH/Feedback#1430]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Plugin (NotEnoughIDs-1.5.4.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 2/13/19 9:20 PM
Description: Initializing game

java.lang.NoClassDefFoundError: gnu/trove/set/hash/THashSet
	at cofh.cofhworld.init.WorldHandler.<clinit>(WorldHandler.java:42)
	at cofh.cofhworld.CoFHWorld.<init>(CoFHWorld.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:191)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:586)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: gnu.trove.set.hash.THashSet
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 45 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cofh.cofhworld.init.WorldHandler.<clinit>(WorldHandler.java:42)
	at cofh.cofhworld.CoFHWorld.<init>(CoFHWorld.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:191)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:586)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 154585568 bytes (147 MB) / 439336960 bytes (418 MB) up to 3656646656 bytes (3487 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx3500M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2814 Optifine OptiFine_1.12.2_HD_U_E3 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                          | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                         | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LC    | mcp                               | 9.42                     | minecraft.jar                                   | None                                     |
	| LC    | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2814.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                             | 14.23.5.2814             | forge-1.12.2-14.23.5.2814.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | openmodscore                      | 0.12.1                   | minecraft.jar                                   | None                                     |
	| LC    | appliedenergistics2               | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LC    | bibliocraft                       | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| LC    | buildcraftlib                     | 7.99.21                  | buildcraft-all-7.99.21.jar                      | None                                     |
	| LC    | buildcraftcore                    | 7.99.21                  | buildcraft-all-7.99.21.jar                      | None                                     |
	| LC    | buildcraftbuilders                | 7.99.21                  | buildcraft-all-7.99.21.jar                      | None                                     |
	| LC    | buildcrafttransport               | 7.99.21                  | buildcraft-all-7.99.21.jar                      | None                                     |
	| LC    | buildcraftsilicon                 | 7.99.21                  | buildcraft-all-7.99.21.jar                      | None                                     |
	| LC    | buildcraftcompat                  | 7.99.21                  | buildcraft-all-7.99.21.jar                      | None                                     |
	| LC    | buildcraftenergy                  | 7.99.21                  | buildcraft-all-7.99.21.jar                      | None                                     |
	| LC    | buildcraftfactory                 | 7.99.21                  | buildcraft-all-7.99.21.jar                      | None                                     |
	| LC    | buildcraftrobotics                | 7.99.21                  | buildcraft-all-7.99.21.jar                      | None                                     |
	| LC    | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                          | 4.6.2                    | CoFHCore-1.12.2-4.6.2.25-universal.jar          | None                                     |
	| L     | cofhworld                         | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| L     | endercore                         | 1.12.2-0.5.45            | EnderCore-1.12.2-0.5.45.jar                     | None                                     |
	| L     | jei                               | 4.14.4.264               | jei_1.12.2-4.14.4.264.jar                       | None                                     |
	| L     | thermalfoundation                 | 2.6.2                    | ThermalFoundation-1.12.2-2.6.2.26-universal.jar | None                                     |
	| L     | thermalexpansion                  | 5.5.3                    | ThermalExpansion-1.12.2-5.5.3.41-universal.jar  | None                                     |
	| L     | enderio                           | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| L     | enderiointegrationtic             | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| L     | enderiobase                       | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| L     | enderioconduits                   | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| L     | enderioconduitsappliedenergistics | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| L     | enderioconduitsopencomputers      | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| L     | enderioconduitsrefinedstorage     | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| L     | enderiointegrationforestry        | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| L     | mantle                            | 1.12-1.3.3.42            | Mantle-1.12-1.3.3.42.jar                        | None                                     |
	| L     | tconstruct                        | 1.12.2-2.12.0.115        | TConstruct-1.12.2-2.12.0.115.jar                | None                                     |
	| L     | enderiointegrationticlate         | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| L     | enderiomachines                   | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| L     | enderiopowertools                 | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| L     | enderstorage                      | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar     | None                                     |
	| L     | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.8.jar                      | None                                     |
	| L     | ic2                               | 2.8.111-ex112            | industrialcraft-2-2.8.111-ex112.jar             | None                                     |
	| L     | inventorytweaks                   | 1.64+dev.146.2180b27     | InventoryTweaks-1.64+dev.146.jar                | None                                     |
	| L     | ironchest                         | 1.12.2-7.0.59.842        | ironchest-1.12.2-7.0.59.842.jar                 | None                                     |
	| L     | journeymap                        | 1.12.2-5.5.3             | journeymap-1.12.2-5.5.3.jar                     | None                                     |
	| L     | jeid                              | 1.0.2-26                 | JustEnoughIDs-1.0.2-26.jar                      | None                                     |
	| L     | neid                              | 1.5.4.3                  | NotEnoughIDs-1.5.4.3.jar                        | None                                     |
	| L     | nei                               | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar   | None                                     |
	| L     | openmods                          | 0.12.1                   | OpenModsLib-1.12.2-0.12.1.jar                   | None                                     |
	| L     | openblocks                        | 1.8                      | OpenBlocks-1.12.2-1.8.jar                       | None                                     |
	| L     | harvestcraft                      | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zb.jar                 | None                                     |
	| L     | thermaldynamics                   | 2.5.4                    | ThermalDynamics-1.12.2-2.5.4.18-universal.jar   | None                                     |
	| L     | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar             | None                                     |

	Loaded coremods (and transformers): 
Plugin (NotEnoughIDs-1.5.4.3.jar)
  ru.fewizz.neid.asm.Transformer
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  org.dimdev.jeid.JEIDTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 418.81' Renderer: 'GeForce GTX 1060 with Max-Q Design/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2814
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 418.81, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 418.81
	OpenGlRenderer: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by KingLemming** [comment]
Reinstall everything. You are missing a basic library somehow.
