### ISSUE TITLE
redstone flux 2.1.0.6 bug

### ISSUE THREAD

**Issue by Violoniste75** [CoFH/Feedback#1436]
At each start of my game, the same problem happen.
Here is my mod list : 
Thermal Fondation 1.12.6-2.6.2.26
COFHCore 4.6.2.25
COFHLib 1.2.1
COFHWorld 1.3.0.6
Redstone Flux 2.1.0.6

here is my crash message : 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Redstone Flux (redstoneflux)

and here is my crash report : 
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2/18/19 3:04 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Redstone Flux (redstoneflux)
Caused by: java.lang.RuntimeException: 
RedstoneFlux has detected that the following OLD API classes from CoFHLib are being repacked!
    cofh.api.energy.ItemEnergyContainer, loaded from: CoFHLib-%5B1.7.10%5D1.2.1-185.jar
    cofh.api.energy.EnergyStorage, loaded from: CoFHLib-%5B1.7.10%5D1.2.1-185.jar
    cofh.api.energy.IEnergyTransport, loaded from: CoFHLib-%5B1.7.10%5D1.2.1-185.jar
    cofh.api.energy.TileEnergyHandler, loaded from: CoFHLib-%5B1.7.10%5D1.2.1-185.jar
    cofh.api.energy.IEnergyConnection, loaded from: CoFHLib-%5B1.7.10%5D1.2.1-185.jar
    cofh.api.energy.IEnergyProvider, loaded from: CoFHLib-%5B1.7.10%5D1.2.1-185.jar
    cofh.api.energy.IEnergyHandler, loaded from: CoFHLib-%5B1.7.10%5D1.2.1-185.jar
    cofh.api.energy.IEnergyStorage, loaded from: CoFHLib-%5B1.7.10%5D1.2.1-185.jar
    cofh.api.energy.IEnergyContainerItem, loaded from: CoFHLib-%5B1.7.10%5D1.2.1-185.jar
    cofh.api.energy.IEnergyReceiver, loaded from: CoFHLib-%5B1.7.10%5D1.2.1-185.jar

To prevent this crash, add "-Dcofh.rf.crashOnOldAPI=false" to your command line arguments.

	at cofh.redstoneflux.internal.OldAPIChecker.check(OldAPIChecker.java:64)
	at cofh.redstoneflux.RedstoneFlux.preInit(RedstoneFlux.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:246)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 446013008 bytes (425 MB) / 671088640 bytes (640 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2739 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version      | Source                                          | Signature                                |
	|:----- |:----------------- |:------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft         | 1.12.2       | minecraft.jar                                   | None                                     |
	| UCH   | mcp               | 9.42         | minecraft.jar                                   | None                                     |
	| UCH   | FML               | 8.0.99.99    | forge-1.12.2-14.23.4.2739.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge             | 14.23.4.2739 | forge-1.12.2-14.23.4.2739.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCEE  | redstoneflux      | 2.1.0        | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | cofhcore          | 4.6.2        | CoFHCore-1.12.2-4.6.2.25-universal.jar          | None                                     |
	| UC    | cofhworld         | 1.3.0        | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thermalfoundation | 2.6.2        | ThermalFoundation-1.12.2-2.6.2.26-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.57' Renderer: 'GeForce MX150/PCIe/SSE2'

**Comment by Tora-B** [comment]
Remove CoFHLib. It's already included in CoFHCore.

**Comment by KingLemming** [comment]
It's like you don't read the very descriptive crash log. There is no bug here.

**Comment by Violoniste75** [comment]
thank you
