### ISSUE TITLE
ClassCastException with ThermalDynamics & SteamFurnace on loading chunk

### ISSUE THREAD

**Issue by LemADEC** [CoFH/Feedback#1462]
We've experienced twice a server crash when loading chunks, only solved by restoring a previous world save.
Each time, the crash is a ClassCastException in Thermal mods.

Loading the chunk is enough to trigger the crash.
Here are few samples of the crash with different forge versions:
```
java.lang.ClassCastException: cofh.thermalexpansion.block.machine.TileFurnace cannot be cast to cofh.thermaldynamics.duct.tiles.TileGrid
        at cofh.thermaldynamics.block.BlockDuct.func_185477_a(BlockDuct.java:152)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:451)
        at net.minecraft.world.World.func_191504_a(World.java:1338)
        at net.minecraft.world.World.func_184144_a(World.java:1362)
        at net.minecraft.entity.EntityLiving.func_70058_J(EntityLiving.java:852)
        at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:773)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

```
java.lang.ClassCastException: cofh.thermalexpansion.block.machine.TileFurnace cannot be cast to cofh.thermaldynamics.duct.tiles.TileGrid
        at cofh.thermaldynamics.block.BlockDuct.func_180656_a(BlockDuct.java:264)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185911_a(BlockStateContainer.java:388)
        at net.minecraft.world.World.func_175651_c(World.java:3265)
        at net.minecraft.world.World.func_175687_A(World.java:3302)
        at cofh.core.block.TileRSControl.onNeighborBlockChange(TileRSControl.java:56)
        at cofh.thermalexpansion.block.dynamo.TileDynamoBase.onNeighborBlockChange(TileDynamoBase.java:285)
        at cofh.core.block.BlockCoreTile.func_189540_a(BlockCoreTile.java:153)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
        at org.spongepowered.common.event.tracking.PhaseTracker.notifyBlockOfStateChange(PhaseTracker.java:635)
        at net.minecraft.world.WorldServer.func_175685_c(WorldServer.java:3440)
        at cofh.core.block.TileCore.callNeighborStateChange(TileCore.java:52)
        at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:203)
        at cofh.thermaldynamics.duct.tiles.DuctUnit.onNeighborBlockChange(DuctUnit.java:283)
        at cofh.thermaldynamics.multiblock.MultiBlockFormer.checkMultiBlock(MultiBlockFormer.java:43)
        at cofh.thermaldynamics.multiblock.MultiBlockFormer.formGrid(MultiBlockFormer.java:23)
        at cofh.thermaldynamics.duct.tiles.DuctUnit.formGrid(DuctUnit.java:252)
        at cofh.thermaldynamics.duct.tiles.DuctUnit.singleTick(DuctUnit.java:349)
        at cofh.thermaldynamics.util.WorldGridList.tickEnd(WorldGridList.java:84)
        at cofh.thermaldynamics.util.TickHandler.tick(TickHandler.java:93)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1776_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:696)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

```
java.lang.ClassCastException: cofh.thermalexpansion.block.machine.TileFurnace cannot be cast to cofh.thermaldynamics.duct.tiles.TileGrid
	at cofh.thermaldynamics.block.BlockDuct.func_185477_a(BlockDuct.java:152)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:453)
	at net.minecraft.world.World.func_191504_a(World.java:1338)
	at net.minecraft.world.World.func_184144_a(World.java:1362)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:721)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1958)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1819)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

Full logs from loading the world in single player: https://gist.github.com/LemADEC/9a46c37baed72257aa94c5453d6cf507
Related versions:
Forge Mod Loader version 14.23.5.2820 for Minecraft 1.12.2
CoFHCore-1.12.2-4.6.2.25
RedstoneFlux-1.12-2.1.0.6
ThermalFoundation-1.12.2-2.6.2.26
ThermalDynamics-1.12.2-2.5.4.18
ThermalExpansion-1.12.2-5.5.3.41

**Comment by KingLemming** [comment]
This has something to do with your world just saving incorrectly and the blocks trying to load in as things they aren't.

The rewrite will hopefully be more robust to this but frankly if you have corruption like this, hiding it isn't a good idea.

**Comment by LemADEC** [comment]
I was hoping some logs to hint on what is causing the issue.
