### ISSUE TITLE
JEI plugin is crashing making Thermal recipes not show in JEI

### ISSUE THREAD

**Issue by Saereth** [CoFH/Feedback#1469]
In development pack, FTB Interactions, we noticed some JEI recipes weren't showing up and after some digging we found this in the debug log:

JEI version: jei_1.12.2-4.15.0.269
ThermalExpansion-1.12.2-5.5.3.41
forge-14.23.5.2795

```
[20:15:52] [Client thread/ERROR] [jei]: Failed to register mod plugin: class cofh.thermalexpansion.plugins.jei.JEIPluginTE
java.lang.IllegalArgumentException: Must have at least 1 tick per cycle.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[guava-21.0.jar:?]
	at mezz.jei.gui.TickTimer.<init>(TickTimer.java:13) ~[TickTimer.class:?]
	at mezz.jei.gui.elements.DrawableAnimated.<init>(DrawableAnimated.java:36) ~[DrawableAnimated.class:?]
	at mezz.jei.gui.GuiHelper.createAnimatedDrawable(GuiHelper.java:87) ~[GuiHelper.class:?]
	at cofh.thermalexpansion.plugins.jei.machine.pulverizer.PulverizerRecipeWrapper.<init>(PulverizerRecipeWrapper.java:87) ~[PulverizerRecipeWrapper.class:?]
	at cofh.thermalexpansion.plugins.jei.machine.pulverizer.PulverizerRecipeWrapper.<init>(PulverizerRecipeWrapper.java:45) ~[PulverizerRecipeWrapper.class:?]
	at cofh.thermalexpansion.plugins.jei.machine.pulverizer.PulverizerRecipeCategory.getRecipes(PulverizerRecipeCategory.java:66) ~[PulverizerRecipeCategory.class:?]
	at cofh.thermalexpansion.plugins.jei.machine.pulverizer.PulverizerRecipeCategory.initialize(PulverizerRecipeCategory.java:54) ~[PulverizerRecipeCategory.class:?]
	at cofh.thermalexpansion.plugins.jei.JEIPluginTE.register(JEIPluginTE.java:105) ~[JEIPluginTE.class:?]
	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:202) [JeiStarter.class:?]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:73) [JeiStarter.class:?]
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55) [JustEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

so particularly "Must have at least 1 tick per cycle." from the pulverizer recipe wrapper. Interestingly enough we have pulverizer turned off in the configs so I wouldnt assume it should even be registering any recipes for it. At anyrate when the jei plugin fails no thermal recipes show in jei. Since it doesnt give any indication as to what the actual recipe is im not sure if its even one of our recipes from the pack or an autogenerated one from TE that's just broken. I'm assuming its not one of our recipes since its not the Crafttweaker jei plugin failing.

**Comment by Shandoo94** [comment]
I have a problem, where the TE recipes don't show up when I have Building Gadgets by Direwolf20 installed (see #1470 ).
I'm not finding the same message in my log files, but if you have Building Gadgets in your pack you could test if it solves your problem as well.

**Comment by Saereth** [comment]
I will check right now

**Comment by Shandoo94** [comment]
I pinned it down the new 2.6.7 version of building gadgets. The changelog says dire added some recipes for constructionpase which can be processed by TE machines. Maybe there is an error when adding the recipes.
The rechipes get displayed normaly with version 2.6.6 of building gadgets in my modpack.

**Comment by Saereth** [comment]
you're absolutely right, disabling this got rid of the error in the debug log so I'm guessing BG is registering the bad recipe or something? guess we can close this issue and move the discussion over to BG

**Comment by KingLemming** [comment]
INTERESTING. Good research. :)

**Comment by Phylogeny** [comment]
I'm using `ThermalExpansionHelper` of CoFH Core's API to register 2 pulverizer recipes (one with an energy cost of 100, and another of 400):
https://github.com/Direwolf20-MC/BuildingGadgets/blob/master/src/main/java/com/direwolf20/buildinggadgets/common/integration/mods/ThermalExpansion.java#L29

Evidently, regardless of
1. the inti phase this is called in _(I've tried every one)_
2. whether BG loads before or after TE _(I've tried both for each phase)_

every time the above mentioned recipes actually manages to register, if the user has set the `BasePower` of the machine in question to above the value in that recipe, in addition to the recipe failing, all JEI integration for that machine breaks.

As there is nothing in `ThermalExpansionHelper` for checking what the `BasePower` is for a given machine, I don't see how I'm doing anything wrong. And regardless of that, surly it's a bug on TE's end that if one uses `ThermalExpansionHelper` to set an energy cost for a machine's recipe lower than its `BasePower` that this would break all JEI integration for that machine.

**Comment by KingLemming** [comment]
Frankly those recipe costs are way too low and the correct fix here is going to be that it'll fail if you try anything that low. Bump up those values please.

I'll also be adjusting things as far as JEI goes, but 100 RF? Bump that up.

**Comment by Phylogeny** [comment]
I don't have any sense of what is a "fair-price" for any mod, really. I let Dire know that he can feel free to change any cost of any mod recipe I added, but I guess he didn't take a look.

I'll set them to whatever you and/or Dire want.

**Comment by KingLemming** [comment]
TBH I don't know what the recipe is doing, but the "default" Pulverizer value is 4000. Lower cost recipes are about 1000 at the lowest.

I had sort of figured this out on my own earlier and had decided to fix up the JEI handling regardless. I'm surprised that the recipe itself fails as well though.

**Comment by Phylogeny** [comment]
Sounds good. I'll use 4000 and 1000, rather than 400 and 100.

Also, it might be worth adding versions of the recipe methods in `ThermalExpansionHelper` that use a default energy cost (and maybe some indication of a standard min value).

**Comment by KingLemming** [comment]
Well, that's getting phased out in favor of the content jsons, but I'll see what I can do.

I just don't want to put a whole lot of code time into the current 1.12 branches because it's all being obliterated.
