### ISSUE TITLE
Crash Ticking Entity

### ISSUE THREAD

**Issue by Insane-96** [CoFH/Feedback#1501]
Happens when a piston is activated.
Sorry I'm from phone and can't format

net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: net.minecraft.tileentity.TileEntityPiston cannot be cast to cofh.thermaldynamics.duct.tiles.TileGrid
	at cofh.thermaldynamics.block.BlockDuct.func_185477_a(BlockDuct.java:152) ~[BlockDuct.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:451) ~[awu$a.class:?]
	at net.minecraft.tileentity.TileEntityPiston.func_190609_a(TileEntityPiston.java:408) ~[awm.class:?]
	at net.minecraft.block.BlockPistonMoving.func_185477_a(BlockPistonMoving.java:159) ~[awl.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:451) ~[awu$a.class:?]
	at net.minecraft.world.World.func_191504_a(World.java:1338) ~[amu.class:?]
	at net.minecraft.world.World.func_184143_b(World.java:1426) ~[amu.class:?]
	at net.minecraft.entity.Entity.func_145771_j(Entity.java:2379) ~[vg.class:?]
	at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:119) ~[acl.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1993) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1955) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1759) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more

**Comment by KingLemming** [comment]
Not us, sorry. Something happened with your world. You have corruption.

**Comment by Insane-96** [comment]
RIP
I'll try to remove the bad piston with MCEdit

**Comment by Insane-96** [comment]
Found out that (probably) was a Quark feature that let you move Tile Entities with Pistons. Ducts didn't like to be moved.

**Comment by KingLemming** [comment]
Oh yeah...that's a hard no.
