### ISSUE TITLE
[1.12.2] CoFH User Loader Warnning

### ISSUE THREAD

**Issue by KuLiPoi** [CoFH/Feedback#1517]
this warning flood my console almost everyday , how can i fix it or hide it.

[17:45:40] [CoFH User Loader/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@bfdec19[id=81092fd0-f3d4-3af2-bba3-42b23a67469c,name=you_yi,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[YggdrasilAuthenticationService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [YggdrasilMinecraftSessionService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [YggdrasilMinecraftSessionService.class:?]
        at cofh.core.util.helpers.SecurityHelper.getProfile(SecurityHelper.java:192) [SecurityHelper.class:?]
        at cofh.core.block.TileAugmentableSecure$1.run(TileAugmentableSecure.java:471) [TileAugmentableSecure$1.class:?]

**Comment by KingLemming** [comment]
You can't. It's harmless and only happens in rare cases.
