### ISSUE TITLE
NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by Insane96** [CoFH/Feedback#1521]
```
java.lang.NullPointerException: Ticking block entity
	at cofh.thermalexpansion.block.dynamo.BlockDynamo.func_185477_a(BlockDynamo.java:179)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:451)
	at net.minecraft.tileentity.TileEntityPiston.func_184322_i(TileEntityPiston.java:139)
	at net.minecraft.tileentity.TileEntityPiston.func_73660_a(TileEntityPiston.java:344)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
```

Probably related to https://github.com/CoFH/Feedback/issues/1501. I've disabled Quark's piston moving tile entities to see if it is the cause

**Comment by KingLemming** [comment]
It is.
