### ISSUE TITLE
I was doing so good too!!!

### ISSUE THREAD

**Issue by Wolfseverest93** [CoFH/Feedback#176]
[00:02:17] [Server thread/ERROR] [FML]: Caught exception from ThermalExpansion
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(Unknown Source) ~[?:1.7.0_60]
	at cofh.lib.util.helpers.StringHelper.titleCase(StringHelper.java:57) ~[StringHelper.class:?]
	at cofh.thermalexpansion.util.crafting.InsolatorManager.addDefaultOreDictionaryRecipe(InsolatorManager.java:179) ~[InsolatorManager.class:?]
	at cofh.thermalexpansion.util.crafting.InsolatorManager.loadRecipes(InsolatorManager.java:118) ~[InsolatorManager.class:?]
	at cofh.thermalexpansion.ThermalExpansion.loadComplete(ThermalExpansion.java:216) ~[ThermalExpansion.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[forge-1.7.10-10.13.2.1307-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:696) ~[Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) ~[1.7.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) ~[OneSixLauncher.class:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) ~[OneSixLauncher.class:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) ~[EntryPoint.class:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) ~[EntryPoint.class:?]
[00:02:17] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event

it now shoots this error every time I go to load my minecraft world, I didn't change any of the mods aside from updating all of the cofh stuff (te,ra,tf,mfr,core) and now, even when i rolled back, i can no longer get on with this instance... i'll miss that world, had tons of months into it...

**Comment by KingLemming** [comment]
Drop the melodrama. We'll have a fix for this. Hang onto your world. :P

**Comment by Wolfseverest93** [comment]
hahah thanks. and yeah, if i ever get rid of a minecraft world it sure won't be one I've worked on for more than 6 months like this one XD 5 cities that go from bedrock to skycap, 20+ factories each, laser drills going to town all over the place. and thats not even a percent of my work in it. would you get rid of a world with that much effort involved?

  btw i made a temporary fix using my at this point highly changed version of minetweaker 3 (kinda added to what all it can do, would be an understatement at this point, it's now my emergency override tool), i temporarily made it so the initialization skips the render of the class which caused the problem, idk if it'll affect gameplay much, but i haven't noticed any differences so far. is that class something for an upcoming feature?

  let me know when the fix is released so i can remove my override and go back to playing normally soon XD thanks @KingLemming

**Comment by KingLemming** [comment]
BTW, the error here is that something is registering the word "seed" to the Ore Dictionary

**Comment by Wolfseverest93** [comment]
ah, thanks for letting me know, i'll poke around and see which of the other mods i use decided to do that, mustve been part of one of their updates, if so i'll rename their registry version while maintaining the ore dictionary connection with the original aspect of seed. that way i won't lose that functionality from this mod, and have it fixed for now. i really need to stop doing vague patch jobs, i couldve really killed my game there...
