### ISSUE TITLE
Crash: Tesselating block in world - Compression Dynamo

### ISSUE THREAD

**Issue by robodonkey** [CoFH/Feedback#177]
Playing FTB Beyond, using ThermalExpansion-1.10.2-5.0.4.90-universal.jar

Crash Description: Tesselating block in world

java.lang.NullPointerException: Tesselating block in world
	at cofh.thermalexpansion.block.dynamo.TileDynamoCompression.getActiveIcon(TileDynamoCompression.java:115)
	at cofh.thermalexpansion.render.RenderDynamo.handleState(RenderDynamo.java:148)

Full Crash Report:
https://pastebin.com/210sQJxU

**Comment by legodude17** [comment]
Do you have optifine installed?

**Comment by robodonkey** [comment]
No I do not have OptiFine. 

Just a bit more info:
I am using Java 8 update 92.
JVM Arguments: -XX:+UseG1GC -Xmx4G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by KingLemming** [comment]
I can't make this happen under any circumstances. Not sure what to tell you.

**Comment by DDzwiedziu** [comment]
I've just got the same crash on Foolcraft client (server didn't care about this) with Optifine.

I was trying to prepare a bug report of dynamos "sticking" with the coil to non-power EnderIO conduits instead of power-transfering  ones (!) or other dynamos. Sneak-renching with the crescent hammer (#dealwithit) a dynamo for the n-th time, and this time it crashed.
The only difference was that I've sneak-wrenched a "stuck" dynamo and behind  it was another dynamo placed correctly (coil up, into a power conduit).

Excerpt from logs:
```
java.lang.NullPointerException: Tesselating block in world
	at cofh.thermalexpansion.block.dynamo.TileDynamoMagmatic.getActiveIcon(TileDynamoMagmatic.java:108)
	at cofh.thermalexpansion.render.RenderDynamo.handleState(RenderDynamo.java:148)
	at codechicken.lib.model.blockbakery.BlockBakery.handleExtendedState(BlockBakery.java:131)
	at cofh.thermalexpansion.block.dynamo.BlockDynamo.getExtendedState(BlockDynamo.java:265)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	at gcewing.architecture.BaseAORenderingManager$CustomBlockRendererDispatcher.func_175018_a(BaseAORenderingManager.java:85)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:290)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by KingLemming** [comment]
Looking at the code, this truly shouldn't be possible, but I put in a mitigation for it.
