### ISSUE TITLE
World crashes with ThermalExpansion-[1.7.10]4.0.0RC2-129

### ISSUE THREAD

**Issue by Johnne25** [CoFH/Feedback#180]
Everything in my world works great.  I am not adding any new mods or removing any exsisting.  I amonly attempting to update all mods to the latest release versions.

I went through every mod I am using and updated them to all use the latest release version.
I updated Ex-Astris and Ex-Nihilo to use a Jenkins version (as instructed in another post).
Ex-Astris-MC1.7.10-1.16-18
Ex-Nihilo-1.38-14

When I update all the mods and restart the server during the restart I get this message in the console:
------------------------------------------------------------------------
08:48:52] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:tool.swordInvar
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:tool.bowInvar
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:tool.shovelInvar
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:tool.shearsInvar
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:tool.fishingRodInvar
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:tool.hoeInvar
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:tool.axeInvar
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:tool.pickaxeInvar
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:armor.plateInvar
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:tool.sickleInvar
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:armor.legsInvar
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:armor.bootsInvar
[08:48:53] [Server thread/INFO] [FML]: Found a missing id from the world ThermalExpansion:armor.helmetInvar
[08:48:53] [Server thread/WARN] [FML]: ****************************************
[08:48:53] [Server thread/WARN] [FML]: * The object cofh.core.item.tool.ItemSwordAdv@4726fc49 has been registered twice for the same name ThermalFoundation:tool.swordInvar.
[08:48:53] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:357)
[08:48:53] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:838)
[08:48:53] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.registry.GameData.processIdRematches(GameData.java:623)
[08:48:53] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.Loader.fireMissingMappingEvent(Loader.java:929)
[08:48:53] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.registry.GameData.injectWorldIDMap(GameData.java:537)
[08:48:53] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.FMLContainer.readData(FMLContainer.java:275)...
[08:48:53] [Server thread/WARN] [FML]: ****************************************
[08:48:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.IllegalStateException
[08:48:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.registry.GameData.processIdRematches(GameData.java:627)
[08:48:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.Loader.fireMissingMappingEvent(Loader.java:929)
[08:48:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.registry.GameData.injectWorldIDMap(GameData.java:537)
[08:48:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLContainer.readData(FMLContainer.java:275)
[08:48:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:403)
[08:48:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122)
[08:48:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:201)
[08:48:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258)
[08:48:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[08:48:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[08:48:53] [Server thread/WARN] [FML]: Forge Mod Loader detected that the backup level.dat is being used.

This may happen due to a bug or corruption, continuing can damage
your world beyond repair or lose data / progress.

It's recommended to create a world backup before continuing.

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer
------------------------------------------------------------------------

I enter /fml confirm and it continues.
It actually gets tot he Done! portion then after a few seconds the server crashes.

Here is the crash report:
---- Minecraft Crash Report ----
// There are four lights!

Time: 2/24/15 8:58 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at cofh.thermalexpansion.block.dynamo.BlockDynamo.func_149743_a(BlockDynamo.java:94)
	at cofh.asm.hooks.HooksCore.getEntityCollisionBoxes(HooksCore.java:87)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:596)
	at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:110)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cofh.thermalexpansion.block.dynamo.BlockDynamo.func_149743_a(BlockDynamo.java:94)
	at cofh.asm.hooks.HooksCore.getEntityCollisionBoxes(HooksCore.java:87)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:596)
	at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:110)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: Item (net.minecraft.entity.item.EntityItem)
	Entity ID: 449
	Entity Name: item.item.ModMagicSeedsRubber
	Entity's Exact location: -140.35, 94.17, 280.32
	Entity's Block location: World: (-141,94,280), Chunk: (at 3,5,8 in -9,17; contains blocks -144,0,272 to -129,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.01, -0.37, 0.04
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 673 Drop: 0
	Level seed: -1612847758
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-128,64,180), Chunk: (at 0,4,4 in -8,11; contains blocks -128,0,176 to -113,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 89059002 game time, 5699272 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 4177 (now: false), thunder time: 73323 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3763535848 bytes (3589 MB) / 4116185088 bytes (3925 MB) up to 4116185088 bytes (3925 MB)
	JVM Flags: 2 total; -Xms4G -Xmx4G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 15, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 41 mods loaded, 41 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forgeMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forgeMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	backpacks16840{3.0.1} [Backpacks!] (zz-backpacks 1.7.10 - 3.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0RC2} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC2-195.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.3.7} [BuildCraft] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.3.7} [BC Transport] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.3.7} [BC Silicon] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.3.7} [BC Builders] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.3.7} [BC Energy] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.3.7} [BC Factory] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chisel{2.3.7.34} [Chisel 2] (Chisel2-2.3.7.34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ComputerCraft{1.71} [ComputerCraft] (ComputerCraft1.71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderIO{1.7.10-2.2.8.349} [Ender IO] (EnderIO-1.7.10-2.2.8.349.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	exnihilo{1.38-14} [Ex Nihilo] (Ex-Nihilo-1.38-14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0RC3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC3-56.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.0RC2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC2-129.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RedstoneArsenal{1.7.10R1.1.0RC2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC2-43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	exastris{MC1.7.10-1.16-18} [Ex Astris] (Ex-Astris-MC1.7.10-1.16-18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	iChunUtil{4.1.0} [iChunUtil] (iChunUtil-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	JABBA{1.2.0b} [JABBA] (Jabba-1.2.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (malisisdoors-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mcicraft{1.0.6c} [MCICraft] (mcicraft_core-1.0.6c_MC-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mcicraft_farming{1.0.6c} [MCICraft Farming] (mcicraft_farming-1.0.6c_MC-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mcicraft_machines{1.0.6c} [MCICraft Machines] (mcicraft_machines-1.0.6c_MC-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mcicraft_redstone{1.0.6c} [MCICraft Redstone] (mcicraft_redstone-1.0.6c_MC-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	StevesFactoryManager{A90} [Steve's Factory Manager] (Steves-Factory-Manager-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore: -[1.7.10]3.0.0RC2-195
	ThermalFoundation: -[1.7.10]1.0.0RC3-56
	ThermalExpansion: -[1.7.10]4.0.0RC2-129
	RedstoneArsenal: Lacking version information.
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 10; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

Restarting the server produces the same crash report.

**Comment by Johnne25** [comment]
I did a mod comparison from my working world and the one that crashes and these are the only mods that are updated (these are the updated versions that crash):
CodeChickenCore-1.7.10-1.0.4.29-universal
CoFHCore-[1.7.10]3.0.0RC2-195
Ex-Astris-MC1.7.10-1.16-18
Ex-Nihilo-1.38-14
ironchest-1.7.10-6.0.62.742-universal
RedstoneArsenal-[1.7.10]1.1.0RC2-43
ThermalExpansion-[1.7.10]4.0.0RC2-129
ThermalFoundation-[1.7.10]1.0.0RC3-56

Note: If I update only IronChest the world does not crash, so it that mod looks ok.

**Comment by KingLemming** [comment]
You were using alphas before this latest update. We *warned* people about this.

You need to backdate your CoFH mods to the December releases (the releases prior to this), load your world, and THEN update.

Why do people not believe us when they say using alphas can cause problems? :(
