### ISSUE TITLE
Conflict between Thermal Foundation and Ex Astris.

### ISSUE THREAD

**Issue by Empmortakaten** [CoFH/Feedback#182]
Mod list:
CoFHCore-[1.7.10]3.0.0RC2-195
Ex-Astris-1.15
Ex-Nihilo-1.37
ThermalExpansion-[1.7.10]4.0.0RC2-129
ThermalFoundation-[1.7.10]1.0.0RC3-56

Forge version:
10.13.2.1291

Minecraft version:
1.7.10

Java version:
Version 8 update 31
(build 1.8.0_31-b13)

Crash report:
---- Minecraft Crash Report ----
// Don't do that.

Time: 2/24/15 11:55 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: thermalfoundation/entity/monster/EntityBlizz
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: thermalfoundation/entity/monster/EntityBlizz
	at ExAstris.ExAstris.PostInitialize(ExAstris.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	... 10 more
Caused by: java.lang.ClassNotFoundException: thermalfoundation.entity.monster.EntityBlizz
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 73203792 bytes (69 MB) / 261816320 bytes (249 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 9 mods loaded, 9 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore{1.7.10R3.0.0RC2} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC2-195.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	exnihilo{1.37} [Ex Nihilo] (Ex-Nihilo-1.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalFoundation{1.7.10R1.0.0RC3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC3-56.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalExpansion{1.7.10R4.0.0RC2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC2-129.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	exastris{1.15} [Ex Astris] (Ex-Astris-1.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	CoFHCore: -[1.7.10]3.0.0RC2-195
	ThermalFoundation: -[1.7.10]1.0.0RC3-56
	ThermalExpansion: -[1.7.10]4.0.0RC2-129

**Comment by KingLemming** [comment]
Yes we know. This is 100% on them. They are directly looking for one of our classes for who knows what purpose.

**Comment by cobaltwarrior19** [comment]
Try reverting Ex Astris to 1.12. I'm not sure if you'll have to revert Ex Nihilo as well, but I do know that a modpack I created a few months ago has no conflict between Ex Astris and Thermal Foundation. 1.12 was the version I was using.
