### ISSUE TITLE
Crash :cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: thermalexpansion/util/crafting/SmelterManager

### ISSUE THREAD

**Issue by MrAmazoni** [CoFH/Feedback#216]
After updating all your mods  I have this crash.Can you help me with it?What did I wrong?
If you need I link the crash report http://pastebin.com/7VgkuFZR.

**Comment by KingLemming** [comment]
Caused by: java.lang.NoClassDefFoundError: thermalexpansion/util/crafting/SmelterManager
        at mrtjp.projectred.compatibility.thermalexpansion.PluginThermalExpansion$.init(PluginThermalExpansion.scala:22)
        at mrtjp.projectred.compatibility.Services$$anonfun$doInit$1.apply(Services.scala:44)
        at mrtjp.projectred.compatibility.Services$$anonfun$doInit$1.apply(Services.scala:44)

^ Caused by Project Red. Update that.

**Comment by MrAmazoni** [comment]
Thanks a lot.
