### ISSUE TITLE
Crash while placing private Tesseract [latest ftb infinity release]

### ISSUE THREAD

**Issue by UnstableZer0** [CoFH/Feedback#237]
crashlog:

[13:34:58] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
at net.minecraft.server.management.PreYggdrasilConverter.func_152719_a(SourceFile:244) ~[nz.class:?]
at cofh.thermalexpansion.block.TileInventory.setOwnerName(TileInventory.java:346) ~[TileInventory.class:?]
at cofh.thermalexpansion.block.ender.BlockEnder.func_149689_a(BlockEnder.java:76) ~[BlockEnder.class:?]
at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:213) ~[abh.class:?]
at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103) ~[abh.class:?]
at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129) ~[add.class:?]
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360) ~[bje.class:?]
at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435) ~[bao.class:?]
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941) ~[bao.class:?]
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) ~[bao.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[13:34:59] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Ouch. That hurt :(

As titel says; crash straight to desktop when placing tesseract (with signalum lock/private) for the first time.

**Comment by UnstableZer0** [comment]
also, when accessing the tesseract the console throws weird exceptions:

[13:49:28] [CoFH User Loader/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[13:49:28] [CoFH User Loader/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cofh.lib.util.helpers.SecurityHelper.getProfile(SecurityHelper.java:137)
[13:49:28] [CoFH User Loader/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cofh.thermalexpansion.block.TileInventory$1.run(TileInventory.java:364)
[13:49:28] [CoFH User Loader/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[13:49:28] [CoFH User Loader/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cofh.lib.util.helpers.SecurityHelper.getProfile(SecurityHelper.java:137)
[13:49:28] [CoFH User Loader/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cofh.thermalexpansion.block.TileInventory$1.run(TileInventory.java:364)
[13:49:28] [CoFH User Loader/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[13:49:28] [CoFH User Loader/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cofh.lib.util.helpers.SecurityHelper.getProfile(SecurityHelper.java:137)
[13:49:28] [CoFH User Loader/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cofh.thermalexpansion.block.TileInventory$1.run(TileInventory.java:364)
[13:49:29] [CoFH User Loader/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[13:49:29] [CoFH User Loader/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cofh.lib.util.helpers.SecurityHelper.getProfile(SecurityHelper.java:137)
[13:49:29] [CoFH User Loader/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cofh.thermalexpansion.block.TileInventory$1.run(TileInventory.java:364)

**Comment by KingLemming** [comment]
What version is in FTB Infinity? This has already been fixed.

**Comment by UnstableZer0** [comment]
Thermal Expansion 4.0.0RC1
