### ISSUE TITLE
Crash from EnderIO/ThermalDynamics item routing

### ISSUE THREAD

**Issue by SteadySword** [CoFH/Feedback#239]
Afternoon,

I appear to be getting a crash on my private server from an interaction between EIO conduits and TD ItemDucts. On one section of a processing chain, i'm using EIO for compact item/redstone/power, but on a visible portion I'm using ItemDucts because I prefer the aesthetics. 

The crashes started after building this- but strangely only seem to happen when people are away from the location (and I don't think it's chunk loaded?). I stayed logged in around it for 2+ hours. Once I logged off and a friend logged on, it happened about every 15 minutes. They ceased to happen once I stopped the item flow. Is it just a terrible idea in general to connect two separate conduit systems? I can see where that might be problematic. For now I'll just sneak a buffer inventory in, but I figured I could at least share the crash log in case it was of any use.

I'll provide screenshots/non-truncated logs or whatever else you need. Also, appreciate your work on updating TD, It's good to have it in my modpack again!

```
Description: Exception in server tick loop

java.lang.IllegalStateException
	at cofh.thermaldynamics.duct.item.DuctUnitItem.getCache(DuctUnitItem.java:345)
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.verifyCache(ServoItem.java:198)
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.getRouteForItem(ServoItem.java:384)
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.insertItem(ServoItem.java:371)
	at cofh.thermaldynamics.duct.item.DuctUnitItem$1.insertItem(DuctUnitItem.java:956)
	at net.minecraftforge.items.ItemHandlerHelper.insertItemStacked(ItemHandlerHelper.java:130)
	at crazypants.enderio.capability.ItemTools.doInsertItem(ItemTools.java:131)
	at crazypants.enderio.conduit.item.NetworkedInventory.insertItem(NetworkedInventory.java:254)
	at crazypants.enderio.conduit.item.NetworkedInventory.insertIntoTargets(NetworkedInventory.java:213)
	at crazypants.enderio.conduit.item.NetworkedInventory.doTransfer(NetworkedInventory.java:177)
	at crazypants.enderio.conduit.item.NetworkedInventory.transferItems(NetworkedInventory.java:167)
	at crazypants.enderio.conduit.item.NetworkedInventory.onTick(NetworkedInventory.java:108)
	at crazypants.enderio.conduit.item.ItemConduitNetwork.doNetworkTick(ItemConduitNetwork.java:225)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:75)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:54)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_418_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 2.6.32-042stab112.15
	Java Version: 1.8.0_102, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 320450920 bytes (305 MB) / 2103885824 bytes (2006 MB) up to 5246550016 bytes (5003 MB)
	JVM Flags: 10 total; -Xms32M -Xmx5176M -XX:OnOutOfMemoryError=curl https://api.creeper.host/callbacks/minecraft/outofmemory.php?instance=mc-592987f3eae65 -k -XX:OnError=curl http://api.creeper.host/callbacks/minecraft/crash.php?instance=mc-592987f3eae65 -k -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=4 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
	IntCache: cache: 0, tcache: 0, allocated: 9, tallocated: 61
```

**Comment by KingLemming** [comment]
Hrm. Somehow EnderIO is forcing an illegal state. For now, your best option is to not mix the systems.

Offhand, my guess is that EnderIO is trying to send an item into an unloaded chunk, which quickly loads/unloads the chunk and causes this invalid state.

**Comment by KingLemming** [comment]
We have a mitigation for this in dev.
