### ISSUE TITLE
Rotating an Autonomous Activator

### ISSUE THREAD

**Issue by IdleMuse** [CoFH/Feedback#257]
java.lang.NullPointerException: Unexpected error
	at cofh.thermalexpansion.block.device.TileActivator.rotateBlock(TileActivator.java:355)
	at cofh.core.block.BlockCoFHBase.rotateBlock(BlockCoFHBase.java:259)
	at cofh.thermalexpansion.item.tool.ItemWrench.onItemUseFirst(ItemWrench.java:85)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:317)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I'm getting this exception when trying to rotate an Autonomous Activator with a Crescent Hammer. There are a mess of other mods on the system, but doesn't seem to be related to them. All current CoFH mods (as of today). I can provide full crash log if necessary. Both SP and MP.

**Comment by KingLemming** [comment]
It's a skyderp.

**Comment by KingLemming** [comment]
Workaround for now is to use a wrench that isn't the Crescent Hammer or Flux-Infused.

**Comment by usafphoenix** [comment]
also had this issue (both while playing online on a server, and a single player client. 
Do we know what causes it? i'll just use a different wrench for now, but i'm sorta curious cause it's happened a few times.
