### ISSUE TITLE
QuantumQuarry causes Error: Tried to assign a mutable BlockPos to tick data

### ISSUE THREAD

**Issue by wilkemeyer** [CoFH/Feedback#258]
When Running a Quantum Quarry from Extra Utilities 2, the server periodically logs an Error (see below).

Depending on my schedule i may investigate the problem further myself.
This problem may be also related to Extra Utilities 2.

Running (Mod) Versions:

- Forge: 12.18.3.2316
- CoFHCore: 1.10.2-4.1.4.7
- ThermalFoundation: 1.10.2-2.1.1.3
- ThermalExpansion 1.10.2-5.1.3.4
- Extra Utilities 2: 1.10.2-1.4.4

The Problem first occurred after updating ThermalExpansion to 5.1.2 

```
[Server thread/WARN]: Tried to assign a mutable BlockPos to tick data...
java.lang.Error: class net.minecraft.util.math.BlockPos
        at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:534) [ls.class:?]
        at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:526) [ls.class:?]
        at net.minecraftforge.fluids.BlockFluidBase.func_176213_c(BlockFluidBase.java:324) [BlockFluidBase.class:?]
        at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:612) [asv.class:?]
        at net.minecraft.world.World.func_180501_a(World.java:331) [aid.class:?]
        at cofh.thermalfoundation.block.BlockOreFluid.removedByPlayer(BlockOreFluid.java:128) [BlockOreFluid.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:275) [lv.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:333) [lv.class:?]
        at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:321) [TileQuarry.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1804) [aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) [ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by KingLemming** [comment]
After tracing through the code, this originates with the quarry itself. It's using MutableBlockPos instead of standard ones. What I'm not really understanding is why they remain Mutable, as I am calling add() which returns standard BlockPos objects.

Having said that, it's actually perfectly harmless. How frequently is this happening?

**Comment by KingLemming** [comment]
Well, despite it being harmless, I'm pretty sure I have a mitigation for it. :)

**Comment by wilkemeyer** [comment]
Depends on the Quarry speed & blocks it's mining
currently running one Quarry at max-speed, and i have a few errors showing about every few minutes (about 3-10 errors within 15-20seconds, then silence for another 3-5 minutes) 


So i'd say it always happens when it tries to mine/break/scan that type of block.
