### ISSUE TITLE
[Thermal Expansion] Right Clicking an Autonomous Activator with a Crescent Hammer crashes the game

### ISSUE THREAD

**Issue by dakotaaesoph** [CoFH/Feedback#261]
CoFHCore: -[1.7.10]3.0.0RC5-207
MineFactoryReloaded: -[1.7.10]2.8.0RC8-86
ThermalFoundation: -[1.7.10]1.0.0RC4-58
ThermalExpansion: -[1.7.10]4.0.0RC6-138
RedstoneArsenal: -[1.7.10]1.1.0RC4-54
ThermalDynamics: -[1.7.10]1.0.0RC5-94
Launched Version: 1.7.10-Forge10.13.2.1291

[00:43:38] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at cofh.thermalexpansion.block.device.TileActivator.rotateBlock(TileActivator.java:355) ~[TileActivator.class:?]
	at cofh.core.block.BlockCoFHBase.rotateBlock(BlockCoFHBase.java:259) ~[BlockCoFHBase.class:?]
	at cofh.thermalexpansion.item.tool.ItemWrench.onItemUseFirst(ItemWrench.java:85) ~[ItemWrench.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:317) ~[bje.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by dakotaaesoph** [comment]
Woops, didn't see it was already reported.
