### ISSUE TITLE
Crash on any keypress

### ISSUE THREAD

**Issue by twothe** [CoFH/Feedback#274]
I just updated to the latest CoFH/TE via Twitch/Curse (1.10.2-4.1.5.8) and now the game crashes as soon as any key is pressed while inside a world. The issue disappears as soon as CoFH Core is removed from the list of mods.

Stack trace:

    java.lang.IndexOutOfBoundsException: 316
      at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
      at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
      at cofh.core.key.KeyHandlerCore.handleKeyInputEvent(KeyHandlerCore.java:52)
      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_285_KeyHandlerCore_handleKeyInputEvent_KeyInputEvent.invoke(.dynamic)
      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
      at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
      at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:555)
      at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1958)
      at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
      at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
      at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
      at net.minecraft.client.main.Main.main(SourceFile:124)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:483)
      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Crash log:
[crash-2017-06-18_21.19.47-client.txt](https://github.com/CoFH/Feedback/files/1083311/crash-2017-06-18_21.19.47-client.txt)

**Comment by KingLemming** [comment]
Yeah so uh...this literally doesn't happen. I'm going to need way way way more info.

**Comment by Wadislav** [comment]
I've got the same. It happened after i crafted the Flux Infused Sword from Redstone Arsenal and try to empower it with the keybind.  The sword does not look empowered.

[Crashlog after empowering the Sword](https://github.com/CoFH/Feedback/files/1104075/crash-2017-06-26_23.15.23-client.txt)
[Crashlog after loading the world and trying to move](https://github.com/CoFH/Feedback/files/1104076/crash-2017-06-26_23.21.53-client.txt)

[Screenshot from the world](https://puu.sh/wvflL/440085f5a5.png)

**Comment by KingLemming** [comment]
Can you make this happen with *only* CoFH mods? And also, are you using a standard keyboard?

**Comment by Wadislav** [comment]
Just made an instance with every CoFH mod i could find and get the same crash over and over again. I am using a German keyboard layout with an Logitech G105. I allready rebooted my pc, closed the Logitech Gaming Software and it still crashes. 
[crash-2017-06-27_07.41.35-client.txt](https://github.com/CoFH/Feedback/files/1104256/crash-2017-06-27_07.41.35-client.txt)

**Comment by KingLemming** [comment]
Interesting. Unfortunately I really have no advice for you here. If the crash were actually in our code, then literally everyone would be getting this.

This is something specific with your hardware and/or setup, and I'm really not sure why it's happening.

What key are you pressing?

**Comment by Wadislav** [comment]
It does not matter, i pressed ESC,E ,F2 . But i do not think that i have done something with my system, it all worked fine till i tried to empower the Flux infused sword.

**Comment by KingLemming** [comment]
Well it does matter, I'd like to try and figure out why this is happening.

What's the keybinding?

**Comment by Wadislav** [comment]
I had the empower keybind on my '<' button which is next to the left shift on the German Layout.

**Comment by KingLemming** [comment]
Change the keybind to something else and let me know if it still crashes.

Try the default - V.

**Comment by Wadislav** [comment]
I tried it and it does not crash.

 It only crashes when i the keybind for Cycle Item Mode is '<'. So i tried to bind the '<' key to a JourneyMap keybind and it did not crash.

**Comment by KingLemming** [comment]
Yeah, figured that may have been the case.

Frankly, I have no idea how to fix that though - we're using the standard Java Keyboard class. The error is fundamentally in Keyboard.

**Comment by twothe** [comment]
I also set that to < as that reports as "none" in the Minecraft keybind when using a German keyboard.

**Comment by KingLemming** [comment]
Right, so basically the issue is that Minecraft Keybindings are client-side only so we have to use our own. I've added a mitigation for this, the side effect being that well - you can't use that key. Sorry.

TL,DR: Don't use that key. :P

**Comment by twothe** [comment]
There has to be a reason why that is happening exclusively with COFH Core, but then I have not the slightest clue where to start searching. It's definitely not in the code mentioned in the stack trace. ;)

Let's hope it vanishes as randomly as it appeared with one of the next versions.

**Comment by KingLemming** [comment]
Already told you why. However, this shouldn't have "randomly" appeared as nothing changed in the key handling. It should have been there a long time, and likely was.

Don't bind that key.
