### ISSUE TITLE
critical exception handling a packet on channel CoFH

### ISSUE THREAD

**Issue by Viper-7** [CoFH/Feedback#286]
I'm getting a world-breaking error on my server. Actually the server gets no error at all, it simply freezes and hangs (i've left it for a good 8 hours, it doesn't tick again.)

I'm using 
COFHCORE-[1.7.10]3.0.0RC2-195.jar
COFHLIB-[1.7.10]1.0.0B9-112.jar
THERMALDYNAMICS-[1.7.10]1.0.0RC2-77.jar
THERMALEXPANSION-[1.7.10]4.0.0RC2-129.jar
THERMALFOUNDATION-[1.7.10]1.0.0RC3-56.jar

Region file containing the erroring content: https://www.dropbox.com/s/6dbcmux1nphadsc/r.-5.0.mca

I've been able to reproduce the problem by downloading the region file and trying it in single player, which produced the following error.

Complete log is available at: https://www.dropbox.com/s/9p81wlswtq84t64/fml-client-latest.log

This *does* seem to be an interaction issue, as loading the region with a reduced mod-set (still including CoFH mods) does work, but I have no way to track this down to anything closer than this region file. The full pack is the current build of Resonant Rise 3 (3.2.4.0)

```
[19:18:02] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel CoFH
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 4
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
	at cofh.thermalexpansion.block.TileRSControl.handleTilePacket(TileRSControl.java:101) ~[TileRSControl.class:?]
	at cofh.thermalexpansion.block.TilePowered.handleTilePacket(TilePowered.java:99) ~[TilePowered.class:?]
	at cofh.thermalexpansion.block.TileReconfigurable.handleTilePacket(TileReconfigurable.java:87) ~[TileReconfigurable.class:?]
	at cofh.thermalexpansion.block.TileAugmentable.handleTilePacket(TileAugmentable.java:165) ~[TileAugmentable.class:?]
	at cofh.core.network.PacketTile.handlePacket(PacketTile.java:43) ~[PacketTile.class:?]
	at cofh.core.network.PacketTile.handleClientSide(PacketTile.java:28) ~[PacketTile.class:?]
	at cofh.core.network.PacketHandler.decode(PacketHandler.java:98) ~[PacketHandler.class:?]
	at cofh.core.network.PacketHandler.decode(PacketHandler.java:40) ~[PacketHandler.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
	... 18 more
```

**Comment by KingLemming** [comment]
Okay well one thing, your mods are all terribly out of date. Please update them.
Secondly, you don't need lib as a separate jar.

Also, this is going to happen if you upgraded incorrectly and FML shredded your ID map. Were you using alphas we told you not to previously?

**Comment by Viper-7** [comment]
This is a new world created on these versions, no mod changes have been made since creating the world whatsoever, which is why the mods are "terribly out of date". The whole pack was updated 2 weeks ago, at which time the versions we're using were the latest available. We don't run a testing/development server, updates are usually handled monthly.

FYI, the problem seems to be an interaction with the itemduct and Player Interface block from Random Things, destroying this itemduct with mcedit resolved the problem for now, but it's still free to re-occur.

Last time I updated CoFH mods (from B8 to RC2) half the pack broke, so my first reaction is not to go through that again, nor to push for another world reset so soon. I'll stick to our usual monthly update cycle and let players know to avoid Itemducts where possible for the meantime.

This seemed an important bug to report, as it stalled the server without showing any error whatsoever, either pointing to CoFH or anyone else. People running their own servers that don't have the knowledge to pull down a region file and try it in single player or such would be experiencing this issue without a clue as to why, or any lead to search on. Especially bad when it occurs in an unmodified version of a highly popular and current pack like Resonant Rise 3.

**Comment by Viper-7** [comment]
Updated to TE4.0.0RC6-138 and tested in single player, the chunk can load, the itemduct has now disconnected itself from the player interface, and won't connect again, even with the target player online.

It's nice that itemducts no longer crash the server, but they still don't exactly seem to work properly.

Does this mean the Player Interface is still doing something wrong for handling itemducts? Other item transport systems seem to work fine.

I'd like to provide a "complete" fix for this issue, if that means taking this over to Random Things no worries, but it'd be nice to be able to provide a little information about what they're doing wrong to upset itemducts.

**Comment by KingLemming** [comment]
What do you mean "don't work properly?" You really need to be a bit more specific on that.

My guess is that the player interface doesn't present itself as an inventory unless the player is online, in which case the duct doesn't see as one and won't connect.

**Comment by Viper-7** [comment]
I mean "the itemduct has now disconnected itself from the player interface, and won't connect again, even with the target player online.", as I said.

**Comment by KingLemming** [comment]
Just tested with the Interface block. Seems to work fine. Not sure what happened, but seems this is sorted now.
