### ISSUE TITLE
[1.11.2] Crash on Batching Chunks

### ISSUE THREAD

**Issue by sueZtheGreat** [CoFH/Feedback#289]
Crash Report: [pastebin.com/Ry3i5ikN](pastebin.com/Ry3i5ikN) (You'll have to copy/paste this, idk how links work)

Details: When a chunk containing a Thermal Expansion machine and a Pam's Harvestcraft Presser tries to render it will crash the client.

Sets to Reproduce:
1. Start a world with the latest versions of Thermal Expansion and Pam's
2. Place a Redstone Furnace and a Presser in the same chunk
3. Run away until the chunk unloads
4. Run back to the machines until the chunk tries to load

Additional Info: I'll also be posting this crash report on the Pam's Harvestcraft GitHub

**Comment by KingLemming** [comment]
Yeah, that's most likely on Pam's.

**Comment by KingLemming** [comment]
Okay, so when I tried to replicate this and got the FULL crash log, I got the following:

`java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]
	at net.minecraft.util.Util.runTask(Util.java:27) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1046) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:372) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [MinecraftForge/:?]
	at GradleStart.main(GradleStart.java:26) [MinecraftForge/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.items.ItemStackHandler.deserializeNBT(ItemStackHandler.java:191) ~[ItemStackHandler.class:?]
	at com.pam.harvestcraft.tileentities.TileEntityPresser.readFromNBT(TileEntityPresser.java:41) ~[TileEntityPresser.class:?]
	at net.minecraft.tileentity.TileEntity.handleUpdateTag(TileEntity.java:333) ~[TileEntity.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:745) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.processPacket(SPacketChunkData.java:101) ~[SPacketChunkData.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.processPacket(SPacketChunkData.java:1) ~[SPacketChunkData.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at net.minecraft.util.Util.runTask(Util.java:26) ~[Util.class:?]
	... 20 more
[20:29:07] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:523]: ---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 6/26/17 8:29 PM
Description: Batching chunks

java.lang.NullPointerException: Batching chunks
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:94)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.renderBlock(CCBlockRendererDispatcher.java:60)
	at net.minecraft.client.renderer.chunk.RenderChunk.rebuildChunk(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(ChunkRenderWorker.java:122)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:50)
	at java.lang.Thread.run(Thread.java:745)`

which means it is 100% absolutely on Harvestcraft.

**Comment by Tora-B** [comment]
Because it's still 100% absolutely on Harvestcraft. Have you considered reporting the issue to them, since they're at fault?

**Comment by KingLemming** [comment]
Actually his issue was project red. He just decided to not read the crash report and then go pout and pretend that it was our fault and that I am a mean cruel person.

His crash report didn't even mention CoFH at all.

**Comment by sueZtheGreat** [comment]
The world in which I generated my crash report only had Thermal Expansion and Pam's Harvestcraft. I reported it to Pam's GitHub a year ago when it happened. I'm sure the versions have changed significantly since then. I don't believe you're a cruel or mean person KingLemming.

**Comment by KingLemming** [comment]
Oh nono, not you. :) The person who replied yesterday saying that this was still an issue.

Sorry for any confusion!

**Comment by bothie** [comment]
@sueZtheGreat: Please link your other bug report here.

Other reports I found on pam's harvestcraft project on github:

[DrGirlfriend on 26 Jul 2017](https://github.com/MatrexsVigil/harvestcraft/issues/2)
[Another report by MysticFlowP on 2 Aug 2017](https://github.com/MatrexsVigil/harvestcraft/issues/12)

@KingLemming: And please don't just assume, this bug is 100% on Pam's harvestcraft's end. It seems to be a relatively specific cross mod conflict, and that means, you are doing something strange too, and maybe it's actually your fault and your bug is only triggered in MatrexsVigil's code.

**Comment by covers1624** [comment]
No @bothie This IS a pams issue i submitted a PR to fix all the tiles pam had at the time, if she hasn't propogate that to new tiles thats pams issue.

**Comment by covers1624** [comment]
For reference: https://github.com/MatrexsVigil/harvestcraft/pull/30
