### ISSUE TITLE
Minecraft Crash

### ISSUE THREAD

**Issue by kremsy** [CoFH/Feedback#292]
I updated some modes icnlduing COHFCore, TE, TF and I can't start the server anymore, this is the crash (hope you can help me to fix this and get the server back running)

Log:

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 3/11/15 6:03 PM
Description: Exception in server tick loop

java.lang.RuntimeException: ambiguous recipe: [[1xtile.netherores.ore.0@0] -> [5xitem.coal@0]]
	at ic2.core.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:39)
	at powercrystals.netherores.ores.Ores.registerMacerator(Ores.java:295)
	at powercrystals.netherores.ores.Ores.registerPulverizing(Ores.java:265)
	at powercrystals.netherores.NetherOresCore.postInit(NetherOresCore.java:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.2.0-4-amd64
	Java Version: 1.7.0_75, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6586267808 bytes (6281 MB) / 8232894464 bytes (7851 MB) up to 8232894464 bytes (7851 MB)
	JVM Flags: 2 total; -Xmx8192M -Xms8192M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 21 mods loaded, 21 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	gregapi{GT6-MC1710} [Greg-API] (gregtech_1.7.10-6.00.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore{1.7.10R3.0.0RC5} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC5-207.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Core{6.4.1} [BuildCraft] (buildcraft-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Transport{6.4.1} [BC Transport] (buildcraft-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Silicon{6.4.1} [BC Silicon] (buildcraft-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Factory{6.4.1} [BC Factory] (buildcraft-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	additionalpipes{3.4} [Additional Pipes] (additionalpipes-4.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Builders{6.4.1} [BC Builders] (buildcraft-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Energy{6.4.1} [BC Energy] (buildcraft-6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IC2{2.2.691-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.691-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry_1.7.10-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalFoundation{1.7.10R1.0.0RC4} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC4-58.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalExpansion{1.7.10R4.0.0RC6} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC6-138.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	gregtech{GT6-MC1710} [GregTech] (gregtech_1.7.10-6.00.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC4-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	eureka{2.2} [Eureka] (Eureka-1.7.10-2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore: -[1.7.10]3.0.0RC5-207
	ThermalFoundation: -[1.7.10]1.0.0RC4-58
	ThermalExpansion: -[1.7.10]4.0.0RC6-138
	NetherOres: Lacking version information.
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by kremsy** [comment]
Found out after some Investigation that the Problem is an update of the GregTech mod, if I downgrade it to the version "6.00.13" everything is fine.

**Comment by StenchBag** [comment]
Still the case...

**Comment by skyboy** [comment]
@StenchBag And it continues to be a GregTech issue. Report it there.

**Comment by StenchBag** [comment]
I did and got temp banned + told it wasn't their bug

**Comment by skyboy** [comment]
Then I guess you need to remove GregTech.
