### ISSUE TITLE
Server crash on start

### ISSUE THREAD

**Issue by sanyashvets** [CoFH/Feedback#305]
Log:
[17:50:37] [main/INFO]: Forge Mod Loader version 7.10.85.1286 for Minecraft 1.7.10 loading
[17:50:37] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_31, running on Linux:amd64:3.2.0-4-amd64, installed at /usr/lib/jvm/java-8-oracle/jre
[17:50:37] [main/INFO]: [AppEng] Core Init
[17:50:38] [main/WARN]: The following coremods do not have a @MCVersion annotation. They may cause problems if this is not the correct version of Minecraft for them.
[17:50:38] [main/WARN]: Missing @MCVersion: buildcraftAdditions.preloader.BCALoadingPlugin  codechicken.core.launch.CodeChickenCorePlugin  cofh.asm.LoadingPlugin  ic2.core.coremod.IC2core  codechicken.nei.asm.NEICorePlugin  
[17:50:40] [main/INFO]: Loaded library ejml-0.23.jar.
[17:50:40] [main/INFO]: [cofh.asm.PCCAccessTransformer:readMappingFile:40]: Adding Accesstransformer map: CoFH_at.cfg
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/WorldServer
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getMethod0(Class.java:3010)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getMethod(Class.java:1776)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:123)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:25)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 6 more
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.WorldServer
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:144)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 13 more
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassFormatError: Duplicate method name&signature in class file net/minecraft/world/WorldServer
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:139)
[17:50:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 15 more

**Comment by sanyashvets** [comment]
Forgot:
mods: 
CoFHCORE RC7-277
Therm. Exp. RC7-141
Therm. Found. RC7-62

Client goin to crash on start too. It just closes the jawaw. process

**Comment by KingLemming** [comment]
We need a full log and modlist. You've likely downloaded something wrong.

**Comment by sanyashvets** [comment]
That was a full log.
Modlist: http://i.gyazo.com/b0b7bac5b314c410af2ccb4e701a02a3.png
(I downgrade to previuos version for a time)

**Comment by KingLemming** [comment]
This is definitely something on your end. What's Asyncworldinjector?

**Comment by sanyashvets** [comment]
https://github.com/SBPrime/AsyncWorldEdit/releases

feature for schematics from WorldEdit

**Comment by KingLemming** [comment]
You get the coveted wtf tag - we can't reproduce this at all.

**Comment by sanyashvets** [comment]
So, u cant do mod, which will be supported in all servers? :\
I have a friend with same error. His server works without AsyncWE..

**Comment by KingLemming** [comment]
It's a mod conflict, there doesn't seem to be a way around it.

**Comment by natedog1177** [comment]
I'm Having the same error loading the 1.1.1 version of the direwolf20 pack on my server.

**Comment by KingLemming** [comment]
Have you modified the pack at all?

**Comment by natedog1177** [comment]
No, but the issue isn't with the mod after a bit more work, it was with my version of forge i was trying to load it with (Cauldron)

**Comment by KingLemming** [comment]
@sanyashvets Are you using Cauldron?

**Comment by MrHelp** [comment]
yes. I'm too. use cauldron. http://pastebin.com/8bpaCyUS

**Comment by sanyashvets** [comment]
@KingLemming yes.

**Comment by KingLemming** [comment]
Sorry, but this is something with Cauldron. We can't officially support it since it's in a legal grey area. There are a lot of packs that don't have any issues. Try and figure out which version of Cauldron they use and go with that one.
