### ISSUE TITLE
Thermal Expansion / Ender IO server crash (1.7.10)

### ISSUE THREAD

**Issue by DJDaemonix** [CoFH/Feedback#31]
Hello,

I recently updated Ender IO for compatibility issues with MineFactory Reloaded, but i stumble across this crash after starting the server :

---- Minecraft Crash Report ----
// Why did you do that?

Time: 18/01/15 11:55
Description: Exception in server tick loop

java.lang.IncompatibleClassChangeError: Class thermalexpansion.block.cell.TileCell does not implement the requested interface cofh.api.energy.IEnergyReceiver
	at crazypants.enderio.power.EnergyReceiverPI.recieveEnergy(EnergyReceiverPI.java:66)
	at crazypants.enderio.conduit.power.NetworkPowerManager.doApplyRecievedPower(NetworkPowerManager.java:152)
	at crazypants.enderio.conduit.power.NetworkPowerManager$InnerTickHandler.tickEnd(NetworkPowerManager.java:539)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:47)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:35)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_112_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:722)

I can provide any information regarding the mod versions / modpack that includes both mods.

Regards,

**Comment by skyboy** [comment]
Update ThermalExpansion.
