### ISSUE TITLE
Thermal Expansion - Fluid Transposer - NPE

### ISSUE THREAD

**Issue by Slind14** [CoFH/Feedback#311]
Reproduction: extra utils bedrockium drum inside a fluid transposer set to fill

	java.lang.NullPointerException: Ticking block entity
		at cofh.thermalexpansion.block.machine.TileTransposer.updateContainerFill(TileTransposer.java:417)
		at cofh.thermalexpansion.block.machine.TileTransposer.processContainerItem(TileTransposer.java:342)
		at cofh.thermalexpansion.block.machine.TileTransposer.func_145845_h(TileTransposer.java:103)
		at net.minecraft.world.World.func_72939_s(World.java:2491)
		at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
		at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
		at java.lang.Thread.run(Thread.java:745)

**Version**
TE: 4.0.0RC2-129
extra util's: 1.2.2

**Comment by KingLemming** [comment]
Ridiculously out of date. Please update your mods.
