### ISSUE TITLE
[CRASH] 1.11.2 Render Item Crash in Inventory (Thermal Dynamics / Expansion / Code Chicken Lib)

### ISSUE THREAD

**Issue by Cakx** [CoFH/Feedback#316]
## net.minecraft.util.ReportedException: Rendering item

CodeChickenLib-1.11.2-3.0.0.274
CoFHCore-1.11.2-4.2.5.11
ThermalDynamics-1.11.2-2.2.4.7
ThermalExpansion-1.11.2-5.2.4.8
ThermalFoundation-1.11.2-2.2.4.8

It seems that the new inventory item rendering functions used in thermal dynamics and thermal expansion are broken. So it could probably also be the CodeChickenLib that has an issue. 

As soon as i open an inventory tab (cretativ tab or JEI page) containing some thermal dynamic or thermal expansion items, the game crashes. 

**Tested with Thermal Foundation only:**

-- Head --
Thread: Client thread
Stacktrace:
	at cofh.thermalexpansion.render.**RenderStrongbox**.getTransforms(RenderStrongbox.java)
	at codechicken.lib.render.item.IItemRenderer.handlePerspective(IItemRenderer.java:44)
	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:439)
	at codechicken.lib.render.item.CCRenderItem.handleTransforms(CCRenderItem.java:101)
	at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:153)

**Tested with Thermal Dynamics only:**

-- Head --
Thread: Client thread
Stacktrace:
	at cofh.thermaldynamics.render.item.**RenderItemCover**.getTransforms(RenderItemCover.java)
	at codechicken.lib.render.item.IItemRenderer.handlePerspective(IItemRenderer.java:44)
	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:439)
	at codechicken.lib.render.item.CCRenderItem.handleTransforms(CCRenderItem.java:101)
	at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:153)

[FullCrashlog-WithDynamicsAndExpansion.txt](https://github.com/CoFH/Feedback/files/1113855/FullCrashlog-WithDynamicsAndExpansion.txt)

I guess it comes from the code chicken lib but im posting this here since you are utilizing it.

**Comment by covers1624** [comment]
Update your mods.. -_-

**Comment by KingLemming** [comment]
You didn't update Thermal Expansion OR Dynamics.

**Comment by Cakx** [comment]
Sorry for stealing your time guys - my browser tabs where some hours old. While the download buttons already said 'updated 2 hours ago' it still linked me to the 4 day old versions.

**Comment by KingLemming** [comment]
No worries, happens!
