### ISSUE TITLE
Inconsistent Client Crash - Possible Incompatibility with Extreme Reactors

### ISSUE THREAD

**Issue by arakielG** [CoFH/Feedback#331]
Should have mentioned that this is on 1.11.2 using Forge 13.20.1.2388

This doesn't happen every time.  But has happened 3 out of the last 4 client launches:

Possibly a race condition during post?  Dunno, I'm not an expert but felt you folks should be aware.
Log attached but also C/Ping the top stack:

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)
Caused by: java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class cofh.thermalexpansion.util.managers.machine.FurnaceManager$ComparableItemStackFurnace id= 446412061 hashCode= 380043264 toString= cofh.thermalexpansion.util.managers.machine.FurnaceManager$ComparableItemStackFurnace@446412061{m:0, i:erogenousbeef.bigreactors.common.block.BlockBROre$ItemBlockOre@756260771, v:5799}; object #2 =class cofh.thermalexpansion.util.managers.machine.FurnaceManager$ComparableItemStackFurnace id= 2138374078 hashCode= 1516 toString= cofh.thermalexpansion.util.managers.machine.FurnaceManager$ComparableItemStackFurnace@2138374078{m:0, i:erogenousbeef.bigreactors.common.block.BlockBROre$ItemBlockOre@756260771, v:5799}

	at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
	at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:448)
	at gnu.trove.map.hash.THashMap.rehash(THashMap.java:403)
	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:388)
	at gnu.trove.map.hash.THashMap.doPut(THashMap.java:178)
	at gnu.trove.map.hash.THashMap.put(THashMap.java:145)
	at cofh.thermalexpansion.util.managers.machine.FurnaceManager.addRecipe(FurnaceManager.java:328)
	at cofh.thermalexpansion.util.managers.machine.FurnaceManager.loadRecipes(FurnaceManager.java:279)
	at cofh.thermalexpansion.util.managers.machine.FurnaceManager.initialize(FurnaceManager.java:230)
	at cofh.thermalexpansion.ThermalExpansion.managerInitialize(ThermalExpansion.java:166)
	at cofh.thermalexpansion.ThermalExpansion.postInit(ThermalExpansion.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[crash-2017-07-01_16.53.34-client.txt](https://github.com/CoFH/Feedback/files/1117414/crash-2017-07-01_16.53.34-client.txt)

**Comment by KingLemming** [comment]
This happens when a mod is doing improper oredict registration. it shuffles around because apparently load order is somewhat random. Extreme Reactors probably isn't the cause, but some other party which cross-registers.
