### ISSUE TITLE
Thermal Dynamics cast block air issue

### ISSUE THREAD

**Issue by jznomoney** [CoFH/Feedback#350]
I am having an issue with Thermal Dynamics crashing.  I started a new map a few days ago.  There is not much in it but a stock furnace crafting table and some wheat growing.  I updated some mods for compatibility.  AE2 Mekanism.  I was using the latest release of COFHMods from your side dated 3/14 and it crashed with this error.

net.minecraft.block.BlockAir cannot be cast to cofh.thermaldynamics.duct.BlockDuct

http://pastebin.com/a7VZ9FG1

I updated your mods to the latest beta builds on curse same crash appears.  If I start a brand new map it loads up fine.  This is the server crashing not the client.

**Comment by KingLemming** [comment]
This is some sort of strange ASM that we aren't invoking. Send this over to the Logistics Pipes guys please.

**Comment by davboecki** [comment]
I don't think that this is caused by LP [It could and I will still look into it]. The only thing that get's modified trough ASM in that class is the getAdjTileEntitySafe method. The reason the ```[LP|ASM]``` appears in the log is because LP automaticly marks every class it modifies with that prefix to the sourcefile so in case it causees an error it is visible that we are involved.
This looks more like a case of an orphan time entity to me.

**Comment by vadimyer** [comment]
@KingLemming this is surely not any other mod's issue. My crash is almost the same:

```
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to cofh.thermaldynamics.duct.BlockDuct
	at cofh.thermaldynamics.block.TileTDBase.getDuctType(TileTDBase.java:758)
	at cofh.thermaldynamics.duct.item.TileItemDuct.getWeight(TileItemDuct.java:230)
	at cofh.thermaldynamics.multiblock.Route.<init>(Route.java:33)
	at cofh.thermaldynamics.multiblock.RouteCache.moveForwards(RouteCache.java:136)
	at cofh.thermaldynamics.multiblock.RouteCache.processStep(RouteCache.java:73)
	at cofh.thermaldynamics.multiblock.MultiBlockGridWithRoutes.doTickProcessing(MultiBlockGridWithRoutes.java:20)
	at cofh.thermaldynamics.core.WorldGridList.tickEnd(WorldGridList.java:73)
	at cofh.thermaldynamics.core.TickHandler.tick(TickHandler.java:95)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_273_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:996)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
	at java.lang.Thread.run(Thread.java:745)
```
