### ISSUE TITLE
ItemBlockRockwool.getUnlocalizedName() crashes with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by multiplemonomials** [CoFH/Feedback#36]
Hi.  I'm writing a mod that, during its init process (which is started in a separate thread by an OnWorldLoadEvent) calls the getUnlocalizedName() method on every item in the game.  I've noticed that when Thermal Expansion is installed, ItemBlockRockwool.getUnlocalizedName() crashes during this init process, and I wanted to let you guys know about this problem. As far as I can tell, this has been an issue since at least the early 1.7.10 builds of TE.  Here's the full stack trace:
```
[20:47:45] [EE3 - DynEmc Init Thread/ERROR] [Equivalent Exchange Reborn]: Um, the EER DynEMC system failed to initialize.  Uh-oh.
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: -32752
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at thermalexpansion.block.simple.ItemBlockRockwool.func_77667_c(ItemBlockRockwool.java:28)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.multiplemonomials.eer.exchange.WrappedStack.hashCode(WrappedStack.java:322)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.AbstractList.hashCode(AbstractList.java:541)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.HashMap.hash(HashMap.java:338)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.HashMap.put(HashMap.java:611)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.HashSet.add(HashSet.java:219)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.collect.AbstractMapBasedMultimap.put(AbstractMapBasedMultimap.java:195)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.collect.AbstractSetMultimap.put(AbstractSetMultimap.java:121)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.collect.HashMultimap.put(HashMultimap.java:49)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.multiplemonomials.eer.recipe.RecipesVanilla.init(RecipesVanilla.java:52)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.multiplemonomials.eer.recipe.RecipesVanilla.getVanillaRecipes(RecipesVanilla.java:26)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.multiplemonomials.eer.recipe.RecipeRegistry.init(RecipeRegistry.java:40)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.multiplemonomials.eer.recipe.RecipeRegistry.<init>(RecipeRegistry.java:24)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.multiplemonomials.eer.recipe.RecipeRegistry.getInstance(RecipeRegistry.java:31)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.multiplemonomials.eer.exchange.EnergyRegistry.computeStackMappings(EnergyRegistry.java:236)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.multiplemonomials.eer.exchange.EnergyRegistry.init(EnergyRegistry.java:146)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.multiplemonomials.eer.exchange.EnergyRegistry.getInstance(EnergyRegistry.java:56)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.multiplemonomials.eer.util.EmcInitializationHelper.run(EmcInitializationHelper.java:27)
[20:47:45] [EE3 - DynEmc Init Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
```
`WrappedStack.java:322` is a call to ItemStack.getUnlocalizedName().  Thanks for your assistance.

**Comment by KingLemming** [comment]
Okay...why are you sending it that Item Index? We certainly don't do that.

**Comment by multiplemonomials** [comment]
Okay, I figured it out.  It turns out that Pahimar's EMC registry code was making the mistake of treating items with Integer.MAX_VALUE wildcard metadatas in recipies as regular items and doing things with them, causing getUnlocalizedName() to be called on an item with an invalid metadata.

 So, it's mostly my/his bug, but you really should put bounds checking in that function.  Thanks.
