### ISSUE TITLE
Crash on start. Anyway to disable the item? 

### ISSUE THREAD

**Issue by Shybella** [CoFH/Feedback#363]
java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to cofh.thermaldynamics.block.BlockDuct
	at cofh.thermaldynamics.block.TileMultiBlock.getDuctType(TileMultiBlock.java:701)
	at cofh.thermaldynamics.ducts.energy.TileEnergyDuctSuperConductor.getNewGrid(TileEnergyDuctSuperConductor.java:21)
	at cofh.thermaldynamics.multiblock.MultiBlockFormer.formGrid(MultiBlockFormer.java:14)
	at cofh.thermaldynamics.block.TileMultiBlock.formGrid(TileMultiBlock.java:572)
	at cofh.thermaldynamics.block.TileMultiBlock.tickMultiBlock(TileMultiBlock.java:560)
	at cofh.thermaldynamics.core.WorldGridList.tickEnd(WorldGridList.java:82)
	at cofh.thermaldynamics.core.TickHandler.tick(TickHandler.java:76)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_649_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

**Comment by KingLemming** [comment]
Please check the readme and provide a full modlist. This isn't very helpful as it stands.

**Comment by skyboy** [comment]
Closing due to lack of response and apparent duplication of other reports.
