### ISSUE TITLE
[Thermal expansion] World not load

### ISSUE THREAD

**Issue by DrummerMC** [CoFH/Feedback#414]
log:

```
[19:01:07] [Server thread/ERROR] [FML/]: 
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	FML{7.10.107.1365} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forge{10.13.3.1365} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	appliedenergistics2-core{rv2-beta-28} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	NotEnoughItems{1.0.4.95} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.95-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	OpenModsCore{0.7} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	appliedenergistics2{rv2-beta-28} [Applied Energistics 2] (appliedenergistics2-rv2-beta-28 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	bdlib{1.7.0.70} [BD Lib] (bdlib-mc1710-1.7.0.70.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ae2stuff{0.1.7.17} [AE2 Stuff] (ae2stuff-mc1710-0.1.7.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft[v1.10.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AWWayofTime{v1.3.1} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Botania{r1.6-174} [Botania] (Botania r1.6-174.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CoFHCore{1.7.10R3.0.0} [CoFH Core] (CoFHCore-[1.7.10]3.0.0-252.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ProjRed|Core{4.5.15.75} [ProjectRed] (ProjectRed-1.7.10-4.5.15.75-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ProjRed|Transmission{4.5.15.75} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.15.75-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CompactMachines{1.7.10-1.18} [Compact Machines] (compactmachines-1.7.10-1.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	EnderIO{1.7.10-2.2.8.367} [Ender IO] (EnderIO-1.7.10-2.2.8.367.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ThermalExpansion{1.7.10R4.0.0} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0-176.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Errored->Errored
	EnderTech{1.7.10-0.3.2.375} [EnderTech] (EnderTech-1.7.10-0.3.2.375.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ExtraUtilities{1.2.4a} [Extra Utilities] (extrautilities-1.2.4a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forestry{3.5.3.11} [Forestry for Minecraft] (forestry_1.7.10-3.5.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	NedeloskCore{1.0a} [NedeloskCore] (Forest-Day-1.4.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forestday{1.4.0a} [Forest Day] (Forest-Day-1.4.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	HardcoreQuesting{The Journey (4.2.1)} [Hardcore Questing Mode] (HQM-The Journey (4.2.1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	TConstruct{1.7.10-1.8.3.build919} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Mariculture{1.7.10-1.2.4.1a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.1a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.1a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MineTweaker3{3.0.9} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	modtweaker2{0.7} [Mod Tweaker 2] (ModTweaker 2-0.7.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	NEIAddons{1.12.5.17} [NEI Addons] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	NEIAddons|Botany{1.12.5.17} [NEI Addons: Botany] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	NEIAddons|Forestry{1.12.5.17} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	NEIAddons|CraftingTables{1.12.5.17} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	NEIAddons|ExNihilo{1.12.5.17} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	neiintegration{1.0.7} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	recipemod{0.2} [NoMoreRecipeConflict] (No-More-Recipe-Conflict-0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	OpenMods{0.7} [OpenMods] (OpenModsLib-1.7.10-0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	OpenBlocks{1.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10h.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ProjRed|Compatibility{4.5.15.75} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.15.75-Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ProjRed|Integration{4.5.15.75} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.15.75-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ProjRed|Illumination{4.5.15.75} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.15.75-Lighting.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	RedstoneArsenal{1.7.10R1.1.0RC7} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC7-74.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	simplyjetpacks{1.4.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	SpiceOfLife{1.2.3} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	StorageDrawers{1.7.10-1.3.7} [Storage Drawers] (StorageDrawers-1.7.10-1.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ThermalDynamics{1.7.10R1.0.0RC8} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0RC8-116.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	IguanaTweaksTConstruct{1.7.10-2.1.4.132} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[19:01:07] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[19:01:07] [Server thread/ERROR] [FML/]: Caught exception from ThermalExpansion
java.lang.NullPointerException
	at net.minecraftforge.fluids.FluidRegistry.getFluidID(FluidRegistry.java:118) ~[FluidRegistry.class:?]
	at net.minecraftforge.fluids.FluidStack.getFluidID(FluidStack.java:112) ~[FluidStack.class:?]
	at cofh.thermalexpansion.util.crafting.TransposerManager.getFillRecipe(TransposerManager.java:41) ~[TransposerManager.class:?]
	at cofh.thermalexpansion.util.crafting.TransposerManager.fillRecipeExists(TransposerManager.java:51) ~[TransposerManager.class:?]
	at cofh.thermalexpansion.util.crafting.TransposerManager.addFillRecipe(TransposerManager.java:195) ~[TransposerManager.class:?]
	at cofh.thermalexpansion.util.crafting.TransposerManager.addFillRecipe(TransposerManager.java:241) ~[TransposerManager.class:?]
	at cofh.thermalexpansion.util.crafting.TransposerManager.loadRecipes(TransposerManager.java:118) ~[TransposerManager.class:?]
	at cofh.thermalexpansion.ThermalExpansion.loadComplete(ThermalExpansion.java:199) ~[ThermalExpansion.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[modpack.jar:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:696) ~[Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:296) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) ~[minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.11.jar:?]
[19:01:07] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server about to start event
java.lang.NullPointerException
	at net.minecraftforge.fluids.FluidRegistry.getFluidID(FluidRegistry.java:118) ~[FluidRegistry.class:?]
	at net.minecraftforge.fluids.FluidStack.getFluidID(FluidStack.java:112) ~[FluidStack.class:?]
	at cofh.thermalexpansion.util.crafting.TransposerManager.getFillRecipe(TransposerManager.java:41) ~[TransposerManager.class:?]
	at cofh.thermalexpansion.util.crafting.TransposerManager.fillRecipeExists(TransposerManager.java:51) ~[TransposerManager.class:?]
	at cofh.thermalexpansion.util.crafting.TransposerManager.addFillRecipe(TransposerManager.java:195) ~[TransposerManager.class:?]
	at cofh.thermalexpansion.util.crafting.TransposerManager.addFillRecipe(TransposerManager.java:241) ~[TransposerManager.class:?]
	at cofh.thermalexpansion.util.crafting.TransposerManager.loadRecipes(TransposerManager.java:118) ~[TransposerManager.class:?]
	at cofh.thermalexpansion.ThermalExpansion.loadComplete(ThermalExpansion.java:199) ~[ThermalExpansion.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[modpack.jar:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~
[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:696) ~[Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:296) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) ~[minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.11.jar:?]
```

**Comment by KingLemming** [comment]
You have a mod handling Fluids badly, but it isn't us. Look at all of the duplicate warnings that Forge is spitting. Sorry.

**Comment by bigbantha** [comment]
Had this same problem. I found that removing ExtraCells fixed it

**Comment by DrummerMC** [comment]
If ec is installed, some other mods load in another order. ec only read fluids from the fluid registy.

**Comment by Jules06** [comment]
Hi, I've got the same problem but I can't find the mod that's causing liquid problems 
modlist : http://puu.sh/hdZoi/c5630aca0d.png

I hope someone can help
Thanks
