### ISSUE TITLE
ASM transformer class null launching server

### ISSUE THREAD

**Issue by Johnne25** [CoFH/Feedback#423]
Updating to CoFHCore-[1.7.10]3.0.1-254 displays

"A critical problem occurred registering the ASM transformer class null
java.lang.NullPointerException"

Error in console.  The error is up near the top of the console and the server still launches.

Using CoFHCore-[1.7.10]3.0.0RC7-211 does not display this error in the console.

Here is the complete error message:
[08:46:35] [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class null
java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:105) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.11.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:101) [forgeMod.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forgeMod.jar:?]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forgeMod.jar:?]

**Comment by KingLemming** [comment]
Fixed in dev, but this doesn't actually hurt anything.

**Comment by Johnne25** [comment]
Thanks.
