### ISSUE TITLE
World not loading with thermal expansion

### ISSUE THREAD

**Issue by ShadowHawk07** [CoFH/Feedback#436]
Whenever I try to load a world with Thermal expansion it just goes back to the main menu and errors. If I remove Thermal expansion but keep foundation and dynamics and every other mod in it loads fine.

Actual error (full logs at bottom):
[17:47:55] [Server thread/ERROR] [FML/]: Caught exception from ThermalExpansion
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(Unknown Source) ~[?:1.8.0_31]
	at cofh.lib.util.helpers.StringHelper.titleCase(StringHelper.java:57) ~[StringHelper.class:?]
	at cofh.thermalexpansion.util.crafting.TECraftingHandler.loadRecipes(TECraftingHandler.java:126) ~[TECraftingHandler.class:?]
	at cofh.thermalexpansion.ThermalExpansion.loadComplete(ThermalExpansion.java:195) ~[ThermalExpansion.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:531) ~[forge-1.7.10-10.13.3.1373-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:696) ~[Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:299) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) ~[1.7.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) ~[OneSixLauncher.class:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) ~[OneSixLauncher.class:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) ~[EntryPoint.class:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) ~[EntryPoint.class:?]
[17:47:55] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server about to start event
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(Unknown Source) ~[?:1.8.0_31]
	at cofh.lib.util.helpers.StringHelper.titleCase(StringHelper.java:57) ~[StringHelper.class:?]
	at cofh.thermalexpansion.util.crafting.TECraftingHandler.loadRecipes(TECraftingHandler.java:126) ~[TECraftingHandler.class:?]
	at cofh.thermalexpansion.ThermalExpansion.loadComplete(ThermalExpansion.java:195) ~[ThermalExpansion.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:531) ~[forge-1.7.10-10.13.3.1373-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:696) ~[Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:299) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) ~[1.7.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) ~[OneSixLauncher.class:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) ~[OneSixLauncher.class:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) ~[EntryPoint.class:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) ~[EntryPoint.class:?]

Full Log http://paste.ee/p/xghyw

**Comment by BoboSims** [comment]
Not sure if it means anything, but this error occurs at line 23220. The *actual* 'fatal error' after which the game cannot continue, seems to occur at line 23100. I see no TE reference there anywhere.

**Comment by KingLemming** [comment]
The issue is TropiCraft. They know about it and are fixing it.
