### ISSUE TITLE
[1.7.10] AIOOBE due condensation to solid glowstone on microblocks

### ISSUE THREAD

**Issue by Ghostlyr** [CoFH/Feedback#438]
Glowstone fluid + condense + forge multipart causes sometime crash. Tested on flares chisel 2, where it is also used.

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at codechicken.lib.vec.BlockCoord.offset(BlockCoord.java:139)
	at codechicken.lib.vec.BlockCoord.offset(BlockCoord.java:134)
	at codechicken.multipart.minecraft.McSidedMetaPart.canStay(McSidedMetaPart.java:32)
	at codechicken.multipart.minecraft.TorchPart.canStay(TorchPart.java:72)
	at codechicken.multipart.minecraft.McSidedMetaPart.dropIfCantStay(McSidedMetaPart.java:38)
	at codechicken.multipart.minecraft.McSidedMetaPart.onNeighborChanged(McSidedMetaPart.java:27)
	at codechicken.multipart.TileMultipart$$anonfun$onNeighborBlockChange$1.apply(TileMultipart.scala:167)
	at codechicken.multipart.TileMultipart$$anonfun$onNeighborBlockChange$1.apply(TileMultipart.scala:167)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:76)
	at codechicken.multipart.TileMultipart.onNeighborBlockChange(TileMultipart.scala:167)
	at codechicken.multipart.BlockMultipart.func_149695_a(BlockMultipart.scala:86)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:648)
	at net.minecraft.world.World.func_147444_c(World.java:613)
	at net.minecraft.world.World.func_72921_c(World.java:553)
	at net.minecraftforge.fluids.BlockFluidClassic.func_149674_a(BlockFluidClassic.java:124)
	at cofh.thermalfoundation.fluid.BlockFluidGlowstone.func_149674_a(BlockFluidGlowstone.java:149)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:550)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:181)
	at WorldServerOF.func_72835_b(WorldServerOF.java:234)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

CoFHCore-[1.7.10]3.1.4-329
ThermalFoundation-[1.7.10]1.2.6-118
ThermalExpansion-[1.7.10]4.1.5-248
ForgeMultipart-1.7.10-1.2.0.347
Forge 1614

**Comment by KingLemming** [comment]
Not us actually. Put that on the FMP issue tracker.

**Comment by KingLemming** [comment]
Oh wait, also for an outdated unsupported version. I doubt you'll get any help there, sorry.

**Comment by covers1624** [comment]
Yeah, FMP isn't maintained for 1.7 anymore either.
