### ISSUE TITLE
Can't load world with forge 10.13.3.1374

### ISSUE THREAD

**Issue by Wykks** [CoFH/Feedback#445]
CoFHCore-[1.7.10]3.0.2-262
CoFHLib-[1.7.10]1.0.1-151
ThermalExpansion-[1.7.10]4.0.0-176
ThermalFoundation-[1.7.10]1.0.0-81

        [B#283] 2015/04/18 16:01:26 [INFOS]  [16:01:26] [Server thread/ERROR] [FML]: The following problems were captured during this phase
        [B#283] 2015/04/18 16:01:26 [INFOS]  [16:01:26] [Server thread/ERROR] [FML]: Caught exception from ThermalExpansion
        [B#283] 2015/04/18 16:01:26 [INFOS]  java.lang.NullPointerException
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraftforge.fluids.FluidRegistry.getFluidID(FluidRegistry.java:188) ~[FluidRegistry.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraftforge.fluids.FluidStack.getFluidID(FluidStack.java:113) ~[FluidStack.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cofh.thermalexpansion.util.crafting.TransposerManager.getFillRecipe(TransposerManager.java:41) ~[TransposerManager.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cofh.thermalexpansion.util.crafting.TransposerManager.fillRecipeExists(TransposerManager.java:51) ~[TransposerManager.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cofh.thermalexpansion.util.crafting.TransposerManager.addFillRecipe(TransposerManager.java:195) ~[TransposerManager.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cofh.thermalexpansion.util.crafting.TransposerManager.addFillRecipe(TransposerManager.java:241) ~[TransposerManager.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cofh.thermalexpansion.util.crafting.TransposerManager.loadRecipes(TransposerManager.java:118) ~[TransposerManager.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cofh.thermalexpansion.ThermalExpansion.loadComplete(ThermalExpansion.java:199) ~[ThermalExpansion.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:531) ~[modpack.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:696) ~[Loader.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:299) ~[FMLClientHandler.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) ~[bao.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) ~[bao.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraft.client.main.Main.main(SourceFile:148) ~[minecraft.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.11.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.11.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  [16:01:26] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
        [B#283] 2015/04/18 16:01:26 [INFOS]  java.lang.NullPointerException
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraftforge.fluids.FluidRegistry.getFluidID(FluidRegistry.java:188) ~[FluidRegistry.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraftforge.fluids.FluidStack.getFluidID(FluidStack.java:113) ~[FluidStack.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cofh.thermalexpansion.util.crafting.TransposerManager.getFillRecipe(TransposerManager.java:41) ~[TransposerManager.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cofh.thermalexpansion.util.crafting.TransposerManager.fillRecipeExists(TransposerManager.java:51) ~[TransposerManager.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cofh.thermalexpansion.util.crafting.TransposerManager.addFillRecipe(TransposerManager.java:195) ~[TransposerManager.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cofh.thermalexpansion.util.crafting.TransposerManager.addFillRecipe(TransposerManager.java:241) ~[TransposerManager.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cofh.thermalexpansion.util.crafting.TransposerManager.loadRecipes(TransposerManager.java:118) ~[TransposerManager.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cofh.thermalexpansion.ThermalExpansion.loadComplete(ThermalExpansion.java:199) ~[ThermalExpansion.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:531) ~[modpack.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:696) ~[Loader.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:299) ~[FMLClientHandler.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) ~[bao.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) ~[bao.class:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraft.client.main.Main.main(SourceFile:148) ~[minecraft.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.11.jar:?]
        [B#283] 2015/04/18 16:01:26 [INFOS]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.11.jar:?]

**Comment by Wykks** [comment]
Nevermind seem to be fixed in ThermalExpansion-[1.7.10]4.0.1-182
