### ISSUE TITLE
Ticking block entity - Server crash on startup

### ISSUE THREAD

**Issue by UnstableZer0** [CoFH/Feedback#461]
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 4/24/15 9:43 AM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:29)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59)
	at cofh.thermaldynamics.duct.fluid.TileFluidDuct.<init>(TileFluidDuct.java:42)
	at cofh.thermaldynamics.duct.fluid.TileFluidDuctFragile.<init>(TileFluidDuctFragile.java:39)
	at cofh.thermaldynamics.duct.DuctFactory$8.createTileEntity(DuctFactory.java:85)
	at cofh.thermaldynamics.duct.BlockDuct.func_149915_a(BlockDuct.java:92)
	at cofh.core.block.BlockCoFHBase.createTileEntity(BlockCoFHBase.java:63)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:951)
	at net.minecraft.world.World.func_147438_o(World.java:3119)
	at cofh.lib.util.helpers.BlockHelper.getAdjacentTileEntity(BlockHelper.java:298)
	at cofh.lib.util.helpers.BlockHelper.getAdjacentTileEntity(BlockHelper.java:313)
	at cofh.lib.util.helpers.FluidHelper.insertFluidIntoAdjacentFluidHandler(FluidHelper.java:98)
	at cofh.thermalexpansion.block.machine.TileAccumulator.transferFluid(TileAccumulator.java:186)
	at cofh.thermalexpansion.block.machine.TileAccumulator.func_145845_h(TileAccumulator.java:107)
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:29)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59)
	at cofh.thermaldynamics.duct.fluid.TileFluidDuct.<init>(TileFluidDuct.java:42)
	at cofh.thermaldynamics.duct.fluid.TileFluidDuctFragile.<init>(TileFluidDuctFragile.java:39)
	at cofh.thermaldynamics.duct.DuctFactory$8.createTileEntity(DuctFactory.java:85)
	at cofh.thermaldynamics.duct.BlockDuct.func_149915_a(BlockDuct.java:92)
	at cofh.core.block.BlockCoFHBase.createTileEntity(BlockCoFHBase.java:63)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:951)
	at net.minecraft.world.World.func_147438_o(World.java:3119)
	at cofh.lib.util.helpers.BlockHelper.getAdjacentTileEntity(BlockHelper.java:298)
	at cofh.lib.util.helpers.BlockHelper.getAdjacentTileEntity(BlockHelper.java:313)
	at cofh.lib.util.helpers.FluidHelper.insertFluidIntoAdjacentFluidHandler(FluidHelper.java:98)
	at cofh.thermalexpansion.block.machine.TileAccumulator.transferFluid(TileAccumulator.java:186)
	at cofh.thermalexpansion.block.machine.TileAccumulator.func_145845_h(TileAccumulator.java:107)

-- Block entity being ticked --
Details:
	Name: thermalexpansion.Accumulator // cofh.thermalexpansion.block.machine.TileAccumulator
	Block type: ID #2303 (tile.thermalexpansion.machine // cofh.thermalexpansion.block.machine.BlockMachine)
	Block data value: 8 / 0x8 / 0b1000
	Block location: World: (-607,68,-1374), Chunk: (at 1,4,2 in -38,-86; contains blocks -608,0,-1376 to -593,255,-1361), Region: (-2,-3; contains chunks -64,-96 to -33,-65, blocks -1024,0,-1536 to -513,255,-1025)
	Actual block type: ID #2303 (tile.thermalexpansion.machine // cofh.thermalexpansion.block.machine.BlockMachine)
	Actual block data value: 8 / 0x8 / 0b1000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 675 Drop: 0
	Level seed: -3544314452580526858
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-779,71,55), Chunk: (at 5,4,7 in -49,3; contains blocks -784,0,48 to -769,255,63), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 53909272 game time, 55690238 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 122664 (now: false), thunder time: 63242 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

It gave me an error before saying block XXX (fluiduct) at position xx, xx, xx ... 

i disabled and then enabled thermal dynamics to get rid of the blocks and now this(crashlog above).  

running latest FTB Infinity (1.4.1) 
thermal dynamics version: ThermalDynamics-[1.7.10]1.0.0RC8-105

**Comment by KingLemming** [comment]
So you updated Forge but not anything else?

TD is out of date.

**Comment by UnstableZer0** [comment]
i had to update forge because of cauldron and its builds which aren't available. 
i blame FTB.

**Comment by KingLemming** [comment]
Either way, the new TD is updated for the newer Forges, but that version isn't. That's the issue.
