### ISSUE TITLE
Player disconnected with NullPointerException when Tesseract is clicked

### ISSUE THREAD

**Issue by ams2990** [CoFH/Feedback#464]
When a player clicks on a Tesseract while holding a Resonant Energy Cell, the following exception is thrown and the player is disconnected. It seems relatively reproducible as it happened several times. 

	[03:31:18 WARN]: Failed to handle packet for /91.119.211.97:63849
	java.lang.NullPointerException
			at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:926) ~[nh.class:?]
			at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
			at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
			at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
			at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
			at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
			at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
			at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
			at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
			at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
	[03:31:18 INFO]: Hidri lost connection: Internal server error
	[03:31:18 INFO]: Hidri left the game.

I am using Cauldron build 1343, CofHCore 3.0.2-262, ThermalFoundation 1.0.0-81, and ThermalExpansion 4.0.1-182. My full list of mods at the time of the error is [here](http://pastebin.com/raw.php?i=zPmVZthH).

**Comment by KingLemming** [comment]
Oh boy. Cauldron.

**Comment by KingLemming** [comment]
Sorry, after looking into it more, this can't be reproduced in any way on Forge installs, and we don't officially support Cauldron. Please mention it to them.
