### ISSUE TITLE
Using EnderIO's wrench to remove an item conduit that is next to an itemduct

### ISSUE THREAD

**Issue by Arkyo** [CoFH/Feedback#479]
`Description: Unexpected error
[crash-2017-08-19_12.17.43-client.txt](https://github.com/CoFH/Feedback/files/1236052/crash-2017-08-19_12.17.43-client.txt)
[crash-2017-08-18_15.37.01-client.txt](https://github.com/CoFH/Feedback/files/1236053/crash-2017-08-18_15.37.01-client.txt)

java.lang.NullPointerException: Unexpected error
	at cofh.lib.util.helpers.WrenchHelper.isHoldingUsableWrench(WrenchHelper.java:29)
	at cofh.thermaldynamics.duct.tiles.TileGrid.shouldRenderCustomHitBox(TileGrid.java:964)
	at cofh.thermaldynamics.block.BlockDuct.onBlockHighlight(BlockDuct.java:442)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1297_BlockDuct_onBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1329)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cofh.lib.util.helpers.WrenchHelper.isHoldingUsableWrench(WrenchHelper.java:29)
	at cofh.thermaldynamics.duct.tiles.TileGrid.shouldRenderCustomHitBox(TileGrid.java:964)
	at cofh.thermaldynamics.block.BlockDuct.onBlockHighlight(BlockDuct.java:442)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1297_BlockDuct_onBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1329)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)`

**Comment by KingLemming** [comment]
Interesting, but unsure if it'll get fixed tbh. EnderIO isn't on 1.12.

**Comment by Arkyo** [comment]
I am sorry but this is 1.10.2

Is it end of support already? :(

**Comment by KingLemming** [comment]
Yes. Please move to 1.12 - it's the next 1.7.10 and people need to migrate.

**Comment by KingLemming** [comment]
Mojang bug. RayTraceResults are always explicitly not null, but this can only happen if one is null.

Mojang screwed up.

**Comment by KingLemming** [comment]
Having said that, I have a mitigation for it.
