### ISSUE TITLE
[bug] ThermalDynamics conduits missing cast check

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#480]
When moving a conduit via [at least] the ProjectRed relocation mod, the game will crash from a failed cast. Has been mirrored to P.R. devs, but have not tested with other frame mods yet. Regardless, there should be a check present to ensure the cast is successful, there could be many other cases that will trigger it to not succeed.

Stacktrace:
	at cofh.thermaldynamics.block.TileTDBase.getDuctType(TileTDBase.java:734)
	at cofh.thermaldynamics.duct.energy.TileEnergyDuct.isConnectable(TileEnergyDuct.java:69)
	at cofh.thermaldynamics.block.TileTDBase.handleSideUpdate(TileTDBase.java:402)
	at cofh.thermaldynamics.block.TileTDBase.onNeighborBlockChange(TileTDBase.java:329)
	at cofh.core.block.BlockCoFHBase.func_149695_a(BlockCoFHBase.java:185)

**Comment by KingLemming** [comment]
If the duct is actually moved correctly, this shouldn't happen. Funky Locomotion seems to get it right.
