### ISSUE TITLE
Creative Copy Dynamics pipe crashes,and I can never launch the game anymore..

### ISSUE THREAD

**Issue by Arkyo** [CoFH/Feedback#495]
`java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177596_a(ModelBakery.java:441)
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:320)
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:170)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:44)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177596_a(ModelBakery.java:441)
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:320)
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:170)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:44)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by covers1624** [comment]
Please don't copy portions of the crash report it contains data we need, im assuming from this you are on 1.10 and have MFR installed, This is the phantom milk bucket issue caused by MFR, go check their tracker to see if it has been fixed. Either way, this isnt a crash in our code and is entirely out of our control.

**Comment by Arkyo** [comment]
Ok got it.
But I am curious,how could u discover that I have MFR by the above crash report?

**Comment by covers1624** [comment]
The issue has been reported thousands of times so i know the crash of the top of my head.
