### ISSUE TITLE
Thermaldynamics 1.0.0-122 crash

### ISSUE THREAD

**Issue by sfPlayer1** [CoFH/Feedback#529]
On FC1 (AS2):
```
[09:33:13] [Server thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$WorldTickEvent@362f1e4c:
java.lang.NullPointerException
        at cofh.thermaldynamics.duct.item.StackMap$ItemEntry.<init>(StackMap.java:36) ~[StackMap$ItemEntry.class:?]
        at cofh.thermaldynamics.duct.item.TravelingItem.getStackEntry(TravelingItem.java:354) ~[TravelingItem.class:?]
        at cofh.thermaldynamics.duct.item.ItemGrid.poll(ItemGrid.java:84) ~[ItemGrid.class:?]
        at cofh.thermaldynamics.duct.item.TileItemDuct.tickItems(TileItemDuct.java:441) ~[TileItemDuct.class:?]
        at cofh.thermaldynamics.duct.item.TileItemDuct.tickPass(TileItemDuct.java:218) ~[TileItemDuct.class:?]
        at cofh.thermaldynamics.duct.item.ItemGrid.tickGrid(ItemGrid.java:46) ~[ItemGrid.class:?]
        at cofh.thermaldynamics.core.WorldGridList.tickEnd(WorldGridList.java:63) ~[WorldGridList.class:?]
        at cofh.thermaldynamics.core.TickHandler.tick(TickHandler.java:95) ~[TickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_437_TickHandler_tick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

And while saving during the following shutdown:
```
[09:33:13] [Server thread/ERROR] [FML/]: A TileEntity type cofh.thermaldynamics.duct.item.TileItemDuct has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
        at cofh.thermaldynamics.duct.item.TravelingItem.toNBT(TravelingItem.java:278) ~[TravelingItem.class:?]
        at cofh.thermaldynamics.duct.item.TileItemDuct.func_145841_b(TileItemDuct.java:483) ~[TileItemDuct.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:350) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:480) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by KingLemming** [comment]
First time this has ever been reported. Is there anything else on FC1 that isn't in the AS2 pack?

**Comment by sfPlayer1** [comment]
I just looked at it, it's crashing because of TD not handling item stack deserialization returning null, thus crashing if there was an item in a pipe that has been removed e.g. by a mod update or removal.

The server also has Fastcraft and Sampler for obvious reasons, but as implied above the problem is fully contained in TD.

**Comment by KingLemming** [comment]
While that sounds probable, bear in mind that we still have no idea what Fastcraft actually does, so can't be sure.

**Comment by Entoarox** [comment]
@KingLemming Usually if fastcraft is involved somewhere, you at least see one to three lines of single-letter function calls in the stack trace that mention it.
