### ISSUE TITLE
Server Won't Start

### ISSUE THREAD

**Issue by Juniormunk** [CoFH/Feedback#536]
I Have No Idea Why It Wont Start Here Is The Consoles sayings and crash report

Console:

server@server-desktop:~$ cd Desktop/BukkitTechServer
server@server-desktop:~/Desktop/BukkitTechServer$ sh Start4GB.sh 
Adding Accesstransformer map: CoFH_at.cfg
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
	at java.lang.Class.getMethod0(Class.java:2856)
	at java.lang.Class.getMethod(Class.java:1668)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 12 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at org.objectweb.asm.tree.ClassNode.<init>(Unknown Source)
	at cofh.asm.ASMCore.writeWorld(ASMCore.java:985)
	at cofh.asm.ASMCore.transform(ASMCore.java:177)
	at cofh.asm.CoFHClassTransformer.transform(CoFHClassTransformer.java:38)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:276)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:174)
	... 14 more

Crash Report;

There Was None

**Comment by KingLemming** [comment]
Post a modlist so we can point out where you're messing up please.

**Comment by Juniormunk** [comment]
OK I will

**Comment by Juniormunk** [comment]
Mod List

Advanced Generators
AnimationAPI
Applied Energistics 2
Bdlib
Biomes O' Plenty
Buildcraft
ChickenChunks
Chisel 2
CodeChickenCore
Cofh Core
CofhLib
ComputerCraft
Custom Mob Spawner
Dense Ores
Ender IO
Ender Storage
Ender Utilities
Ex Nihilo
Extra Utilities 
Hats
iChunUtil
Jabba
Magical Crops
Mantle
Minefactory Reloaded
Morph
MrCrayFish's Furniture Mod
NetherOres
NotEnoughItems
OpenBlocks
OpenModsLib
PlunderPizel's Shaders
PneumaticCraft
Power Converters
Project Read - Base
Thaumcraft
Thermal Dynamics

**Comment by KingLemming** [comment]
We need exact versions. Specifically, I am pretty sure you have a Dev version of CoFH Core.

Post a full log please

**Comment by Juniormunk** [comment]
I figured that you would need versions I'll get them in a couple hours (if
I remember)
Thanks for helping me

On May 22, 2015 4:51 PM, "KingLemming" <notifications@github.com> wrote:
>
> We need exact versions. Specifically, I am pretty sure you have a Dev
version of CoFH Core.
