### ISSUE TITLE
[CoFHTweaks] Hanging on Loading Screen

### ISSUE THREAD

**Issue by KamiKazeKenji** [CoFH/Feedback#568]
Minecraft hangs on the loading screen when it gets to this part:
 Loading - Initializing mods Phase 2 (4/7)
 Initialization - CoFH Tweak ASM (5/6)
This happens with CoFHTweaks 0.2.0B1-31 installed. 0.1.0B2-30 works fine.

forge-1.7.10-10.13.3.1408-1.7.10 (also tried 1403)
CoFHCore-[1.7.10]3.0.2-283.jar (with and without, also tried 262)
CoFHTweaks-[1.7.10]0.2.0B1-31.jar

Crash report:
[03:47:48] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[03:47:48] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[03:47:48] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[03:47:48] [main/INFO] [FML]: Forge Mod Loader version 7.99.4.1408 for Minecraft 1.7.10 loading
[03:47:48] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 8.1:amd64:6.3, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[03:47:48] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:47:48] [main/WARN] [FML]: The coremod cofh.tweak.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:47:48] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[03:47:48] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[03:47:48] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[03:47:48] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[03:47:48] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[03:47:49] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[03:47:49] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[03:47:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[03:47:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[03:47:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[03:47:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[03:47:49] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[03:47:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[03:47:49] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[03:47:50] [main/INFO]: Setting user: KamiKazeKenji
[03:47:51] [Client thread/INFO]: LWJGL Version: 2.9.1
[03:47:51] [Client thread/INFO] [STDOUT]: [cpw.mods.fml.client.SplashProgress:start:180]: ---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 5/30/15 3:47 AM
Description: Loading screen debug info

java.lang.Throwable
	at cpw.mods.fml.client.SplashProgress.start(SplashProgress.java:179)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:192)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 74692184 bytes (71 MB) / 183791616 bytes (175 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 350.12' Renderer: 'GeForce GTS 450/PCIe/SSE2'
[03:47:51] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[03:47:51] [Client thread/INFO] [FML]: MinecraftForge v10.13.3.1408 Initialized
[03:47:51] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[03:47:51] [Client thread/INFO] [FML]: Preloading CrashReport classes
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.World$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.World$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.World$3
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.World$4
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.chunk.Chunk$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$3
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.entity.Entity$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.entity.Entity$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.entity.EntityTracker$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.layer.GenLayer$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.layer.GenLayer$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.entity.player.InventoryPlayer$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$3
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$3
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$4
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$5
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.nbt.NBTTagCompound$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.nbt.NBTTagCompound$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.network.NetHandlerPlayServer$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.network.NetworkSystem$3
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$3
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$3
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$4
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$5
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$6
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$7
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$8
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$9
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$3
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$4
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$5
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$6
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$7
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$8
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$9
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$10
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$11
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$12
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$13
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$14
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$15
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$3
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$4
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$3
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$4
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.EntityRenderer$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.EntityRenderer$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.EntityRenderer$3
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.server.integrated.IntegratedServer$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.server.integrated.IntegratedServer$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.RenderGlobal$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$3
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$4
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureAtlasSprite$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureManager$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureMap$1
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureMap$2
[03:47:51] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureMap$3
[03:47:51] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[03:47:52] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[03:47:52] [Client thread/INFO] [FML]: Searching C:\Users\Kenji\AppData\Roaming\.minecraft\nexus-test\mods for mods
[03:47:53] [Client thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[03:47:53] [Client thread/INFO] [FML]: FML has found a non-mod file CoFHTweaks-[1.7.10]0.2.0B1-31.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[03:47:53] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, <CoFH ASM>, <CoFH Tweak>, CoFHCore] at CLIENT
[03:47:53] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, <CoFH ASM>, <CoFH Tweak>, CoFHCore] at SERVER
[03:47:54] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:CoFH Core
[03:47:54] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[03:47:54] [Client thread/INFO] [FML]: Found 337 ObjectHolder annotations
[03:47:54] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[03:47:54] [Client thread/INFO] [CoFHWorld]: Registering Default Templates.
[03:47:54] [Client thread/INFO] [CoFHWorld]: Registering default generators
[03:47:54] [Client thread/INFO] [CoFHWorld]: Complete
[03:47:54] [Client thread/INFO] [FML]: Applying holder lookups
[03:47:54] [Client thread/INFO] [FML]: Holder lookups applied
[03:47:54] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[03:47:54] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[03:47:54] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[03:47:54] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[03:47:54] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[03:47:55] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[03:47:55] [Sound Library Loader/INFO]: Sound engine started
[03:47:55] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[03:47:55] [Client thread/INFO]: Created: 256x256 textures/items-atlas

**Comment by XFactHD** [comment]
If I am right, this doesn't have anything to do with CoFH Tweaks, it's a crash that is issued by forge when you start Minecraft for the first time with forge 1395 or so. In that way, the forge devs want to get information about what they have to optimize on their loading screen.

**Comment by KingLemming** [comment]
It's not us. It just happens to be showing us when it occurs. I don't know if XFactHD is correct, but the log does show it has nothing to do with CoFH anything.

**Comment by KamiKazeKenji** [comment]
I can confirm the same thing happens on Forge 1355, and even 1291. So no progress bar here, it just hangs on the Mojang screen. fml-client-latest.log stops at 
`[10:49:37] [Client thread/TRACE] [<CoFH Tweak>/<CoFH Tweak>]: Sending event FMLInitializationEvent to mod <CoFH Tweak>`

[(Pastebin)](http://pastebin.com/ax7PV8yc)

Again, this hang only occurs when I have CoFHTweaks-[1.7.10]0.2.0B1-31 installed. No other mods or previous versions of CoFHTweaks causes this.

If this is in fact on Forge, I suppose I should report it to them?

**Comment by sandalle** [comment]
My [fml-client-latest.log](https://www.dropbox.com/s/yoq2x26ps4zuhmu/%5BCoFHTweaks%5D%20Hanging%20on%20Loading%20Screen%20%23568%20fml-client-latest.7z?dl=0) shows similar using [CoFHTweaks-[1.7.10]0.2.0B1-31](http://minecraft.curseforge.com/mc-mods/230020-cofhtweaks/files/2239549), using Java 8u45 64-bit, Windows 7, Minecraft 1.7.10. I tried with [Forge](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html) 1307, 1408, and 1420 on my client. Trying [KCauldron](http://tcpr.ca/cauldron) 1408 and 1420 on my headless Linux server and CoFHTweaks-[1.7.10]0.2.0B1-31 and the server starts without issue for both KCauldron releases, though I don't think CoFHTweaks does much for a headless server. ;)

from [fml-client-latest.log](https://www.dropbox.com/s/yoq2x26ps4zuhmu/%5BCoFHTweaks%5D%20Hanging%20on%20Loading%20Screen%20%23568%20fml-client-latest.7z?dl=0):
````
...
[19:06:39] [Client thread/TRACE] [<CoFH ASM>/<CoFH ASM>]: Sending event FMLInitializationEvent to mod <CoFH ASM>
[19:06:39] [Client thread/TRACE] [<CoFH ASM>/<CoFH ASM>]: Sent event FMLInitializationEvent to mod <CoFH ASM>
[19:06:39] [Client thread/TRACE] [<CoFH Tweak>/<CoFH Tweak>]: Sending event FMLInitializationEvent to mod <CoFH Tweak>
````

For reference, [FastCraft-1.21](http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820) works with the 1307, 1408, and 1420 clients.
