### ISSUE TITLE
java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by cheeseonhead** [CoFH/Feedback#57]
I'm on Mac, I don't know if that had to do with anything, but when installing CoFHCore-[1.7.10]3.0.0B9-40 I can't just leave the .jar file be, I have to unzip it using Unarchiver to a folder, otherwise minecraft will just ignore the .jar file and throw a zip file error exception of some sort.

This is the farthest I have gotten, it seems like Thermal Expansion is trying to access something from cofh.core, but doesn't have access?

Is this a bug or how do I fix this problem? I searched google all over but there are no solid answers out there.

EDIT: I have seen your comment on issue 56, and I believe I don't have anything not recommended I think. You said his ThermalFoundation is in alpha, it caused an error for him but not me :/

Thank you for reading and making these amazing mods.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/27/15 6:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemSpade.field_150916_c from class cofh.core.item.tool.ItemShovelAdv
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemSpade.field_150916_c from class cofh.core.item.tool.ItemShovelAdv
	at cofh.core.item.tool.ItemShovelAdv.<init>(ItemShovelAdv.java:12)
	at thermalexpansion.item.TEEquipment.preInit(TEEquipment.java:49)
	at thermalexpansion.item.TEItems.preInit(TEItems.java:39)
	at thermalexpansion.ThermalExpansion.preInit(ThermalExpansion.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 143393528 bytes (136 MB) / 258199552 bytes (246 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 12 mods loaded, 12 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40) Unloaded->Constructed->Pre-initialized
	BuildCraft|Core{6.3.3} [BuildCraft] (buildcraft-6.3.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Transport{6.3.3} [BC Transport] (buildcraft-6.3.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Silicon{6.3.3} [BC Silicon] (buildcraft-6.3.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Builders{6.3.3} [BC Builders] (buildcraft-6.3.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Energy{6.3.3} [BC Energy] (buildcraft-6.3.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Factory{6.3.3} [BC Factory] (buildcraft-6.3.3.jar) Unloaded->Constructed->Pre-initialized
	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13) Unloaded->Constructed->Pre-initialized
	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed->Errored

**Comment by cheeseonhead** [comment]
I actually have seen the previous issue 56, and nothing of mine is from curseforge, no dev, no alpha, only beta, like the ones in the report.

**Comment by cheeseonhead** [comment]
Oh wait, crap. I didn't see your last sentence, I'm guessing my ThermalFoundation is in alpha too.
But where else can I get it then, if not from the website?

**Comment by KingLemming** [comment]
Oh, so your Mac is ignoring the .jars.

*That's* the issue. You can't just unzip them; ATs are not being properly processed if you do that.

For a lot of reasons, I'd recommend not owning a Mac, but since I realize that's not an option necessarily, I'll refer skyboy to this. There was a version released where Macs didn't know what to do because they're bad. I believe it's been fixed, but may require something new.

**Comment by cheeseonhead** [comment]
Ah I see, thanks. It's kinda weird though. I don't have to unzip ThermalExpansion itself or buildcraft. But I have to unzip COFH and ThermalFoundation. I'll hope for the good news from skyboy.

**Comment by skyboy** [comment]
Some of the release files have 2 trailing garbage bytes; using java7 or windows permits handling of them gracefully, as does removing them yourself (via a hex editor or a unix tool; in hex: 0A 0D)

**Comment by cheeseonhead** [comment]
Oh! I'm going to try that. Just to make sure, throw the .jar file into the hex editor and search for 0A 0D?
Thank you.

**Comment by cheeseonhead** [comment]
Thanks for the help, this is popping up though.
"FML has found a non-mod file CoFHLib-[1.7.10]1.0.0B8-34.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible."
How can it suddenly become a non-mod without those two bytes? Haha

**Comment by skyboy** [comment]
Lib has never been a mod; it's just a library.

Closing this now though.
