### ISSUE TITLE
I right clicked a portable tank and this happened. World is unable to load.

### ISSUE THREAD

**Issue by Toapoint** [CoFH/Feedback#595]
[07:54:08] [Server thread/INFO]: Starting minecraft server version 1.12.2
[07:54:42] [Server thread/INFO]: Loading properties
[07:54:42] [Server thread/INFO]: Default game type: SURVIVAL
[07:54:42] [Server thread/INFO]: Generating keypair
[07:54:42] [Server thread/INFO]: Starting Minecraft server on *:25565
[07:54:42] [Server thread/INFO]: Using default channel type
[07:55:08] [Server thread/INFO]: Preparing level "world"
[07:55:12] [Server thread/INFO]: Loaded 542 advancements
[07:55:12] [Server thread/INFO]: Preparing start region for level 0
[07:55:13] [Server thread/INFO]: Preparing spawn area: 0%
[07:55:14] [Server thread/INFO]: Preparing spawn area: 33%
[07:55:16] [Server thread/INFO]: Preparing spawn area: 90%
[07:55:16] [Server thread/INFO]: Done (8.161s)! For help, type "help" or "?"
[07:55:19] [User Authenticator #1/INFO]: UUID of player shaverman5000 is 73f9d5ad-8a21-4c98-add8-f22d3f1e1fe5
[07:55:21] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at cofh.core.util.helpers.FluidHelper.insertFluidIntoAdjacentFluidHandler(FluidHelper.java:137) ~[FluidHelper.class:?]
	at cofh.thermalexpansion.block.storage.TileTank.transferFluid(TileTank.java:222) ~[TileTank.class:?]
	at cofh.thermalexpansion.block.storage.TileTank.func_73660_a(TileTank.java:155) ~[TileTank.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1829) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more
[07:55:21] [Server thread/ERROR]: This crash report has been saved to: C:\MC_Server_1.12.1\.\crash-reports\crash-2017-10-17_07.55.21-server.txt
[07:55:21] [Server thread/INFO]: Stopping server
[07:55:21] [Server thread/INFO]: Saving players
[07:55:21] [Server thread/INFO]: Saving worlds
[07:55:21] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[07:55:21] [Server thread/INFO]: Saving chunks for level 'world'/the_nether
[07:55:21] [Server thread/INFO]: Saving chunks for level 'world'/the_end

**Comment by KingLemming** [comment]
You have a tile entity which is a liar. It claimed to have a capability and then handed back a null. This is a contract violation and whoever is doing it is in the wrong. So basically, this isn't caused by us - it's caused by whatever the tank was attempting to fill.

**Comment by KingLemming** [comment]
I am adding some defensive code on our end which will prevent this in the future, but it's crap like this which makes modded MC run slower. We shouldn't have to add extra defensive code to just to guard against other mods from screwing up. >:(
