### ISSUE TITLE
Runaway java VM

### ISSUE THREAD

**Issue by dabaer** [CoFH/Feedback#605]
Okay. The server that this is running on has one of its internet routes nulled at the datacenter level temporarily. It can access some web services but not others. So i decided to try it anyways.

```
[19:28:46 ERROR]: [PlugMan] The updater could not contact dev.bukkit.org for updating.
[19:28:46 ERROR]: [PlugMan] If you have not recently modified your configuration and this is the firs                                t time you are seeing this message, the site may be experiencing temporary downtime.
[19:28:46 ERROR]: [PlugMan] null
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgori                                thmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:1.7.0_79]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1904) ~[?:1.7.0_79]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1862) ~[?:1.7.0_79]
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1845) ~[?:1.7.0_79]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1366) ~[?:1.7.0_79]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343) ~[?:1.7.0_79]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563) ~[?:1.7.0_79]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttp                                sURLConnection.java:185) ~[?:1.7.0_79]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301) ~[                                ?:1.7.0_79]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.ja                                va:254) ~[?:1.7.0_79]
        at net.gravitydevelopment.updater.Updater.read(Updater.java:516) [PlugMan.jar:?]
        at net.gravitydevelopment.updater.Updater.access$200(Updater.java:41) [PlugMan.jar:?]
        at net.gravitydevelopment.updater.Updater$UpdateRunnable.run(Updater.java:554) [PlugMan.jar:?                                ]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterExcep                                tion: the trustAnchors parameter must be non-empty
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90) ~[?:1.7.0_79]
        at sun.security.validator.Validator.getInstance(Validator.java:179) ~[?:1.7.0_79]
        at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:314) ~[?:1.7.                                0_79]
        at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:173) ~[?:                                1.7.0_79]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:186) ~[?:1.7.                                0_79]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126) ~[                                ?:1.7.0_79]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1428) ~[?:1.7.0_                                79]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:209) ~[?:1.7.0_79]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:901) ~[?:1.7.0_79]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:837) ~[?:1.7.0_79]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1023) ~[?:1.7.0_79]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332) ~[?:1.7.0_                                79]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359) ~[?:1.7.0_79]
        ... 9 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-e                                mpty
        at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200) ~[?:1.7.0_79]
        at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120) ~[?:1.7.0_79]
        at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104) ~[?:1.7.0_                                79]
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88) ~[?:1.7.0_79]
        at sun.security.validator.Validator.getInstance(Validator.java:179) ~[?:1.7.0_79]
        at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:314) ~[?:1.7.                                0_79]
        at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:173) ~[?:                                1.7.0_79]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:186) ~[?:1.7.                                0_79]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126) ~[                                ?:1.7.0_79]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1428) ~[?:1.7.0_                                79]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:209) ~[?:1.7.0_79]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:901) ~[?:1.7.0_79]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:837) ~[?:1.7.0_79]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1023) ~[?:1.7.0_79]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332) ~[?:1.7.0_                                79]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359) ~[?:1.7.0_79]
        ... 9 more
[19:28:46 WARN]: [PlugMan] Updater was unable to connect with dev.bukkit.org to look for updates.
[19:28:58 ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/world/World$5
        at net.minecraft.world.World.func_72914_a(World.java:4497) ~[ahb.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:959) ~[MinecraftSer                                ver.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) ~[lt                                .class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftSer                                ver.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:                                ?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World$5
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[laun                                chwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
        ... 6 more
Caused by: java.lang.OutOfMemoryError: PermGen space
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_79]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_79]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_79]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[laun                                chwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
        ... 6 more
[19:28:58 ERROR]:       Cause of unexpected exception was
java.lang.ClassNotFoundException: net.minecraft.world.World$5
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[laun                                chwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
        at net.minecraft.world.World.func_72914_a(World.java:4497) ~[ahb.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:959) ~[MinecraftSer                                ver.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) ~[lt                                .class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftSer                                ver.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:                                ?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.OutOfMemoryError: PermGen space
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_79]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_79]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_79]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[laun                                chwrapper-1.11.jar:?]
        ... 8 more
[19:29:18 INFO]: Stopping server
[19:29:18 INFO]: [ChatEx] Disabling ChatEx v1.2
[19:29:18 INFO]: [ChatEx] is now disabled!
[19:29:18 INFO]: [BanItem] Disabling BanItem v2.8
[19:29:18 INFO]: BanItem is now Disabled!
[19:29:25 WARN]: java.net.ConnectException: Connection timed out
[19:29:25 WARN]:        at java.net.PlainSocketImpl.socketConnect(Native Method)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-10"
[19:29:25 ERROR]: Update check for Redstone Arsenal failed.
java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.7.0_79]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[?:1.7.0_79]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[?:1.                                7.0_79]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[?:1.7.0_79]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.7.0_79]
        at java.net.Socket.connect(Socket.java:579) ~[?:1.7.0_79]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625) ~[?:1.7.0_79]
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160) ~[?:1.7.0_79]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.7.0_79]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[?:1.7.0_79]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[?:1.7.0_79]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275) ~[?:1.7.0_79]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371) ~[?:1.7.0_79]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDel                                egateHttpsURLConnection.java:191) ~[?:1.7.0_79]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933) ~[?:1                                .7.0_79]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttp                                sURLConnection.java:177) ~[?:1.7.0_79]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301) ~[                                ?:1.7.0_79]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.ja                                va:254) ~[?:1.7.0_79]
        at java.net.URL.openStream(URL.java:1037) ~[?:1.7.0_79]
        at cofh.mod.updater.UpdateCheckThread.run(UpdateCheckThread.java:44) [UpdateCheckThread.class                                :?]

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "iChunUtil M                                od Version Check"
[19:29:28 WARN]: If you see a error just below this line, its prob fine to ignore <3 chococraft

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Morph Onlin                                e Resource Thread"
[19:29:53 WARN]: Version check Failed: Connection timed out
[19:30:17 ERROR]: Exception stopping the server
java.lang.OutOfMemoryError: PermGen space

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "CoFHUpdater                                :NetherOres"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Hats Mod Mo                                b Support Thread"
>
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-12"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "CoFHUpdater                                :MineFactoryReloaded"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "CoFHUpdater                                :ThermalDynamics"
[19:30:29 INFO]: Applying holder lookups

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Server thre                                ad"
[19:30:29 WARN]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.bl                                ock.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wro                                ng with the registry?
[19:30:29 WARN]: Unable to lookup chisel:obsidian2 for public static com.cricketcraft.chisel.block.Bl                                ockCarvable com.cricketcraft.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the re                                gistry?
[19:30:29 INFO]: Holder lookups applied
>stop
^COpenJDK 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signal                                 SIGINT to handler- the VM may need to be forcibly terminated
^C^COpenJDK 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signa                                l SIGINT to handler- the VM may need to be forcibly terminated

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Server cons                                ole handler"
^C^C^C^C^COpenJDK 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching                                 signal SIGINT to handler- the VM may need to be forcibly terminated
Killed
```

I've stringently disabled most update checkers, however CoFHCore (uselessly) still checks and reports on critical updates. In tangent with the aforementioned null route seemed to have made the JVM critically run away on me. Since CoFH is prominent in the OOM entries I thought maybe you guys could help me understand what's going on (or if it's even remotely related to CoFH).

Thanks

**Comment by dabaer** [comment]
Some more information - This server starts correctly using Java8 under windows, however spins out of control using Java7 under Linux.

**Comment by KingLemming** [comment]
Sorry, it's not us. You just happen to see our threads falling victim to the underlying problem, which is that you're out of memory. If you notice, we're hardly the only ones.

You need to increase your permgen space, something which is gone in Java 8 but still exists in Java 7. 
https://stackoverflow.com/questions/3003855/increase-permgen-space should help you.
