### ISSUE TITLE
Connecting Itemduct to Phytogenic Insulator causes game crash

### ISSUE THREAD

**Issue by TygreWolf** [CoFH/Feedback#606]
Occurs on both Infinity 1.5.1 or 1.6.2 - both use:

ThermalExpansion 4.0.1-182
ThermalDynamics 1.0.0-122

Connected a Phytogenic Infuser to an AE system, with an interface and pattern to create wheat.  Phytogenic insulator working fine, began creating wheat.  The Phytogenic insulator was configured to not output on any sides (yet).  Placed an AE interface down several blocks away, and began connecting impulse itemducts from interface towards insulator.  Once itemducts reached insulator, changed the insulator configuration to output on itemduct side, and game immediately crashes.  Cannot open game back up, as it continues to immediately crash.  This issue is repeatable.

**UPDATE**
You don't need a complicated setup to reproduce this bug.  Just connect an impulse itemduct to a phytogenic insulator, and change the output of that side to the "white/grey" colored output.  That will be enough to reproduce the crash.

Crash report:
=======================================================================

```
[09:51:06] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel CoFH
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 7
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 7
	at cofh.thermalexpansion.block.TileAugmentable.func_94128_d(TileAugmentable.java:366) ~[TileAugmentable.class:?]
	at cofh.thermaldynamics.duct.item.TileItemDuct.isSignificantTile(TileItemDuct.java:177) ~[TileItemDuct.class:?]
	at cofh.thermaldynamics.block.TileTDBase.handleSideUpdate(TileTDBase.java:405) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.block.TileTDBase.onNeighborTileChange(TileTDBase.java:496) ~[TileTDBase.class:?]
	at cofh.core.block.BlockCoFHBase.onNeighborChange(BlockCoFHBase.java:195) ~[BlockCoFHBase.class:?]
	at net.minecraft.world.World.func_147453_f(World.java:3875) ~[ahb.class:?]
	at cofh.core.block.TileCoFHBase.callNeighborTileChange(TileCoFHBase.java:64) ~[TileCoFHBase.class:?]
	at cofh.thermalexpansion.block.TileReconfigurable.handleTilePacket(TileReconfigurable.java:101) ~[TileReconfigurable.class:?]
	at cofh.thermalexpansion.block.TileAugmentable.handleTilePacket(TileAugmentable.java:198) ~[TileAugmentable.class:?]
	at cofh.thermalexpansion.block.machine.TileMachineBase.handleTilePacket(TileMachineBase.java:315) ~[TileMachineBase.class:?]
	at cofh.core.network.PacketTile.handlePacket(PacketTile.java:31) ~[PacketTile.class:?]
	at cofh.core.network.PacketCoFHBase.handleServerSide(PacketCoFHBase.java:376) ~[PacketCoFHBase.class:?]
	at cofh.core.network.PacketHandler.decode(PacketHandler.java:104) ~[PacketHandler.class:?]
	at cofh.core.network.PacketHandler.decode(PacketHandler.java:40) ~[PacketHandler.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
	... 13 more
```

**Comment by TygreWolf** [comment]
Just noticed this was a duplicate and already fixed in dev.  Marking as closed.
