### ISSUE TITLE
BungeeCord error with this mod.

### ISSUE THREAD

**Issue by florian96** [CoFH/Feedback#609]
Hey i have a Modpack with 100 Mods. Without the CoFH mods it works to connect with BungeeCord but with your mods i can not Connect with the Newest Version.

**Comment by KingLemming** [comment]
We've been over this with them. It's on their end and should have been fixed. Update your mods and report it to them if that doesn't work.

**Comment by florian96** [comment]
Now i have ony 3 Mods installed on Client and on the Server. I have installed 

CoFHCore-[1.7.10]3.0.2-262
CoFHLib-[1.7.10]1.0.2-160
ThermalFoundation-[1.7.10]1.0.0-81

But i Cannot connect With BungeeCord. I got this Error: 

23:37:12 [SCHWERWIEGEND] [florian96] <-> DownstreamBridge <-> [tekkit] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: -26
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -26
	at net.md_5.bungee.protocol.Protocol$DirectionData.hasPacket(Protocol.java:125)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:31)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 16 more

**Comment by florian96** [comment]
I have Tested it. It works with CoFH core 3.0.0 but dont with 3.0.1 and 3.0.2.

**Comment by KingLemming** [comment]
Yes. We know what changed. It's been reported to them and they said that they would be fixing it.

**Comment by florian96** [comment]
I have the newes Build of BungeeCord (Build 1071)

**Comment by florian96** [comment]
It works with a newer Forge Version and a Older BungeeCord version.
