### ISSUE TITLE
[TE] Crash when putting an TE-machine into a cache + hopper

### ISSUE THREAD

**Issue by EoD** [CoFH/Feedback#611]
ThermalExpansion: -[1.7.10]4.0.1-182

When I try to put a redstone furnace for example into the cache in the top here, its image on the cache disappears although the hopper below is filled with netherrack. And once it is not shown on the cache anymore the server crashes.

![2015-06-17_13 52 31](https://cloud.githubusercontent.com/assets/293499/8206316/a0a9f6d4-14f8-11e5-8b85-791f40330670.png)

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/17/15 1:53 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at cofh.thermalexpansion.block.cache.TileCache.func_70298_a(TileCache.java:298)
	at net.minecraft.tileentity.TileEntityHopper.func_145892_a(TileEntityHopper.java:530)
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:490)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:251)
	at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:231)
	at net.minecraft.world.World.func_72939_s(World.java:2512)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cofh.thermalexpansion.block.cache.TileCache.func_70298_a(TileCache.java:298)
	at net.minecraft.tileentity.TileEntityHopper.func_145892_a(TileEntityHopper.java:530)
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:490)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:251)
	at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:231)

-- Block entity being ticked --
Details:
	Name: Hopper // net.minecraft.tileentity.TileEntityHopper
	Block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-904,57,1003), Chunk: (at 8,3,11 in -57,62; contains blocks -912,0,992 to -897,255,1007), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Actual block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2512)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [GCEntityPlayerMP['_EoD_'/194, l='world', x=-904.70, y=56.50, z=1001.28](_EoD_ at -904.6999999880791,56.49657404410093,1001.275499782332)]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: 6089228570780880843
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-864,64,999), Chunk: (at 0,4,7 in -54,62; contains blocks -864,0,992 to -849,255,1007), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 25040682 game time, 25702969 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 68198 (now: false), thunder time: 127737 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.19.0-15-generic
	Java Version: 1.8.0_45-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 154236208 bytes (147 MB) / 792817664 bytes (756 MB) up to 1712717824 bytes (1633 MB)
	JVM Flags: 3 total; -Xmx1650m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1420 42 mods loaded, 42 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1420.120-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1420} [Minecraft Forge] (KCauldron-1.7.10-1420.120-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	kimagine{0.1} [KImagine] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv2-stable-3} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv2-stable-3} [Applied Energistics 2] (appliedenergistics2-rv2-stable-3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1283-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forestry{3.5.7.16} [Forestry for Minecraft] (forestry_1.7.10-3.5.7.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BinnieCore{2.0-pre11} [Binnie Core] (binnie-mods-2.0-pre11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Botany{2.0-pre11} [Botany] (binnie-mods-2.0-pre11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraBees{2.0-pre11} [Extra Bees] (binnie-mods-2.0-pre11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraTrees{2.0-pre11} [Extra Trees] (binnie-mods-2.0-pre11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Genetics{2.0-pre11} [Genetics] (binnie-mods-2.0-pre11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.339.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.339.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	JourneyMapServer{1.0.5_MC1.7.10} [JourneyMapServer] (JourneyMapServer1.0.5_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Morpheus{1.7.10-1.6.4} [Morpheus] (Morpheus-1.7.10-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons{1.12.9.32} [NEI Addons] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|AppEng{1.12.9.32} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|Botany{1.12.9.32} [NEI Addons: Botany] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|Forestry{1.12.9.32} [NEI Addons: Forestry] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|CraftingTables{1.12.9.32} [NEI Addons: Crafting Tables] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|ExNihilo{1.12.9.32} [NEI Addons: Ex Nihilo] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	neiintegration{1.0.9} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AE2 Version: stable rv2-stable-3 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.2-262
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	TConstruct Environment: Environment healthy.
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 10; [GCEntityPlayerMP['_EoD_'/194, l='world', x=-904.70, y=56.50, z=1001.28](_EoD_ at -904.6999999880791,56.49657404410093,1001.275499782332)]
	Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by KingLemming** [comment]
This is a Mojang bug with the hopper it would seem, but we'll try and work around it.

My recommendation is not to use hoppers as a general rule, they're laggy, inefficient, and apparently do not properly extract items.

**Comment by EoD** [comment]
Is there a replacement for hoppers in CoFH, TF or TE?

**Comment by KingLemming** [comment]
Thermal Dynamics. An Itemduct works very well.

**Comment by KingLemming** [comment]
Okay, so I have sort of worked around this issue. In the vast majority of use cases, the hopper will work as expected.

There is an unfixable corner case that persists, but it won't result in a crashed game.
