### ISSUE TITLE
Viaduct GUI not working

### ISSUE THREAD

**Issue by ireece1** [CoFH/Feedback#612]
So in Thermal Dynamics 2.3.5.12 for Minecraft 1.12.2 i tried right-clicking on an open Viaduct but nothing would happen, so i check the logs and it shows this:

[19:09:39] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: cofh/thermaldynamics/gui/client/GuiTransport
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: cofh/thermaldynamics/gui/client/GuiTransport
	at cofh.thermaldynamics.duct.entity.DuctUnitTransport.getGuiClient(DuctUnitTransport.java:300) ~[DuctUnitTransport.class:?]
	at cofh.thermaldynamics.duct.tiles.TileGrid.getGuiClient(TileGrid.java:1036) ~[TileGrid.class:?]
	at cofh.thermaldynamics.gui.GuiHandler.getClientGuiElement(GuiHandler.java:28) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:277) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2546) ~[aed.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43) ~[OpenGuiHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more

**Comment by covers1624** [comment]
Provide your full log, that portion of the stack trace is meaning less.

**Comment by KingLemming** [comment]
Right, without the full log, we just don't know what you're doing wrong / have done wrong / have a corrupted jar, or what.

But...this is definitely not a thing in our codebase.
