### ISSUE TITLE
Crash when placing Block Smasher when MoreCommands is installed

### ISSUE THREAD

**Issue by jcotton42** [CoFH/Feedback#615]
# Versions:
- Minecraft: 1.7.10
- CoFH Core: 3.0.2-262
- MoreCommands: 1.4
- Thermal Foundation: 1.0.0-81
- Thermal Expansion: 4.0.1-182
- Forge: 10.13.4.1448
- Forge ModLoader: 7.10.99.99

# Crash log:
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 6/20/15 6:44 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.mrnobody.morecommands.command.server.CommandBreakspeed.onEvent(CommandBreakspeed.java:30)
	at com.mrnobody.morecommands.command.server.CommandBreakspeed.onEvent(CommandBreakspeed.java:15)
	at com.mrnobody.morecommands.handler.Handler.onEvent(Handler.java:53)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_146_Handler_onEvent_Event.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:89)
	at net.minecraft.entity.player.EntityPlayer.getBreakSpeed(EntityPlayer.java:855)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:138)
	at net.minecraft.block.Block.func_149737_a(Block.java:643)
	at cofh.core.entity.CoFHFakePlayer.isBlockBreakable(CoFHFakePlayer.java:40)
	at cofh.thermalexpansion.block.device.TileBreaker.breakBlock(TileBreaker.java:137)
	at cofh.thermalexpansion.block.device.TileBreaker.func_145845_h(TileBreaker.java:115)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mrnobody.morecommands.command.server.CommandBreakspeed.onEvent(CommandBreakspeed.java:30)
	at com.mrnobody.morecommands.command.server.CommandBreakspeed.onEvent(CommandBreakspeed.java:15)
	at com.mrnobody.morecommands.handler.Handler.onEvent(Handler.java:53)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_146_Handler_onEvent_Event.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:89)
	at net.minecraft.entity.player.EntityPlayer.getBreakSpeed(EntityPlayer.java:855)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:138)
	at net.minecraft.block.Block.func_149737_a(Block.java:643)
	at cofh.core.entity.CoFHFakePlayer.isBlockBreakable(CoFHFakePlayer.java:40)
	at cofh.thermalexpansion.block.device.TileBreaker.breakBlock(TileBreaker.java:137)
	at cofh.thermalexpansion.block.device.TileBreaker.func_145845_h(TileBreaker.java:115)

-- Block entity being ticked --
Details:
	Name: thermalexpansion.Breaker // cofh.thermalexpansion.block.device.TileBreaker
	Block type: ID #482 (tile.thermalexpansion.device // cofh.thermalexpansion.block.device.BlockDevice)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (-466,56,-153), Chunk: (at 14,3,7 in -30,-10; contains blocks -480,0,-160 to -465,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #482 (tile.thermalexpansion.device // cofh.thermalexpansion.block.device.BlockDevice)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Sandbox
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 7976474025792506610
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 2;7,3x1,52x24;2;
	Level spawn location: World: (-510,4,-176), Chunk: (at 2,0,0 in -32,-11; contains blocks -512,0,-176 to -497,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 494048 game time, 318000 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 132879 (now: false), thunder time: 23044 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 270687904 bytes (258 MB) / 689098752 bytes (657 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) 
	UCHIJAAAA	BuildCraft|Core{7.0.11} [BuildCraft] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.0.11} [BC Energy] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.0.11} [BC Factory] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.0.11} [BC Robotics] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.0.11} [BC Silicon] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.0.11} [BC Transport] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.0.11} [BC Builders] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.0.8} [BuildCraft Compat] (buildcraft-compat-7.0.8.jar) 
	UCHIJAAAA	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) 
	UCHIJAAAA	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.7.10-beta-5c.jar) 
	UCHIJAAAA	FWG{1.0.3} [Fun World Gen] (FWG-1.0.3.jar) 
	UCHIJAAAA	mrnobody_morecommands{1.4} [More Commands] (MoreCommands-1.7.10-1.4.jar) 
	UCHIJAAAA	OWG{1.0.3} [Old World Gen] (OWG-1.0.3-1.7.10.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.0.9.18} [MrTJPCore] (MrTJPCore-1.7.10-1.0.9.18-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre1.84} [ProjectRed] (ProjectRed-1.7.10-4.7.0pre1.84-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre1.84} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.7.0pre1.84-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre1.84} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.7.0pre1.84-Mechanical_beta.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre1.84} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.7.0pre1.84-World.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre1.84} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.7.0pre1.84-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre1.84} [ProjectRed-Integration] (ProjectRed-1.7.10-4.7.0pre1.84-Integration.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre1.84} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.7.0pre1.84-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre1.84} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.7.0pre1.84-Mechanical_beta.jar) 
	UCHIJAAAA	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) 
	UCHIJAAAA	RWG{Alpha 1.3.2} [Realistic World Gen Alpha] (RWG-alpha-1.3.2.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) 
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.0.2-262
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	RedstoneArsenal: -[1.7.10]1.1.0-80
	ThermalDynamics: -[1.7.10]1.0.0-122
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by KingLemming** [comment]
Okay. Better let them know, it's not on us.
