### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by bosseftw** [CoFH/Feedback#619]
So I just tried to update some of my mods and got a crash-message on startup.

I've tried with multiple forge versions, and different versions of mods aswell.

Here's the crashreport, any suggestions? Just in case, I'm new to this so try to dumb your answers down a bit so I can understand them :)

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2015-06-23 19:08
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:719)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:304)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
	at forestry.pipes.proxy.ProxyPipes.initPropolisPipe(ProxyPipes.java:35)
	at forestry.pipes.proxy.ClientProxyPipes.initPropolisPipe(ClientProxyPipes.java:28)
	at forestry.plugins.PluginPropolisPipe.postInit(PluginPropolisPipe.java:64)
	at forestry.plugins.PluginManager.runPostInit(PluginManager.java:296)
	at forestry.core.ForestryCore.postInit(ForestryCore.java:118)
	at forestry.core.ForestryClient.postInit(ForestryClient.java:41)
	at forestry.Forestry.postInit(Forestry.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:717)
	... 10 more
Caused by: java.lang.ClassNotFoundException: buildcraft.core.CreativeTabBuildCraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 777135632 bytes (741 MB) / 2106064896 bytes (2008 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.130.1395 Minecraft Forge 10.13.3.1395 Optifine OptiFine_1.7.10_HD_B7 95 mods loaded, 95 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.130.1395} [Forge Mod Loader] (forge-1.7.10-10.13.3.1395-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.3.1395} [Minecraft Forge] (forge-1.7.10-10.13.3.1395-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Core{7.0.12} [BuildCraft] (buildcraft-7.0.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1237-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IC2{2.2.657-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forestry{3.5.3.11} [Forestry for Minecraft] (forestry_1.7.10-3.5.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Energy{7.0.12} [BC Energy] (buildcraft-7.0.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Factory{7.0.12} [BC Factory] (buildcraft-7.0.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Builders{7.0.12} [BC Builders] (buildcraft-7.0.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Artifice{1.7.10R1.1.4} [Artifice] (Artifice-1.7.10-1.1.5R-396.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Backpack{2.0.0} [Backpack] (backpack-2.0.0-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BattleTowers{1.5.2} [Battle Towers] (BattleTowers-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Transport{7.0.12} [BC Transport] (buildcraft-7.0.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Silicon{7.0.12} [BC Silicon] (buildcraft-7.0.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Robotics{7.0.12} [BC Robotics] (buildcraft-7.0.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ChiselFacades{1.7.10-2.11-cricket} [Chisel Facades] (ChiselFacades-1.7.10-2.11-cricket.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CustomOreGen{1.2.18} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	props{1.11} [Decocraft] (Decocraft-v1.11_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	dungeonpack{1.7.10-1.0} [Dungeon Pack] (dungeonpack-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Eln{46} [Electrical Age] (ElectricalAge_BETA-1.9_r46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mekanism{8.1.5} [Mekanism] (Mekanism-1.7.10-8.1.5.246.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EnhancedBooks{1.7.10.01} [Enhanced Books] (Enhanced Books-1.7.10.01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ExtraUtilities{1.2.4} [Extra Utilities] (extrautilities-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MrTJPCoreMod{1.0.9.17} [MrTJPCore] (MrTJPCore-1.7.10-1.0.9.17-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeRelocation{0.0.1a.1} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1a.1-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	RelocationFMP{0.0.1a.1} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1a.1-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	fossil{1.7.10 Build 7.1.0} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	malisiscore{1.7.10-0.11.4} [MalisisCore] (malisiscore-1.7.10-0.11.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	malisisdoors{1.7.10-1.7.1} [Malisis' Doors] (malisisdoors-1.7.10-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MekanismGenerators{8.1.5} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.5.246.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MekanismTools{8.1.5} [MekanismTools] (MekanismTools-1.7.10-8.1.5.246.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TConstruct{1.7.10-1.8.3.build912} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3RC1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	morechisels{@VERSION@} [More Chisels] (MoreChisels-1.7.10-1.0-20.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bettercraft{2.7.2} [MoreCraft] (MoreCraft-1.7.10-2.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Oceancraft{1.4.1} [Oceancraft] (Oceancraft-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	UltraTech{1.7.10-0.9.6.1} [UltraTech] (Ultratech-1.7.10-0.9.6.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	zipline{1.0} [Zipline] (Zipline-1.0(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.06' Renderer: 'GeForce GTX 860M/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.0.2-262
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	ThermalDynamics: -[1.7.10]1.0.0-122
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.

**Comment by bosseftw** [comment]
Got it to work, had to update my forestry mod, delete this if u want to
