### ISSUE TITLE
Error rendering furnace?

### ISSUE THREAD

**Issue by darkhax** [CoFH/Feedback#623]
I am being spammed with this error message on the BTM Moon server. 

Minecraft: 1.12.2
Forge: 14.23.0.2543
CofhCore: 4.3.6.14
Thermal Expansion: 5.3.6.20
CodeChickenLib: 3.1.3.313

```
[11:14:42] [Chunk Batcher 7/ERROR] [CodeChickenLib]: CCL has caught an exception whilst another mod's block is being rendered. Original crash may have been discarded, possible null client side tile. Pos: 'MutableBlockPos{x=-120, y=77, z=176}', State: 'thermalexpansion:machine[type=furnace]', block class: 'class cofh.thermalexpansion.block.machine.BlockMachine'
java.lang.NullPointerException: null
        at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94) ~[bvm.class:?]
        at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64) [CCBlockRendererDispatcher.class:?]
        at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200) [bxr.class:?]
        at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100) [bxn.class:?]
        at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by KingLemming** [comment]
That's fundamentally caused by another mod. CCL probably needs a better error message to see if it can assign blame, but it's not actually caused by either CCL or TE.

Basically somebody isn't properly cleaning up their GL calls.

**Comment by covers1624** [comment]
Actually, i just improved the log output of that on TE's end and there has been no release since. Some mod is crashing whilst reading nbt on the client, also this isnt in GL, this is baking / chunk batching. So yeah, likely a tile crashing on nbt load clientside causing TE's tile to be null and TE unintentionally self destructing.
