### ISSUE TITLE
Crashing when trying to move Energy Cells with Funky Locomotion

### ISSUE THREAD

**Issue by FryoKnight** [CoFH/Feedback#639]
Was trying to build a tunneler when I came across an issue when trying to power it.

```
Description: Tesselating block in world
 
java.lang.ClassCastException: com.rwtema.funkylocomotion.blocks.TileMovingClient cannot be cast to cofh.thermalexpansion.block.storage.TileCell
    at cofh.thermalexpansion.render.RenderCell.handleState(RenderCell.java:92)
    at codechicken.lib.model.bakery.ModelBakery.handleExtendedState(ModelBakery.java:122)
    at cofh.thermalexpansion.block.storage.BlockCell.getExtendedState(BlockCell.java:177)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79)
    at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64)
    at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:95)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:296)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
    at java.lang.Thread.run(Thread.java:745)
```

Minecraft Version: 1.12.2
Mod Pack: Horizons III v1.1.0
Mod Version: 5.3.6.20

Full Crash report: https://pastebin.com/raw/nUim4fJF

Edit: Also left this on the other mod's issues forums.

**Comment by KingLemming** [comment]
Yeah frames are a bad idea and always have been. This might be fundamentally unaddressable.

**Comment by covers1624** [comment]
This is likely an issue with FunkyLocomotion not setting the tile before triggering a render update. Mitigation has been added so these blocks wont crash anymore, that's all we can do from this end.
