### ISSUE TITLE
Exception after logging out from the nether

### ISSUE THREAD

**Issue by krakel** [CoFH/Feedback#651]
I build a simple wither spawner on a test world nether. Only a zombie spawner on cursed earth, spikes, fans, vacuum hopper and some starage drawer. All this was working correct. After logout I got this fatal error on the next login.
```
[10:04:36] [Server thread/ERROR] [FML/]: 
A fatal exception occurred during the server about to start event
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. 
During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.
This violates the general contract of java.lang.Object.hashCode().  
See bullet point two in that method's documentation. 
object #1 =class cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace id= 1069073138 hashCode= 138575871 toString= cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace@1069073138{m:32767, i:net.minecraft.item.ItemBlock@1928304319, v:2114}; 
object #2 =class cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace id= 2064039564 hashCode= 138575871 toString= cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace@2064039564{m:32767, i:net.minecraft.item.ItemBlock@1928304319, v:2114}
```

**Comment by krakel** [comment]
I forget the stacktrace.
```
	at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464) ~[TObjectHash.class:3.0.3]
	at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:448) ~[TObjectHash.class:3.0.3]
	at gnu.trove.map.hash.THashMap.rehash(THashMap.java:403) ~[THashMap.class:3.0.3]
	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:388) ~[THash.class:3.0.3]
	at gnu.trove.map.hash.THashMap.doPut(THashMap.java:178) ~[THashMap.class:3.0.3]
	at gnu.trove.map.hash.THashMap.put(THashMap.java:145) ~[THashMap.class:3.0.3]
	at cofh.thermalexpansion.util.crafting.FurnaceManager.addRecipe(FurnaceManager.java:201) ~[FurnaceManager.class:?]
	at modtweaker2.mods.thermalexpansion.handlers.Furnace$Remove.undo(Furnace.java:90) ~[Furnace$Remove.class:?]
	at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:83) ~[MTTweaker.class:?]
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:589) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:555) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.mc1710.MineTweakerMod.onServerAboutToStart(MineTweakerMod.java:166) ~[MineTweakerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_76]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[modpack.jar:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_76]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_76]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:859) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:273) [FMLCommonHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:91) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

**Comment by krakel** [comment]
Oh, the error happens because the game was not complete unloaded. After killing the java process and restart the game, this error was not occur again.
I do not know why the game was not correct closed on logout from nether.
The guidlines for equal and hashcode on java is of course your problem.

**Comment by KingLemming** [comment]
Well, sort of. The problem here is that you're using Modtweaker and it's actively violating them.

**Comment by krakel** [comment]
I know this thread was closed. 
My last test confirmed a conflict between Modtweaker and Thermal. The recipe refresh of Modtweaker crash with cofh.thermalexpansion.util.crafting.SmelterManager.refreshRecipes. Is there a chance for a agreement between these mods.

**Comment by KingLemming** [comment]
Right, the issue is definitely on Minetweaker/Modtweaker there.

**Comment by jaredlll08** [comment]
Yea, our hashcode / equals is incorrect, I'll fix it asap
