### ISSUE TITLE
Thermal Expansion Exceptions

### ISSUE THREAD

**Issue by Howsyomamanem** [CoFH/Feedback#664]
I get the following when I crash after looking in the direction of the Magmatic Dynamo and the Tank above it in my base.

Fatal exception thrown whilst baking block model for: thermalexpansion:dynamo[type=magmatic]
java.lang.NullPointerException
	at cofh.thermalexpansion.render.RenderDynamo.bakeLayerFace(RenderDynamo.java:211)
	at codechicken.lib.model.bakery.ModelBakery.generateModel(ModelBakery.java:286)
	at codechicken.lib.model.bakery.ModelBakery$$Lambda$2380/1994647688.apply(Unknown Source)
	at codechicken.lib.model.bakery.ModelBakery.timeModelGeneration(ModelBakery.java:336)
	at codechicken.lib.model.bakery.ModelBakery.getCachedModel(ModelBakery.java:244)
	at codechicken.lib.model.bakery.CCBakeryModel.func_188616_a(CCBakeryModel.java:40)
	at journeymap.client.mod.vanilla.VanillaBlockSpriteProxy.getSprites(VanillaBlockSpriteProxy.java:111)
	at journeymap.client.mod.vanilla.VanillaBlockSpriteProxy.getSprites(VanillaBlockSpriteProxy.java:77)
	at journeymap.client.mod.vanilla.VanillaBlockColorProxy.getSpriteColor(VanillaBlockColorProxy.java:124)
	at journeymap.client.mod.vanilla.VanillaBlockColorProxy.deriveBlockColor(VanillaBlockColorProxy.java:57)
	at journeymap.client.model.BlockMD.getTextureColor(BlockMD.java:453)
	at journeymap.client.mod.vanilla.VanillaBlockColorProxy.getBlockColor(VanillaBlockColorProxy.java:79)
	at journeymap.client.model.BlockMD.getBlockColor(BlockMD.java:442)
	at journeymap.client.cartography.render.BaseRenderer.setStratumColors(BaseRenderer.java:277)
	at journeymap.client.cartography.Strata.nextUp(Strata.java:209)
	at journeymap.client.cartography.render.CaveRenderer.paintStrata(CaveRenderer.java:351)
	at journeymap.client.cartography.render.CaveRenderer.renderUnderground(CaveRenderer.java:227)
	at journeymap.client.cartography.render.CaveRenderer.render(CaveRenderer.java:127)
	at journeymap.client.cartography.ChunkRenderController.renderChunk(ChunkRenderController.java:118)
	at journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:125)
	at journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:75)
	at journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:416)
	at journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Fatal exception thrown whilst baking block model for: thermalexpansion:tank
java.lang.NullPointerException
	at cofh.thermalexpansion.render.RenderTank.bakeLayerFace(RenderTank.java:160)
	at codechicken.lib.model.bakery.ModelBakery.generateModel(ModelBakery.java:286)
	at codechicken.lib.model.bakery.ModelBakery$$Lambda$2380/1994647688.apply(Unknown Source)
	at codechicken.lib.model.bakery.ModelBakery.timeModelGeneration(ModelBakery.java:336)
	at codechicken.lib.model.bakery.ModelBakery.getCachedModel(ModelBakery.java:244)
	at codechicken.lib.model.bakery.CCBakeryModel.func_188616_a(CCBakeryModel.java:40)
	at journeymap.client.mod.vanilla.VanillaBlockSpriteProxy.getSprites(VanillaBlockSpriteProxy.java:111)
	at journeymap.client.mod.vanilla.VanillaBlockSpriteProxy.getSprites(VanillaBlockSpriteProxy.java:77)
	at journeymap.client.mod.vanilla.VanillaBlockColorProxy.getSpriteColor(VanillaBlockColorProxy.java:124)
	at journeymap.client.mod.vanilla.VanillaBlockColorProxy.deriveBlockColor(VanillaBlockColorProxy.java:57)
	at journeymap.client.model.BlockMD.getTextureColor(BlockMD.java:453)
	at journeymap.client.mod.vanilla.VanillaBlockColorProxy.getBlockColor(VanillaBlockColorProxy.java:79)
	at journeymap.client.model.BlockMD.getBlockColor(BlockMD.java:442)
	at journeymap.client.cartography.render.BaseRenderer.setStratumColors(BaseRenderer.java:277)
	at journeymap.client.cartography.Strata.nextUp(Strata.java:209)
	at journeymap.client.cartography.render.SurfaceRenderer.paintStrata(SurfaceRenderer.java:382)
	at journeymap.client.cartography.render.SurfaceRenderer.renderSurface(SurfaceRenderer.java:190)
	at journeymap.client.cartography.render.SurfaceRenderer.render(SurfaceRenderer.java:113)
	at journeymap.client.cartography.render.SurfaceRenderer.render(SurfaceRenderer.java:86)
	at journeymap.client.cartography.ChunkRenderController.renderChunk(ChunkRenderController.java:143)
	at journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:125)
	at journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:75)
	at journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:416)
	at journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by covers1624** [comment]
The snippit you have provided is CCL catching an exception from one of our block bakeries, if you actually experienced a crash please provide the full crash report.

**Comment by KingLemming** [comment]
Yeah, this seems to be journeymap calling something wrong and us correctly NOT crashing. ;)

**Comment by Howsyomamanem** [comment]
Thx for your reply…  However, I checked the “crash-reports” folder for a recent file and non exists.  So, it’s not generating a crash report.

Additionally, the exceptions I submitted in the ticket occur sometime before the actual game crash.  The crash I’m getting doesn’t seem to generate any exception output.

Here’s a screen shot of my client “Minecraft game output” right before the last crash only a few minutes ago:

http://puu.sh/ywe8V/d26a39d20f.png

Oh well, I guess there’s not much that can be done.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by KingLemming** [comment]
Yep. That's 100% Journeymap. And we're preventing a crash, not causing it. :)
