### ISSUE TITLE
Crash with ForgeMultiparts

### ISSUE THREAD

**Issue by XakerTwo** [CoFH/Feedback#666]
Hello, and thanks for your work and regular updates.
But last two updates ThermalDynamic (build 154 and 155) crashed if i used ForgeMultipart and mods depending on it(ProjectRed, ExtraUtilities). When used ThermalDynamic build 153 all work normal. Below the log-text from the console with full list mods and their version.
<pre>
[23:01:54] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from POSTINITIALIZATION to AVAILABLE. Loading cannot continue
[23:01:54] [Client thread/ERROR] [FML]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (Forge_v10.13.4.1481.jar) 
	UCHIJ	Forge{10.13.4.1481} [Minecraft Forge] (Forge_v10.13.4.1481.jar) 
	UCHIJ	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHIJ	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJ	coloredlightscore{1.3.7.38} [Colored Lights Core] (minecraft.jar) 
	UCHIJ	asielib{0.2.7} [asielib] (AsieLib_v1.7.10.jar) 
	UCHIJ	Backpack{2.0.1} [Backpack] (BackPack_v2.0.1.jar) 
	UCHIJ	CoFHCore{1.7.10R3.0.3B2} [CoFH Core] (CoFHCore_v3.0.3b297.jar) 
	UCHIJ	BuildCraft|Core{7.0.13} [BuildCraft] (BuildCraft_v7.0.13(Core).jar) 
	UCHIJ	BuildCraft|Builders{7.0.13} [BuildCraft Builders] (BuildCraft_v7.0.13(Builders).jar) 
	UCHIJ	BuildCraft|Energy{7.0.13} [BuildCraft Energy] (BuildCraft_v7.0.13(Energy).jar) 
	UCHIJ	BuildCraft|Factory{7.0.13} [BuildCraft Factory] (BuildCraft_v7.0.13(Factory).jar) 
	UCHIJ	BuildCraft|Robotics{7.0.13} [BuildCraft Robotics] (BuildCraft_v7.0.13(Robotics).jar) 
	UCHIJ	BuildCraft|Silicon{7.0.13} [BuildCraft Silicon] (BuildCraft_v7.0.13(Silicon).jar) 
	UCHIJ	BuildCraft|Transport{7.0.13} [Buildcraft Transport] (BuildCraft_v7.0.13(Transport).jar) 
	UCHIJ	craftguide{1.6.8.2} [CraftGuide] (CraftGuide_v1.6.8.2.jar) 
	UCHIJ	DamageIndicatorsMod{3.2.3} [Damage Indicators] (DamageIndicators_v3.2.3.jar) 
	UCHIJ	props{2.0.2} [Decocraft] (DecoCraft_v2.0.2.jar) 
	UCHIJ	ThermalFoundation{1.7.10R1.2.0B1} [Thermal Foundation] (ThermalFoundation_v1.2.0b97.jar) 
	UCHIJ	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJ	ExtraUtilities{1.2.8} [Extra Utilities] (ExtraUtilities_v1.2.8.jar) 
	UCHIJ	GardenCore{1.7.10-1.6.3} [Garden Core] (GardenStuff_v1.6.3.jar) 
	UCHIJ	GardenContainers{1.7.10-1.6.3} [Garden Containers] (GardenStuff_v1.6.3.jar) 
	UCHIJ	GardenStuff{1.7.10-1.6.3} [Garden Stuff] (GardenStuff_v1.6.3.jar) 
	UCHIJ	GardenTrees{1.7.10-1.6.3} [Garden Trees] (GardenStuff_v1.6.3.jar) 
	UCHIJ	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurniture_v3.4.7.jar) 
	UCHIJ	fodc{1.6.1} [Ore Dictionary Converter] (OreDictionaryConverter_v1.6.1.jar) 
	UCHIJ	MrTJPCoreMod{1.1.0.27} [MrTJPCore] (MrTJPCore-1.1.0.27-universal.jar) 
	UCHIJ	ProjRed|Core{4.7.0pre5.89} [ProjectRed Core] (ProjectRed_v4.7.0.5.89(Base).jar) 
	UCHIJ	ProjRed|Transmission{4.7.0pre5.89} [ProjectRed Transmission] (ProjectRed_v4.7.0.5.89(Integration).jar) 
	UCHIJ	ProjRed|Transportation{4.7.0pre5.89} [ProjectRed Transportation] (ProjectRed_v4.7.0.5.89(Mechanical).jar) 
	UCHIJ	ProjRed|Exploration{4.7.0pre5.89} [ProjectRed Exploration] (ProjectRed_v4.7.0.5.89(World).jar) 
	UCHIJ	ThermalExpansion{1.7.10R4.0.2B2} [Thermal Expansion] (ThermalExpansion_v4.0.2b210.jar) 
	UCHIJ	ProjRed|Compatibility{4.7.0pre5.89} [ProjectRed Compatibility] (ProjectRed_v4.7.0.5.89(Compat).jar) 
	UCHIJ	ProjRed|Integration{4.7.0pre5.89} [ProjectRed Integration] (ProjectRed_v4.7.0.5.89(Integration).jar) 
	UCHIJ	ProjRed|Fabrication{4.7.0pre5.89} [ProjectRed Fabrication] (ProjectRed_v4.7.0.5.89(Fabrication).jar) 
	UCHIJ	ProjRed|Illumination{4.7.0pre5.89} [ProjectRed Illumination] (ProjectRed_v4.7.0.5.89(Lighting).jar) 
	UCHIJ	ProjRed|Expansion{4.7.0pre5.89} [ProjectRed Expansion] (ProjectRed_v4.7.0.5.89(Mechanical).jar) 
	UCHIJ	Railcraft{9.6.1.0} [Railcraft] (RailCraft_v9.6.1.0.jar) 
	UCHIJ	row{1.7.10-15.01.02-20.40} [Rails of War] (RailsOfWar_v15.01.02b20.40.jar) 
	UCHIJ	rfwindmill{0.7a} [RF Windmill] (RFWindMill_v0.7a.jar) 
	UCHIJ	RightClickTorch{1.0.2} [RightClickTorch] (RightClickTorch_v1.0.2.jar) 
	UCHIJ	SolarFlux{1.7.10-0.8a} [Solar Flux] (SolarFlux_v0.8a.jar) 
	UCHIJ	statues{2.1.3} [Statues] (Statues_v1.7.10.jar) 
	UCHIE	ThermalDynamics{1.7.10R1.1.0B2} [Thermal Dynamics] (ThermalDynamics_v1.1.0b155.jar)
	UCHIJ	easycoloredlights{1.3.7.38} [Easy Colored Lights] (ColoredLights_v1.3.7b38.jar) 
	UCHIJ	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJ	ForgeRelocation{0.0.1.3} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
	UCHIJ	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
	UCHIJ	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJ	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UD	asielibcore{} [AsieLib CoreMod] (minecraft.jar) 
[23:01:54] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[23:01:54] [Client thread/ERROR] [FML]: Caught exception from ThermalDynamics
java.lang.NullPointerException
	at com.rwtema.extrautils.multipart.microblock.ItemMicroBlock.func_150895_a(ItemMicroBlock.java:75) ~[ItemMicroBlock.class:?]
	at cofh.thermaldynamics.item.ItemCover.postInit(ItemCover.java:130) ~[ItemCover.class:?]
	at cofh.thermaldynamics.ThermalDynamics.postInit(ThermalDynamics.java:134) ~[ThermalDynamics.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_76]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[Forge_v10.13.4.1481.jar:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_76]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[Forge_v10.13.4.1481.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[Forge_v10.13.4.1481.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_76]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_76]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
</pre>

**Comment by KingLemming** [comment]
Hi. Please stop downloading alphas. You should only use builds posted to Curse. That's it.

**Comment by XakerTwo** [comment]
I Should? I should download and used only stable build and will be std user, but it's not interesting. Then why let build? I want to help you and to send the error/crash report on my MC assembly, is this possible? Your mod interested for me, he have many useful function and opportunities, but will can more.

**Comment by KingLemming** [comment]
Builds were done automatically by the Jenkins. I've put a stop to that to end confusion.
