### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Yoshicrafter1531** [CoFH/Feedback#679]
Help my minecraft just stop bienary and crash
Heres the Error:
-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 34673904 bytes (33 MB) / 189243392 bytes (180 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2869' Renderer: 'Intel(R) G41 Express Chipset'
[14:11:19] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[14:11:19] [Client thread/INFO] [FML]: MinecraftForge v10.13.4.1481 Initialized
[14:11:19] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[14:11:19] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[14:11:20] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[14:11:20] [Client thread/INFO] [FML]: Searching C:\Users\mendoza\AppData\Roaming\.minecraft\mods for mods
[14:11:20] [Client thread/INFO] [FML]: Also searching C:\Users\mendoza\AppData\Roaming\.minecraft\mods\1.7.10 for mods
[14:11:23] [Client thread/WARN] [DamageIndicatorsMod]: Mod DamageIndicatorsMod is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 3.2.0
[14:11:23] [Client thread/WARN] [ExtraUtilities]: Mod ExtraUtilities is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.2.6
[14:11:24] [Client thread/INFO] [FML]: Forge Mod Loader has identified 34 mods to load
[14:11:24] [Client thread/INFO] [FML]: Found mod(s) [VoltzEngine] containing declared API package cofh.api.energy (owned by CoFHAPI) without associated API reference
[14:11:24] [Client thread/INFO] [FML]: Found mod(s) [ExtraUtilities] containing declared API package baubles.api (owned by Baubles) without associated API reference
[14:11:25] [Client thread/INFO] [FML]: FML has found a non-mod file CoFHLib-[1.7.10]1.0.3B3-173.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[14:11:25] [Client thread/INFO] [FML]: FML has found a non-mod file iChunUtil-5.3.0.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[14:11:25] [Client thread/INFO] [FML]: FML has found a non-mod file Localized-Weather-Stormfronts-Mod-1.7.10.zip in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[14:11:25] [Client thread/INFO] [FML]: FML has found a non-mod file CodeChickenLib-1.7.10-1.1.1.99-universal.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[14:11:25] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, NotEnoughItems, <CoFH ASM>, Trapcraft, DamageIndicatorsMod, Treecapitator, CarpentersBlocks, CoFHCore, BuildMod, CoroAI, ExtendedRenderer, ConfigMod, DragonMounts, EnderTech, ExtraUtilities, HopperDuctMod, icbm, iChunUtil, JABBA, lasermod, LittleBlocks, lootbags, magicalcrops, Morph, SlimevoidLib, ThermalExpansion, ThermalFoundation, treeGrowingSimulator, VoltzEngine, XaeroMinimap, bspkrsCore] at CLIENT
[14:11:25] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, NotEnoughItems, <CoFH ASM>, Trapcraft, DamageIndicatorsMod, Treecapitator, CarpentersBlocks, CoFHCore, BuildMod, CoroAI, ExtendedRenderer, ConfigMod, DragonMounts, EnderTech, ExtraUtilities, HopperDuctMod, icbm, iChunUtil, JABBA, lasermod, LittleBlocks, lootbags, magicalcrops, Morph, SlimevoidLib, ThermalExpansion, ThermalFoundation, treeGrowingSimulator, VoltzEngine, XaeroMinimap, bspkrsCore] at SERVER
[14:11:27] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Trapcraft, FMLFileResourcePack:Damage Indicators, FMLFileResourcePack:Treecapitator, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Build Mod, FMLFileResourcePack:CoroAI, FMLFileResourcePack:Extended Renderer, FMLFileResourcePack:Extended Mod Config, FMLFileResourcePack:Dragon Mounts, FMLFileResourcePack:EnderTech, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:Hopper Ducts, FMLFileResourcePack:ICBM, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:JABBA, FMLFileResourcePack:Laser Mod, FMLFileResourcePack:Little Blocks, FMLFileResourcePack:Loot Bags, FMLFileResourcePack:Magical Crops, FMLFileResourcePack:Morph, FMLFileResourcePack:Slimevoid Library, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:Tree Growing Simulator 2014, FMLFileResourcePack:Voltz Engine, FMLFileResourcePack:Xaero's Minimap, FMLFileResourcePack:bspkrsCore
[14:11:27] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[14:11:27] [Client thread/INFO] [FML]: Found 337 ObjectHolder annotations
[14:11:27] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[14:11:27] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[14:11:27] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[14:11:28] [Client thread/WARN] [FML]: ****************************************
[14:11:28] [Client thread/WARN] [FML]: * Illegal extra prefix trapcraft for name trapcraft:igniterrange, invalid registry invocation/invalid name?
[14:11:28] [Client thread/WARN] [FML]: *  at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:805)
[14:11:28] [Client thread/WARN] [FML]: *  at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:149)
[14:11:28] [Client thread/WARN] [FML]: *  at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:137)
[14:11:28] [Client thread/WARN] [FML]: *  at trapcraft.TrapcraftMod.preLoad(TrapcraftMod.java:109)
[14:11:28] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:11:28] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[14:11:28] [Client thread/WARN] [FML]: ****************************************
[14:11:28] [Client thread/INFO] [Treecapitator]: Loading configuration file C:\Users\mendoza\AppData\Roaming\.minecraft\config\Treecapitator.cfg
[14:11:28] [Client thread/INFO] [Treecapitator]: Proceeding to load tree/mod configs from file.
[14:11:28] [Client thread/INFO] [CarpentersBlocks]: Designs found: Bed(6), Chisel(9), FlowerPot(18), Tile(13)
??? PLS AWNSER ME

**Comment by KingLemming** [comment]
Well done. You didn't read the README at all. This is 1) a tech support request, NOT an issue, and 2) there is LITERALLY NOTHING in this log that points to CoFH in any way.

**Comment by Yoshicrafter1531** [comment]
XD LEL IDK WHERE THE BUTTON

**Comment by Yoshicrafter1531** [comment]
sry  idk wheres the support tech
