### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by loordgek** [CoFH/Feedback#692]
https://gist.github.com/loordgek/5e49af8eca923294b710

using Agrarian Skies 2
ThermalExpansion-[1.7.10]4.0.2B2-210

java.lang.NullPointerException: Ticking block entity
	at cofh.thermalexpansion.block.machine.TilePulverizer.processFinish(TilePulverizer.java:117)
	at cofh.thermalexpansion.block.machine.TileMachineBase.func_145845_h(TileMachineBase.java:105)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by KingLemming** [comment]
AG2 is out of date.
