### ISSUE TITLE
Critical error reading from a world generation file for MC 1.12.2

### ISSUE THREAD

**Issue by trilexcom** [CoFH/Feedback#708]
hi COFH team 

Forge : 2556
MC 1.12.2
Crashlog file : https://pastebin.com/NWMF4wvg
COFH Core version : COFHCore -1.12.2-4.3.7.25 universal
COFH World- cofhworld-1.12.2-1.0.2.10 

we are getting console error from COFH world below are is the error msg.

Critical error reading from a world generation file: "C:\Users\admin\Documents\Curse\Minecraft\Instances\Trilex Pack\config\cofh\world\01_thermalfoundation_ores.json" > Please be sure the file is correct!
cofh.shade.com.typesafe.config.ConfigException$Parse: C:\Users\admin\Documents\Curse\Minecraft\Instances\Trilex Pack\config\cofh\world\01_thermalfoundation_ores.json: 181: unbalanced close brace '}' with no open brace (if you intended '}' to be part of a key or string value, try enclosing the key or value in double quotes)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:435)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:431)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:741)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993)
	at cofh.shade.com.typesafe.config.impl.Parser.parse(Parser.java:34)
	at cofh.shade.com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222)
	at cofh.shade.com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:210)
	at cofh.shade.com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
	at cofh.shade.com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
	at cofh.shade.com.typesafe.config.impl.Parseable.parse(Parseable.java:227)
	at cofh.shade.com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:595)
	at cofh.cofhworld.init.FeatureParser.parseGenerationFiles(FeatureParser.java:142)
	at cofh.cofhworld.init.WorldHandler.reloadConfig(WorldHandler.java:108)
	at cofh.cofhworld.CoFHWorld.loadComplete(CoFHWorld.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:727)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Critical error reading from a world generation file: "C:\Users\admin\Documents\Curse\Minecraft\Instances\Trilex Pack\config\cofh\world\03_thermalfoundation_clathrates.json" > Please be sure the file is correct!
cofh.shade.com.typesafe.config.ConfigException$Parse: C:\Users\admin\Documents\Curse\Minecraft\Instances\Trilex Pack\config\cofh\world\03_thermalfoundation_clathrates.json: 95: unbalanced close brace '}' with no open brace (if you intended '}' to be part of a key or string value, try enclosing the key or value in double quotes)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:435)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:431)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:741)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993)
	at cofh.shade.com.typesafe.config.impl.Parser.parse(Parser.java:34)
	at cofh.shade.com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222)
	at cofh.shade.com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:210)
	at cofh.shade.com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
	at cofh.shade.com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
	at cofh.shade.com.typesafe.config.impl.Parseable.parse(Parseable.java:227)
	at cofh.shade.com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:595)
	at cofh.cofhworld.init.FeatureParser.parseGenerationFiles(FeatureParser.java:142)
	at cofh.cofhworld.init.WorldHandler.reloadConfig(WorldHandler.java:108)
	at cofh.cofhworld.CoFHWorld.loadComplete(CoFHWorld.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:727)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
17:05:58	cofhworld	main	Critical error reading from a world generation file: "C:\Users\admin\Documents\Curse\Minecraft\Instances\Trilex Pack\config\cofh\world\bauxitealum_ores.json" > Please be sure the file is correct!
cofh.shade.com.typesafe.config.ConfigException$Parse: C:\Users\admin\Documents\Curse\Minecraft\Instances\Trilex Pack\config\cofh\world\bauxitealum_ores.json: 26: unbalanced close brace '}' with no open brace (if you intended '}' to be part of a key or string value, try enclosing the key or value in double quotes)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:435)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:431)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:741)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993)
	at cofh.shade.com.typesafe.config.impl.Parser.parse(Parser.java:34)
	at cofh.shade.com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222)
	at cofh.shade.com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:210)
	at cofh.shade.com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
	at cofh.shade.com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
	at cofh.shade.com.typesafe.config.impl.Parseable.parse(Parseable.java:227)
	at cofh.shade.com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:595)
	at cofh.cofhworld.init.FeatureParser.parseGenerationFiles(FeatureParser.java:142)
	at cofh.cofhworld.init.WorldHandler.reloadConfig(WorldHandler.java:108)
	at cofh.cofhworld.CoFHWorld.loadComplete(CoFHWorld.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:727)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
17:05:58	cofhworld	main	Critical error reading from a world generation file: "C:\Users\admin\Documents\Curse\Minecraft\Instances\Trilex Pack\config\cofh\world\forestry_ores.json" > Please be sure the file is correct!
cofh.shade.com.typesafe.config.ConfigException$Parse: C:\Users\admin\Documents\Curse\Minecraft\Instances\Trilex Pack\config\cofh\world\forestry_ores.json: 24: unbalanced close brace '}' with no open brace (if you intended '}' to be part of a key or string value, try enclosing the key or value in double quotes)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:435)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:431)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:741)
	at cofh.shade.com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993)
	at cofh.shade.com.typesafe.config.impl.Parser.parse(Parser.java:34)
	at cofh.shade.com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222)
	at cofh.shade.com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:210)
	at cofh.shade.com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
	at cofh.shade.com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
	at cofh.shade.com.typesafe.config.impl.Parseable.parse(Parseable.java:227)
	at cofh.shade.com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:595)
	at cofh.cofhworld.init.FeatureParser.parseGenerationFiles(FeatureParser.java:142)
	at cofh.cofhworld.init.WorldHandler.reloadConfig(WorldHandler.java:108)
	at cofh.cofhworld.CoFHWorld.loadComplete(CoFHWorld.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:727)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by KingLemming** [comment]
Either your pack didn't download properly or your packmaker has broken the json.

**Comment by trilexcom** [comment]
thanks
