### ISSUE TITLE
[Thermal Expansion] Error parsing fluidstack in crafting config

### ISSUE THREAD

**Issue by metoray** [CoFH/Feedback#758]
FluidStacks will parse fine when only specifying a name but wil throw an error when adding other information.

Error:
```
[22:02:15] [Client thread/INFO] [ThermalExpansion/ThermalExpansion]: 1 crafting files present in /home/metoray/.minecraft/config/cofh/thermalexpansion/crafting/.
[22:02:15] [Client thread/INFO] [ThermalExpansion/ThermalExpansion]: Reading template info from: /home/metoray/.minecraft/config/cofh/thermalexpansion/crafting/test.json:
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.UnsupportedOperationException: JsonObject
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.thermalexpansion.util.crafting.TECraftingParser.parseFluidStack(TECraftingParser.java:740)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.thermalexpansion.util.crafting.TECraftingParser.addTransposerRecipe(TECraftingParser.java:393)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.thermalexpansion.util.crafting.TECraftingParser.acquireCraftingEntry(TECraftingParser.java:129)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.thermalexpansion.util.crafting.TECraftingParser.parseCraftingFiles(TECraftingParser.java:94)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.thermalexpansion.ThermalExpansion.postInit(ThermalExpansion.java:166)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[22:02:15] [Client thread/INFO] [STDERR/ThermalExpansion]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

The contents of test.json:
```
{
	"test": {
		"type": "transposer",
		"input": {
			"name": "minecraft:wool",
			"meta": 3
		},
		"output": {
			"name": "minecraft:dirt",
			"meta": 0
		},
		"fluid": {
			"name": "cryotheum",
			"amount": 250
		},
		"energy": 2000
	}
}
```

**Comment by KingLemming** [comment]
Right, the feature isn't released yet. We haven't announced anything and there is no documentation.

Why have you tried using it?

**Comment by metoray** [comment]
Sorry, I tried using it because MineTweaker no longer seems to  support it.

**Comment by KingLemming** [comment]
No worries. We'll let you know when it's ready. ATM it tries to parse things but won't add new recipes, it just isn't finished yet.
