### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by mrlamb** [CoFH/Feedback#780]
We've been getting an odd crash tonight that's referencing your mod (Thermal Expansion I think) as well as Gendustry so I'm posting to both of you in hopes we can figure out what's going on. The crash seems to happen when breaking an industrial apiary. This apiary was connected to a leadstone fluxduct. It hasn't happened every time we've broken it until recently. By that I mean I broke one a few times in the last couple days and no crash, however another player broke two tonight and crashed both times. This latest crash affected all three who were logged into the server, but apparently the server continued on with no problem (expected, honestly as it appeared to be a rendering problem).

Modpack: Direwolf20 for 1.12.2 on the latest release version via twitch.
Crash log: https://pastebin.com/67azCyy8

I'll be happy to provide any more information you might need, just let me know.

**Comment by mrlamb** [comment]
#bdew/gendustry/issues/253

**Comment by KingLemming** [comment]
Yeah, without screenshots of the area, there's not a whole lot we can do. Can you provide some please?

Offhand this *sounds* like it is Gendustry's fault.

**Comment by mrlamb** [comment]
Absolutely. I'll annoy the crap out of my server mates tonight, crash it a few times, and get those screenshots.

**Comment by mrlamb** [comment]
Screenshots:
https://www.dropbox.com/s/1seqgjyc7qq4ita/Screenshot%202017-12-29%2021.31.48.png?dl=0

And actually I didn't have this info last night because I thought it was another apiary that he had crashed the server. Turns out it was just this one... which happens to be adjacent to a thermal tank!

Breaking the tank first, then the apiary prevents the crash.

**Comment by KingLemming** [comment]
Thanks for the screenshot.

Thing is, I can't make this happen. Like, literally just does not happen.

**Comment by mrlamb** [comment]
We sure could that one night. Let me play around with it in single player a bit and try to recreate the setup. Maybe it's just a server thing, but I assume you tested that possibility?

**Comment by mrlamb** [comment]
Got it to crash two times in a row and I think I may have found a contributing factor. It occurred to me that the guy must have had some gendustry upgrades in the apiary. Most likely culprits: automation, lighting and open sky.

With all three it crashed, so I tried one at a time and the lighting one crashed it right off. The lighting upgrade does cause a change in the light level of the area around it which perhaps is interacting with the tank in a weird way.

Reloading again to try a third time, but as soon as I started punching the apiary it triggered the crash once the lighting upgrade was in place.

**Comment by KingLemming** [comment]
This is entirely a gendustry (bdlib, actually) issue. Assumptions are being made during the lighting update which are absolutely incorrect. What ends up happening is that the tile entity isn't found and is forcibly replaced, causing a crash.

Attempting to break the apiary (w/ lighting upgrade) with a vanilla chest next to it results in this:

`[08:37:40] [main/WARN] [bdlib]: Tile entity for block Block{gendustry:industrial_apiary} at (-206,68,-45) is corrupt or missing - recreating
[08:37:40] [main/WARN] [bdlib]: Error retrieving TE of type net.bdew.gendustry.machines.apiary.BlockApiary$ at BlockPos{x=-206, y=68, z=-45} (world is net.minecraft.client.multiplayer.WorldClient)
java.lang.IllegalArgumentException: Don't know how to convert minecraft:chest[facing=north] back into data...
	at net.minecraft.block.Block.getMetaFromState(Block.java:204) ~[Block.class:?]
	at net.minecraft.block.Block.createTileEntity(Block.java:1274) ~[Block.class:?]
	at net.bdew.lib.block.HasTE$class.getTE(HasTE.scala:54) ~[HasTE$class.class:?]
	at net.bdew.gendustry.machines.apiary.BlockApiary$.getTE(BlockApiary.scala:25) ~[BlockApiary$.class:?]
	at net.bdew.lib.block.HasTE$class.getTE(HasTE.scala:69) [HasTE$class.class:?]
	at net.bdew.gendustry.machines.apiary.BlockApiary$.getTE(BlockApiary.scala:25) [BlockApiary$.class:?]
	at net.bdew.gendustry.machines.apiary.BlockApiary$.getLightValue(BlockApiary.scala:34) [BlockApiary$.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getLightValue(BlockStateContainer.java:510) [BlockStateContainer$StateImplementation.class:?]
	at net.minecraft.block.Block.getPackedLightmapCoords(Block.java:378) [Block.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getPackedLightmapCoords(BlockStateContainer.java:362) [BlockStateContainer$StateImplementation.class:?]
	at net.minecraftforge.client.model.pipeline.BlockInfo.updateFlatLighting(BlockInfo.java:170) [BlockInfo.class:?]
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.updateBlockInfo(VertexLighterFlat.java:298) [VertexLighterFlat.class:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:134) [ForgeBlockModelRenderer.class:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelFlat(ForgeBlockModelRenderer.java:82) [ForgeBlockModelRenderer.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:47) [BlockModelRenderer.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:38) [BlockModelRenderer.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlockDamage(BlockRendererDispatcher.java:47) [BlockRendererDispatcher.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.renderBlockDamage(CCBlockRendererDispatcher.java:39) [CCBlockRendererDispatcher.class:?]
	at net.minecraft.client.renderer.RenderGlobal.drawBlockDamageTexture(RenderGlobal.java:1937) [RenderGlobal.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1373) [EntityRenderer.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259) [EntityRenderer.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062) [EntityRenderer.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1117) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:397) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [MinecraftForge/:?]
	at GradleStart.main(GradleStart.java:26) [MinecraftForge/:?]`

being spammed in the log continually. The vanilla chest doesn't freak out due to how it renders, but our stuff does, because tiles should NEVER be forcibly replaced in that manner.

Closing this down, @covers1624 will submit a report to bdlib.
