### ISSUE TITLE
Java issue when loading CoFHcore

### ISSUE THREAD

**Issue by NaomiBloodwing** [CoFH/Feedback#784]
when the forge gets to loading CoFHcore it causes the java to fail and and for the new thermal expansion mod it wont let me use any CoFHcore older than CoFHcore 3.0.3 but 3.0.3 and newer isnt working and having the same problem as I said. Is there any way to fix this problem/

**Comment by Frenzy2121** [comment]
I have the same problem, I have Java 8, and any version of CoFH core will crash my minecraft when it loads and java will tell me "Java SE Binary has stopped working".

Here is a crash report with CoFH core as the only mod:

[19:30:42] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[19:30:42] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[19:30:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[19:30:43] [main/INFO] [FML]: Forge Mod Loader version 7.10.140.1401 for Minecraft 1.7.10 loading
[19:30:43] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows Vista:amd64:6.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[19:30:43] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:30:43] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:30:43] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[19:30:43] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:30:43] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:30:43] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:30:45] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[19:30:45] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[19:30:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:30:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[19:30:45] [main/INFO] [STDOUT]: [cofh.asm.CoFHAccessTransformer:readMappingFile:40]: Adding Accesstransformer map: CoFH_at.cfg
[19:30:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:30:46] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[19:30:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[19:30:46] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:30:48] [main/INFO]: Setting user: Frenzy212121
[19:30:51] [Client thread/INFO]: LWJGL Version: 2.9.1
[19:30:53] [Client thread/INFO] [STDOUT]: [cpw.mods.fml.client.SplashProgress:start:178]: ---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 8/13/15 7:30 PM
Description: Loading screen debug info

java.lang.Throwable
	at cpw.mods.fml.client.SplashProgress.start(SplashProgress.java:177)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:191)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows Vista (amd64) version 6.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5920726088 bytes (5646 MB) / 6174015488 bytes (5888 MB) up to 6174015488 bytes (5888 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms6144m -XX:MaxPermSize=128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2104' Renderer: 'Intel(R) HD Graphics'
[19:30:53] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[19:30:53] [Client thread/INFO] [FML]: MinecraftForge v10.13.3.1401 Initialized
[19:30:53] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[19:30:53] [Client thread/INFO] [FML]: Preloading CrashReport classes
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.World$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.World$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.World$3
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.World$4
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.chunk.Chunk$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$3
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.entity.Entity$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.entity.Entity$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.entity.EntityTracker$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.layer.GenLayer$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.layer.GenLayer$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.entity.player.InventoryPlayer$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$3
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$3
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$4
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$5
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.nbt.NBTTagCompound$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.nbt.NBTTagCompound$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.network.NetHandlerPlayServer$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.network.NetworkSystem$3
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$3
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$3
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$4
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$5
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$6
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$7
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$8
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$9
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$3
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$4
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$5
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$6
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$7
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$8
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$9
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$10
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$11
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$12
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$13
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$14
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$15
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$3
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$4
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$3
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$4
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.EntityRenderer$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.EntityRenderer$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.EntityRenderer$3
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.server.integrated.IntegratedServer$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.server.integrated.IntegratedServer$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.RenderGlobal$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$3
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$4
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureAtlasSprite$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureManager$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureMap$1
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureMap$2
[19:30:53] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureMap$3
[19:30:53] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[19:30:54] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[19:30:54] [Client thread/INFO] [FML]: Searching C:\Users\Rahn\AppData\Roaming\.minecraft\mods for mods
[19:30:59] [Client thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[19:30:59] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, <CoFH ASM>, CoFHCore] at CLIENT
[19:30:59] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, <CoFH ASM>, CoFHCore] at SERVER
[19:31:00] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:CoFH Core
[19:31:00] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[19:31:00] [Client thread/INFO] [FML]: Found 337 ObjectHolder annotations
[19:31:00] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0

(Sorry its pasted like that  don't know how to make it a link)

Everything I tried by looking at other solutions to the same problem hasn't worked.

**Comment by KingLemming** [comment]
Sounds like you should disable FML's splash screen.

**Comment by XFactHD** [comment]
This isn't even a crash even though it looks like one. The only purpose is for the Forge team to get some information about the software and hardware of your computer that is used by Minecraft to improve the splash screen.

**Comment by NaomiBloodwing** [comment]
how do you disable the FML's splash screen? @KingLemming

**Comment by cabralRodrigo** [comment]
@NaomiBloodwing Check the config file.

**Comment by Frenzy2121** [comment]
i have already tried disabling the loading screen, that didn't work either

**Comment by oscarwn1** [comment]
it says i need coFH Core minimum 1.7.10R3.0.0 i have 3.0.1 how can i fix this
