### ISSUE TITLE
TE4 Unable to place energy cells when recipe is disabled

### ISSUE THREAD

**Issue by keenerb** [CoFH/Feedback#822]
Forge 1481 and 1492.

CoFHCore-[1.7.10]3.0.3-303
ThermalExpansion-[1.7.10]4.0.3B1-218
ThermalFoundation-[1.7.10]1.2.0-102

Setting Recipe.Enable=false for energy cells make them unplaceable in the world.  I haven't noticed this with any other blocks.

SSP reports no issue in logs, but multiplayer server reports:

```
[17:29:30 ERROR]: Packet payload failure! Please check your config files!
[17:29:30 WARN]: java.lang.NullPointerException
[17:29:30 WARN]:        at cofh.thermalexpansion.network.PacketTEBase.handlePacket(PacketTEBase.java:42)
[17:29:30 WARN]:        at cofh.core.network.PacketCoFHBase.handleServerSide(PacketCoFHBase.java:376)
[17:29:30 WARN]:        at cofh.core.network.PacketHandler.decode(PacketHandler.java:104)
[17:29:30 WARN]:        at cofh.core.network.PacketHandler.decode(PacketHandler.java:40)
[17:29:30 WARN]:        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
[17:29:30 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
[17:29:30 WARN]:        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[17:29:30 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[17:29:30 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[17:29:30 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[17:29:30 WARN]:        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[17:29:30 WARN]:        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[17:29:30 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[17:29:30 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[17:29:30 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[17:29:30 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[17:29:30 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[17:29:30 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[17:29:30 WARN]:        at java.lang.Thread.run(Thread.java:745)

```

**Comment by KingLemming** [comment]
Can't recreate this nor is there literally any reason at all that this would occur.

Your server and client have something mismatched.

**Comment by keenerb** [comment]
It is happening in single player as well.  I will attach the configs i am using shortly.

**Comment by keenerb** [comment]
http://modpacks.roleplayga.org/modpacks/cofh.zip

With that set of configs, only the creative energy cell is placeable in the world, although existing energy cells seem to work fine.

Those configs are my attempt to disable crafting of virtually all TE items for a specialized survival server.

**Comment by keenerb** [comment]
https://www.youtube.com/watch?v=8ZQ6VlNiB7s

There's the issue captured in video.

**Comment by Tora-B** [comment]
Shift+Left-Click to break caches in creative.

**Comment by keenerb** [comment]
That makes sense Tora-B, I didn't really think it was related but I wasn't sure.
