### ISSUE TITLE
[Client Crash] [1.12] Old augments crash client on machine GUI open. 

### ISSUE THREAD

**Issue by thundR** [CoFH/Feedback#839]
After updating to a version where the Ender substrate is no longer an augment, client will crash if you open the augment tab. Expected, but probably should have some safety in there, maybe check NBT on placement for old augments. 

TE v: 1.12.2-5.3.7.31-universal
log: 
```
java.lang.NullPointerException: Rendering screen
	at cofh.thermalexpansion.item.ItemAugment.getAugmentType(ItemAugment.java:166)
	at cofh.thermalexpansion.item.ItemAugment.func_77624_a(ItemAugment.java:67)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.gui.GuiScreen.func_191927_a(GuiScreen.java:143)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at cofh.core.gui.GuiContainerCore.func_73863_a(GuiContainerCore.java:146)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:353)
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:555)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1449)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by KingLemming** [comment]
It wasn't a dumb issue, it had just been fixed already. ;)
