### ISSUE TITLE
Severe lag in some areas, NPE in client

### ISSUE THREAD

**Issue by Baughn** [CoFH/Feedback#849]
When walking into one area, players on my servers get the below error, along with a multi-second client stall. What am I supposed to be checking the config files for?

[19:03:29] [Client thread/ERROR] [ThermalExpansion]: Packet payload failure! Please check your config files!
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cofh.thermalexpansion.network.PacketTEBase.handlePacket(PacketTEBase.java:37)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cofh.core.network.PacketCoFHBase.handleClientSide(PacketCoFHBase.java:367)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cofh.core.network.PacketHandler.decode(PacketHandler.java:98)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cofh.core.network.PacketHandler.decode(PacketHandler.java:40)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.client.main.Main.main(SourceFile:148)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.reflect.Method.invoke(Method.java:497)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:03:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Baughn** [comment]
minecraft:modpack/ (master✗) $ ls|grep -i therm                      [18:17:48]
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.0.3B1-218.jar
ThermalFoundation-[1.7.10]1.2.0-102.jar

**Comment by Baughn** [comment]
This appears to happen when approaching a base which is not chunkloaded.

**Comment by KingLemming** [comment]
That error message was written back when you had control over IDs. Basically your world has been corrupted somehow, possibly through installing and uninstalling mods and FML/Forge mismanaging the internal map.

Sorry, but this isn't our fault nor can we fix it. :( Welcome to the post-ID era of 1.7.

**Comment by Baughn** [comment]
Would it be possible to add the exact IDs involved to the error message? That'd help me debug the map and/or filter out those items.

**Comment by Baughn** [comment]
More info: This is caused by placing a not-chunkloaded tesseract.

It does not appear to be ID map corruption, as the tesseract functions normally if it is chunkloaded.
