### ISSUE TITLE
cofh.thermalfoundation.block.BlockOre.getLightValue(BlockOre.java:51)

### ISSUE THREAD

**Issue by matrix2021** [CoFH/Feedback#85]
java.lang.ArrayIndexOutOfBoundsException: 11
	at cofh.thermalfoundation.block.BlockOre.getLightValue(BlockOre.java:51)
	at net.minecraft.block.Block.func_149677_c(Block.java:528)
	at net.minecraft.client.renderer.RenderBlocks.func_147736_d(RenderBlocks.java:6570)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4716)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:307)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:325)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2256)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1333)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at launcher.client.ClientLauncher.launch(ClientLauncher.java:313)
	at launcher.client.ClientLauncher.main(ClientLauncher.java:196)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cofh.thermalfoundation.block.BlockOre.getLightValue(BlockOre.java:51)
	at net.minecraft.block.Block.func_149677_c(Block.java:528)
	at net.minecraft.client.renderer.RenderBlocks.func_147736_d(RenderBlocks.java:6570)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4716)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:307)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:325)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2256)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1333)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Matrix'/1720467, l='MpServer', x=5167.61, y=78.99, z=-179.35]]
	Chunk stats: MultiplayerChunkCache: 93, 93
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-3859,63,-2281), Chunk: (at 13,3,7 in -242,-143; contains blocks -3872,0,-2288 to -3857,255,-2273), Region: (-8,-5; contains chunks -256,-160 to -225,-129, blocks -4096,0,-2560 to -3585,255,-2049)
	Level time: 2956064 game time, 638080 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 20 total; [EntityPig['Ñâèíüÿ'/1680398, l='MpServer', x=5194.94, y=64.00, z=-200.78], EntityFallingBlock['Ïàäàþùèé áëîê'/1715203, l='MpServer', x=5160.50, y=24.49, z=-182.50], EntityFallingBlock['Ïàäàþùèé áëîê'/1715204, l='MpServer', x=5161.50, y=24.49, z=-183.50], EntityPig['Ñâèíüÿ'/1680317, l='MpServer', x=5197.84, y=70.00, z=-158.66], EntityCreeper['Êðèïåð'/1695537, l='MpServer', x=5152.50, y=51.00, z=-177.50], EntityClientPlayerMP['Matrix'/1720467, l='MpServer', x=5167.61, y=78.99, z=-179.35], EntityFallingBlock['Ïàäàþùèé áëîê'/1718836, l='MpServer', x=5160.50, y=26.49, z=-182.50], EntityPig['Ñâèíüÿ'/1680310, l='MpServer', x=5158.84, y=69.00, z=-157.75], EntityFallingBlock['Ïàäàþùèé áëîê'/1718837, l='MpServer', x=5161.50, y=27.49, z=-183.50], EntityCaveSpider['Ïåùåðíûé ïàóê'/1584, l='MpServer', x=16.41, y=-60.99, z=2.60], EntityPig['Ñâèíüÿ'/1680290, l='MpServer', x=5200.16, y=70.00, z=-148.16], EntityItem['item.tile.gravel'/1721182, l='MpServer', x=5202.13, y=22.13, z=-153.69], EntityItem['item.tile.gravel'/1721183, l='MpServer', x=5203.38, y=22.13, z=-152.97], EntityItem['item.tile.doublePlant.sunflower'/1720530, l='MpServer', x=5144.78, y=63.13, z=-177.13], EntityItem['item.tile.gravel'/1721163, l='MpServer', x=5201.66, y=22.13, z=-152.84], EntityPig['Ñâèíüÿ'/1680333, l='MpServer', x=5147.75, y=67.00, z=-150.84], EntityItem['item.item.seeds'/1718770, l='MpServer', x=5166.38, y=63.13, z=-190.28], EntityItem['item.item.seeds'/1720560, l='MpServer', x=5202.25, y=69.13, z=-153.13], EntityItem['item.item.seeds'/1718769, l='MpServer', x=5156.75, y=63.13, z=-178.63], EntityItem['item.tile.gravel'/1721192, l='MpServer', x=5202.16, y=22.13, z=-155.44]]
	Retry entities: 0 total; []
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at launcher.client.ClientLauncher.launch(ClientLauncher.java:313)
	at launcher.client.ClientLauncher.main(ClientLauncher.java:196)

**Comment by AmdKing** [comment]
Seems like a block's position is illegal, mod can't get x,y,z of that block.

return LIGHT[world.getBlockMetadata(x, y, z)]; 
This code should be like this:
try
{
    return LIGHT[world.getBlockMetadata(x, y, z)];
}
catch            
{
    return LIGHT[1];
}

**Comment by KingLemming** [comment]
The code shouldn't *have* to be like that. This is caused by a mod grabbing our block and using it to calculate light on *another* block.

**Comment by AmdKing** [comment]
But at least try and catch will prevent game crashing(?)

**Comment by KingLemming** [comment]
It is not. try/catch is slow and it shouldn't need to be there. It hides errors. The correct course of action is to find the mod at fault and fix it.

**Comment by KingLemming** [comment]
Also, just realized this is for 1.7.10. This doesn't need to be addressed. I'm sorry that you have an incorrect mod, but there's nothing to do on our end.
