### ISSUE TITLE
Thermal dynamics error in console anlong with issues from #849

### ISSUE THREAD

**Issue by deadgamer1030** [CoFH/Feedback#856]
I get this error when ever i save my world.

[01:37:29] [pool-7-thread-1/ERROR] [FML]: A TileEntity type cofh.thermaldynamics.duct.item.TileItemDuct has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at cofh.thermaldynamics.duct.attachments.ConnectionBase.writeToNBT(ConnectionBase.java:63) ~[ConnectionBase.class:?]
	at cofh.thermaldynamics.block.TileTDBase.func_145841_b(TileTDBase.java:716) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.duct.item.TileItemDuct.func_145841_b(TileItemDuct.java:477) ~[TileItemDuct.class:?]
	at mapwriter.region.MwChunk.writeChunkToNBT(MwChunk.java:366) [MwChunk.class:?]
	at mapwriter.region.MwChunk.write(MwChunk.java:399) [MwChunk.class:?]
	at mapwriter.tasks.SaveChunkTask.run(SaveChunkTask.java:17) [SaveChunkTask.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
[01:37:29] [pool-7-thread-1/ERROR] [FML]: A TileEntity type cofh.thermaldynamics.duct.fluid.TileFluidDuct has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at cofh.thermaldynamics.duct.attachments.ConnectionBase.writeToNBT(ConnectionBase.java:63) ~[ConnectionBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoBase.writeToNBT(ServoBase.java:53) ~[ServoBase.class:?]
	at cofh.thermaldynamics.block.TileTDBase.func_145841_b(TileTDBase.java:716) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.duct.fluid.TileFluidDuct.func_145841_b(TileFluidDuct.java:384) ~[TileFluidDuct.class:?]
	at mapwriter.region.MwChunk.writeChunkToNBT(MwChunk.java:366) [MwChunk.class:?]
	at mapwriter.region.MwChunk.write(MwChunk.java:399) [MwChunk.class:?]
	at mapwriter.tasks.SaveChunkTask.run(SaveChunkTask.java:17) [SaveChunkTask.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
[01:37:30] [pool-7-thread-1/ERROR] [FML]: A TileEntity type cofh.thermaldynamics.duct.item.TileItemDuct has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at cofh.thermaldynamics.duct.attachments.ConnectionBase.writeToNBT(ConnectionBase.java:63) ~[ConnectionBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoBase.writeToNBT(ServoBase.java:53) ~[ServoBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.writeToNBT(ServoItem.java:59) ~[ServoItem.class:?]
	at cofh.thermaldynamics.block.TileTDBase.func_145841_b(TileTDBase.java:716) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.duct.item.TileItemDuct.func_145841_b(TileItemDuct.java:477) ~[TileItemDuct.class:?]
	at mapwriter.region.MwChunk.writeChunkToNBT(MwChunk.java:366) [MwChunk.class:?]
	at mapwriter.region.MwChunk.write(MwChunk.java:399) [MwChunk.class:?]
	at mapwriter.tasks.SaveChunkTask.run(SaveChunkTask.java:17) [SaveChunkTask.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
[01:37:30] [pool-7-thread-1/ERROR] [FML]: A TileEntity type cofh.thermaldynamics.duct.fluid.TileFluidDuct has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at cofh.thermaldynamics.duct.attachments.ConnectionBase.writeToNBT(ConnectionBase.java:63) ~[ConnectionBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoBase.writeToNBT(ServoBase.java:53) ~[ServoBase.class:?]
	at cofh.thermaldynamics.block.TileTDBase.func_145841_b(TileTDBase.java:716) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.duct.fluid.TileFluidDuct.func_145841_b(TileFluidDuct.java:384) ~[TileFluidDuct.class:?]
	at mapwriter.region.MwChunk.writeChunkToNBT(MwChunk.java:366) [MwChunk.class:?]
	at mapwriter.region.MwChunk.write(MwChunk.java:399) [MwChunk.class:?]
	at mapwriter.tasks.SaveChunkTask.run(SaveChunkTask.java:17) [SaveChunkTask.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
[01:37:30] [pool-7-thread-1/ERROR] [FML]: A TileEntity type cofh.thermaldynamics.duct.fluid.TileFluidDuct has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at cofh.thermaldynamics.duct.attachments.ConnectionBase.writeToNBT(ConnectionBase.java:63) ~[ConnectionBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoBase.writeToNBT(ServoBase.java:53) ~[ServoBase.class:?]
	at cofh.thermaldynamics.block.TileTDBase.func_145841_b(TileTDBase.java:716) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.duct.fluid.TileFluidDuct.func_145841_b(TileFluidDuct.java:384) ~[TileFluidDuct.class:?]
	at mapwriter.region.MwChunk.writeChunkToNBT(MwChunk.java:366) [MwChunk.class:?]
	at mapwriter.region.MwChunk.write(MwChunk.java:399) [MwChunk.class:?]
	at mapwriter.tasks.SaveChunkTask.run(SaveChunkTask.java:17) [SaveChunkTask.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
[01:37:30] [pool-7-thread-1/ERROR] [FML]: A TileEntity type cofh.thermaldynamics.duct.item.TileItemDuct has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at cofh.thermaldynamics.duct.attachments.ConnectionBase.writeToNBT(ConnectionBase.java:63) ~[ConnectionBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoBase.writeToNBT(ServoBase.java:53) ~[ServoBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.writeToNBT(ServoItem.java:59) ~[ServoItem.class:?]
	at cofh.thermaldynamics.block.TileTDBase.func_145841_b(TileTDBase.java:716) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.duct.item.TileItemDuct.func_145841_b(TileItemDuct.java:477) ~[TileItemDuct.class:?]
	at mapwriter.region.MwChunk.writeChunkToNBT(MwChunk.java:366) [MwChunk.class:?]
	at mapwriter.region.MwChunk.write(MwChunk.java:399) [MwChunk.class:?]
	at mapwriter.tasks.SaveChunkTask.run(SaveChunkTask.java:17) [SaveChunkTask.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
[01:37:30] [pool-7-thread-1/ERROR] [FML]: A TileEntity type cofh.thermaldynamics.duct.item.TileItemDuct has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at cofh.thermaldynamics.duct.attachments.ConnectionBase.writeToNBT(ConnectionBase.java:63) ~[ConnectionBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoBase.writeToNBT(ServoBase.java:53) ~[ServoBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.writeToNBT(ServoItem.java:59) ~[ServoItem.class:?]
	at cofh.thermaldynamics.block.TileTDBase.func_145841_b(TileTDBase.java:716) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.duct.item.TileItemDuct.func_145841_b(TileItemDuct.java:477) ~[TileItemDuct.class:?]
	at mapwriter.region.MwChunk.writeChunkToNBT(MwChunk.java:366) [MwChunk.class:?]
	at mapwriter.region.MwChunk.write(MwChunk.java:399) [MwChunk.class:?]
	at mapwriter.tasks.SaveChunkTask.run(SaveChunkTask.java:17) [SaveChunkTask.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
[01:37:30] [pool-7-thread-1/ERROR] [FML]: A TileEntity type cofh.thermaldynamics.duct.item.TileItemDuct has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at cofh.thermaldynamics.duct.attachments.ConnectionBase.writeToNBT(ConnectionBase.java:63) ~[ConnectionBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoBase.writeToNBT(ServoBase.java:53) ~[ServoBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.writeToNBT(ServoItem.java:59) ~[ServoItem.class:?]
	at cofh.thermaldynamics.block.TileTDBase.func_145841_b(TileTDBase.java:716) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.duct.item.TileItemDuct.func_145841_b(TileItemDuct.java:477) ~[TileItemDuct.class:?]
	at mapwriter.region.MwChunk.writeChunkToNBT(MwChunk.java:366) [MwChunk.class:?]
	at mapwriter.region.MwChunk.write(MwChunk.java:399) [MwChunk.class:?]
	at mapwriter.tasks.SaveChunkTask.run(SaveChunkTask.java:17) [SaveChunkTask.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
[01:37:30] [pool-7-thread-1/ERROR] [FML]: A TileEntity type cofh.thermaldynamics.duct.fluid.TileFluidDuctSuper has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at cofh.thermaldynamics.duct.attachments.ConnectionBase.writeToNBT(ConnectionBase.java:63) ~[ConnectionBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoBase.writeToNBT(ServoBase.java:53) ~[ServoBase.class:?]
	at cofh.thermaldynamics.block.TileTDBase.func_145841_b(TileTDBase.java:716) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.duct.fluid.TileFluidDuct.func_145841_b(TileFluidDuct.java:384) ~[TileFluidDuct.class:?]
	at mapwriter.region.MwChunk.writeChunkToNBT(MwChunk.java:366) [MwChunk.class:?]
	at mapwriter.region.MwChunk.write(MwChunk.java:399) [MwChunk.class:?]
	at mapwriter.tasks.SaveChunkTask.run(SaveChunkTask.java:17) [SaveChunkTask.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
[01:37:32] [Client thread/INFO] [MapWriter]: done
[01:37:32] [Client thread/INFO] [Mekanism]: VoiceServer: Stopping client connection...
[01:37:33] [Client thread/INFO] [Mekanism]: Finished loading Cardboard Box blacklist (loaded 0 entries)
[01:37:33] [Client thread/INFO] [Mekanism]: Reloaded config.
-------------------------------------------------------------------------------------------------------------------------------

I was also getting the error from #849 . I had to load a backup of my world and it has since fixed the second error but not the first one.  #849 stayed between worlds until i restarted the game so i have no cant be world corruption can it?
I should probably state this also, I recently went from windows to ubuntu and none of this happened. 

This all started (#849 and the first time i noticed the current error) after I placed a flux-plated fluid duct next to an infinite water source from pressure pipes. the duct was touching 2 hardened fluxduct. I cannot get this to happen again as the pre-backup word is unplayable at 2 frames. 
I have all the latest cofh mods off of curse and the latest forge.
is this a mapwriter 2 issue or a cofh issue? Thanks

**Comment by KingLemming** [comment]
Pretty sure this is MapWriter and some weirdness with chunk loading. We can't make it happen with only CoFH mods.

**Comment by deadgamer1030** [comment]
Thanks, mapwriter,and mapwriter2, seems to have a lot of issues.
