### ISSUE TITLE
CoFHCore-[1.7.10]3.0.0B9-129 (and 130) crash when placing item in cache

### ISSUE THREAD

**Issue by bjokuty** [CoFH/Feedback#86]
Like the title says, I put some cobble in a (basic) cache and the (internal) server crashed.

Stack trace for convenience: 

java.lang.AbstractMethodError: thermalexpansion.block.cache.TileCache.getOwner()Ljava/util/UUID;
	at cofh.core.block.TileCoFHBase.canPlayerAccess(TileCoFHBase.java:85)
	at thermalexpansion.block.TileInventory.openGui(TileInventory.java:93)
	at thermalexpansion.block.BlockTEBase.func_149727_a(BlockTEBase.java:89)
	at thermalexpansion.block.cache.BlockCache.func_149727_a(BlockCache.java:94)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

crash log/mod list: http://paste.ee/p/LTntQ

Thanks for all the hard work. Great mods. Let me know if you'd like me to test without other mods or anything like that. I suspect it's probably not other mods as CoFH core was one of only a handful that I updated, prior to which the caches worked fine. Hope I've filed this issue correctly. Sorry if not.

**Comment by KingLemming** [comment]
Please do not use alpha versions. :/ That's what CurseForge is. Please use the actual releases on Curse.

**Comment by bjokuty** [comment]
Oh, ok, sorry!
