### ISSUE TITLE
Modpack crash

### ISSUE THREAD

**Issue by xxyannjeuxx** [CoFH/Feedback#869]
18:31:03] [main/INFO]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[18:31:03] [main/INFO]: Using primary tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[18:31:03] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[18:31:03] [main/INFO]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[18:31:03] [main/INFO]: Bootstrapping LiteLoader 1.7.10
[18:31:03] [main/INFO]: Registering API provider class com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient
[18:31:04] [main/INFO]: Spawning API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' ...
[18:31:04] [main/INFO]: API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' provides API 'liteloader'
[18:31:04] [main/INFO]: Initialising API 'liteloader' ...
[18:31:04] [main/INFO]: LiteLoader begin PREINIT...
[18:31:04] [main/INFO]: Initialising Loader properties...
[18:31:04] [main/INFO]: Setting up logger...
[18:31:04] [main/INFO]: LiteLoader 1.7.10_04 starting up...
[18:31:04] [main/INFO]: Java reports OS="windows 10"
[18:31:04] [main/INFO]: Enumerating class path...
[18:31:04] [main/INFO]: Class path separator=";"
[18:31:04] [main/INFO]: Class path entries=(
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\mumfrey\liteloader\1.7.10\liteloader-1.7.10.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\16.0\guava-16.0.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.7.10-10.13.4.1448-1.7.10\forge-1.7.10-10.13.4.1448-1.7.10.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.3.5\realms-1.3.5.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.3.1\vecmath-1.3.1.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\15.0\guava-15.0.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch\5.16\twitch-5.16.jar
   classpathEntry=C:\Users\stephanesabrina\AppData\Roaming\.minecraft\versions\1.7.10\1.7.10.jar
)
[18:31:04] [main/INFO]: Registering discovery module EnumeratorModuleClassPath: [<Java Class Path>]
[18:31:04] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\stephanesabrina\AppData\Roaming\.minecraft\mods]
[18:31:04] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\stephanesabrina\AppData\Roaming\.minecraft\mods\1.7.10]
[18:31:04] [main/INFO]: Adding supported mod class prefix 'LiteMod'
[18:31:04] [main/INFO]: Discovering tweaks on class path...
[18:31:04] [main/INFO]: Discovering valid mod files in folder C:\Users\stephanesabrina\AppData\Roaming\.minecraft\mods
[18:31:04] [main/INFO]: Considering valid mod file: C:\Users\stephanesabrina\AppData\Roaming\.minecraft\mods\mod_voxelMap_1.5.17_for_1.7.10.litemod
[18:31:04] [main/INFO]: Adding newest valid mod file 'C:\Users\stephanesabrina\AppData\Roaming\.minecraft\mods\mod_voxelMap_1.5.17_for_1.7.10.litemod' at revision 1517,0000
[18:31:04] [main/INFO]: Discovering valid mod files in folder C:\Users\stephanesabrina\AppData\Roaming\.minecraft\mods\1.7.10
[18:31:04] [main/INFO]: Searching for tweaks in 'Baubles-1.7.10-1.0.1.10.jar'
[18:31:04] [main/WARN]: Error parsing manifest entries in 'C:\Users\stephanesabrina\AppData\Roaming\.minecraft\mods\1.7.10\Baubles-1.7.10-1.0.1.10.jar'
[18:31:04] [main/INFO]: Searching for tweaks in 'CodeChickenLib-1.7.10-1.1.3.140-universal.jar'
[18:31:04] [main/WARN]: Error parsing manifest entries in 'C:\Users\stephanesabrina\AppData\Roaming\.minecraft\mods\1.7.10\CodeChickenLib-1.7.10-1.1.3.140-universal.jar'
[18:31:04] [main/INFO]: Searching for tweaks in 'ForgeMultipart-1.7.10-1.2.0.345-universal.jar'
[18:31:04] [main/WARN]: Error parsing manifest entries in 'C:\Users\stephanesabrina\AppData\Roaming\.minecraft\mods\1.7.10\ForgeMultipart-1.7.10-1.2.0.345-universal.jar'
[18:31:04] [main/INFO]: Searching for tweaks in 'MrTJPCore-1.7.10-1.1.0.31-universal.jar'
[18:31:04] [main/WARN]: Error parsing manifest entries in 'C:\Users\stephanesabrina\AppData\Roaming\.minecraft\mods\1.7.10\MrTJPCore-1.7.10-1.1.0.31-universal.jar'
[18:31:04] [main/INFO]: Searching for tweaks in '[1.7.10]bspkrsCore-universal-6.16.jar'
[18:31:04] [main/WARN]: Error parsing manifest entries in 'C:\Users\stephanesabrina\AppData\Roaming\.minecraft\mods\1.7.10\[1.7.10]bspkrsCore-universal-6.16.jar'
[18:31:04] [main/INFO]: Mod file 'mod_voxelMap_1.5.17_for_1.7.10.litemod' provides classTransformer 'com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer', adding to class loader
[18:31:04] [main/INFO]: classTransformer 'com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer' was successfully added
[18:31:04] [main/INFO]: LiteLoader PREINIT complete
[18:31:04] [main/INFO]: Sorting registered packet transformers by priority
[18:31:04] [main/INFO]: Added 0 packet transformer classes to the transformer list
[18:31:04] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.transformers.event.EventProxyTransformer'
[18:31:04] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.launch.LiteLoaderTransformer'
[18:31:04] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.client.transformers.CrashReportTransformer'
[18:31:04] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[18:31:04] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer'
[18:31:04] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer'
[18:31:04] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[18:31:04] [main/INFO]: Forge Mod Loader version 7.99.16.1448 for Minecraft 1.7.10 loading
[18:31:04] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[18:31:04] [main/INFO]: [AppEng] Core Init
[18:31:04] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:04] [main/WARN]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod mrtjp.relocation.asm.RelocationPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/ERROR]: The coremod info.jbcs.minecraft.idfix.IdfixCore is requesting minecraft version 1.6.4 and minecraft is 1.7.10. It will be ignored.
[18:31:05] [main/WARN]: The coremod mods.immibis.core.ICCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/INFO]: Loading tweaker net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer from legacyjavafixer-1.0 (1).jar
[18:31:05] [main/WARN]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of CodeChickenLib, 1.1.3.140 is newer than request 1.1.3.136
[18:31:05] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of bspkrsCore, 6.16 is newer than request 6.15
[18:31:05] [main/WARN]: The coremod mcp.mobius.mobiuscore.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod mrtjp.core.handler.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod openeye.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_C1.jar
[18:31:05] [main/WARN]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod com.dynious.refinedrelocation.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod thaumic.tinkerer.preloader.ThaumicTLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/WARN]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:31:05] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:31:05] [main/INFO]: Loading tweak class name net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker@6f01b95f
[18:31:05] [main/INFO]: [LegacyJavaFixer] Replacing tweaker cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker@6f01b95f with net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement@4007f65e
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: FMLCorePlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: FMLForgePlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: AppleCore {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: AppEngCore {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: CoreMod {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: Brandon's Core {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: LoadingPlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: DragonAPIASMHandler {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: EnderCorePlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: FldLoadingPlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: DepLoader {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: RelocationPlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: ICCoreMod {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: IC2core {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: FMLPlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: MalisisCorePlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: LoadingHook {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: CoreDescription {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: CorePlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: NEICorePlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: OpenBlocksCorePlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: OpenEyePlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: OpenModsCorePlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: DepLoader {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: LoadingPlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: RotaryASMHandler {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: LoadingPlugin {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: DepLoader {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: ThaumicTLoaderContainer {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: DepLoader {[]}
[18:31:05] [main/INFO]: [LegacyJavaFixer] Tweaker: cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker@6f01b95f
[18:31:05] [main/INFO]: [LegacyJavaFixer] Replacing tweaker cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker@6f01b95f with net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement@4007f65e
[18:31:05] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[18:31:05] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[18:31:05] [main/INFO]: Calling tweak class net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement
[18:31:05] [main/INFO]: [LegacyJavaFixer] Replacing sort
[18:31:05] [main/INFO]: [LegacyJavaFixer] Detected TerminalTweaker
[18:31:05] [main/INFO]: Calling tweak class net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement
[18:31:05] [main/INFO]: Calling tweak class net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer
[18:31:05] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[18:31:05] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions
[18:31:05] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader
[18:31:05] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer
[18:31:05] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/C:/Users/stephanesabrina/AppData/Roaming/.minecraft/mods/OptiFine_1.7.10_HD_C1.jar
[18:31:05] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@239a307b
[18:31:05] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:31:06] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:31:09] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[18:31:09] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[18:31:09] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:31:09] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:31:09] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:31:09] [main/INFO]: Finished data injection.
[18:31:09] [main/INFO]: Finished data injection.
[18:31:09] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:31:09] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:31:09] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:31:09] [main/INFO]: Loaded library EJML-core-0.26.jar.
[18:31:09] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:31:09] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:31:09] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:31:09] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:31:09] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
Exception in thread "main" [18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: codechicken/core/launch/CodeChickenCorePlugin
[18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.asm.NEICorePlugin.getASMTransformerClass(NEICorePlugin.java:23)
[18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:98)
[18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: codechicken.core.launch.CodeChickenCorePlugin
[18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 4 more
[18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[18:31:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 6 more

**Comment by KingLemming** [comment]
This has literally nothing to do with us.
