### ISSUE TITLE
Crash in server when placing a Thermal Dynamics cover on a duct.

### ISSUE THREAD

**Issue by duncanwebb** [CoFH/Feedback#884]
Hi,

I'm running FTB Infinity 1.11.2

I have a really strange but reproducible crash. I have a lot of thermal dynamics ducts in my world and at one specific point in my base if I place a cover on a duct the server crashes and I cannot start FTB again. If I point to this duct and switch to a cover them I can start the game again.

The action that I took was disable Thermal Dynamics mod on the server and client and then I could restart the world but of course without the ducts. After this I re-enabled the mod and restarted the game without a problem and of course without the ducts.

The crash report is:
[21:17:59] [Server thread/INFO] [Draconic Evolution]: false
[21:41:22] [Netty IO #2/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.7.0_65]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.7.0_65]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.7.0_65]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.7.0_65]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[?:1.7.0_65]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
[21:41:22] [Server thread/INFO]: budivudi lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[21:41:22] [Server thread/INFO]: budivudi left the game

I making a youtube video which will be Episode 45, Up and running again https://www.youtube.com/playlist?list=PL9B1Jk4PNPoK_hDit3CqZG41KmVjzVYcP which I will publish tomorrow, where I have demonstrated the crash in the last few seconds.

I really hope that you can help me resolve this crash as it took me nearly two weeks to identify the crash and repair most of the damage caused by the problem.

Kind regards and thanks
Duncan

**Comment by KingLemming** [comment]
So basically it was reproducible, but you just outright removed TD, ruining any chance of reproducing it again.

And then you have a crash log which doesn't list any CoFH mods at all.

Surely you see the problem here.

**Comment by skyboy** [comment]
Error indicates client-side crash. Open a new issue with the appropriate stacktrace.

**Comment by duncanwebb** [comment]
I can reproduce it even after removing and putting back both thermal dynamics and replacing all the ducts. If I couldn't reproduce then I would not have reported it as I know that you would have no chance investigating it.

What I find really strange is that the crash only occurs at one specific coordinate. I'm sure that I haven't given you enough information to investigate it, so what do you need, the full server log, a copy of the world, anything else?

I raised an earlier case on the FTB forum, http://support.feed-the-beast.com/t/infinity-1-11-2-crashing-after-getting-world-packet/18978/2

**Comment by duncanwebb** [comment]
@shyboy sorry to be so dumb do you want be to open a identical ticket again? The title has server crash and the stack trace was included. What happened is that once the server crashed then the client always crashed at start up. If I have a cover in my hand and try to place the cover on the duct then the server crashes and the client repeatedly crashes. I pointing to the duct and selecting the cover the crash only happens in the server.

Let me know the next step that you would like from me. I'm willing to help in anyway I can. BTW I did maintain freevo for nearly 5 years so I don understand what you face rather well.

**Comment by duncanwebb** [comment]
Thank you your it works, not updating the jar files but moving the Travel Anchor. Updating the jar files caused another crash that seems to be quite unrelated as just moving the pointer to the travel anchor caused it to crash. I had googled the TD cover crash a number of times but didn't find anything useful.

I only thing that I didn't understand is why you wanted a new issue, was it because of the title?

Thanks for your help.
