### ISSUE TITLE
[Thermal Dynamic 1.1.0-161] Client crash all time when logging-in in multiplayer

### ISSUE THREAD

**Issue by sylphio** [CoFH/Feedback#887]
Hi

My client is crashing each time i am trying to log-in on my multiplayer world. 
What is the strangest is that we dont have any bluepower machine in the whole map.

If i edit my player position to spawn farther away. I no longer crash and i can came back to my initial spawn position. Really look like to be a problem only during the initial loading.

Any idea? Thank you 

java.lang.ClassCastException: com.bluepowermod.block.machine.BlockCircuitDatabase cannot be cast to cofh.thermaldynamics.duct.BlockDuct
	at cofh.thermaldynamics.block.TileTDBase.getDuctType(TileTDBase.java:758)
	at cofh.thermaldynamics.duct.item.TileItemDuct.getPipeLength(TileItemDuct.java:389)
	at cofh.thermaldynamics.duct.item.TravelingItem.tickClientForward(TravelingItem.java:239)
	at cofh.thermaldynamics.duct.item.TileItemDuct.tickItemsClient(TileItemDuct.java:678)

Full crash report with modlist
https://gist.github.com/sylphio/eda6ad3341f2ff678093

**Comment by KingLemming** [comment]
Well, your map seems to think that you DO have a Bluepower machine.

And that's fundamentally the issue. Looks like a tile entity wasn't wiped properly and you have some sort of map corruption.
