### ISSUE TITLE
 Crash placing a Thermal Dynamics cover on a duct.

### ISSUE THREAD

**Issue by duncanwebb** [CoFH/Feedback#889]
Hi,

Please do not close the issue without consent. Not only is this rather impolite but I'm actually trying to help and it takes quite some time to prepare the issue and I'm not trying to waste your time. I apologise if this is the wrong place to report a problem if it is then please point me to the correct place.

I'm running FTB Infinity 1.11.2

I have a really strange but *reproducible* crash. The crash can be reproduced on both a server or on a standalone client. I can upload my world.zip for you to inspect. This is a link of my video where the crash happens https://youtu.be/gznoWBBPMnE?t=21m30s

I have a lot of thermal dynamics ducts in my world and at one specific point in my base if I place a cover on a duct the server crashes and I cannot start FTB again. If I point to this duct and switch to a cover them I can start the game again.

The action that I took was disable Thermal Dynamics mod on the server and client and then I could restart the world but of course without the ducts. After this I re-enabled the mod and restarted the game without a problem and of course without the ducts.

The client log is available for download from http://support.feed-the-beast.com/t/infinity-1-11-2-crashing-after-getting-world-packet/18978/2

The crash report from the server console window was:
[21:17:59] [Server thread/INFO] [Draconic Evolution]: false
[21:41:22] [Netty IO #2/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.7.0_65]
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.7.0_65]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.7.0_65]
at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.7.0_65]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[?:1.7.0_65]
at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
[21:41:22] [Server thread/INFO]: budivudi lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[21:41:22] [Server thread/INFO]: budivudi left the game

I really hope that you can help me resolve this crash as it took me nearly two weeks to identify the crash and repair most of the damage caused by the problem. Please let me know the next step that you would like from me. I'm willing to help in anyway I can.

Kind regards and thanks
Duncan

**Comment by KingLemming** [comment]
Okay so this is exactly what you posted last time.

Last time, @skyboy asked you to post the correct crash log. You haven't done that yet. :(

Please understand, basically what you're saying is, "halp it dont work!!1!"

There is NOTHING in this log that points to TD in any way at all.

**Comment by duncanwebb** [comment]
Hi you can watch the last two minutes of the video to see exactly what happened. 

I think that the server log is even less useful. I presume that this is what you want. but there are quite a few logs in the directory, including fml-server-latest.log and latest.log. I logrotate the logs so that logwatch makes some more sense. I would be helpful to have a date in the logs.

```
cat latest.log-20151021
[21:15:52] [Server thread/INFO]: Starting minecraft server version 1.7.10
[21:15:52] [Server console handler/ERROR]: Exception handling console input
java.io.IOException: Bad file descriptor
        at java.io.FileInputStream.readBytes(Native Method) ~[?:1.7.0_65]
        at java.io.FileInputStream.read(FileInputStream.java:272) ~[?:1.7.0_65]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:273) ~[?:1.7.0_65]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:334) ~[?:1.7.0_65]
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283) ~[?:1.7.0_65]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325) ~[?:1.7.0_65]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177) ~[?:1.7.0_65]
        at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.7.0_65]
        at java.io.BufferedReader.fill(BufferedReader.java:154) ~[?:1.7.0_65]
        at java.io.BufferedReader.readLine(BufferedReader.java:317) ~[?:1.7.0_65]
        at java.io.BufferedReader.readLine(BufferedReader.java:382) ~[?:1.7.0_65]
        at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:97) [lv.class:?]
[21:16:54] [Server thread/INFO]: Loading properties
[21:16:54] [Server thread/INFO]: Default game type: SURVIVAL
[21:16:54] [Server thread/INFO]: Generating keypair
[21:16:54] [Server thread/INFO]: Starting Minecraft server on *:25566
[21:17:30] [Server thread/INFO]: Preparing level "world"
[21:17:32] [Server thread/INFO]: Preparing start region for level 0
[21:17:35] [Server thread/INFO]: Preparing spawn area: 18%
[21:17:36] [Server thread/INFO]: Preparing spawn area: 42%
[21:17:37] [Server thread/INFO]: Preparing spawn area: 95%
[21:17:37] [Server thread/INFO]: Done (7.860s)! For help, type "help" or "?"
[21:17:37] [Server thread/INFO]: Starting remote control listener
[21:17:37] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:25576
[21:17:40] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2328ms behind, skipping 46 tick(s)
[21:17:57] [User Authenticator #1/INFO]: UUID of player budivudi is 14ed56de-2240-4438-8d51-4c2095154411
[21:17:57] [Server thread/INFO]: budivudi[/10.19.57.111:54293] logged in with entity id 740 at (111.89784343504242, 63.0, -386.0798112563038)
[21:17:57] [Server thread/INFO]: budivudi joined the game
[21:41:22] [Server thread/INFO]: budivudi lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[21:41:22] [Server thread/INFO]: budivudi left the game
[21:57:08] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2198ms behind, skipping 43 tick(s)
```
I can send you all the logs or even the world as a zip and you will be able to reproduce the crash. Let me know *precisely* what you need from me or would like to do - enable debugging or whatever.

**Comment by skyboy** [comment]
This stacktrace in your client log on line 2897 (the one I told you to post in #884, which you helpfully ignored) is what we needed.

```
Time: 12/10/15 22:02
Description: Unexpected error
 
java.lang.NullPointerException: Unexpected error
        at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4975)
        at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
        at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
        at cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.renderCover(CoverRenderer.java:42)
        at cofh.thermaldynamics.duct.attachments.cover.Cover.drawSelectionExtra(Cover.java:209)
        at cofh.thermaldynamics.item.ItemAttachment.onBlockHighlight(ItemAttachment.java:121)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1102_ItemAttachment_onBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:256)
        at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)
        at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Combined with your video showing the EIO anchor thing, you are experiencing this bug: https://github.com/CoFH/Feedback/issues/828

And since this bug is EIO's implementation of one of our interfaces, and they have resolved it in an update of their mod, I am closing this. Whether or not your pack has or is able to update is beyond my control.

**Comment by duncanwebb** [comment]
Sorry I was not sure that you wanted the client side log. What I was seeing was a single exception in the server and then exception in the client and I wasn't sure which was the chicken or egg.

I will update the mods to EnderCore-1.7.10-0.1.0.25_beta and EnderIO-1.7.10-2.3.0.417_beta or later and see if the problem goes away. I'm actually not convinced that this is the problem as I've since removed all the EnderIO conduits (except for 2 new blocks).

The client stack trace is:
[21:41:06] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4975) ~[blm.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247) ~[blm.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255) ~[blm.class:?]
	at cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.renderCover(CoverRenderer.java:42) ~[CoverRenderer.class:?]
	at cofh.thermaldynamics.duct.attachments.cover.Cover.drawSelectionExtra(Cover.java:209) ~[Cover.class:?]
	at cofh.thermaldynamics.item.ItemAttachment.onBlockHighlight(ItemAttachment.java:121) ~[ItemAttachment.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1102_ItemAttachment_onBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:256) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
 
This trace does show thermal dynamics cover. in the exception.

BTW I will be delighted to have Ender IO fixed.
