### ISSUE TITLE
Disable Thermal Expansion check

### ISSUE THREAD

**Issue by drazisil** [CoFH/Feedback#90]
As far as I can see, there is no way to request TE to not check for an update at start-up. Since your TE repository is private, this will always fail. Nothing game-breaking, but I dislike easy errors :)

Version: ThermalExpansion-[1.7.10]4.0.0B8-23

Thanks for your time.

Log:

[16:38:02] [CoFHUpdater:ThermalExpansion/WARN]: Update check for Thermal Expansion failed.
java.io.FileNotFoundException: https://raw.githubusercontent.com/CoFH/ThermalExpansion/master/VERSION
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1624) ~[?:1.7.0_67]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.7.0_67]
	at java.net.URL.openStream(URL.java:1037) ~[?:1.7.0_67]
	at cofh.mod.updater.UpdateCheckThread.run(UpdateCheckThread.java:44) [UpdateCheckThread.class:?]

**Comment by bochen415** [comment]
Duplicate
https://github.com/CoFH/Feedback/issues/4

**Comment by KingLemming** [comment]
Yeah, see that Version repo? It's in there, but we're busy dealing with Mojang's latest snafus to have a release out.

**Comment by drazisil** [comment]
fair enough :) (closeing as a dupe)
