### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by resursator** [CoFH/Feedback#900]
[03:28:06] [Server thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@6e7a90ff:
java.lang.NullPointerException
    at cofh.core.util.oredict.OreDictionaryArbiter.initialize(OreDictionaryArbiter.java:64) ~[OreDictionaryArbiter.class:?]
    at cofh.core.util.FMLEventHandler.handleIdMappingEvent(FMLEventHandler.java:47) ~[FMLEventHandler.class:?]
    at cofh.core.util.FMLEventHandler.onPlayerLogin(FMLEventHandler.java:38) ~[FMLEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_229_FMLEventHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) [FMLCommonHandler.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:180) [oi.class:?]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) [NetworkDispatcher.class:?]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463) [NetworkDispatcher.class:?]
    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) [HandshakeCompletionHandler.class:?]
    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) [HandshakeCompletionHandler.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

Full log:
http://paste.ee/p/eOXH9

**Comment by resursator** [comment]
Looks like it is railcraft problem. There is not that error without it,

**Comment by resursator** [comment]
Nope, that error return after removing some mods.
http://paste.ee/p/HzDD4

**Comment by resursator** [comment]
So, CoFH & Gregtech don't work together =(
http://paste.ee/p/w0ESi

**Comment by KingLemming** [comment]
Yup. Seems that Greg is doing some ASM that breaks things on login. Sorry, nothing we can do about that.

**Comment by GregoriusT** [comment]
Okay even though this is a bit more than 3 months ago (I got linked to it), it worries me a lot. As soon as someone mentions "GregTech" you cease to even remotely care about trying to fix Issues. What is already bad by itself, but why is a Nullpointer within your code something that was caused by me, without me doing anything, that could cause that, to my knowledge?

What could I have done wrong to cause that during your processing of an ID Remap Event?

The only thing I do during an ID Remap is reinitialising my own HashMaps so the Keys are revalidated. And that doesn't even make use of the Parameter the Event offers, so it cant be that either.

I would really like to know what happened to cause this. Btw I have CoFH, TE and GT on my Setup and all works like it is supposed to.

**Comment by skyboy** [comment]
It likely requires additional mods, and may no longer occur due to changes in all mods involves.

The crashing section of our code is this:
```diff
		for (ItemWrapper wrapper : stackIDs.keySet()) {
			if (wrapper.metadata != WILDCARD_VALUE) {
				ItemWrapper wildItem = new ItemWrapper(wrapper.item, WILDCARD_VALUE);
				if (stackIDs.containsKey(wildItem)) {
+					stackIDs.get(wrapper).addAll(stackIDs.get(wildItem));
					stackNames.get(wrapper).addAll(stackNames.get(wildItem));
				}
			}
		}
```

The highlighted line crashing. There is no reasonable method in which this can crash under normal circumstances, not even mutating ItemStacks as we do not rely on them.
If you have any insight as to how this code can crash outside someone manipulating it via ASM, it's welcome. However, this crash hasn't been reported in considerable time.

**Comment by GregoriusT** [comment]
I dont think there is anything crashable inside it, but I would
recommend iterating over entrySet instead of keySet for performance
reasons, since you use both, key and value.

**Comment by theJ8910** [comment]
Hi, I'm occasionally having a crash related to OreDictionaryArbiter. (Minecraft 1.7.10, CoFH Core 3.1.3-327).

In my case, the crash was on [line 96](https://github.com/CoFH/CoFHCore/blob/b490f66a4361ecd7742a561091c20ffae3337672/src/main/java/cofh/core/util/oredict/OreDictionaryArbiter.java#L96):
```
[06:27:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.IllegalArgumentException: value already present: 2194
[06:27:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
[06:27:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
[06:27:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cofh.core.util.oredict.OreDictionaryArbiter.registerOreDictionaryEntry(OreDictionaryArbiter.java:82)
[06:27:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cofh.core.util.oredict.OreDictionaryArbiter.initialize(OreDictionaryArbiter.java:57)
[06:27:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cofh.core.util.FMLEventHandler.handleIdMappingEvent(FMLEventHandler.java:47)
[06:27:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cofh.CoFHCore.handleConfigSync(CoFHCore.java:191)
[06:27:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cofh.core.network.PacketCore.handlePacket(PacketCore.java:26)
[06:27:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cofh.core.network.PacketCoFHBase.handleClientSide(PacketCoFHBase.java:404)
[06:27:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cofh.core.network.PacketHandler.decode(PacketHandler.java:98)
[06:27:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cofh.core.network.PacketHandler.decode(PacketHandler.java:40)
[06:27:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
[06:27:09] [Server thread/ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@33df1e1f:
java.lang.NullPointerException
	at cofh.core.util.oredict.OreDictionaryArbiter.registerOreDictionaryEntry(OreDictionaryArbiter.java:96) ~[OreDictionaryArbiter.class:?]
	at cofh.core.util.oredict.OreDictionaryArbiter.initialize(OreDictionaryArbiter.java:57) ~[OreDictionaryArbiter.class:?]
	at cofh.core.util.FMLEventHandler.handleIdMappingEvent(FMLEventHandler.java:47) ~[FMLEventHandler.class:?]
	at cofh.core.util.FMLEventHandler.onPlayerLogin(FMLEventHandler.java:38) ~[FMLEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_140_FMLEventHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) [FMLCommonHandler.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:180) [oi.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) [NetworkDispatcher.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463) [NetworkDispatcher.class:?]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) [HandshakeCompletionHandler.class:?]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) [HandshakeCompletionHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

I haven't been able to catch it in the act in a debugger yet, but I think both the original crash and my crash could be explained by a race condition. Every time this particular crash has happened, I was joining my singleplayer world. Furthermore, whether it occurs or not is seemingly random which tends to be a property of race conditions.

Since stackNames can never be null by the logic of the program, the only way I can see a NullPointerException occurring on that line is if stackNames is replaced with a new list (possibly [here](https://github.com/CoFH/CoFHCore/blob/b490f66a4361ecd7742a561091c20ffae3337672/src/main/java/cofh/core/util/oredict/OreDictionaryArbiter.java#L49) by a different thread. If this happens after the .contains()/.add() call and before the .get() call, this would mean the .get() call would return null, then when you attempt to do something with this value, generate a NullPointerException.

**Comment by theJ8910** [comment]
Update: I've been studying your a code a little bit more and I've noticed that in [FMLEventHandler#onPlayerLogin()](https://github.com/CoFH/CoFHCore/blob/08c327bc7dacecdd7cff8fa3ecc2f5369e98df6e/src/main/java/cofh/core/util/FMLEventHandler.java#L30-L39), the server sends a ConfigSyncPacket to the client, then the server immediately calls [FMLEventHandler#handleIdMappingEvent()](https://github.com/CoFH/CoFHCore/blob/08c327bc7dacecdd7cff8fa3ecc2f5369e98df6e/src/main/java/cofh/core/util/FMLEventHandler.java#L41-L48), which calls [OreDictionaryArbiter#initialize()](https://github.com/CoFH/CoFHCore/blob/08c327bc7dacecdd7cff8fa3ecc2f5369e98df6e/src/main/java/cofh/core/util/oredict/OreDictionaryArbiter.java#L43-L70) on the server.

When the client receives the ConfigSync packet, this is handled by [CoFHCore#handleConfigSync()](https://github.com/CoFH/CoFHCore/blob/08c327bc7dacecdd7cff8fa3ecc2f5369e98df6e/src/main/java/cofh/CoFHCore.java#L189-L194) which also calls [FMLEventHandler#handleIdMappingEvent()](https://github.com/CoFH/CoFHCore/blob/08c327bc7dacecdd7cff8fa3ecc2f5369e98df6e/src/main/java/cofh/core/util/FMLEventHandler.java#L41-L48), which in turn calls [OreDictionaryArbiter#initialize()](https://github.com/CoFH/CoFHCore/blob/08c327bc7dacecdd7cff8fa3ecc2f5369e98df6e/src/main/java/cofh/core/util/oredict/OreDictionaryArbiter.java#L43-L70) on the client.

From what I can see, it seems very likely the same method could be running concurrently on two different threads, operating on the same shared memory in an unsynchronized fashion. I'd wager this coincides with GregTech frequently because of the huge volume of ore dictionary entries that mod adds. In other words, the server thread would be stuck in the loop long enough that the initialize call on the client would have a greater chance of coinciding with the initialize call on the server.
