### ISSUE TITLE
Ducts causing chunks to be loaded while checking for chunk unload?

### ISSUE THREAD

**Issue by tornewuff** [CoFH/Feedback#905]
I'm trying to debug issues on my server with chunks being constantly loaded and unloaded when no players are online and no chunkloaders are in use, and after writing a small mod to log chunk load events with stack traces it appears that one of the (several) mods doing this is Thermal Dynamics. The stack I see repeatedly in the log is:

```
at net.minecraft.world.chunk.Chunk.onLoad(Chunk.java:920)
at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:105)
at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:130)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:101)
at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:147)
at net.minecraft.world.World.getChunkFromChunkCoords(World.java:361)
at net.minecraft.world.World.getChunkFromBlockCoords(World.java:353)
at net.minecraft.world.World.getBlockState(World.java:994)
at net.minecraft.world.World.getRedstonePower(World.java:3523)
at net.minecraft.world.World.isBlockPowered(World.java:3551)
at cofh.thermaldynamics.duct.tiles.TileGrid.isPowered(TileGrid.java:822)
at cofh.thermaldynamics.duct.tiles.TileGridStructureBase.isPowered(TileGridStructureBase.java:88)
at cofh.thermaldynamics.duct.attachments.ConnectionBase.getPowerState(ConnectionBase.java:127)
at cofh.thermaldynamics.duct.attachments.ConnectionBase.onNeighborChange(ConnectionBase.java:114)
at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborBlockChange(TileGrid.java:190)
at cofh.thermaldynamics.duct.tiles.TileGrid.checkForChunkUnload(TileGrid.java:335)
at cofh.thermaldynamics.duct.tiles.DuctUnit.tickPass(DuctUnit.java:289)
at cofh.thermaldynamics.duct.item.DuctUnitItem.tickPass(DuctUnitItem.java:254)
at cofh.thermaldynamics.duct.item.GridItem.tickGrid(GridItem.java:64)
at cofh.thermaldynamics.util.WorldGridList.tickEnd(WorldGridList.java:62)
at cofh.thermaldynamics.util.TickHandler.tick(TickHandler.java:93)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_336_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:849)
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:414)
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:741)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
at java.lang.Thread.run(Thread.java:748)
```

I've not looked into the thermal dynamics code deeply as it's quite complex and I'm new to mod development, but from a small look I'm guessing that checkForChunkUnload is not supposed to be causing chunks to be reloaded?

The chunks in question do not stay loaded: after the normal cache timeouts they are unloaded, and then on the very next tick reloaded again with the same originating stack.

Is this a bug in Thermal Dynamics, or could it be a bad interaction with another mod (I haven't yet tried to reproduce this with no other mods loaded), or am I holding it wrong? :)

The CoFH mods I'm using:

CoFHCore-1.12.2-4.3.10.5-universal.jar
CoFHWorld-1.12.2-1.1.1.12-universal.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
ThermalCultivation-1.12.2-0.1.5.3-universal.jar
ThermalDynamics-1.12.2-2.3.10.4-universal.jar
ThermalExpansion-1.12.2-5.3.10.15-universal.jar
ThermalFoundation-1.12.2-2.3.10.6-universal.jar

on Forge 1.12.2-14.23.1.2587

**Comment by KingLemming** [comment]
If all of the chunks are actually unloaded, then there should not be any grids in memory whatsoever. However, if you have ducts in a spawn chunk, those never actually unload.

You said that there are several mods doing this, so my initial thought is that this is something inherent to either Minecraft or something hinky on your server specifically.

Can you please share those logs?

**Comment by tornewuff** [comment]
They're not in a spawn chunk, but it's possible that another mod is causing one of the chunks containing part of the duct network to be loaded (since yes, there are several mods causing this). However, even if that's the case, it seems like a bug if that then causes additional chunks to be loaded by thermal dynamics? For example, if part of the network was kept permanently loaded (intentionally) by a chunkloader, it would be unfortunate if the chunks containing the rest of the network constantly loaded and unloaded forever..

I'm working on testing different combinations of the implicated mods to see if I can track down whether this is what's happening.

Here's the full (spammy) log from the server:
[fml-junk-earlystartup.log](https://github.com/CoFH/Feedback/files/1693977/fml-junk-earlystartup.log)

**Comment by tornewuff** [comment]
OK, experimenting a bit more it looks like the *original* culprit here is integrated dynamics (which I've already filed a bug about), but there does still appear to be a secondary issue with thermal dynamics as I describe: when integrated dynamics causes a chunk to be loaded that contains thermal ducts, thermal dynamics appears to cause additional chunks to load in a pattern that follows the shape of the duct network, including chunks that don't contain any integrated dynamics blocks/entities.

So, yeah, it looks like you're right that if all the chunks are unloaded it's fine, but this behaviour still seems like a bug, just a less severe one.

**Comment by ktole1999** [comment]
if there is activity in the duct and it hits an unloaded chunk then 2 options. load the chunk to finish the operation or void the item. i seem to recall that the unloaded duct is loaded to finish the operation per KingLemming to keep people from losing items. i could be wrong so take it for what its worth.

**Comment by tornewuff** [comment]
There's no activity in any of the ducts - no items or fluids being moved and no power being transferred. In the save where I'm testing this, everything is idle or switched off.

I can reliably get the server into a state where after a few other chunks are loaded, TD repeatedly loads specific adjacent chunks over and over again, immediately loading them again on the next tick after they unload, and this continues forever unless something happens to change the chunk cache state (e.g. a player coming online and being in the vicinity). If all the involved chunks get unloaded simultaneously, then the activity stops, but if even one of the chunks stays loaded one tick longer than the others, the others all get reloaded again immediately, and this starts a cycle of this happening forever.

All the loads always have the exact stack mentioned here, so it looks like it's a specific issue with checking for redstone power and not a generic problem with duct activity.

I'm going to keep experimenting and see if I can reduce the network down to isolate the issue, or debug it more in the code, when I have time.

**Comment by nullKomplex** [comment]
Could this in theory cause a feedback loop? As in a conduit going from chunk A to chunk B and a separate (or even the same?) conduit going from chunk B to chunk A. Chunk A is loaded through whatever means and isn't intended to stay loaded. Chunk B is loaded through https://github.com/CoFH/Feedback/issues/905#issuecomment-363550651 . Chunk A theoretically either unloads or stays loaded, but as a result Chunk B is now loaded (through Chunk A, as mentioned) and will attempt to load Chunk A with its cables regardless.

Is this a sound theory?

**Comment by KingLemming** [comment]
I think this has basically been explained at this point, and it needs to be addressed by Integrated Dynamics.

**Comment by tornewuff** [comment]
Sorry for not getting back to you here, I've been busy, but: Integrated Dynamics only loads chunks one time at startup to check for network validity, and doesn't cause any further load events after that.

TD is still causing the repeated loads; there just needs to be *any* reason for one of the involved chunks to be loaded (either another mod loading it, or just a player coming near enough, or a chunkloader) and then there will be repeated load/unload events caused by TD that never stop (because the chunks involved time out of the cache at different times, and so it just cycles forever; if they ever "line up" and all get unloaded on the same tick, then it does stop, but that doesn't appear to ever happen in most cases).

checkForChunkUnload causing a chunk to get loaded still seems wrong ;)

I'm in the middle of moving house at the moment so don't have my desktop available to try to produce a minimised test case, but I'll see if I can do it at some point.

**Comment by KingLemming** [comment]
Don't waste your time unless you want to also PR a non-breaking fix.

TD is slated for rewrite and I'll likely not touch it aside from doing that.

**Comment by KingLemming** [comment]
I've attempted a quick mitigation. If it works, great, if not, too bad.

This is basically what people asked for since they bugged me for Comparator features and it's why I initially didn't port it. Minecraft is really stupid about how it checks for RS power.
