### ISSUE TITLE
Flux-Infused Bow in FTB Beyond (v1.0.1)[Minecraft Version 1.10.2] Spits error instead of firing the arrow.

### ISSUE THREAD

**Issue by ipaqmaster** [CoFH/Feedback#91]
Firing a Minecraft Arrow from a Flux-Infused Bow works fine in single player.. (Tested in a flatworld)

Firing a Minecraft Arrow with it on a server immediately spits the below error in the server log:

`[12:36:15] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.projectile.EntityArrow.func_70016_h(DDD)V
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.projectile.EntityArrow.func_70016_h(DDD)V
        at cofh.core.item.tool.ItemBowCore.func_77615_a(ItemBowCore.java:176) ~[ItemBowCore.class:?]
        at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:463) ~[adz.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184597_cx(EntityLivingBase.java:2641) ~[sf.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:597) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more`

This appears the tick you fire the bow, and the arrow is consumed on client side predictions but is still in inventory serverside

**Comment by KingLemming** [comment]
Seems that a method we're using is client-only. Forge hasn't marked it as such. Lovely.

We'll fix it, but I'm attaching the label for blame purposes. :)
