### ISSUE TITLE
Crash in EnervationFuelCategory:getRecipes

### ISSUE THREAD

**Issue by mezz** [CoFH/Feedback#910]
```
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: java.lang.IllegalArgumentException: Must have at least 1 tick per cycle.
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at mezz.jei.gui.TickTimer.<init>(TickTimer.java:13)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at mezz.jei.gui.GuiHelper.createTickTimer(GuiHelper.java:106)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at mezz.jei.gui.GuiHelper.createAnimatedDrawable(GuiHelper.java:85)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelWrapper.<init>(EnervationFuelWrapper.java:39)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory.getRecipes(EnervationFuelCategory.java:85)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory.initialize(EnervationFuelCategory.java:52)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at cofh.thermalexpansion.plugins.jei.JEIPluginTE.register(JEIPluginTE.java:123)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:175)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:60)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:118)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:54)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:728)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:33:55] [main/INFO] [STDERR/jei]: [cofh.thermalexpansion.plugins.jei.dynamo.enervation.EnervationFuelCategory:getRecipes:90]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Also please use log4j instead of `printStackTrace()`,  If you add an exception as the last parameter in a log4j log call, it will print the stack trace more nicely instead of to stdout:
https://github.com/CoFH/ThermalExpansion/blob/b9a2325c7e9e26b30524fd37ca826fd9166614ab/src/main/java/cofh/thermalexpansion/plugins/jei/dynamo/enervation/EnervationFuelCategory.java#L90
can be 
```java
logger.error("Crashed while getting EnervationFuelCategory recipes.", e);
```

**Comment by KingLemming** [comment]
Right so...what mod is actually causing this?

Can you provide a full log please?

**Comment by mezz** [comment]
Full log: https://gist.github.com/Vitali8/676abb0da286b78631fca17743e8eb57

This crash happens when some fuel's `EnervationManager.getFuelEnergy` is 0, so I think you can find the mod and prevent the crash if you add a check for that earlier somewhere.

**Comment by KingLemming** [comment]
Hrm. So this is actually a non-trivial discovery. I'm already doing a check to ensure that energy is > 0 on the energy container items, but not on default fuels.

So that means there is a mod actively screwing up IMC somehow. :/

**Comment by KingLemming** [comment]
Yeah, it doesn't happen when it's 0...happens when it's < 40. Which...ehh okay. That's kind of stupid for anybody to be making an item like that, but I get it.

Fixed.

**Comment by mezz** [comment]
Cool thanks!
