### ISSUE TITLE
[Bug] in MineFactoryReloded "A broken ore dictionary registration with name listAllmilk has occurred"

### ISSUE THREAD

**Issue by TheShadow385** [CoFH/Feedback#915]
Mod:MineFactoryReloded-[1.7.10]2.8.0-104
Hi in the Game Output I found this:

[22:14:46] [Client thread/WARN] [FML]: ****************************************
[22:14:46] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name listAllmilk has occurred. It adds an item (type: class powercrystals.minefactoryreloaded.MineFactoryReloadedCore$1) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod MineFactory Reloaded report it to them!
[22:14:46] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:507)
[22:14:46] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:474)
[22:14:46] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:472)
[22:14:46] [Client thread/WARN] [FML]: *  at powercrystals.minefactoryreloaded.setup.recipe.Vanilla.registerOredict(Vanilla.java:125)
[22:14:46] [Client thread/WARN] [FML]: *  at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.preInit(MineFactoryReloadedCore.java:529)
[22:14:46] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:14:46] [Client thread/WARN] [FML]: ****************************************

Sorry if the fault lies with me. But if if the mod says this is a bug I better send that. ^^

![mods6 11 15](https://cloud.githubusercontent.com/assets/15231607/11009364/9739ed7c-84d6-11e5-9fd5-2e766bf24e9e.png)

The mods work together. Therefore no crash report. If you want I will cause a crash and send the crash report.

**Comment by skyboy** [comment]
Do not use newer than the recommended version of forge, which is 1448.
