### ISSUE TITLE
[CoFHTweaks] java.lang.ArrayIndexOutOfBoundsException: 118 in ClientChunk.run()

### ISSUE THREAD

**Issue by OreCruncher** [CoFH/Feedback#921]
CoFHTweaks-[1.7.10]1.0.1-38-dev.jar

`[12:54:23] [Chunk Worker/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: 118
Exception in thread "Chunk Worker" [12:54:23] [Chunk Worker/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.repack.cofh.lib.util.IdentityLinkedHashList.seek(IdentityLinkedHashList.java:34)
[12:54:23] [Chunk Worker/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.repack.cofh.lib.util.LinkedHashList.contains(LinkedHashList.java:260)
[12:54:23] [Chunk Worker/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.tweak.asmhooks.world.ClientChunk$ChunkThread.run(ClientChunk.java:46)`

I was just wandering around in my test world when it triggered.

**Comment by skyboy** [comment]
Fixed in 1.0.2B1
