### ISSUE TITLE
[CoFHTweaks] NPE in Chunk Worker...

### ISSUE THREAD

**Issue by OreCruncher** [CoFH/Feedback#926]
CoFHTweaks-[1.7.10]1.0.21B1-41-dev.jar

I get the following exception sporadically when running my test world:

[09:18:01] [Chunk Worker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException

[09:18:01] [Chunk Worker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.tweak.asmhooks.world.ClientChunk$ChunkThread.run(ClientChunk.java:49)

**Comment by KingLemming** [comment]
WTF is Chunk Worker?

**Comment by OreCruncher** [comment]
Dunno - see [#921] for a prior issue.

**Comment by skyboy** [comment]
Does this still happen in 1.1.0B1?

**Comment by OreCruncher** [comment]
I will check today.  It can be sporadic so it may take a little bit.

**Comment by OreCruncher** [comment]
Unfortunately, no. :(

CoFHTweaks 1.1.0B1-52-dev

[11:13:40] [Chunk Worker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
Exception in thread "Chunk Worker" [11:13:40] [Chunk Worker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.tweak.asmhooks.world.ClientChunk$ChunkThread.run(ClientChunk.java:50)

Any swags as to what may  be up?  All I am doing is flying around in creative and it triggers.  It is sporadic - it took about 20 mins or so with my fiddling around in game before it happened.

**Comment by skyboy** [comment]
A build 57 will be up before long that should cover it.

**Comment by OreCruncher** [comment]
So far 57 seems to be holding up.  Also noticed that the visual artifacts and TPS hits with water I have seen are gone as well.

**Comment by skyboy** [comment]
I'm going to close this then, post back if it happens again.
