### ISSUE TITLE
MFR Crash with Creative Inventory

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#938]
<b>Crash output:</b>
-------------------------------------------------------------------------------------------------------------------
Time: 11/22/15 7:55 AM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at cofh.lib.render.RenderFluidOverlayItem.doRenderItem(RenderFluidOverlayItem.java:96)
	at cofh.lib.render.RenderFluidOverlayItem.renderItem(RenderFluidOverlayItem.java:63)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:202)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cofh.lib.render.RenderFluidOverlayItem.doRenderItem(RenderFluidOverlayItem.java:96)
	at cofh.lib.render.RenderFluidOverlayItem.renderItem(RenderFluidOverlayItem.java:63)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:202)

-- Item being rendered --
Details:
	Item Type: powercrystals.minefactoryreloaded.item.base.ItemFactoryBucket@376de4f8
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (308, 146). Absolute: (923, 396)
	Screen size: Scaled: (534, 279). Absolute: (1600, 837). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['VanaeAlcarus'/3, l='MpServer', x=-195.77, y=57.62, z=-984.99]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-218,4,-982), Chunk: (at 6,0,10 in -14,-62; contains blocks -224,0,-992 to -209,255,-977), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 2114773 game time, 8864483 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityClientPlayerMP['VanaeAlcarus'/3, l='MpServer', x=-195.77, y=57.62, z=-984.99]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

<b>Possible Cause of Crash:</b>
--------------------------------------------------------------------------------------------------------------------
The crash occurs when my mouse is hovering over any of the liquid buckets while scrolling up in MFR's creative inventory tab. Possibly due to NEI's item stack movement function with scroll wheel trying to move the unstackable buckets of fluids.

**Comment by DrakoAlcarus** [comment]
@skyboy I'm not sure if you are the guy that deals with MFR, but here is a crash log.

**Comment by skyboy** [comment]
I'm unable to reproduce this, but a build of MFR that will print out some more useful information will be available shortly.

**Comment by DrakoAlcarus** [comment]
I can't seem to recreate it either, but I did find another game crashing bug.

Holding shit or pressing the scroll wheel to grab a stack of plastic sheets from the MFR inventory tab and placing them in an inventory or duplicating them in an inventory causes this error:
---------------------------------------
java.lang.IndexOutOfBoundsException: Index: 49, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_25]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_25]
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104) ~[zs.class:?]
	at codechicken.nei.NEIServerUtils.getSlotContents(NEIServerUtils.java:76) ~[NEIServerUtils.class:?]
	at codechicken.nei.NEISPH.setInventorySlot(NEISPH.java:142) ~[NEISPH.class:?]
	at codechicken.nei.NEISPH.handlePacket(NEISPH.java:39) ~[NEISPH.class:?]
	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:117) ~[PacketCustom$ServerInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:77) ~[PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:64) ~[PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

**Comment by DrakoAlcarus** [comment]
Also, scooping up sludge and sewage (and possibly other mfr fluids) sometimes doesn't register. I get the bucket (or a water filled one) and the sludge will vanish, but I will still get flowing sludge around the space where the sludge disappeared from until I right click. I get a bucket again and it registers regularly.

**Comment by skyboy** [comment]
The second crash is caused by the inventory you have open not being the same on the client and server - this is unrelated to MFR and can happen with any mod and any item.

Your scooping issue is just normal minecraft client/server desync - you can see it happen extremely regularly on any minecraft channel on youtube or twitch.

**Comment by DrakoAlcarus** [comment]
That's odd, because I'm not on a server.

But if I was on a server, how come the lava and water are just fine?

**Comment by DrakoAlcarus** [comment]
On top of that, the crash with the plastic sheets only happen with the plastic sheets. no other item.
