### ISSUE TITLE
Won't work clean install

### ISSUE THREAD

**Issue by tiripon** [CoFH/Feedback#958]
Hi,

I have an installation of Forge 1.8 - 11.14.4.1577 on an Amazon EC2 instance m4.large 64 bits
With Oracle Java 8 64 bits.
The Forge server works perfectly. No mod are currently install. It's a clean install.

But when I put the "CoFHCore-[1.7.10]3.0.3-303.jar" file in the mods folder, I can't start the Forge server. When I remove the file from the mods folder I can start my Forge server again.

I pretty sure I'm following the instructions which are very easy.

Is there something I'm doing wrong?

**Comment by KingLemming** [comment]
Without a log, we can't help you. Obviously, the mod works, so this is specific to your setup and hardware.

**Comment by tiripon** [comment]
[19:32:10] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
[19:32:10] [main/INFO] [FML/]: Forge Mod Loader version 11.14.4.1563 for Minecraft 1.8 loading
[19:32:10] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_66, running on Linux:amd64:3.13.0-71-generic, installed at /usr/lib/jvm/java-8-oracle/jre
[19:32:10] [main/DEBUG] [FML/]: Java classpath at launch is forge-1.8-11.14.4.1563-universal.jar
[19:32:10] [main/DEBUG] [FML/]: Java library path at launch is /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
[19:32:10] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
[19:32:10] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
[19:32:10] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[19:32:10] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
[19:32:10] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
[19:32:10] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
[19:32:10] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
[19:32:10] [main/DEBUG] [FML/]: Attempting to load commandline specified mods, relative to /home/ubuntu/forge/.
[19:32:10] [main/DEBUG] [FML/]: Discovering coremods
[19:32:10] [main/DEBUG] [FML/]: Examining for coremod candidacy CoFHCore-[1.7.10]3.0.3-303.jar
[19:32:10] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in CoFHCore-[1.7.10]3.0.3-303.jar, it will be examined later for regular @Mod instances
[19:32:10] [main/DEBUG] [FML/]: Instantiating coremod class LoadingPlugin
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.forName0(Native Method)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.forName(Class.java:348)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:485)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:409)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:241)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:79)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:19)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 29 more
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 31 more
[19:32:10] [main/ERROR] [FML/]: An error occurred trying to configure the minecraft home at /home/ubuntu/forge/. for Forge Mod Loader
java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_66]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_66]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_66]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_66]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_66]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_66]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_66]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_66]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_66]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:485) ~[forge-1.8-11.14.4.1563-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:409) ~[forge-1.8-11.14.4.1563-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:241) ~[forge-1.8-11.14.4.1563-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95) [forge-1.8-11.14.4.1563-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:79) [forge-1.8-11.14.4.1563-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39) [forge-1.8-11.14.4.1563-universal.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:19) [forge-1.8-11.14.4.1563-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.8-11.14.4.1563-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.8-11.14.4.1563-universal.jar:?]
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]
	... 29 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]
	... 29 more
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.forName0(Native Method)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.forName(Class.java:348)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:485)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:409)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:241)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:79)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:19)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 6 more
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 29 more
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[19:32:10] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 31 more

**Comment by KingLemming** [comment]
I should have read your initial post more carefully. This mod is for 1.7.10. You're trying to install it on 1.8.

**Comment by tiripon** [comment]
Maybe the instructions should be updated:
"Installation

Backup your world!
Delete any old versions of the CoFHCore .jar file from your ".minecraft/mods" folder.
Install Minecraft Forge
Download and drop the CoFHCore .jar file into your ".minecraft/mods" folder."

There is no indication that it is not compatible with Forge 1.8
It just says to install Forge.

**Comment by XFactHD** [comment]
Look at the version in the file name, also curse/curseforge tells you the version, you just have to look at it. And if you do not download the mod from curse/curseforge or via the links in teamcofh.com, that's bad.

**Comment by tiripon** [comment]
Well, adding "only compatible with Forge 1.7" somewhere would be too much trouble?

**Comment by skyboy** [comment]
The version is listed everywhere you download it and included in the file name and version. User error is not our problem to solve, and is quite literally impossible - there will always be someone who didn't read, and it's not our job to make sure they read; we're not their parents.
