### ISSUE TITLE
crah on startp up

### ISSUE THREAD

**Issue by Tsyklop** [CoFH/Feedback#965]
Crash on start up game: http://pastebin.com/ymqkdXL4

Full my log: https://gist.githubusercontent.com/Tsyklop/ca420daef6a00ccdc9cd/raw/72aa5d852d26fae3ac452676a604cb0d29593f16/fuul%2520log

if I remove lodeloader - error remains.

same problem here: https://github.com/SleepyTrousers/EnderIO/issues/3055

**Comment by skyboy** [comment]
```
Caused by: java.lang.NoClassDefFoundError: zs
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
        at java.lang.Class.getConstructor0(Unknown Source)
        at java.lang.Class.getConstructor(Unknown Source)
        at me.planetguy.lib.prefab.GuiHandlerPrefab.<init>(GuiHandlerPrefab.java:28)
        at me.planetguy.lib.prefab.GuiHandlerPrefab.create(GuiHandlerPrefab.java:16)
        at me.planetguy.remaininmotion.core.ModRiM.PostInit(ModRiM.java:135)
```

This has nothing to do with us.

**Comment by HenryLoenwind** [comment]
I beg to differ. "zs" is net.minecraft.inventory.Container, commit https://github.com/CoFH/CoFHCore/commit/0edd1b6892ce4877f27cdf1e2084a37f8eb6c6b8 which is in build 319 changes net.minecraft.inventory.Container, and and oh wonder, the crash comes and goes by switching between build 318 and 319.

**Comment by skyboy** [comment]
> I beg to differ. "zs" is net.minecraft.inventory.Container, commit https://github.com/CoFH/CoFHCore/commit/0edd1b6892ce4877f27cdf1e2084a37f8eb6c6b8 which is in build 319 changes net.minecraft.inventory.Container, and and oh wonder, the crash comes and goes by switching between build 318 and 319.

Next time you beg to differ you can be more polite about it. Fixed by https://github.com/CoFH/CoFHCore/commit/f4c14f0ad42e5c36d8191b7bc7995a6ac0bbaacf
