### ISSUE TITLE
Thermal Expansion crash when compactors are disabled. 1.12.2

### ISSUE THREAD

**Issue by Silver-Wulf** [CoFH/Feedback#989]
If I set the Compactor to enabled=false it crashes the server when it tries to hook into JEI, even on the server.

ThermalExpansion-1.12.2-5.3.10.15-universal.jar 

Time: 17/03/18 14:12
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.NoClassDefFoundError: cofh/thermalexpansion/plugins/jei/machine/compactor/CompactorRecipeCategory
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:663)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:589)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:718)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: cofh/thermalexpansion/plugins/jei/machine/compactor/CompactorRecipeCategory
	at cofh.thermalexpansion.block.machine.BlockMachine.addRecipes(BlockMachine.java:475)
	at cofh.thermalexpansion.block.machine.BlockMachine.register(BlockMachine.java:378)
	at cofh.thermalexpansion.init.TEBlocks.registerRecipes(TEBlocks.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_323_TEBlocks_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:655)
	... 9 more
Caused by: java.lang.ClassNotFoundException: cofh.thermalexpansion.plugins.jei.machine.compactor.CompactorRecipeCategory
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: cofh/thermalexpansion/plugins/jei/machine/BaseRecipeCategory
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 18 more
Caused by: java.lang.ClassNotFoundException: cofh.thermalexpansion.plugins.jei.machine.BaseRecipeCategory
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:663)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:589)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:718)

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjf000(MinecraftServer.java:4013)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:556)
	at java.lang.Thread.run(Thread.java:748)

**Comment by KingLemming** [comment]
Okay. Well, don't do that then.
