### ISSUE TITLE
Opengl - fix problem

### ISSUE THREAD

**Issue by JohnDog3112** [CoFH/Feedback#989]
I have an old graphics card and cofh core wasn't working but I found 1 mod that fixed it. But in a certaint modpack it has a different/higher version of the mod making it so I can't put the mod that works in it without having problems with forge. The mod that fixes it is OpenModsLib-1.7.10-0.8 so could some one make a different version of the same mod that will allow me to fix the problem.

**Comment by KingLemming** [comment]
Can't help without a log and no we aren't making a custom mod just to support hardware that really shouldn't be running Minecraft in the first place.

**Comment by JohnDog3112** [comment]
Tons of people have the same problem I just want to know how to change the mod.class file so I can get it working like it used to.

**Comment by KingLemming** [comment]
You can't. That's the point. And there's no way I could possibly tell you what to change without knowing what is wrong. Post a log please.

**Comment by JohnDog3112** [comment]
Ok here is the problem I can't find anything that I can post the log on since it is so long.

**Comment by JohnDog3112** [comment]
[16:29:38] [main/INFO]: Setting user: JohnDog3112
[16:29:41] [Client thread/INFO]: LWJGL Version: 2.9.1
[16:30:56] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:OpenEye, FMLFileResourcePack:Lucky Block, FMLFileResourcePack:Furnace 3D, FMLFileResourcePack:ArmorStatusHUD, FMLFileResourcePack:Damage Indicators, FMLFileResourcePack:StartingInventory, FMLFileResourcePack:AE2 Stuff, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:AutoFood, FMLFileResourcePack:Automagy, FMLFileResourcePack:AutoPackager, FMLFileResourcePack:BD Lib, FMLFileResourcePack:Better Title Screen, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:BiblioWoods Natura Edition, FMLFileResourcePack:Big Reactors, FMLFileResourcePack:Botania, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:Chisel 2, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Cosmetic Armor, FMLFileResourcePack:Decocraft, FMLFileResourcePack:Draconic Evolution, FMLFileResourcePack:Dragon Mounts, FMLFileResourcePack:Dual Hotbar, FMLFileResourcePack:Emotes, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderStorage, FMLFileResourcePack:EnderTech, FMLFileResourcePack:Ender Utilities, FMLFileResourcePack:Ex Astris, FMLFileResourcePack:Ex Nihilo, FMLFileResourcePack:ExtraCells, FMLFileResourcePack:ExtraTiC, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:Food Plus, FMLFileResourcePack:Forbidden Magic, FMLFileResourcePack:FoxLib, FMLFileResourcePack:Greg's Lighting, FMLFileResourcePack:Hats, FMLFileResourcePack:HatStand, FMLFileResourcePack:Headcrumbs, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Iguana Tinker Tweaks, FMLFileResourcePack:Immibis Core, FMLFileResourcePack:InGame Info XML, FMLFileResourcePack:InGame Info XML - Simply Jetpacks Integration, FMLFileResourcePack:InGame Info XML - Thaumcraft Integration, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:It's Raining Food, FMLFileResourcePack:JABBA, FMLFileResourcePack:Liquid XP, FMLFileResourcePack:Loot Bags, FMLFileResourcePack:LunatriusCore, FMLFileResourcePack:Magical Crops, FMLFileResourcePack:Mantle, FMLFileResourcePack:MinefactoryReloaded & MagicalCrops extra compatibility, FMLFileResourcePack:MineFactory Reloaded, FMLFileResourcePack:MFR Compat: Applied Energistics, FMLFileResourcePack:MFR Compat: Atum, FMLFileResourcePack:MFR Compat: BackTools, FMLFileResourcePack:MFR Compat: BuildCraft, FMLFileResourcePack:MFR Compat: Chococraft, FMLFileResourcePack:MFR Compat: ExtraBiomes, FMLFileResourcePack:MFR Compat: Forestry, FMLFileResourcePack:MFR Compat: ForgeMicroblock, FMLFileResourcePack:MFR Compat: IC2, FMLFileResourcePack:MFR Compat: Mystcraft, FMLFileResourcePack:MFR Compat ProjectRed, FMLFileResourcePack:MFR Compat: Railcraft, FMLFileResourcePack:MFR Compat: Sufficient Biomes, FMLFileResourcePack:MFR Compat: Thaumcraft, FMLFileResourcePack:MFR Compat: Thermal Expansion, FMLFileResourcePack:MFR Compat: Tinkers' Construct, FMLFileResourcePack:MFR Compat: TwilightForest, FMLFileResourcePack:MFR Compat: Vanilla, FMLFileResourcePack:MineTweaker 3, FMLFileResourcePack:Mod Tweaker 2, FMLFileResourcePack:Moo Fluids, FMLFileResourcePack:Morpheus, FMLFileResourcePack:Natura, FMLFileResourcePack:NEI Addons, FMLFileResourcePack:NEI Addons: Botany, FMLFileResourcePack:NEI Addons: Forestry, FMLFileResourcePack:NEI Addons: Crafting Tables, FMLFileResourcePack:NEI Addons: Ex Nihilo, FMLFileResourcePack:NEI Integration, FMLFileResourcePack:OpenBlocks, FMLFileResourcePack:OpenMods, FMLFileResourcePack:OpenPeripheralAddons, FMLFileResourcePack:OpenPeripheralCore, FMLFileResourcePack:OpenPeripheralIntegration, FMLFileResourcePack:MapWriter, FMLFileResourcePack:Opis, FMLFileResourcePack:Plugin Messages Mod, FMLFileResourcePack:Ranchable Fluid Cows, FMLFileResourcePack:RedLogic, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:Reliquary, FMLFileResourcePack:RFTools, FMLFileResourcePack:Simple Achievements, FMLFileResourcePack:Simply Jetpacks, FMLFileResourcePack:Slabcraft, FMLFileResourcePack:Solar Flux, FMLFileResourcePack:Staircraft, FMLFileResourcePack:Sync, FMLFileResourcePack:Tabula Rasa, FMLFileResourcePack:TC Node Tracker, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Thaumcraft, FMLFileResourcePack:Thaumcraft NEI Plugin, FMLFileResourcePack:Thaumic Energistics, FMLFileResourcePack:Thermal Casting, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:Translocator, FMLFileResourcePack:Tree Growing Simulator 2014, FMLFileResourcePack:ttCore, FMLFileResourcePack:Utility Mobs, FMLFileResourcePack:Vein Miner, FMLFileResourcePack:Mod Support, FMLFileResourcePack:Waila, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:Waila NBT, FMLFileResourcePack:What Are We Looking At, FMLFileResourcePack:Witchery, FMLFileResourcePack:WR-CBE Core, FMLFileResourcePack:WR-CBE Addons, FMLFileResourcePack:WR-CBE Logic, FMLFileResourcePack:YUNoMakeGoodMap, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:Baubles, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:libsandstone
[16:32:43] [Sound Library Loader/INFO]: Sound engine started
[16:32:45] [Client thread/WARN]: Invalid sounds.json
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 4 column 2
	at com.google.gson.Gson.fromJson(Gson.java:818) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[Gson.class:?]
	at net.minecraft.client.audio.SoundHandler.func_110549_a(SourceFile:78) [btp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:130) [brg.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:486) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 4 column 2
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:494) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184) ~[MapTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[MapTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	... 12 more
[16:33:23] [Client thread/INFO]: Created: 2048x2048 textures/blocks-atlas
[16:33:39] [Client thread/INFO]: Created: 2048x1024 textures/items-atlas
[16:35:37] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:OpenEye, FMLFileResourcePack:Lucky Block, FMLFileResourcePack:Furnace 3D, FMLFileResourcePack:ArmorStatusHUD, FMLFileResourcePack:Damage Indicators, FMLFileResourcePack:StartingInventory, FMLFileResourcePack:AE2 Stuff, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:AutoFood, FMLFileResourcePack:Automagy, FMLFileResourcePack:AutoPackager, FMLFileResourcePack:BD Lib, FMLFileResourcePack:Better Title Screen, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:BiblioWoods Natura Edition, FMLFileResourcePack:Big Reactors, FMLFileResourcePack:Botania, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:Chisel 2, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Cosmetic Armor, FMLFileResourcePack:Decocraft, FMLFileResourcePack:Draconic Evolution, FMLFileResourcePack:Dragon Mounts, FMLFileResourcePack:Dual Hotbar, FMLFileResourcePack:Emotes, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderStorage, FMLFileResourcePack:EnderTech, FMLFileResourcePack:Ender Utilities, FMLFileResourcePack:Ex Astris, FMLFileResourcePack:Ex Nihilo, FMLFileResourcePack:ExtraCells, FMLFileResourcePack:ExtraTiC, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:§bFood Plus, FMLFileResourcePack:Forbidden Magic, FMLFileResourcePack:FoxLib, FMLFileResourcePack:Greg's Lighting, FMLFileResourcePack:Hats, FMLFileResourcePack:HatStand, FMLFileResourcePack:Headcrumbs, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Iguana Tinker Tweaks, FMLFileResourcePack:Immibis Core, FMLFileResourcePack:InGame Info XML, FMLFileResourcePack:InGame Info XML - Simply Jetpacks Integration, FMLFileResourcePack:InGame Info XML - Thaumcraft Integration, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:It's Raining Food, FMLFileResourcePack:JABBA, FMLFileResourcePack:Liquid XP, FMLFileResourcePack:Loot Bags, FMLFileResourcePack:LunatriusCore, FMLFileResourcePack:Magical Crops, FMLFileResourcePack:Mantle, FMLFileResourcePack:MinefactoryReloaded & MagicalCrops extra compatibility, FMLFileResourcePack:MineFactory Reloaded, FMLFileResourcePack:MFR Compat: Applied Energistics, FMLFileResourcePack:MFR Compat: Atum, FMLFileResourcePack:MFR Compat: BackTools, FMLFileResourcePack:MFR Compat: BuildCraft, FMLFileResourcePack:MFR Compat: Chococraft, FMLFileResourcePack:MFR Compat: ExtraBiomes, FMLFileResourcePack:MFR Compat: Forestry, FMLFileResourcePack:MFR Compat: ForgeMicroblock, FMLFileResourcePack:MFR Compat: IC2, FMLFileResourcePack:MFR Compat: Mystcraft, FMLFileResourcePack:MFR Compat ProjectRed, FMLFileResourcePack:MFR Compat: Railcraft, FMLFileResourcePack:MFR Compat: Sufficient Biomes, FMLFileResourcePack:MFR Compat: Thaumcraft, FMLFileResourcePack:MFR Compat: Thermal Expansion, FMLFileResourcePack:MFR Compat: Tinkers' Construct, FMLFileResourcePack:MFR Compat: TwilightForest, FMLFileResourcePack:MFR Compat: Vanilla, FMLFileResourcePack:MineTweaker 3, FMLFileResourcePack:Mod Tweaker 2, FMLFileResourcePack:Moo Fluids, FMLFileResourcePack:Morpheus, FMLFileResourcePack:Natura, FMLFileResourcePack:NEI Addons, FMLFileResourcePack:NEI Addons: Botany, FMLFileResourcePack:NEI Addons: Forestry, FMLFileResourcePack:NEI Addons: Crafting Tables, FMLFileResourcePack:NEI Addons: Ex Nihilo, FMLFileResourcePack:NEI Integration, FMLFileResourcePack:OpenBlocks, FMLFileResourcePack:OpenMods, FMLFileResourcePack:OpenPeripheralAddons, FMLFileResourcePack:OpenPeripheralCore, FMLFileResourcePack:OpenPeripheralIntegration, FMLFileResourcePack:MapWriter, FMLFileResourcePack:Opis, FMLFileResourcePack:Plugin Messages Mod, FMLFileResourcePack:Ranchable Fluid Cows, FMLFileResourcePack:RedLogic, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:Reliquary, FMLFileResourcePack:RFTools, FMLFileResourcePack:Simple Achievements, FMLFileResourcePack:Simply Jetpacks, FMLFileResourcePack:Slabcraft, FMLFileResourcePack:Solar Flux, FMLFileResourcePack:Staircraft, FMLFileResourcePack:Sync, FMLFileResourcePack:Tabula Rasa, FMLFileResourcePack:TC Node Tracker, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Thaumcraft, FMLFileResourcePack:Thaumcraft NEI Plugin, FMLFileResourcePack:Thaumic Energistics, FMLFileResourcePack:Thermal Casting, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:Translocator, FMLFileResourcePack:Tree Growing Simulator 2014, FMLFileResourcePack:ttCore, FMLFileResourcePack:Utility Mobs, FMLFileResourcePack:Vein Miner, FMLFileResourcePack:Mod Support, FMLFileResourcePack:Waila, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:Waila NBT, FMLFileResourcePack:What Are We Looking At, FMLFileResourcePack:Witchery, FMLFileResourcePack:WR-CBE Core, FMLFileResourcePack:WR-CBE Addons, FMLFileResourcePack:WR-CBE Logic, FMLFileResourcePack:YUNoMakeGoodMap, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:Baubles, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:libsandstone, FMLFileResourcePack:Carpenter's Blocks Cached Resources
[16:36:27] [Client thread/INFO]: Created: 2048x2048 textures/blocks-atlas
[16:36:55] [Client thread/INFO]: Created: 2048x2048 textures/items-atlas
[16:36:56] [Sound Library Loader/INFO]: Sound engine started
[16:37:01] [Client thread/WARN]: Invalid sounds.json
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 4 column 2
	at com.google.gson.Gson.fromJson(Gson.java:818) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[Gson.class:?]
	at net.minecraft.client.audio.SoundHandler.func_110549_a(SourceFile:78) [btp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143) [brg.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121) [brg.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:609) [bao.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 4 column 2
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:494) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184) ~[MapTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[MapTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	... 15 more
[16:37:04] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:OpenEye, FMLFileResourcePack:Lucky Block, FMLFileResourcePack:Furnace 3D, FMLFileResourcePack:ArmorStatusHUD, FMLFileResourcePack:Damage Indicators, FMLFileResourcePack:StartingInventory, FMLFileResourcePack:AE2 Stuff, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:AutoFood, FMLFileResourcePack:Automagy, FMLFileResourcePack:AutoPackager, FMLFileResourcePack:BD Lib, FMLFileResourcePack:Better Title Screen, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:BiblioWoods Natura Edition, FMLFileResourcePack:Big Reactors, FMLFileResourcePack:Botania, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:Chisel 2, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Cosmetic Armor, FMLFileResourcePack:Decocraft, FMLFileResourcePack:Draconic Evolution, FMLFileResourcePack:Dragon Mounts, FMLFileResourcePack:Dual Hotbar, FMLFileResourcePack:Emotes, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderStorage, FMLFileResourcePack:EnderTech, FMLFileResourcePack:Ender Utilities, FMLFileResourcePack:Ex Astris, FMLFileResourcePack:Ex Nihilo, FMLFileResourcePack:ExtraCells, FMLFileResourcePack:ExtraTiC, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:§bFood Plus, FMLFileResourcePack:Forbidden Magic, FMLFileResourcePack:FoxLib, FMLFileResourcePack:Greg's Lighting, FMLFileResourcePack:Hats, FMLFileResourcePack:HatStand, FMLFileResourcePack:Headcrumbs, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Iguana Tinker Tweaks, FMLFileResourcePack:Immibis Core, FMLFileResourcePack:InGame Info XML, FMLFileResourcePack:InGame Info XML - Simply Jetpacks Integration, FMLFileResourcePack:InGame Info XML - Thaumcraft Integration, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:It's Raining Food, FMLFileResourcePack:JABBA, FMLFileResourcePack:Liquid XP, FMLFileResourcePack:Loot Bags, FMLFileResourcePack:LunatriusCore, FMLFileResourcePack:Magical Crops, FMLFileResourcePack:Mantle, FMLFileResourcePack:MinefactoryReloaded & MagicalCrops extra compatibility, FMLFileResourcePack:MineFactory Reloaded, FMLFileResourcePack:MFR Compat: Applied Energistics, FMLFileResourcePack:MFR Compat: Atum, FMLFileResourcePack:MFR Compat: BackTools, FMLFileResourcePack:MFR Compat: BuildCraft, FMLFileResourcePack:MFR Compat: Chococraft, FMLFileResourcePack:MFR Compat: ExtraBiomes, FMLFileResourcePack:MFR Compat: Forestry, FMLFileResourcePack:MFR Compat: ForgeMicroblock, FMLFileResourcePack:MFR Compat: IC2, FMLFileResourcePack:MFR Compat: Mystcraft, FMLFileResourcePack:MFR Compat ProjectRed, FMLFileResourcePack:MFR Compat: Railcraft, FMLFileResourcePack:MFR Compat: Sufficient Biomes, FMLFileResourcePack:MFR Compat: Thaumcraft, FMLFileResourcePack:MFR Compat: Thermal Expansion, FMLFileResourcePack:MFR Compat: Tinkers' Construct, FMLFileResourcePack:MFR Compat: TwilightForest, FMLFileResourcePack:MFR Compat: Vanilla, FMLFileResourcePack:MineTweaker 3, FMLFileResourcePack:Mod Tweaker 2, FMLFileResourcePack:Moo Fluids, FMLFileResourcePack:Morpheus, FMLFileResourcePack:Natura, FMLFileResourcePack:NEI Addons, FMLFileResourcePack:NEI Addons: Botany, FMLFileResourcePack:NEI Addons: Forestry, FMLFileResourcePack:NEI Addons: Crafting Tables, FMLFileResourcePack:NEI Addons: Ex Nihilo, FMLFileResourcePack:NEI Integration, FMLFileResourcePack:OpenBlocks, FMLFileResourcePack:OpenMods, FMLFileResourcePack:OpenPeripheralAddons, FMLFileResourcePack:OpenPeripheralCore, FMLFileResourcePack:OpenPeripheralIntegration, FMLFileResourcePack:MapWriter, FMLFileResourcePack:Opis, FMLFileResourcePack:Plugin Messages Mod, FMLFileResourcePack:Ranchable Fluid Cows, FMLFileResourcePack:RedLogic, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:Reliquary, FMLFileResourcePack:RFTools, FMLFileResourcePack:Simple Achievements, FMLFileResourcePack:Simply Jetpacks, FMLFileResourcePack:Slabcraft, FMLFileResourcePack:Solar Flux, FMLFileResourcePack:Staircraft, FMLFileResourcePack:Sync, FMLFileResourcePack:Tabula Rasa, FMLFileResourcePack:TC Node Tracker, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Thaumcraft, FMLFileResourcePack:Thaumcraft NEI Plugin, FMLFileResourcePack:Thaumic Energistics, FMLFileResourcePack:Thermal Casting, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:Translocator, FMLFileResourcePack:Tree Growing Simulator 2014, FMLFileResourcePack:ttCore, FMLFileResourcePack:Utility Mobs, FMLFileResourcePack:Vein Miner, FMLFileResourcePack:Mod Support, FMLFileResourcePack:Waila, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:Waila NBT, FMLFileResourcePack:What Are We Looking At, FMLFileResourcePack:Witchery, FMLFileResourcePack:WR-CBE Core, FMLFileResourcePack:WR-CBE Addons, FMLFileResourcePack:WR-CBE Logic, FMLFileResourcePack:YUNoMakeGoodMap, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:Baubles, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:libsandstone, FMLFileResourcePack:Carpenter's Blocks Cached Resources, resources

**Comment by JohnDog3112** [comment]
But it just decides to stop working once it launches. What happens is it gives me a not responding screen and just closes on it's self.

**Comment by JohnDog3112** [comment]
nvm it is going to be fixed.
